### ISSUE TITLE
stat_ecdf plots extra points

### ISSUE THREAD

**Issue by smirarab** [hadley/ggplot2#1000]
When I try to plot cumulative density function using `stat_ecdf` and with `geom_point`, I see a strange behavior: two extra points are added to my numbers, one before everything, and another one after everything else. This kind of make sense if the default `geom_step` was used for plotting, but with `geom_point`, this is very confusing if not outright wrong.  

Here is an example:

    qplot(a,data=data.frame(a=1:10),stat="ecdf",geom="point")

which produces:

![ecdf plot with one point extra point at zero and one at one][1]

Note the extra points at 0 and at 10. 

**Suggestion 1**: adding a new parameter to `stat_ecdf` to prevent addition of these new values.  

**Suggestion 2**: I think it should be `geom_step` that computes an adds these two extra points, not `stat_ecdf`. The extra points are only for visualization and not part of the summary of the data. 

Here is my R session info:

    > sessionInfo()
    R version 3.1.1 (2014-07-10)
    Platform: x86_64-apple-darwin13.1.0 (64-bit)
    ... 
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base
    other attached packages:
    [1] scales_0.2.4  ggplot2_1.0.0

  [1]: http://i.stack.imgur.com/2QMTv.jpg

**Comment by hadley** [comment]
I'd be happy to review a pull request to fix this.
