### ISSUE TITLE
scatterplots of categorical variables cause 'row names were found from a short variable' warning

### ISSUE THREAD

**Issue by richierocks** [hadley/ggplot2#1003]
Scatterplots of categorical variable cause a warning about short variable names being discarded to be thrown.  For example,

    ggplot(mpg, aes(manufacturer, hwy)) + geom_point()
    ## Warning message:
    ## In data.frame(x = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  :
    ##   row names were found from a short variable and have been discarded

By setting `options(warn = 2)`, we can see the traceback of where the problem occurs:

    traceback(max.lines = 1)
    ## 11: stop(list(message = "(converted from warning) row names were found from a short variable and have been discarded", 
    ##     ##   ...
    ## 10: .Call("plyr_loop_apply", PACKAGE = "plyr", n, f)
    ## 9: loop_apply(n, do.ply)
    ## 8: llply(.data = pieces, .fun = .fun, ..., .progress = .progress, 
    ##     ##  ...
    ## 7: dlply(layer_data, "PANEL", function(df) {
    ##     ##  ...
    ## 6: (function (layer, layer_data) 
    ##     ##  ...
    ## 5: mapply(FUN = f, ..., SIMPLIFY = FALSE)
    ## 4: Map(build_grob, plot$layer, data)
    ## 3: ggplot_gtable(data)
    ## 2: print.ggplot(list(data = list(manufacturer = c(1L, 1L, 1L, 1L, 
    ##     ##  ...
    ## 1: print(list(data = list(manufacturer = c(1L, 1L, 1L, 1L, 1L, 1L, 
    ##     ##  ...

In general, this problem is caused by a short named column when creating a data frame.  For example,

    data.frame(x = c(a = 1, b = 2), y = 1:4)

**Comment by hadley** [comment]
I can't reproduce this warning any more.
