### ISSUE TITLE
'guides' documentation, possible improvement in last example

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1004]
In the last example in `?guides` and http://docs.ggplot2.org/0.9.3.1/guides.html, the `aes`thetics used in the `qplot` call are `size`, `colour` and `shape` (`size = hwy, colour = cyl, shape = drv`). However, in `guides`, `shape` is not mentioned, but instead the unused aesthetic `alpha` appears. I suggest that `alpha` is replaced by `shape`.

**Comment by hadley** [comment]
Good catch - thanks!
