### ISSUE TITLE
Option to ensure all the geoms are within plot canvas

### ISSUE THREAD

**Issue by vlsi** [hadley/ggplot2#1009]
It is quite common for scatterplot labels to be truncated:
http://stackoverflow.com/questions/17241182/how-to-make-geom-text-plot-within-the-canvass-bounds

It looks like all the "solutions" involving `strwidth(, units="inches")` and `strwidth(, units="figure")` do not apply for different zoom levels.

Even examples of `geom_text` (http://docs.ggplot2.org/current/geom_text.html) fail to make labels fit into the canvas.

Can you please create an option to fit geoms into the canvas and/or a way to calculate label width?

**Comment by hadley** [comment]
Unfortunately it's extremely difficult to do this due to the interaction between data space and plot space.
