### ISSUE TITLE
scale_colour_log10?

### ISSUE THREAD

**Issue by naught101** [hadley/ggplot2#1012]
Would it be possible to have these scales?

```
scale_colour_log10       scale_colour_reverse     scale_colour_sqrt
scale_color_log10       scale_color_reverse     scale_color_sqrt
scale_fill_log10       scale_fill_reverse     scale_fill_sqrt
```

They can be pretty useful when using oddly distributed continuous data on colour scales.

**Comment by hadley** [comment]
Thanks for capturing my thoughts exactly @BrianDiggs !

**Comment by naught101** [comment]
fair enough, thanks :)
