### ISSUE TITLE
How to modify lines within the legend

### ISSUE THREAD

**Issue by JamesD73** [hadley/ggplot2#1013]
Can anyone tell me how to edit the size of the lines in the legend. I have an ROC plot, with three lines for three different models. I have the main ROC lines nice and thick, but I have not been able to change the size of the lines in the legend. There seems to be nothing here (http://docs.ggplot2.org/current/theme.html) where I can add in a call to element_line to increase the size of the lines in the legend. An intuitive way to do it would be to create a call to the following:
legend_lines = element_line(size=5,"cm")
But I cannot find anything similar

**Comment by hadley** [comment]
See `guide_legend()` and the `override.aes` option
