### ISSUE TITLE
Why does Jitterdodge require fill to be set?

### ISSUE THREAD

**Issue by Martin-Jung** [hadley/ggplot2#1014]
I am plotting multiple <b>geom_pointrange</b> geometries each with different shapes that I am going to use in a legend. Because the values often overlap I want to jitterdodge them. Strangely position_jitterdodge requires the fill attribute and thus adds another unnecessary legend to my plot (that I have to disable manually afterwards via <b>scale_fill_discrete(guide="none")</b> )

So if you try to add a pointrange similar to this command (sorry for not providing a FRE):
>p + geom_pointrange(data = data,aes(ymax=upper_est,ymin=lower_est,shape=Grouping,group=Grouping),color="black",size=1.2,position=position_jitterdodge(dodge.width = .5) )

The above command does not work unless I set <b>fill</b> in the aesthetics. I see no reason why it should be set?
What is the reason for <b>position_jitterdodge</b> to require the fill attribute set in the first place?

**Comment by hadley** [comment]
Could you please provide a minimal reprex?
