### ISSUE TITLE
ggsave Error For Some Grobs

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1015]
> class(wholePlot)
[1] "arrange" "gTree"   "grob"    "gDesc" 
> ggsave("wholePlot.png", wholePlot)
Error in ggsave("wholePlot.png", wholePlot) :
  plot should be a ggplot2 plot

It sometimes works for some grobs and not others. Can it be made wholly compatible for the next release ?

The workaround

> ggsave <- ggplot2::ggsave; body(ggsave) <- body(ggplot2::ggsave)[-2];

works, but it'd be good for users to have reproducible workflows, rather than modifying package code in their script.  The object is available [here](https://groups.google.com/group/ggplot2/attach/ae0fed199bef73f6/wholePlot.obj?part=0.1&authuser=0).

**Comment by hadley** [comment]
Please provide a minimal reproducible example and re-open.

**Comment by DarioS** [comment]
An example which can be simply copied and pasted into R is :

    library(ggplot2)
    library(gridExtra)
    library(gtable)

    firstGrob <- ggplot_gtable(ggplot_build(qplot(1:10, 1:10)))
    sencondGrob <- ggplot_gtable(ggplot_build(qplot(1:10, 10:1)))

    plotTable <- gtable(unit(8, "cm"), unit.c(unit(5, "cm"), unit(5, "cm")))
    plotTable <- gtable_add_grob(plotTable, firstGrob, 1, 1)
    plotTable <- gtable_add_grob(plotTable, sencondGrob, 2, 1)

    wholePlot <- arrangeGrob(plotTable, main = textGrob("Scatterplots"))
    print(wholePlot)
    class(wholePlot)
    ggsave("scatter.png", wholePlot)  # Error about incorrect class of object.

**Comment by hadley** [comment]
Well, `wholePlot` isn't a ggplot2 object, so I don't think that's ever worked. But see #970
