### ISSUE TITLE
ggplot2_gtable Unexpectedly Opens New Graphics Device

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1019]
[Download classesPlot](https://groups.google.com/group/ggplot2/attach/f749f60a8b5ab721/classesPlot.obj?part=0.1&authuser=0)

    load("classesPlot.obj")
    requireNamespace("ggplot2")
    requireNamespace("grid")
    requireNamespace("gridExtra")

    classGrob <- ggplot2::ggplot_gtable(ggplot2::ggplot_build(classesPlot))

opens a window with a blank plotting area titled

R Graphics: Device 2 (ACTIVE)

However, the documentation for ggplot_gtable has

Value : a gtable object

    > class(classGrob)
    [1] "gtable" "grob"   "gDesc"

That's true, but why is there a new device opened as a side effect ? It is not documented and it is unwanted.

**Comment by hadley** [comment]
I think this was a side-effect of a ggplot2 dependency that has since been fixed.
