### ISSUE TITLE
geom_boxplot() + scale_y_log10()   bug

### ISSUE THREAD

**Issue by ra81** [hadley/ggplot2#1020]
This bug cost me a full day of working.

Some sample of working code

```R
abc <- adply(matrix(rnorm(100, mean = 20, sd = 5), ncol = 5), 2, quantile, c(0, .25, .5, .75, 1))
abc$X1  <- NULL
abc$X1  <- c(1:5)
abc[6, ]  <- c(10, 18, 20, 25, 1000, 6)

# working code
b <- ggplot(abc, aes(group=X1, x = X1, ymin = `0%`, lower = `25%`, middle = `50%`, upper = `75%`, ymax = `100%`))
 b + geom_boxplot(stat = "identity", aes(fill=X1)) + coord_trans(y="log10")
```
This all ok. Picture is ok. 
![image](https://cloud.githubusercontent.com/assets/1291741/4609305/f83d7504-529a-11e4-8e58-2c60ba747d98.png)

```R
# broken code
b <- ggplot(abc, aes(group=X1, x = X1, ymin = `0%`, lower = `25%`, middle = `50%`, upper = `75%`, ymax = `100%`))
d <- b + geom_boxplot(stat = "identity") + scale_y_log10()
```

ggplot makes ranges of y axe as  c(0.8490745, 3.1024250). 
max value from abc is 1000 = 10^3. 
y range upper bound = 10^3 + small margin. So it is log scale.
BUT when data is plotted ggplot uses absolute values of abc data not log values.
So we have wrong picture 
![image](https://cloud.githubusercontent.com/assets/1291741/4609312/0cc97400-529b-11e4-9691-13d369b2e647.png)

Problem like this was discussed here 
https://github.com/hadley/ggplot2/issues/274
http://stackoverflow.com/questions/9502003/ggplot-scale-y-log10-issue

**Comment by hadley** [comment]
Here's a simpler reproducible example:

```R
library(plyr)
df <- data.frame(
  x = c("a", "b"),
  y1 = c(10, 10),
  y2 = c(15, 18),
  y3 = c(20, 20),
  y4 = c(22, 25),
  y5 = c(30, 1000)
)

ggplot(df, aes(x = x, ymin = y1, lower = y2, middle = y3, upper = y4, ymax = y5)) + 
  geom_boxplot(stat = "identity") + 
  scale_y_log10()
```

**Comment by hadley** [comment]
Oh hmmm, it's because lower, middle and upper aren't transformed by the scale (while `ymin` and `ymax` are). This isn't usually a problem because the stat operates on the transformed values, so you'll only see this with stat identity and a transformed y axis.
