### ISSUE TITLE
Smallest points are removed from plot

### ISSUE THREAD

**Issue by geotheory** [hadley/ggplot2#1022]
This [stackoverflow question](http://stackoverflow.com/questions/26402336/ggplot-fails-to-plot-smallest-points?noredirect=1#comment41454360_26402336) gives detail.

The smallest points are lost from the plot when data ranges across several orders of magnitude and scale_size_area is being used, I think due to rounding to zero somewhere.  The example demonstrates (look for the 10 point):

`d = data.frame(x=1:4, y=rep(1,4), v=10^(1:4))`
`ggplot(d, aes(x, y, size=v)) + geom_point(alpha=.5) + geom_text(aes(label = v), size=8, col='red') +`
`   scale_size_area(max_size = 500) + theme(legend.position = "none")`

Mostly not a problem, but can be for some plots - [this map of commuter patterns](https://dl.dropboxusercontent.com/u/46043231/docs/city_interaction.pdf) loses points in neighbouring cities (white labels show where points should be).

**Comment by hadley** [comment]
Ah good point, thanks!

```R
d <- data.frame(x = 1:4, y = rep(1, 4), v = 10 ^ (1:4))
ggplot(d, aes(x, y, size=v)) + 
  geom_point(alpha = 1/3) + 
  geom_text(aes(label = v), size = 8, col = "red") +
  scale_size_area(max_size = 500) + 
  theme(legend.position = "none") +
  xlim(0, 5)

last_plot() %+% d[1:3, ]
```

Looks like the rounding is happening somewhere else

**Comment by hadley** [comment]
Oh I bet it's this:

```R
scale_map.continuous <- function(scale, x, limits = scale_limits(scale)) {
  x <- scale$oob(scale$rescaler(x, from = limits))

  # Points are rounded to the nearest 500th, to reduce the amount of
  # work that the scale palette must do - this is particularly important
  # for colour scales which are rather slow.  This shouldn't have any
  # perceptual impacts.
  x <- round_any(x, 1 / 500)
  uniq <- unique(x)
  pal <- scale$palette(uniq)
  scaled <- pal[match(x, uniq)]

  ifelse(!is.na(scaled), scaled, scale$na.value)
}
```
