### ISSUE TITLE
thicker lines in bottom and right side 

### ISSUE THREAD

**Issue by bigdataage** [hadley/ggplot2#1023]
Unequal panel border size: https://github.com/hadley/ggplot2/issues/670
I these two days have also met this problem!
How did you solve the problem?  Can you please share?

**Comment by hadley** [comment]
I think it's to do with the way that the plot is clipped and the way that lines are drawn.  The plot is clipped hard on the bottom-left, but not on the top-right, so possibly half the line is getting clipped.  Unfortunately I don't see any easy fix for this.

**Comment by bigdataage** [comment]
O, thank you!
