### ISSUE TITLE
Documentation trans argument in continuous_scale

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1029]
In `?scale_x_continuous` `trans` is mentioned in the **Arguments** section, and it is referred to `continuous_scale` for more details. However, in `?continuous_scale` there are no details to be found - `trans` only appears in **Usage** (`trans = "identity"`). Back in `?scale_x_continuous`, a few 'shortcuts' are mentioned (`scale_y_log10`, `scale_y_sqrt`, `scale_y_reverse`) and there is a pointer to `?scale::trans_new` (shouldn't it be `scales`, with an 's'?), but examples of `trans` itself and valid transformer names, such as those in Table 6.2 in the ggplot book, are lacking. Furthermore, in the book it says "Table 6.2 list **some of the more common** transformers", which I interpret as there are even more, albeit less common, but still potentially useful transformers.

I believe it would be nice with an exhaustive table of valid `trans`former names in the help text.

**Comment by SamGG** [comment]
In relation to the trans argument, the minor_breaks argument should be documented to have a different behavior from breaks when a transformation is given: values given to minor_breaks should be transformed whereas untransformed values are given to breaks.

**Comment by hadley** [comment]
I've completely overhauled both the function specification and the documentation. This should be much better now :)
