### ISSUE TITLE
TikZ device doesn't use LaTeX-aware label metrics with facets

### ISSUE THREAD

**Issue by neapel** [hadley/ggplot2#1031]
When plotting with facets it seems the label width is not computed using the LaTeX-aware method, resulting in extraneous whitespace. Here's a knitr document showing the problem:
```
\documentclass{article}
\begin{document}
<<dev='tikz', echo=F, fig.height=1.5>>=
library(ggplot2)
mylabel <- function() {
  function(xs) { sprintf("\\ensuremath{%g}",xs) }
}
data <- data.frame(x=c(1,10), y=c(1,10), kind=c("a","a"))

ggplot(data,aes(x=x,y=y)) + geom_point() +
  scale_y_continuous(labels=mylabel())
@

<<dev='tikz', echo=F, fig.height=1.5>>=
ggplot(data,aes(x=x,y=y)) + geom_point() +
  scale_y_continuous(labels=mylabel()) +
  facet_grid(~ kind)
@

<<echo=F, fig.height=1.5>>=
ggplot(data,aes(x=x,y=y)) + geom_point() +
  scale_y_continuous(labels=mylabel())
@
\end{document}
```
Output:
![screen shot 2014-12-03 at 00 49 22](https://cloud.githubusercontent.com/assets/77855/5273947/4d580258-7a86-11e4-9f8a-ba2610e63789.png)

Expected: the label metrics in the second plot to be the same as the ones in the first (both using `dev=tikz`) not as the third (which is not using a TeX-aware dev)

**Comment by hadley** [comment]
I don't think this is a ggplot2 bug - I have no idea how the TikZ device generates label metrics
