### ISSUE TITLE
"inherit from" statement in documentation incorrect

### ISSUE THREAD

**Issue by annoporci** [hadley/ggplot2#1037]
The documentation (http://docs.ggplot2.org/0.9.3.1/theme.html) claims:
axis.text 	tick labels along axes (element_text; inherits from text)
axis.text.x 	x axis tick labels (element_text; inherits from axis.text)
axis.text.y 	y axis tick labels (element_text; inherits from axis.text)

If I understand the meaning of "inherit from", setting a colour for text should also set the colour for axis.text, but it doesn't.

ggplot(data = mtcars, aes(x = mpg, y = wt)) + geom_line() + 
    theme(text = element_text(size = 20, colour = "red"))

ggplot(data = mtcars, aes(x = mpg, y = wt)) + geom_line() + 
    theme(text = element_text(size = 20, colour = "red")) +
    theme(axis.text = element_text(size = 20, colour = "red"))

ggplot(data = mtcars, aes(x = mpg, y = wt)) + geom_line() + 
    theme(text = element_text(size = 20, colour = "red")) +
    theme(axis.text.x = element_text(size = 20, colour = "red"))

sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] ggplot2_1.0.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 digest_0.6.8     grid_3.1.2      
 [4] gtable_0.1.2     labeling_0.3     MASS_7.3-35     
 [7] munsell_0.4.2    plyr_1.8.1       proto_0.3-10    
[10] Rcpp_0.11.3      reshape2_1.4.1   scales_0.2.4    
[13] stringr_0.6.2    tools_3.1.2

**Comment by BrianDiggs** [comment]
The default theme has various things set which you must also consider. In particular

```r
> theme_grey()$axis.text
List of 8
 $ family    : NULL
 $ face      : NULL
 $ colour    : chr "grey50"
 $ size      :Class 'rel'  num 0.8
 $ hjust     : NULL
 $ vjust     : NULL
 $ angle     : NULL
 $ lineheight: NULL
 - attr(*, "class")= chr [1:2] "element_text" "element"
```

That is, unless otherwise specified, `axis.text` has a color set which takes precedence over the inheritance. 

Compare that with a theme that does not specify a color at that level

```r
ggplot(data = mtcars, aes(x = mpg, y = wt)) + 
geom_line() +
theme_minimal() +
theme(text = element_text(size = 20, colour = "red"))
```

and you can see that the theme allows inheritance here.

```r
> theme_minimal()$axis.text
List of 8
 $ family    : NULL
 $ face      : NULL
 $ colour    : NULL
 $ size      :Class 'rel'  num 0.8
 $ hjust     : NULL
 $ vjust     : NULL
 $ angle     : NULL
 $ lineheight: NULL
 - attr(*, "class")= chr [1:2] "element_text" "element"
```

**Comment by annoporci** [comment]
Thanks for the feedback Brian. I see what's going on. Perhaps the doc could explain this just as you did above. It's not your everyday meaning of 'inherit': I would have thought that most users who read the doc would expect that setting a color for 'text' would also set a color for 'axis.text' and children. However, admittedly, most users wouldn't have read the doc ;-)
