### ISSUE TITLE
labs() does not process argument NULL

### ISSUE THREAD

**Issue by annoporci** [hadley/ggplot2#1038]
More like a comment rather than an "issue":

1_  qplot(x = rnorm(1), y = seq(0, 1, length = 10)) + xlab(NULL) + ylab( NULL)   # okay

2_  qplot(x = rnorm(1), y = seq(0, 1, length = 10)) + labs(x=NULL, y= NULL)  # okay

3_  qplot(x = rnorm(1), y = seq(0, 1, length = 10)) + labs(NULL)   # unexpected

**Comment by DarioS** [comment]
You're using it incorrectly. You have to name the axes.

    qplot(x = rnorm(1), y = seq(0, 1, length = 10)) + labs(x = NULL, y = NULL)

**Comment by annoporci** [comment]
DarioS, thanks: my comment wast that while you can write xlab(NULL), you cannot write labs(NULL), as you can see the second case I listed is the one you are showing.

**Comment by hadley** [comment]
Yeah, all arguments to `labs()` must be named
