### ISSUE TITLE
Buffer for text option

### ISSUE THREAD

**Issue by Robinlovelace** [hadley/ggplot2#1039]
This is a feature request that could make labeling in complex graphics much more aesthetically pleasing: buffers - where you have an area of another colour (typically white) slightly larger than the main text behind the main text to allow the text to be read regardless of what's behind it. This is commonly used in maps, and is implemented to very good effect in QGIS: http://manual.linfiniti.com/en/vector_classification/label_tool.html

**Comment by hadley** [comment]
This is do-able, but fiddly because you have to figure out the size of the text at draw time - this means effectively you have to create a custom grid grob. However, I vaguely remember seeing that somewhere, so I'll see it's available.

It would also be useful to expose the `check.overlap` argument - it's not perfect (since you can't control what gets removed) but it might be helpful in some situations.

**Comment by Robinlovelace** [comment]
Worth asking the QGIS guys how they do it I'd say. I'll look into it. Cheers.

**Comment by hadley** [comment]
I think the right way to tackle this is to develop a new grid grob. Here's a start from Paul Murrell:

```R
library(grid)

textbg <- function(t, x, y, col) {
  grid.draw(gTree(label = t, x = x, y = y, col = col, cl = "textbg"))
}

#' @export
makeContent.textbg <- function(x, ...) {
  tg <- textGrob(x$label, x$x, x$y)
  bg <- roundrectGrob(x$x, x$y,
    width = grobWidth(tg) + unit(2, "mm"),
    height = grobWidth(tg) + unit(2, "mm"),
    gp = gpar(
      col = NA, 
      fill = x$col
    )
  )
  setChildren(x, gList(bg, tg))
}

grid.newpage()
textbg("test", .5, .5, "green")
```

I don't have the time to develop it further at the moment.

**Comment by Robinlovelace** [comment]
Cool.

And I don't think I have the skills!

Will make time to read the [grob section](https://github.com/hadley/ggplot2-book/blob/4f9bcdc3ba65edd7ecdbfdf14a71649c59bf400b/grid.rmd#plot-grobs-secplot-grobs) in an attempt to aquire them. Would you recommend this to go into core ggplot2 or an add-on package in the unlikely event that I can do with this or in the likelier event that someone else can?

Will be useful for ggmap.

Related question: are there any elements of ggmap that need to adjust to accomodate ggplot2 1.0.0?

**Comment by t-kalinowski** [comment]
Any updates on this? A halo option for text labels would be useful.
