### ISSUE TITLE
ggplotGrob sometimes plots blank objects

### ISSUE THREAD

**Issue by jonadler** [hadley/ggplot2#1042]
If you use ggplotGrob on a simple graph with a legend, it seems to render a blank plot. For example, try running this code in Rstudio and you'll see a plot of a blank image be rendered:

``` temp <- ggplotGrob(ggplot(data.frame(x=c(1,2)),aes(x=x,fill=factor(x)))+geom_bar())```

Interestingly, if your plot doesn't have a legend, this doesn't seem to be the case. The following code does not render a plot:
``` temp <- ggplotGrob(ggplot(data.frame(x=c(1,2)),aes(x=x))+geom_bar())```

This is a problem for me, since I'm running R on a server environment, which for happens to give me this error when I ever happen to plot to the default device:
```Error: cannot open file 'Rplots.pdf'```

**Comment by zji90** [comment]
I am having the same problem. It is quite concerning...

**Comment by hadley** [comment]
Seems to be fine for me.  This may have been related to a problem in the colorSpaces (?) package that has now been fixed.

**Comment by giuseppec** [comment]
Not sure if it worked for a while, but right now, I have exactly the same issue with ggplot2 (version 2.0.0).

**Comment by spooner1** [comment]
same for me, also version 2.0.0
