### ISSUE TITLE
cut_number Doesn't Work With Duplicated Values

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1046]
cut_number fails sometimes when there are duplicated values.

    > cut_number(rep(1:5, 2), 10, labels = FALSE)
    Error in cut.default(x, breaks(x, "n", n), include.lowest = TRUE, ...) : 'breaks' are not unique

This limitation should at least be stated in the documentation, but ideally changed to produce a meaningful result.

**Comment by hadley** [comment]
This is nothing to do with duplicated input - it's because you've asked for 10 bins with equal numbers of bins in them, and there are only 5 values
