### ISSUE TITLE
geom_bar(width = ) fails with datetime scales

### ISSUE THREAD

**Issue by nacnudus** [hadley/ggplot2#1050]
library(lubridate)
    library(dplyr)
    library(tidyr)
    library(ggplot2)

    lakers %>%
      mutate(month = floor_date(ymd(date), "month")) %>%
      count(month) %>%
      ggplot(aes(month, n)) + 
      geom_bar(stat = "identity", width = 1)

**Comment by hadley** [comment]
It doesn't fail - you've just made the bars 1s wide.

**Comment by nacnudus** [comment]
Whoops, sorry.
