### ISSUE TITLE
Documentation: link in coord_map is incorrect

### ISSUE THREAD

**Issue by zachcp** [hadley/ggplot2#1051]
The ggplot documentation for [coord-map](http://docs.ggplot2.org/current/coord_map.html)  links to a [dead link](http://www.inside-r.org/r-doc/mapproj/mapproject). The coordman source code shows:

```
#' @param ... other arguments passed on to
#'   \code{\link[mapproj]{mapproject}}
```

so I think link-generation for other packages is generating incorrect URLs.

not sure where to fix this but wanted to let you know.

zach cp

**Comment by Autodidact24** [comment]
@zachcp @hadley The purpose of that link is to let users know of projections chord_map takes as argument. We can link that to http://cran.r-project.org/web/packages/mapproj/mapproj.pdf.

**Comment by hadley** [comment]
This is really a staticdocs problem :/
