### ISSUE TITLE
vline not working as annotation

### ISSUE THREAD

**Issue by elbamos** [hadley/ggplot2#1052]
Reproducible example:  

data.frame(a = rnorm(1000), b = rnorm(1000)) %>% 
     ggplot(aes(x = a, y = b)) + 
     geom_point() + 
     annotate("vline", xintercept = 0)

If you specify x instead of xintercept, it throws an error that its missing xend.  If you specify xend, it still throws an error that its missing xend.

**Comment by hadley** [comment]
Yes, vline is a special geom that doesn't work as annotation. You can just do `+ geom_vline(xintercept = 0)`
