### ISSUE TITLE
ggplot2 installation fails on R 3.0.2

### ISSUE THREAD

**Issue by lbergelson** [hadley/ggplot2#1056]
Our CI server started failing all our builds today.  We were using R pegged to 3.0.2  with ggplot2.  We tracked the problem down to failing to install MASS, a prerequisite of ggplot2.  MASS updated today to version 3.9 which now requires R 3.1.0.  (http://cran.r-project.org/web/packages/MASS/index.html) 

Updating our version of R fixed the problem, but it was a very confusing issue.

**Comment by hadley** [comment]
Unfortunately I don't have the resource to support ggplot2 on old versions of R.
