### ISSUE TITLE
x axis labels wrong using facet_grid

### ISSUE THREAD

**Issue by marvel64** [hadley/ggplot2#1058]
Hi,

I sometimes use the row names of a data frame to label the x axis of my plots. Today, this resulted in incorrect assignments of x axis labels to the data. Code for a (hopefully) reproducible example is below. I was using `fill` and `color` for an explorative analysis of two categorical variables,
and noticed that after adding facet_grid on a third variable, the assignment of the x axis labels
was off.

The small table (6 x 32) can be downloaded here: https://www.dropbox.com/s/zu4i7xbg0hl64l7/ggplot2.xls?dl=0.
The data looks like this:

```
Customer | UnitA | UnitB | Category | Change | Month | CEO
---------|-------|-------|----------|--------|-------|------
A1	| 23668	| 402393	| high| 	6.491608782	| January	| John
A2	| 4098	| 83704	| high	| 7.798828697	| March	| John
A3 | 	19568	| 320138	| high	| 6.246519899	| January	| John
...
```

Now, this works:

```r
library(ggplot2)
df = read.delim("ggplot2.xls")
## creating the plot based on df as is
p = ggplot(df,
       aes(x = Customer, y = log2(Change),
           fill = CEO, color = Category)) +
   geom_bar(stat = "identity") +
   theme(text = element_text(size = 8),
         axis.text.x = element_text(hjust = 1, vjust = 1, angle = 45)) +
   scale_color_manual(values = c("firebrick3", "darkblue")) +
   scale_fill_manual(values = c("grey70", "grey80"))
   
## no difference in "Category" between simple barplot,
p
## and after adding facets
p + facet_grid(. ~ Month, scales = "free")
```

See images 1 and 2.

![image1](https://cloud.githubusercontent.com/assets/1090101/6322840/6cc78892-baec-11e4-8dd2-fd1d122467dd.png)
![image2](https://cloud.githubusercontent.com/assets/1090101/6322842/6ccc6d94-baec-11e4-9486-004629555cbe.png)

Redrawing the plot using data.frame row names to label the x axis, everything is fine
without adding facets (image3.png), but 

```r
rownames(df) = df$Customer

p = ggplot(df,
       aes(x = rownames(df), y = log2(Change),
           fill = CEO, color = Category)) +
   geom_bar(stat = "identity") +
   theme(text = element_text(size = 8),
         axis.text.x = element_text(hjust = 1, vjust = 1, angle = 45)) +
   scale_color_manual(values = c("firebrick3", "darkblue")) +
   scale_fill_manual(values = c("grey70", "grey80"))

## simple barplot correct, see image3.png
p
## now Customer and Category do not match! (image4.png)
p + facet_grid(. ~ Month, scales = "free")
```

![image3](https://cloud.githubusercontent.com/assets/1090101/6322841/6ccbedba-baec-11e4-8eef-c3a4cd2af53b.png)
![image4](https://cloud.githubusercontent.com/assets/1090101/6322843/6cccd00e-baec-11e4-91a6-d4e91b433a09.png)

Thanks!

```r
R> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.0  colorout_1.0-3 setwidth_1.0-3

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 digest_0.6.4     grid_3.1.2       gtable_0.1.2    
 [5] labeling_0.3     MASS_7.3-35      munsell_0.4.2    plyr_1.8.1      
 [9] proto_0.3-10     Rcpp_0.11.3      reshape2_1.4     scales_0.2.4    
[13] stringr_0.6.2   
R> 
```

**Comment by marvel64** [comment]
Sorry, my post was truncated. The last paragraph should have been:

Redrawing the plot using data.frame row names to label the x axis, everything is fine
without adding facets (image3.png), but after `facet_grid` the bars previously and correctly
assigned to A17, A26, A28, and A5 are now A10, A15, A26, and A28 (image4.png)!

**Comment by hadley** [comment]
Could you please try and create a minimal example that uses data that you can include inline (with `dput()`). Otherwise, I'm unfortunately unlikely to be able to find the time to look into it.

**Comment by marvel64** [comment]
I still had the data from the example above. Here it is, I hope it helps!

structure(list(Customer = structure(c(1L, 12L, 23L, 26L, 27L, 
28L, 29L, 30L, 31L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 
13L, 14L, 15L, 16L, 17L, 18L, 19L, 20L, 21L, 22L, 24L, 25L), .Label = c("A1", 
"A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17", "A18", 
"A19", "A2", "A20", "A21", "A22", "A23", "A24", "A25", "A26", 
"A27", "A28", "A29", "A3", "A30", "A31", "A4", "A5", "A6", "A7", 
"A8", "A9"), class = "factor"), UnitA = c(23668L, 4098L, 19568L, 
16634L, 29L, 852L, 32902L, 72703L, 23687L, 7196L, 69642L, 198516L, 
19585L, 144626L, 12124L, 13724L, 296L, 40196L, 57115L, 18148L, 
49740L, 76445L, 44880L, 80208L, 69155L, 0L, 2243L, 6L, 13518L, 
48524L, 30860L), UnitB = c(402393L, 83704L, 320138L, 301919L, 
23807L, 330522L, 736079L, 2097137L, 516717L, 217473L, 2152911L, 
3686157L, 600019L, 2291008L, 538752L, 798983L, 33761L, 492461L, 
559878L, 429685L, 1507116L, 2340665L, 931401L, 1069973L, 903710L, 
153811L, 124507L, 4108L, 405623L, 963861L, 1181196L), Category = structure(c(1L, 
1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 1L), .Label = c("high", 
"low"), class = "factor"), Change = c(6.491608782, 7.798828697, 
6.246519899, 6.930096667, 315.625, 148.1211268, 8.542089139, 
11.01361701, 8.329196008, 11.53843588, 11.80351512, 7.089814423, 
11.69750628, 6.048331425, 16.96733643, 22.22803183, 43.48987854, 
4.677792041, 3.742814522, 9.040402037, 11.56904704, 11.69089853, 
7.923930481, 5.093447038, 4.989571223, Inf, 21.19636169, 261.4, 
11.45690191, 7.584217425, 14.61426294), Month = structure(c(1L, 
3L, 1L, 1L, 3L, 1L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 1L, 2L, 2L, 
1L, 1L, 1L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L), .Label = c("January", 
"July", "March"), class = "factor"), CEO = structure(c(2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L), .Label = c("Jack", 
"John"), class = "factor")), .Names = c("Customer", "UnitA", 
"UnitB", "Category", "Change", "Month", "CEO"), class = "data.frame", row.names = c(NA, 
-31L))

**Comment by hadley** [comment]
Oh this is an obvious problem - you shouldn't use things that aren't variables in your data frame. The data obviously gets reordered by `facet_wrap()`, and the external variable doesn't get reordered along with it.
