### ISSUE TITLE
stat_bin() does not seem to work for integer data

### ISSUE THREAD

**Issue by ghaarsma** [hadley/ggplot2#1059]
Creating a simple data.frame with integers and binning it with stat_bin, should bin the integers.

```R
df <- data.frame(xint = sample.int(10,size = 100,replace=TRUE))
is.integer(df$xint)
ggplot() + stat_bin(data = df,aes(x=xint),geom='line')
```
Code in `stat_bin.r` shows that for integers you should not get a `binwidth defaulted to range/30` msg and it should bin at:
```R
  if (is.integer(x)) {
    bins <- x
    x <- sort(unique(bins))
    width <- width
```
Don't know the root cause but it seems integer data is no longer integer by the time it gets passed to `calculate` and `bin` functions, but shows up as an numeric.

Gabe Haarsma

**Comment by hadley** [comment]
Yeah, the only things that are integers at that point are factors. It's a suboptimal design, but it's too late to change now.
