### ISSUE TITLE
OHLC and Themes

### ISSUE THREAD

**Issue by angeloklin** [hadley/ggplot2#1060]
Hello,  
  Let me start with Thanks for ggplot.  

  I am working on automating a process that will gather financial data from Yahoo! Finance and after using a series of checks will list suitable stock, mainly as financial style charts. This is entirely for personal use, I have no intention to turn this into a product.  

  My questions/comments/request are:  
  - I know about quantmod, but I cannot modify or create something on top of it (without modifying quantmod itself, which I not interested or capable of doing, and would be beyond what I can spend in time.  
  - Any chance to have a new chart type OHLC (Open, High, Low, Close)? Normally it also comes with a pairing Candlestick chart, which I don't care for my project.  
  - As there is no such geom_ohlc yet :smile: , I am doing it all by myself, creating it all bit-by-bit.  
  - something generic that would be nice: be able to move the y axis to the right, just move, no need for a second in this case.  
  - I am using gridExtra to have charts combined (common in these financial charts) and the scales (x) do not align perfectly.  
  - mere for the looks, any change to have themes plot.background and panel.background to produce a gradient fill?  

Here is an example:
![screen shot 2015-03-02 at 23 18 44](https://cloud.githubusercontent.com/assets/2324700/6440599/c9f45800-c132-11e4-91b6-cc427e5182b8.png)

  - To create this chart I have a function that is about 200 lines of code. A good 50 are ggplot specific, so again, a geom_ohlc would be great (if we could still have the ability to play with the elements);  
  - Doing it all by hand is fine, but I would like the y axis on the right;  
  - I would like to be able to align the x scale. In this case it is a 1:55 for both (it is the same data.frame).  
  - Again, just for the looks, a gradient for panel and plot areas would be nice.  

![screen shot 2015-03-02 at 23 28 33](https://cloud.githubusercontent.com/assets/2324700/6440698/eb446594-c133-11e4-96d9-ab3bbbc328a8.png)

  - The panels do not align, if the range/format of the y axis is different;  
  - For the RSI (bottom chart) I could not make the stat_ribbon to work for the red fill under the line of 30, so I had to create a second series changing the numbers. I am still having problems when it crosses the line of 30. 
  - There is a minor gap between the two charts, probably gridExtra or simply the ways things are underneath.  

For the top chart:
```
g <- ggplot(Chart)
g <- g + geom_linerange(aes(x=Timeline, ymin=Low, ymax=High, colour=Colour), size=1.5) # High/Low bar
g <- g + geom_segment(aes(x=Timeline, xend=Timeline-0.4, y=Open,  yend=Open,  colour=Colour), size=1.5) # Open
g <- g + geom_segment(aes(x=Timeline, xend=Timeline+0.4, y=Close, yend=Close, colour=Colour), size=1.5) # Close
g <- g + scale_colour_manual(name="", values=c(Down=DC, Flat=FC, Up=UC)) # set the colour
g <- g + theme_ohlc
g <- g + geom_line(aes(x=Timeline, y=Trail), colour="darkred", size=1.3) # Trailing Stop
g <- g + geom_line(aes(x=Timeline, y=Profit.Taker), colour="green", size=1.3) # Profit Taker
# . . .
g <- g + scale_x_continuous(breaks=which(Chart$Timeline %% axis.x.interval == 0))
g <- g + theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
g <- g + theme(plot.margin  = unit(c(1, 5, -22, 15), units = "points"))
y.top <- ggplot_build(g)$panel$ranges[[1]]$y.range[2] # high y limit from the chart internal structure
g <- g + annotate("text", x = 1, y = y.top, label = code) # put title inside the chart
g <- g + labs(x="", y="")   # no x, y labels
```

For the bottom chart:
```
r <- ggplot(Chart)
r <- r + geom_hline(aes(yintercept=70), colour="black", linetype="dashed", size=0.5, alpha=0.5) # Upper line
r <- r + geom_hline(aes(yintercept=30), colour="black", linetype="dashed", size=0.5, alpha=0.5) # Lower line
r <- r + geom_line(aes(x=Timeline, y=RSI), colour="red") # RSI
r <- r + geom_ribbon(aes(x=Timeline, ymin=Cut, ymax=30), fill="red", alpha=0.5)
r <- r + scale_x_continuous(breaks=which(Chart$Timeline %% axis.x.interval == 0), 
                            labels=format(Chart$Date[which(Chart$Timeline %% axis.x.interval == 0)], axis.x.format))
r <- r + scale_y_continuous(breaks=c(30, 50, 70))
r <- r + annotate("text", x = 2, y = 75, label = "RSI(7)") # put title inside the chart
r <- r + labs(x="", y="")  # no x, y labels
r <- r + theme_ohlc
r <- r + theme(plot.margin  = unit(c(0, 5, 4, 15), units = "points"))
#     ggplot_build(r)$panel$ranges[[1]]$x.range <- ggplot_build(g)$panel$ranges[[1]]$x.range

# charting both
    grid.arrange(g, r, heights=c(0.7, 0.3))
```

Thanks again and regards,
Angelo Klin
Melbourne, Australia

**Comment by hadley** [comment]
Sorry, `geom_ohlc` is just not something I have the time to write.
