### ISSUE TITLE
mapping slot is empty when aes(x,y) is declared in geom_polygon()

### ISSUE THREAD

**Issue by Tungurahua** [hadley/ggplot2#1061]
If the x and y aesthetics are defined in geom_polygon() the gg-object contains an empty mapping-slot. This creates a problem when using gglocator() from the ggmap package. In my understanding it should not make a difference if x/y aesthetics are defined in the main plot command or in the geom for this usage.

See detailled example here:
http://stackoverflow.com/questions/28754762/how-to-locate-points-on-map-from-shapefile-in-ggplot-ggmaps

**Comment by hadley** [comment]
Could you please include a minimal reprex inline?

**Comment by Tungurahua** [comment]
Thanks for looking into this! The following script should reproduce the error message.

```R
library(maptools)
library(ggmap)

## Get shapefiles for plotting
download.file("http://ec.europa.eu/eurostat/cache/GISCO/geodatafiles/NUTS_2010_60M_SH.zip",paste0(tempdir(),"/NUTS_2010_60M_SH.zip"))
unzip(paste0(tempdir(),"/NUTS_2010_60M_SH.zip"),exdir=tempdir())
eurMap <- readShapePoly(fn=paste0(tempdir(),"/NUTS_2010_60M_SH/Data/NUTS_RG_60M_2010"))
eurMapDf <- fortify(eurMap, region='NUTS_ID')

## Create the figure
gg <- ggplot(data=eurMapDf) + geom_polygon(aes(x=long, y=lat,group=group)) 
gg

## use gglocator()
gglocator()

## >  Error in `[.data.frame`(data, , deparse(mapping$x)) : 
##    undefined columns selected
```

I get the coordinates when I provide the mapping to ggplot instead of geom_polygon (see below). However I think the above code should work as well, or am I missing out on a general concept here?

## Additional Info ##
It looks like the `mapping` slot is not always defined when creating the `gg object`. I can make `gglocator()` run by explicitly setting the mapping to the variables of the `data` slot. E.g. the following works:
    
    
```R
    gg$mapping$x  <- substitute(long)
    gg$mapping$y <- substitute(lat)
    gg
  
    ## gglocator() works as expected
    gglocator()
```

So I guess my real question is how to ensure that `mapping` is set when calling `ggplot`. 

## This works ##
All works fine when the mapping is provided in the ggplot function call and not as argument to `geom_polygon()`. E.g. 

```R
    gg2 <- ggplot(data=eurMapDf,aes(x=long, y=lat,group=group)) +   geom_polygon() 
    gg2
    
    ## works fine now
    gglocator()
```

I am not sure if there is a reason why mapping needs to be declared in the `ggplot()` call or if this is a bug. Many of the examples found around the web use the syntax I used first (or to put it differently, the syntax I used first was copy-pasted from one of the many examples I found around the web).

**Comment by hadley** [comment]
Sorry, I didn't notice that this was a problem with `gglocator()` - you should file this bug at https://github.com/dkahle/ggmap
