### ISSUE TITLE
ggplot2 requires X11 in OSX causes R to crash when closing it

### ISSUE THREAD

**Issue by ddiez** [hadley/ggplot2#1064]
It seems loading ggplot2 1.0 causes X11 to launch in OSX Yosemite 10.10.2. Closing X11 afterwards crashes R. It is not clear to me whether this is cause by ggplot2 version 1.0 or some other interaction (i.e. The issue did not appear a few weeks ago in a computer in which I though ggplot2 was installed- but can't be completely sure). Related stackoverflow [thread](http://stackoverflow.com/questions/28952128/loading-ggplot2-opens-up-x11?noredirect=1#comment46168111_28952128).

> library(ggplot2)
Need help? Try the ggplot2 mailing list: http://groups.google.com/group/ggplot2.
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
locale:
[1] C/UTF-8/C/C/C/C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] ggplot2_1.0.0
loaded via a namespace (and not attached):
 [1] MASS_7.3-39      Rcpp_0.11.5      colorspace_1.2-5 digest_0.6.8    
 [5] grid_3.1.2       gtable_0.1.2     munsell_0.4.2    plyr_1.8.1      
 [9] proto_0.3-10     reshape2_1.4.1   scales_0.2.4     stringr_0.6.2   
[13] tcltk_3.1.2

Closing X11 causes:

> XIO:  fatal IO error 35 (Resource temporarily unavailable) on X server "/private/tmp/com.apple.launchd.pOwV8XJreV/org.macosforge.xquartz:0"
      after 33 requests (33 known processed) with 0 events remaining.

**Comment by kohske** [comment]
This is due to the change in colorspace package.
The maintainers of the package are going to fix this problem.

**Comment by dwinsemius** [comment]
It doesn't occur with colorspace 1.2-4, so a temporary fix might be to revert to that version.
