### ISSUE TITLE
stat_contour fill - 2 issues

### ISSUE THREAD

**Issue by raidsteel** [hadley/ggplot2#1066]
Hello everyone,

I have been using ggplot2  for quite sometime now it's a great library! But I am stuck on some (known from what I have searched) issues of stat_contour. 

1) When I set geom="polygon" the levels that are not fully closed are not filled correctly.
2) Higher levels cover/hide the lower levels.

Straight to a simple example to show you what I mean:
### Creating the data
>library(ggplot2)
x = seq(-1, 1, length.out = 100)
y = x
R = expand.grid(x, y)
dim(R)
names(R) = c("x", "y")
R$z = R$x^2 + R$y^2
head(R)

### Ploting contour
>ggplot(R, aes(x = x, y = y, z = z)) + stat_contour()
![stat_contour1](https://cloud.githubusercontent.com/assets/8446323/6605024/6ad40550-c835-11e4-9528-9361885931e0.png)

### Ploting filled contour by setting geom="polygon"
>ggplot(R, aes(x = x, y = y, z = z)) + stat_contour(geom="polygon")
![stat_contour2](https://cloud.githubusercontent.com/assets/8446323/6605028/72b6195c-c835-11e4-8c19-c0faf60e9553.png)

### In order to see what is filled correctly and what is not
>ggplot(R, aes(x = x, y = y, z = z, fill=..level..)) +
  stat_contour(geom="polygon") + 
  stat_contour() + 
  scale_fill_gradient(low = "blue", high = "red") +
  coord_map(xlim=c(-1,1),ylim=c(-1,1))
![stat_contour3](https://cloud.githubusercontent.com/assets/8446323/6605033/77587982-c835-11e4-9cde-aa6f3b24065c.png)

### And if we reverse the values of R$z we can display the inner/hidden levels (multiply *-1)
>ggplot(R*-1, aes(x = x, y = y, z = z, fill=..level..)) +
  stat_contour(geom="polygon") + 
  stat_contour() + 
  scale_fill_gradient(low = "blue", high = "red") +
  coord_map(xlim=c(-1,1),ylim=c(-1,1))
![stat_contour4](https://cloud.githubusercontent.com/assets/8446323/6605037/7f0b83cc-c835-11e4-8c41-ef94b5d90a92.png)

### The first problem is somehow fixed (not completely) by expanding my grid with the same values that has in each side. Something like this:
>R_fill <- subset(R, x==1 | x==-1 | y==1 | y==-1)
R_fill[R_fill$x==1,]$x=5
R_fill[R_fill$x==-1,]$x=-5
R_fill[R_fill$y==1,]$y=5
R_fill[R_fill$y==-1,]$y=-5
R_fill <- rbind(R_fill,R)
ggplot(R_fill*-1, aes(x = x, y = y, z = z, fill=..level..)) +
  stat_contour(geom="polygon") + 
  stat_contour() + 
  scale_fill_gradient(low = "blue", high = "red") +
  coord_map(xlim=c(-1,1),ylim=c(-1,1))
![stat_contour5](https://cloud.githubusercontent.com/assets/8446323/6605039/84390388-c835-11e4-8267-a9047de12f63.png)

To sum up, (1) every level that is higher than 1 is not filled correctly since the level line is not closed on the edges. So whenever the level is not closed, ggplot is forcing a closure by connecting the two edges of the semi-circles. Maybe the only way to correct the above problem is to handle and plot the levels in stat_contour as polygons with certain coordination. Can I somehow obtain the exact point position that belong to each contour line? If I could then I would be able to plot them as polygons and set a certain box around the region I want to plot and "close" the "un-closed" levels in order to be filled correctly.

And (2) since ggplot (to my understanding) is plotting lower to higher levels, the lower levels are obscured. I have no idea how this could be fixed, since some datasets contain regions of lower values around higher levels.

I don't know how hard is to tackle and correct these problems since I have no experience on the ggplot code. It would be really useful if stat_contour acted as filled.contour, since ggplot2 has some many possibilities. So I would like to hear your thoughts and your suggestions.

Thank you in advance,
Thanos

**Comment by chengvt** [comment]
I am also hoping that stat_contour(geom="polygon") can act as filled.contour too. Hopefully this problem will be considered.

**Comment by hadley** [comment]
Fixing this is complicated because ggplot2 uses `contourLines()`. `contourLines()` doesn't complete contour lines to the edges of the plot, so someone either needs to rewrite the contouring algorithm from scratch to do this (hard), or look at the output from `contourLines()` and patch it up (somewhat less hard).

**Comment by raidsteel** [comment]
Yeah it demands some serious coding to make it work without flaws. For the time being I did some easy changes in the filled.contour and I am using that. But as I said ggplot2 is more powerful. I think it would be good to have this tread in case someone in the future wants to work on that update. Thanks for the feedback, Cheers!

**Comment by LukeDetwiler** [comment]
raidsteel,

I'd be very interested in your altered filled.contour code. I'm having similar issues with blank polygons in stat_contour and the current functionality for filled.contour doesn't provide the necessary functionality for me.

**Comment by chengvt** [comment]
@LukeDetwiler not sure if this is what you are looking for but you may find this hack useful. https://stackoverflow.com/questions/28469829/how-to-fill-in-the-contour-fully-using-stat-contour
