### ISSUE TITLE
Width of error bars is calculated by the number of groups and not by the `width` argument. 

### ISSUE THREAD

**Issue by grssnbchr** [hadley/ggplot2#1068]
When attempting to draw error bars in a plot with multiple groups, the width of the error bar seems to be calculated dynamically from the number of groups in the plot, e.g.:

```
hod <- some data (see Stackoverflow link below

dayplot <- ggplot(hod, aes(x=h, y=mean, colour=as.factor(t),group=as.factor(t))) + 
    geom_line() +
    geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci),
                  width=1,
                  size=0.5)
```
Let's say in example A) I have one group, in example B) I have 5 groups. In order to have the same width of error bars in both examples, I need to set `width = 5` in example B). 

See [this Stackoverflow question](http://stackoverflow.com/questions/19420903/width-of-error-bars-in-ggplot2/29059601) for more information and illustrative graphics.

**Comment by hadley** [comment]
Could you please include a minimal reproducible example inline?

**Comment by orb16** [comment]
Just encountered this. Dodging also doesn't occur which is fine but it would be nice to have constant errorbar width across the plot. Here's an example. 
```{r}
data(warpbreaks)
require(dplyr)
require(ggplot2)

warpbreaks %>%
  group_by(wool, tension) %>%
  summarise(mean_breaks = mean(breaks),
            se_breaks = sd(breaks)/sqrt(length(breaks))) %>%
  filter(! (wool == "B" & tension == "M") ) %>%
  ggplot(aes(x = tension, y = mean_breaks)) +
  geom_errorbar(aes(group = wool,
                    ymin = mean_breaks - se_breaks,
                    ymax = mean_breaks + se_breaks), 
                position = position_dodge(0.2),
                width = 0.4) +
  geom_point(aes(shape = wool), size = 3, 
             position = position_dodge(0.2))
```

**Comment by miguelazo82** [comment]
I am having the same problem with different widths - has an option for constant width of errorbars been included in the mean time?

**Comment by qdread** [comment]
People are still having trouble with this one. I had the problem myself and encountered this question on stackoverflow: https://stackoverflow.com/questions/42716425/ggplot2-position-dodge-affects-error-bar-width. It would be helpful to have some way to fix this without an awkward workaround.
