### ISSUE TITLE
Can't use named color vectors in scale_color/fill_manual

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/ggplot2#1073]
Reproducible example (blank plot):

    devtools::install_github("hrbrmstr/swatches")
    library(swatches)
    library(ggplot2)

    keep_the_change <- read_ase(system.file("palettes", "keep_the_change.ase", 
                                            package="swatches"))

    gg <- ggplot(mtcars, aes(x=mpg, y=disp))
    gg <- gg + geom_point(aes(col=factor(gear)), size=3)
    gg <- gg + scale_color_manual(values=keep_the_change)
    gg <- gg + theme_bw()
    gg

If that's changed to `scale_color_manual(values=unname(keep_the_change))`

I was going to add an `unname` into the appropriate ggplot2 color/fill scale functions and submit a PR but wanted to check here first to ensure this isn't just me missing something.

**Comment by hadley** [comment]
That's by design - it lets you match specific values to specific colours.
