### ISSUE TITLE
facet strings in facet_wrap?

### ISSUE THREAD

**Issue by ackman678** [hadley/ggplot2#1074]
Strings can be used for facets instead of formula objects in facet_grid() but not facet_wrap().

![screen shot 2015-03-25 at 3 40 21 pm](https://cloud.githubusercontent.com/assets/4317308/6837050/4df217c6-d305-11e4-9170-24aeddb4fa85.png)

![screen shot 2015-03-25 at 3 41 14 pm](https://cloud.githubusercontent.com/assets/4317308/6837077/70f3de8a-d305-11e4-8246-fecbc7c6abab.png)

**Comment by hadley** [comment]
Docs updated in the dev version
