### ISSUE TITLE
Reversed stacked barplot with facet_wrap

### ISSUE THREAD

**Issue by richardbeare** [hadley/ggplot2#1078]
Hi,
I'm seeing a very strange error, with all versions of ggplot2 (mac, windows from can, mac from github). In a faceted plot the last facet has the stacking order reversed:

library(RCurl)
table.text <- getURL("https://raw.githubusercontent.com/richardbeare/ggplotissues/master/barplot_problem.csv")
dat <- read.csv(text=table.text)
#dat <- read.csv("barplot_problem.csv")
library(ggplot2)
ggplot(dat, aes(x=counts.vc, y=duration, 
                             colour=duration.type, fill=duration.type)) + 
  stat_summary(fun.y=mean, geom="bar", position="stack") + facet_wrap(~speaker)

The resulting plot on my system is attached.

![s_reversed](https://cloud.githubusercontent.com/assets/780449/6938953/80fd8d68-d8b3-11e4-8822-35a4257fd0d4.png)

**Comment by joranE** [comment]
It's actually not ggplot, per se, what's going wrong is happening in some plyr functions that are used to calculate a single grouping variable. (Specifically, `plyr::id`.) That function doesn't "know" anything about how the groups are supposed to be ordered, so in some cases the somewhat convoluted arithmetic there ends up with orderings you didn't intend. The easiest fix is to explicitly specify `group = duration.type`.

**Comment by richardbeare** [comment]
Thanks - that seems to fix it. I thought I'd used that combination, but obviously not.
