### ISSUE TITLE
error bar with stacked barplot

### ISSUE THREAD

**Issue by richardbeare** [hadley/ggplot2#1079]
In a problem related to the data in the previous question, behaviour when adding error bars to stacked bar plots isn't sensible - seems the mean position isn't correctly adjust by the stacking offset. Not sure if I'm doing this correctly:

ibrary(RCurl)
table.text <- getURL("https://raw.githubusercontent.com/richardbeare/ggplotissues/master/barplot_problem.csv")
dat <- read.csv(text=table.text)
#dat <- read.csv("barplot_problem.csv")
library(ggplot2)
ggplot(dat, aes(x=counts.vc, y=duration, 
                             colour=duration.type, fill=duration.type)) + 
  stat_summary(fun.y=mean, geom="bar", position="stack") + 
  stat_summary(fun.data=mean_cl_normal, geom="errorbar", colour="black") +
  facet_wrap(~speaker)

**Comment by hadley** [comment]
This s a rather confusing display - what does the error bar on the top represent? The error associated with "dur.vowels" or "dur.vc" + "dur.vowels"?   I don't think it's reasonable to stack error bars in general (or at least not without a lot of thought about what it means), so you'll need to do the calculations "by hand"

**Comment by richardbeare** [comment]
Hi,
As it turned out, the "customer" didn't want stacking after all, so this didn't matter. However, the idea was that the error bars would be separate for dur.vc and dur.vowels. The first bar (count.vc=0) confuses the issue because the two values are the same and the two error bars get drawn over the top of one another. For counts greater than zero, I'd have thought it makes sense to have the error bar glued to the top of the appropriate bar component. At the moment they are getting drawn correctly for the orange, but not being offset for the blue. Not sure if I can see a way to fix it by hand without performing all the calculations manually and creating a new dataframe. 

Thanks for your feedback.

# version with group option added to correct colour ordering.
library(RCurl)
table.text <- getURL("https://raw.githubusercontent.com/richardbeare/ggplotissues/master/barplot_problem.csv")
dat <- read.csv(text=table.text)
#dat <- read.csv("barplot_problem.csv")
library(ggplot2)
ggplot(dat, aes(x=counts.vc, y=duration, group=duration.type,
colour=duration.type, fill=duration.type)) +
stat_summary(fun.y=mean, geom="bar", position="stack") +
stat_summary(fun.data=mean_cl_normal, geom="errorbar", colour="black") +
facet_wrap(~speaker)
