### ISSUE TITLE
stat_km and geom_km for Kaplan-Meier Survival curves

### ISSUE THREAD

**Issue by sachsmc** [hadley/ggplot2#1080]
People occasionally ask about plotting survival curves with ggplot2. While it is possible, [see here for some examples](https://stackoverflow.com/search?q=%5Bggplot2%5D+survival), it's not done in the "ggplot way" and people often revert to the base plot because it's so much easier (but not nearly as powerful).  

I've worked a bit on adding a stat and geom for computing and plotting survival curves [here](https://github.com/hadley/ggplot2/compare/master...sachsmc:feature/kmcurve). I view it as along the same lines as `stat_ecdf` but for censored data. Before submitting a pull request I wanted to ask if this would be suitable for inclusion in ggplot2, or if it would be better as a standalone package?

Here's an example code and plot: 

```r
df <- survival::lung
ggplot(df, aes(x = time, status = status, color = factor(sex))) + geom_km()
```

![image](https://cloud.githubusercontent.com/assets/5464185/6966565/17a8f7ce-d928-11e4-9b02-1a517c532614.png)

**Comment by MarcinKosinski** [comment]
It looks like `autoplot` function from package `survMisc` produces KM curves for `survfit` object in a `ggplot-way`. It also produces a table with risk set size dependency over time.
http://www.inside-r.org/packages/cran/survMisc/docs/autoplot

````{Ruby}
library(survMisc)
data(kidney, package="KMsurv")
s1 <- survfit(Surv(time=time, event=delta) ~ type, data=kidney)
autoplot(s1)
autoplot(s1, CI=TRUE, pval=TRUE, plotTable=TRUE, divideTime=5,
 legendLabs=c("surgical", "percutaneous"),
 title="Time to infection following catheter placement \n
   by type of catheter, for dialysis patients")
s1 <- survfit(Surv(time=time, event=delta) ~ 1, data=kidney)
autoplot(s1)
data(rectum.dat, package="km.ci")
s1 <- survfit(Surv(time, status) ~ 1, data=rectum.dat)
### change confidence intervals to log Equal-Precision confidence bands
km.ci::km.ci(s1, method="logep")
autoplot(s1, bands=TRUE)
````

**Comment by sachsmc** [comment]
@MarcinKosinski  Thanks for pointing that out, I was not aware of that function. While this autoplot does use ggplot2 to create a survival plot, I don't agree that it is done in the "ggplot way". I.e., there is no support for faceting, scale transformations, or even themes. Furthermore, it ignores the key concepts of the grammar of graphics, such as aesthetic mappings, layers, statistical transformations, and so on.

**Comment by hadley** [comment]
I'd rather it go in a separate package - have you considered adding the data related parts to broom?

**Comment by fpbarthel** [comment]
I'm very much interested in these functions, have been looking for survival functionality for ggplot forever. Found some solutions but none have been very satisfactory. How can I access these functions?

**Comment by sachsmc** [comment]
@fpbarthel They're available at my repo [here](https://github.com/sachsmc/ggkm), still under development and not on CRAN yet.

**Comment by fpbarthel** [comment]
Thanks

**Comment by MarcinKosinski** [comment]
Have a look at 'survminer' package :) available at CrAN and github 

Marcin Kosinski

Dnia 18.02.2016 o godz. 18:18 fpbarthel <notifications@github.com> napisał(a):

**Comment by srw6v** [comment]
@MarcinKosinski great package.  Much more flexible than autoplot.
