### ISSUE TITLE
Histograms for multiple distributions in one plot

### ISSUE THREAD

**Issue by jergosh** [hadley/ggplot2#1081]
I've been looking for a way to plot histograms for multiple distributions in a single plot. I've tried to use position="dodge" but in case of my data it's very hard to see anything.

Then I came across this SO thread: http://stackoverflow.com/questions/3541713/how-to-plot-two-histograms-together-in-r (the first couple of plots are density but the rest are actual histograms) and all solutions there are based on using transparency. It occurred to me that a more universal way to do it would be to use solid bars but for each bin, plot the bars in the order from highest to lowest so that all of them are visible (hope this makes sense). I've had a cursory look at the ggplot code and couldn't see a simple way of implementing this that would be compatible with how things are organised. 

I would really appreciate any suggestions on how to get this kind of plot to work.

**Comment by hadley** [comment]
I'd recommend using `geom_freqpoly()` instead. There's no guarantee that all of the bars will be different, so while ordering will help, it's not a panacea.
