### ISSUE TITLE
integer64 not supported by ggplot2

### ISSUE THREAD

**Issue by sfischme** [hadley/ggplot2#1091]
It seems that when using large integer values (e.g., int64 through the bit64 package) one has to always define the scales:

```
ggplot(q,aes(x=time,y=p)) + geom_line()
Don't know how to automatically pick scale for object of type integer64. Defaulting to continuous
Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1
```

It would be nice if ggplot would support this out of the box.

**Comment by hadley** [comment]
I'd be happy to review a PR that implemented this, but I suspect it would be quite a lot of work.  (Also the bit64 approach is rather fragile - if any operation loses the class attribute, you'll silently get wrong values)

**Comment by sfischme** [comment]
Ok. In case others run into the same problem. A simple workaround is the following:

```
ggplot(q,aes(x=as.integer(time),y=p)) + geom_line()
```

**Comment by hadley** [comment]
I don't think that will work in general unless your integers happen to all be 32-bit integers already.

**Comment by tylermanning** [comment]
Is there no workaround for this? We have no choice but to use 64-bit integers for unix epoch time stamps if we want to maintain precision. So either we give up accuracy in order to visualize it or we just don't visualize it with ggplot?
