### ISSUE TITLE
Extent of stat_smooth() should be ignored when determining graph limits

### ISSUE THREAD

**Issue by eMPee584** [hadley/ggplot2#1093]
For example, when plotting frequency over year and the data trends upwards at the beginning, `stat_smooth()` will go below 0% and the graph limits will expand accordingly, which is bogus in this case. The workaround to explicitly set visual limits with `coord_cartesian()` works everywhere, except when using `facet_grid(scales = "free_y")`.. so after giving it some thought, IMHO `stat_smooth()` should always be ignored when determining the data limits. Does that make any sense to you?
BTW, if `coord_cartesian(ylim = c(0, NA))` would proceed to only override the lower boundary, that would also be a solution to this.

**Comment by hadley** [comment]
I don't think it makes sense to special-case the behaviour of one statistic - and it is reasonable to know that your smooth is giving unreasonable predictions.
