### ISSUE TITLE
Add optimization of scatterplot point opacity level?

### ISSUE THREAD

**Issue by robertfeldt** [hadley/ggplot2#1095]
This recent CHI'15 paper shows how people seem to prefer a "Mean Opacity of Utilized Pixels" (MOUP) in scatterplots of around 40% regardless of point distribution:

http://autodeskresearch.com/pdf/Overplotting-authored.pdf

There is also an illustrative video here:

http://autodeskresearch.com/publications/overplotting

Would be nice to add a way that one can automatically tune this in a ggplot2 scatterplot. Is there some simple way I can access the generated pixels and/or their opacities directly and then tune them?

**Comment by hadley** [comment]
Unfortunately not - R's graphics system is vector based, so it's extremely difficult to calculate this sort of metric. Thanks for the pointer to the paper!
