### ISSUE TITLE
suppressMessages not working with geom_histogram

### ISSUE THREAD

**Issue by vnijs** [hadley/ggplot2#1101]
library(ggplot2)
suppressMessages( ggplot(diamonds, aes(x = price)) + geom_histogram() )

Result: "stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this."

Occurs on Mac and Windows with R 3.2.0 with ggplot2 1.0.1
Also on Windows with R 3.1.3 with ggplot2 1.0.0

suppressMessages(message("test message")) does work as expected

**Comment by BrianDiggs** [comment]
It is working as designed, though maybe not as expected. In ggplot, plots are created in two phases: the definition of the plot and the rendering of the plot. An expression like `ggplot(diamonds, aes(x = price)) + geom_histogram()` defines a plot, and that definition can be stored in an object (and further modified). However, it is not until `print` is called on that object that the actual visual graphic is made. Making that visual includes many steps. The warning that you see is from one of those steps, specifically the binning step. So what happened was you defined an object, suppressed the messages associated with the creation of that object, and then that was printed which generated the message you saw.

As a further example, consider splitting it into separate steps and also look at what happens when you change the order of the steps with an explicit `print`:

```r
> p <- ggplot(diamonds, aes(x=price)) + geom_histogram()
> print(p)
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> suppressMessages(p <- ggplot(diamonds, aes(x=price)) + geom_histogram())
> suppressMessages(print(p))
> suppressMessages(print(ggplot(diamonds, aes(x=price)) + geom_histogram()))
> 
```

**Comment by hadley** [comment]
Thanks for the explanation @BrianDiggs!

**Comment by vnijs** [comment]
Thank you for your response and the explanation. I had tested the assign-the-print option as well but that produced the same problem. Furthermore, all the examples provided in your reply print the 'stat_bin' message, i.e., it is *not* suppressed by suppressMessages at all. See also example below:

> p <- ggplot(diamonds, aes(x = price)) + geom_histogram()
> suppressMessages( print(p) )
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.

I do not recall this being an issue in the prior version of ggplot2 on my systems. Is there a way to install the pre-1.0.0 version?

**Comment by vnijs** [comment]
Asked a student to check on his system (Windows 8.1 with R-3.1.2) and the latest ggplot2 from CRAN:

> p <- ggplot(diamonds, aes(x = price)) + geom_histogram()
> suppressMessages( print(p) )
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.

**Comment by BrianDiggs** [comment]
Hmm. That's odd. I got those results with a configuration of

```r
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.6.8 (Snow Leopard)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 digest_0.6.8     grid_3.1.3       gtable_0.1.2    
 [5] labeling_0.3     MASS_7.3-40      munsell_0.4.2    plyr_1.8.1      
 [9] proto_0.3-10     Rcpp_0.11.5      reshape2_1.4.1   scales_0.2.4    
[13] stringr_0.6.2   
```
I have not yet updated to R version 3.2.0, but my version is still ahead of yours. I really don't know what could be causing it. Perhaps someone else can test it with your exact configuration (which I do not have).

**Comment by vnijs** [comment]
@BrianDiggs Here is my sessionInfo. I asked two students using R3.1.3 and R3.2 on Windows and they get the same result with ggplot2 1.0.1

`> library(ggplot2)
> p <- ggplot(diamonds, aes(x = price)) + geom_histogram()
> suppressMessages( print(p) )
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] labeling_0.3     MASS_7.3-40      colorspace_1.2-6 scales_0.2.4     magrittr_1.5     plyr_1.8.2       tools_3.2.0      gtable_0.1.2     reshape2_1.4.1   Rcpp_0.11.6      stringi_0.4-1   
[12] grid_3.2.0       stringr_1.0.0    digest_0.6.8     proto_0.3-10     munsell_0.4.2 `

**Comment by hadley** [comment]
`stat_bin()` definitely uses `message()`, so if `suppressMessage()` doesn't work, it's probably an R buglet.

**Comment by vnijs** [comment]
@hadley Seems like it. I installed the version 0.9.3.1 from github (nice devtools feature by the way!) and get the same result. The strange thing is that I have only seen this effect with ggplot2 plotting messages. See below. Suggestions on how to proceed?

> suppressMessages(library(ggplot2))
> p <- ggplot(diamonds, aes(x = price)) + geom_histogram()
> suppressMessages( print(p) )
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> 
> suppressMessages(library(dplyr))
> 
> message("Test suppress")
Test suppress
> suppressMessages(message("Test suppress"))
>

**Comment by BrianDiggs** [comment]
I've update my version of R, and now I am seeing it as well

```r
> library(ggplot2)
> p <- ggplot(diamonds, aes(x=price)) + geom_histogram()
> print(p)
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> suppressMessages(p <- ggplot(diamonds, aes(x=price)) + geom_histogram())
> suppressMessages(print(p))
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> suppressMessages(print(ggplot(diamonds, aes(x=price)) + geom_histogram()))
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> sessionInfo()
R version 3.2.0 Patched (2015-05-08 r68348)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.6.8 (Snow Leopard)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] labeling_0.3     MASS_7.3-40      colorspace_1.2-6 scales_0.2.4     magrittr_1.5     plyr_1.8.1      
 [7] tools_3.2.0      gtable_0.1.2     reshape2_1.4.1   Rcpp_0.11.5      stringi_0.4-1    grid_3.2.0      
[13] stringr_1.0.0    digest_0.6.8     proto_0.3-10     munsell_0.4.2   
```
I'll try to get some time in the next few days to hunt down exactly where the bug is (in R 3.2.0, or something which changed in R 3.2.0 which exposed a bug in ggplot2). In the meantime, I do not have a workaround.

**Comment by BrianDiggs** [comment]
I've narrowed down the problem, though I have not completely isolated it. However, I do know that it is not a bug in ggplot. The problem is in `plyr:::loop_apply`. Here is some code which demonstrates that:

```r
library("ggplot2")
library("proto")

mg <- function(i=NULL) {
  DF <- transform(mtcars, x=mpg)
  sb <- stat_bin()
  sb$stat$informed <- FALSE
  sb$stat$calculate(data = DF, 
                    scales=list(x=scale_x_continuous(), 
                                y=scale_y_continuous()))
  invisible(NULL)
}

mg()
suppressMessages(mg())
plyr:::loop_apply(1, mg)
suppressMessages(plyr:::loop_apply(1, mg))
plyr:::loop_apply(1, function(i) suppressMessages(mg(i)))
lapply(seq_len(1), mg)
suppressMessages(lapply(seq_len(1), mg))
```

the output of which is

```r
> mg()
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
> suppressMessages(mg())
> plyr:::loop_apply(1, mg)
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
[[1]]
NULL

> suppressMessages(plyr:::loop_apply(1, mg))
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
[[1]]
NULL

> plyr:::loop_apply(1, function(i) suppressMessages(mg(i)))
[[1]]
NULL

> lapply(seq_len(1), mg)
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
[[1]]
NULL

> suppressMessages(lapply(seq_len(1), mg))
[[1]]
NULL
```

I will shortly be filing a bug on plyr and reference this.

**Comment by vnijs** [comment]
[This](https://github.com/hadley/plyr/commit/3256bb524dbe04982ad54300057dd1e1bf852906) fix for [plyr](https://github.com/hadley/plyr/issues/256#event-323508131) resolves the ggplot2 issue I was having. Thanks @BrianDiggs and @hadley!
