### ISSUE TITLE
Semi-transparent borders around bars not consistent

### ISSUE THREAD

**Issue by BrianDiggs** [hadley/ggplot2#1103]
# Summary

The algorithms for drawing the lines around bars in `geom_bar` assume that the color is completely opaque and can lead to different colors due to overplotting when semi-transparent.

# Example

```r
library("ggplot2")
library("scales")
ggplot(mtcars[1:8,], aes(x = factor(carb), y = disp)) +
geom_bar(stat = "identity", lwd = 7, colour = alpha("white", 0.5)) +
theme(panel.background = element_rect(fill = "lightblue"))
```

![](https://cloud.githubusercontent.com/assets/463252/7579755/bc780682-f81d-11e4-92b2-ecf9bde65461.png)

The borders are 50% transparent white and absurdly large to make the effects more obvious. The borders between the stacked bars are not all the same color.

# Discussion

Fixing this completely would be very hard, especially the double plotting that occurs at the corners. I submit this bug more to mark it as a known issue than to get (or submit) a fix. What I might suggest is a comment in the details section of `geom_bar` such as

> Borders around bars (defined by the `colour` aesthetic) are drawn assuming a completely opaque color. A semi-transparent color can be used, but the effects will not be as expected.

**Comment by hadley** [comment]
Hmmm, I'm happy to improve the docs, but I'm not loving that explanation - the results are exactly as I expect.

**Comment by hadley** [comment]
I'm going to close for now. Feel free to re-open (or do a PR) if you think of a good wording.
