### ISSUE TITLE
Tweak position of categorical data

### ISSUE THREAD

**Issue by tongcx** [hadley/ggplot2#1109]
For the following example

    x <- c(1,3,2,5)
    y <- c("a","c","d","c")
    qplot(x, y)
How do I move all points a bit downward? I can use `position_jitter`, but that's random. I think the best solution is to program a customized version of sth like `position_jitter`. However after reading source code
https://github.com/hadley/ggplot2/blob/master/R/position-jitter.r
https://github.com/hadley/ggplot2/blob/master/R/position-.r
I am still not clear how to achieve this.

**Comment by hadley** [comment]
Maybe call it position nudge?
