### ISSUE TITLE
%+% only works if it's the first argument

### ISSUE THREAD

**Issue by jcfisher** [hadley/ggplot2#1110]
I don't know if this a bug or a deliberate design decision, but `%+%` only works if it's the first argument.  To show this in an example, say I'm plotting 5 straight lines, and then I want to omit 2 of them:

    library(ggplot2)
    library(dplyr)
    
    # Sample data: lines
    df <- data.frame(
        x = rep(1:20, each = 5),
        grouping = factor(rep(1:5, 20))
        )
    df <- within(df, y <- x * as.numeric(grouping))
    
    # Plot the raw data
    (p1 <- qplot(data = df, x = x, y = y, color = grouping, geom = "line"))
    
    # Subset out 2 of the 5 lines.  This works:
    p1 %+% filter(df, grouping != 3, grouping != 4) +
      scale_color_brewer(type = "div") %+%
    
    # But this doesn't.  Seems like this should throw an error, at minimum
    p1 + scale_color_brewer(type = "div") %+%
      filter(df, grouping != 3, grouping != 4)

If this isn't a bug, it does seem like there should at least be a warning when the user puts in a `%+%` command that ggplot ignores, so that way I know which data the plot is using in cases where it might not be obvious.

Thanks!  Please let me know if I can help in any other way.

**Comment by hadley** [comment]
This is unfortunately a consequence of operator precedence in R - you'll need to use brackets.
