### ISSUE TITLE
Option for symmetry in geom_violin

### ISSUE THREAD

**Issue by mwalkup55** [hadley/ggplot2#1112]
The beanplot package outputs a similar charts to the violin chart, but it has the argument "side"  where you can choose to plot the left, right or both sides of the density.  The geom_violin defaults to plotting a symmetric density, and I do not believe there is an argument similar to beanplots "side"

An example is given as the first comment on this SO question:

http://stackoverflow.com/questions/26214471/how-to-make-beanplot-and-boxplot-in-the-same-chart

**Comment by hadley** [comment]
I'd be happy to review a PR for this, but I don't plan to implement it myself.
