### ISSUE TITLE
Add 3D capabilities

### ISSUE THREAD

**Issue by flying-sheep** [hadley/ggplot2#1113]
For techniques like spectral decomposition (PCA, diffusion maps, …), the actual units on the axes are less important than visual closeness and separation.

A 3D→2D projection of three principal/diffusion components is therefore desirable and more useful than a plot matrix (like ggpairs)

**Comment by hadley** [comment]
Unfortunately this is outside the scope of ggplot2

**Comment by flying-sheep** [comment]
and why, if i may ask?

**Comment by lefft** [comment]
interesting -- anyone have any insight on the main challenges for representing 3d surfaces or scatterplots in `ggplot2::`??

from a user perspective, the syntax could be straightforward: 

```r
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, z=Petal.Length, color=Species) + 
  geom_3d_scatter()
```

but obviously this says nothing about how complicated the implementation would have to be!

**Comment by thomasp85** [comment]
Have a look at https://github.com/AckerDWM/gg3D

But be aware that there are probably reasons beyond technical for the lack of 3D support in ggplot2

**Comment by flying-sheep** [comment]
“out of scope” includes the possibility of a technical reason in my eyes, as well as “it’s too hard to implement” and “it inflates the API too much”.
