### ISSUE TITLE
ggplot doesn't show in RStudio when mixed with base plot

### ISSUE THREAD

**Issue by mesner** [hadley/ggplot2#1117]
Submitting ggplot and base plot in a single batch (using multiple lines and ctrl + Enter or Source or within a function) causes the ggplot window to be blank.  If the theme is not modified, the ggplot shows fine.

To reproduce:
Within R studio, place the following code in a new file and Source it.
```
ggplot(cars,aes(speed,dist)) + geom_point() +
theme(legend.title=element_blank());
plot(cars)
```

Expected Results:
Both plots show in the Plots window

Actual Results:
The second (base) plot shows, but the first plot (ggplot) is blank.

Environment:                     
```
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.0                         
year           2015                        
month          04                          
day            16                          
svn rev        68180                       
language       R                           
version.string R version 3.2.0 (2015-04-16)
nickname       Full of Ingredients     
```

**Comment by hadley** [comment]
Works for me. You might need to upgrade your RStudio
