### ISSUE TITLE
Position dodge does not work in geom_point

### ISSUE THREAD

**Issue by zhuzelong** [hadley/ggplot2#1119]
Would you mind referring to the post in StackOverflow [here](http://stackoverflow.com/questions/30768312/dodge-points-in-point-char-with-ggplot2/30768450#30768450)?

I tried to dodge the points, but only horizontal dodge (`position_dodge(width=1)`) works, the vertical dodge (`position_dodge(height=1)`) does not work.

Thank you.

**Comment by hadley** [comment]
Dodging is only defined for geoms that have ymin and ymax - the bug is actually it works at all.
