### ISSUE TITLE
Symbol ∈ (unicode u2208) cannot be displayed in ggplot axis.text or title

### ISSUE THREAD

**Issue by tingtingzhan** [hadley/ggplot2#1129]
However some other unicode is OK, such as the "double angle" » (unicode u00BB, using "\u00BB" in R).

Is that I miss some component of the program?

Thanks :)

**Comment by hadley** [comment]
Please provide a reproducible example.

**Comment by tingtingzhan** [comment]
dat <- data.frame(
  time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
  total_bill = c(14.89, 17.23)
)
dat

library(ggplot2)

# Figure 1.  Unrecognized symbol
ggplot(data=dat, aes(x=time, y=total_bill)) + geom_bar(stat="identity") + ggtitle("\u2208")
# Figure 2.  Good
ggplot(data=dat, aes(x=time, y=total_bill)) + geom_bar(stat="identity") + ggtitle("\u00BB")


![fig1](https://cloud.githubusercontent.com/assets/8326410/8206176/3159df66-14c5-11e5-9454-66aed5f526c2.png)
![fig2](https://cloud.githubusercontent.com/assets/8326410/8206175/31589c3c-14c5-11e5-89b8-30e76c35276c.png)

**Comment by tingtingzhan** [comment]
Meanwhile if I type "\u2208" directly in the console, it will be displayed correctly

> "\u2208"
[1] "∈"

Thanks!

**Comment by hadley** [comment]
It's probably a font problem, so there's not much I can do about it inside ggplot2. Have you looked at `showtext()`?

**Comment by tingtingzhan** [comment]
Looking now.  I'll post a note here if I sort this out!
