### ISSUE TITLE
vjust not working for axis.text.x

### ISSUE THREAD

**Issue by geritwagner** [hadley/ggplot2#1131]
```vjust``` does not seem to work for ```axis.text.x``` if ```angle=0``` (or without ```angle```). This is a short example with the same values for ```vjust```:
```R
library(ggplot2)

png(filename="without-angle.png",type="cairo", units="in", width=3, height=2, pointsize=12, res=96)
ggplot(ChickWeight, aes(x=Diet)) + geom_boxplot(aes(y=weight)) + theme(axis.text.x=element_text(vjust=-50))
dev.off()
```
![without-angle](https://cloud.githubusercontent.com/assets/3872815/8187183/ce1c2ab0-144e-11e5-8eaf-bf6c22c20aaf.png)

```R
png(filename="with-angle.png",type="cairo", units="in", width=3, height=2, pointsize=12, res=96)
ggplot(ChickWeight, aes(x=Diet)) + geom_boxplot(aes(y=weight)) + theme(axis.text.x=element_text(angle=1, vjust=-50))
dev.off()
```

![with-angle](https://cloud.githubusercontent.com/assets/3872815/8187184/ce1d373e-144e-11e5-8281-69abf8943180.png)

**Comment by hadley** [comment]
I don't think you should expect `vjust` to work like that - it's only defined to take a value between 0 and 1, and indeed it does work with multi line labels:

```R
df <- data.frame(x = c("a", "a\nb","a\nb\nc"), y = 1:3)
ggplot(df, aes(x, y)) + 
  geom_point() + 
  theme(axis.text.x = element_text(vjust = 0))

ggplot(df, aes(x, y)) + 
  geom_point() + 
  theme(axis.text.x = element_text(vjust = 1))
```
