### ISSUE TITLE
geom_violin produces error when all values in a series are the same

### ISSUE THREAD

**Issue by RichardLorenz** [hadley/ggplot2#1136]
Posted on StackOverflow:

http://stackoverflow.com/questions/30721548/geom-violin-produces-error-when-all-values-in-a-series-are-the-same

    library(ggplot2)
    d1 <- data.frame(x=c("a","a","a","b","b","b"),y=c(1,2,2,1,2,1)) # Two series of three with different values through each series
    d2 <- data.frame(x=c("a","a","a","b","b","b"),y=c(1,2,2,1,1,1)) # Two series of three, one series has all the same values
    ggplot(data=d1) + geom_violin(aes(x=x,y=y))                     # This works
    ggplot(data=d2) + geom_violin(aes(x=x,y=y))                     # This produces an error

    Error message: 
    Error in `$<-.data.frame`(`*tmp*`, "n", value = 3L) : 
      replacement has 1 row, data has 0

**Comment by hadley** [comment]
Already fixed in the dev version.
