### ISSUE TITLE
geom_violin produces empty plot when only two values in the series and scale count used

### ISSUE THREAD

**Issue by RichardLorenz** [hadley/ggplot2#1137]
As posted on StackOverflow:

http://stackoverflow.com/questions/30659308/violin-produces-empty-plot-when-only-two-values-in-the-series-and-scale-count-us

geom_violin produces an empty plot when there are only two values in the series and scale=count used.

    library(ggplot2)
    d1 <- data.frame(x=c("a","a","a","b","b","b"),y=c(1,2,2,1,2,1)) # Two series of three with different values through each series
    d2 <- data.frame(x=c("a","a","a","b","b"),    y=c(1,2,2,1,2))   # Two series, one of three, one of two with different values through each series
    ggplot(data=d1) + geom_violin(aes(x=x,y=y))                     # This works
    ggplot(data=d1) + geom_violin(aes(x=x,y=y), scale="count")      # This works
    ggplot(data=d2) + geom_violin(aes(x=x,y=y))                     # This works
    ggplot(data=d2) + geom_violin(aes(x=x,y=y), scale="count")      # This produces an empty plot

**Comment by hadley** [comment]
Already fixed in the dev version
