### ISSUE TITLE
Review all uses of do.call

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1143]
And ensure arguments are quoted if they exist in the current.

**Comment by lionel-** [comment]
Last time I checked with a recent R, most of the performance gaps in http://rpubs.com/hadley/do-call were solved, so quoting is not as important as before. The last remaining perf gap is when an exception is raised.

**Comment by hadley** [comment]
Yeah, I'm most concerned about the exception problem. It used to be really annoying in practice (but I haven't been able to reproduce it, so maybe it's not a such a problem anyway)
