### ISSUE TITLE
Labels ignore \t character

### ISSUE THREAD

**Issue by LindsayVass** [hadley/ggplot2#1144]
I originally encountered this problem when attempting to include \t in facet labels with a custom labeller, but after posting on [StackOverflow](http://stackoverflow.com/questions/30923852/include-t-character-in-facet-strip-text-with-custom-labeller), this appears to occur any time \t is included in a label.

```r
ggplot(mtcars, aes(mpg, cyl)) + geom_point() + labs(x = "Tab\tneeded", y = "Newline\nneeded")
```

![rplot](https://cloud.githubusercontent.com/assets/11479770/8262821/4c0826f8-168a-11e5-8426-924ed48f1216.png)

**Comment by hadley** [comment]
It doesn't look like R supports tab characters in graphics devices:

```R
plot(1)
text(1, 1, "blah\tblah")
```
