### ISSUE TITLE
stat_bin2d: doesn't handle integer-valued data

### ISSUE THREAD

**Issue by tgs** [hadley/ggplot2#1147]
When I make a `stat_bin2d` using integer data, I still get the "range / 30" bin width.
```r
> df <- data.frame(x = 0:3, y = 0:3)
> str(df)
'data.frame':   4 obs. of  2 variables:
 $ x: int  0 1 2 3
 $ y: int  0 1 2 3
> g <- ggplot(df, aes(x, y))
> g + stat_bin2d()
```
![default stat_bin2d](https://cloud.githubusercontent.com/assets/229502/8314722/570a2eca-19b9-11e5-8ae9-7d07cf9fcf95.png)

However, in [stat-bin2d.r](https://github.com/hadley/ggplot2/blob/v1.0.1/R/stat-bin2d.r#L66), it looks like it is trying to handle integer data specially, to end up with something like this:
```r
> g + stat_bin2d(binwidth=c(1,1), origin=c(-0.5,-0.5))
```
![explicit stat_bin2d](https://cloud.githubusercontent.com/assets/229502/8314782/b5650d00-19b9-11e5-848a-f68de732db72.png)

Maybe, at some point, `data$x` retained its R integer type, but now something switches it to just numeric, and so the `is.integer` tests fail?

Here's a failing test case:
```r
df <- data.frame(x = 0:3, y = 0:3)
g <- ggplot(df, aes(x, y))
p <- ggplot_build(g + stat_bin2d())

want_xbin <- cut(df$x, seq(-0.5, 4, 1))
expect_equal(p$data[[1]]$xbin, want_xbin)
```

**Comment by hadley** [comment]
Factors are turned into integers by the time the get to the stat function. It's not the best design, but it's too late to change now.
