### ISSUE TITLE
Is there a way to allow scales in facet_grid to be completely "free"?

### ISSUE THREAD

**Issue by kendonB** [hadley/ggplot2#1152]
Suppose we have an n x m grid.

Currently:
* ``scales = free_x`` allows for m scales along the bottom, and 1 common scale for all rows.
* ``scales = free_y`` allows for n scales along the side, and 1 common scale for all columns.
* ``scales = free`` allows for n scales along the side, and m scales along the bottom.

Is there a way to have all scales free? i.e. this would result in n*m independent scales, one for each subplot?

**Comment by hadley** [comment]
Nope, sorry. If you want that, you can use `facet_wrap`.
