### ISSUE TITLE
Problem with strip_dots and anonymous functions

### ISSUE THREAD

**Issue by NikNakk** [hadley/ggplot2#1154]
The current code which handles anonymous functions within strip_dots (in aes_calculated.r) is broken for anonymous functions. With pairlists, it tries to lapply each member of the pairlist to itself lapply(expr, expr) which I think will always result in an error.

Minimal reproducible example:

ggplot2:::strip_dots(quote(function(x) x))

I'm about to submit a pull request which fixes this issue.

**Comment by jeremycg** [comment]
Nice one! see also the original q on stackoverflow: http://stackoverflow.com/questions/31212054/functions-inside-aes/

**Comment by NikNakk** [comment]
I was the one to answer that question! I've mentioned it in the pull request but forgot to put it into the issue.

**Comment by hadley** [comment]
Fixed in #1155
