### ISSUE TITLE
grid.arrange() fails with infinite recursion error in r-devel

### ISSUE THREAD

**Issue by kmiddleton** [hadley/ggplot2#1159]
In r-devel (2015-07-07 r68640) with the development version of ggplot2 and gridExtra version 0.9.1, calls to `grid.arrange()` fail with the error:

> Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
> Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?

using the minimal code:

```
library("ggplot2")
library("gridExtra")

p1 <- qplot(rnorm(5))
p2 <- qplot(rnorm(5))

grid.arrange(p1, p2)
```

My `sessionInfo()`:

```
R Under development (unstable) (2015-07-07 r68640)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods
base

other attached packages:
[1] gridExtra_0.9.1    ggplot2_1.0.1.9002 fortunes_1.5-2 devtools_1.8.0

loaded via a namespace (and not attached):
  [1] Rcpp_0.11.6      digest_0.6.8     MASS_7.3-42      plyr_1.8.3 gtable_0.1.2     git2r_0.10.1     magrittr_1.5     scales_0.2.5
  [9] stringi_0.5-5    curl_0.9.1       reshape2_1.4.1   xml2_0.1.1 labeling_0.3     tools_3.3.0      stringr_1.0.0    munsell_0.4.2
[17] colorspace_1.2-6 rversions_1.0.1  memoise_0.2.1
```

**Comment by hrbrmstr** [comment]
Verified this as reproducible just now (debugging some code for someone)

**Comment by hadley** [comment]
This seems like a gridExtra bug to me.

**Comment by sctyner** [comment]
@kmiddleton I got the same error. So, I uninstalled the dev version of ggplot2, restarted my R session, installed the CRAN version of ggplot2, reran the same code, and it worked just as expected.  There is definitely something happening with the interaction of the gridExtra package and the dev version of ggplot2.

**Comment by baptiste** [comment]
People running into this error should probably update gridExtra to v2.0.0. My guess is that the message comes from changes in grid.draw for ggplot2 / gtable objects, but it's pointless to track it down since the current packages are compatible and don't show the problem.

**Comment by zhenglei-gao** [comment]
Got the same error and fixed by updating gridExtra.
