### ISSUE TITLE
Automatic height of saved plot

### ISSUE THREAD

**Issue by Godisemo** [hadley/ggplot2#1163]
I have created a plot in ggplot2 using a fixed aspect ratio for all facets. When I save the plot I want to specify the width, and have the height automatically calculated. At the moment the plot is resized to fit the saved image, but I want the saved image to be resized to fit the plot. How would this be possible? In the picture below I only want the part with magenta background, and I want it to have a specific width.

<img width="918" alt="skarmavbild 2015-07-13 kl 14 27 36" src="https://cloud.githubusercontent.com/assets/847898/8649643/75347e10-296c-11e5-8b50-05c084433a16.png">

Code used to produce the plot:

``` R
library(ggplot2)

p <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  facet_wrap( ~ Species) +
  geom_point() +
  theme(aspect.ratio = 2 / (sqrt(5) + 1), plot.background = element_rect(fill = "magenta"))

ggsave(filename = "plot.png", plot = p, width = 8)

show(p)
```

**Comment by hadley** [comment]
It's not possible, as far as I know.

**Comment by Godisemo** [comment]
I use the plots in my scientific articles, and by saving all of them with the same width and scaling them by the paper width I can achieve the same font size, etc. for all plots.

I would therefore suggest marking this as a feature request.

**Comment by Godisemo** [comment]
Also worth adding is my current workaround. I save the pictures using the width I want, say 12 cm, and a much larger height, say 200 cm or something big enough. The final step is to crop the image manually in some image software or pdf editor.

**Comment by baptiste** [comment]
see http://stackoverflow.com/a/16442029/471093
