### ISSUE TITLE
Log scales should have more values labeled on their axes

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/ggplot2#1166]
The vast majority of the time I use a log scale in ggplot, by default it ends up with only 2 values labelled on the axis. This is problematic because with only two values, it is not immediately obvious that the scale is non-linear. I would say that 3 is the absolute minimum number of values that should be allowed on the scale, to make the non-linearity clear. And I think that as long as room is available, every order of magnitude should be labelled, since orders of magnitude are the basic unit that one thinks about when working on a log scale. I'm attaching a plot that demonstrates both problems (the actual content of the plot is unimportant):

![Under-labeled log scales](https://cloud.githubusercontent.com/assets/228145/8680016/5cd3ee6c-2a13-11e5-99ad-751d2c8053e6.png)

**Comment by hadley** [comment]
Could you please file this issue in the scales repo?

**Comment by wch** [comment]
@DarwinAwardWinner Also see `annotation_logticks`: http://docs.ggplot2.org/current/annotation_logticks.html
