### ISSUE TITLE
Extra padding is added between facet labels on vertical axis and plot when using also facets on horizontal axis

### ISSUE THREAD

**Issue by crtahlin** [hadley/ggplot2#1170]
Using the `facet_grid` option of `switch = "y"` for vertical facets and also using facets on the horizontal axis, I get some padding between the labels on the vertical axis and the plot. This padding is not present if I only plot the vertical facets.

See plots for illustration:

 **vertical facets only**
![image](https://cloud.githubusercontent.com/assets/1554520/8777254/3626f852-2ef7-11e5-9da4-49845ede28b6.png)

**vertical & horizontal facets**
![image](https://cloud.githubusercontent.com/assets/1554520/8777279/62fd96a6-2ef7-11e5-9b5b-2daec14ab7d1.png)

The code for both is identical (except for the facet definition) and will attach it below. I have attempted all the options I could find, to get rid of the padding, with no success. Therefore, I believe this might be a bug, since it would make sense to be able to have no padding between the facet labels and the plot (esp. since there is none if there are no "horizontal" facets).

Using ggplot2 version 1.0.1.9002.

See code bellow: 

```
library(ggplot2)
data("iris")

# add another column to data to facet by in the second example
iris2 <- iris
iris2$Species2 <- rep(c("one","two","three"), 50)

# plot with facet on vertical axis
ggplot(data=iris2, aes(x=Sepal.Length, y=Sepal.Width )) +
  geom_point() +
  facet_grid(Species ~ . , switch = "y") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        axis.ticks.margin = unit(0, "cm"),
        axis.line.y = element_blank(),
        panel.border = element_blank(),
        panel.margin = unit(0, "cm"),
        strip.text.y = element_text(angle = 180),
        strip.switch.pad.grid = unit(0, "cm")
  )

# plot with facets on both axis
ggplot(data=iris2, aes(x=Sepal.Length, y=Sepal.Width )) +
  geom_point() +
  facet_grid(Species ~ Species2 , switch = "y") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.length = unit(0, "cm"),
        axis.ticks.margin = unit(0, "cm"),
        axis.line.y = element_blank(),
        panel.border = element_blank(),
        panel.margin = unit(0, "cm"),
        strip.text.y = element_text(angle = 180),
        strip.switch.pad.grid = unit(0, "cm")
        )


```

**Comment by hadley** [comment]
@lionel- do you think your change might have done this?

**Comment by lionel-** [comment]
yes there is some padding added between the axis label and the plot. See the graphs in #974. In the second picture the padding should be removed because of `strip.switch.pad.grid = unit(0, "cm")` but for some reason it does not. I'll look into it.

By the way, I was thinking maybe the default padding is not so well integrated with ggplot2's default themes because the axis titles and labels of unswitched scales are not padded. I will propose a default value that fits better the default overall look.
