### ISSUE TITLE
Geom/stat/position objname field should be replaced with a function

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1176]
The `objname` field should be replaced with a function that looks at the object's class attribute.

For example, currently `GeomBar$objname` is specified as `"bar"`. Instead, `Geom` could simply have a method like this:

```
    objname = function(self) {
      classes <- setdiff(class(self), c("Geom", "proto2"))
      if (length(classes) == 0)
        return(NULL)

      classes <- classes[1]
      sub("^Geom", "", classes)
    }
```

This will return `"Bar"`. The camel case could be converted to underscore case to have the same behavior as we have now, but I think it's better to leave it as camel case.

**Comment by hadley** [comment]
See #1173
