### ISSUE TITLE
Layer$new() should be a separate function, like new_layer()

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1180]
It's a little confusing that `Layer$new()` doesn't really create a new layer; it creates a descendant object of the `Layer` object. Same for `Position$new()`

`GeomVline` also has a `new` method where this also applies. I'm not sure why it's the only geom that has one.

**Comment by hadley** [comment]
* [ ] Move existing `layer$new()` method into `layer()`
* [ ] Change all uses of `layer$new()` to `layer()`
