### ISSUE TITLE
label = FALSE in guide_legend results in error

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1182]
From `?guide.legend`:
"label: [...] If `FALSE` then the labels are invisible."

But:    
     
    df <- data.frame(x = 1, y = 1)

    p <- ggplot(df, aes(x = x, y = y, color = factor(x))) + 
            geom_point()
    p
    
    p + guides(color = guide_legend(label = FALSE))
    # Error in (function (name)  : grob 'NULL' not found

See also [**this post on SO**](http://stackoverflow.com/questions/31501217/remove-legend-labels-using-label-false-in-guide-legend-or-labels-null-in-di)

**Comment by hadley** [comment]
Probably related to #1175

**Comment by Henrik-P** [comment]
Perhaps it could also be worth considering a consistent naming of the label(s) arguments in `guide_legend` and `discrete_scale`: `guide_legend`: `label`; discrete_scale`: `labels`.

**Comment by hadley** [comment]
It's too late to change names unfortunately.

**Comment by Henrik-P** [comment]
OK. No big deal. I just stumbled over it.

**Comment by hadley** [comment]
Ah, given that it doesn't work and there's an existing way to do it (labels = NULL) in the scale, I think I'll just remove this option altogether

**Comment by hadley** [comment]
Ugh, the colour bar legend has a label option, so I'll just make it work.

**Comment by Henrik-P** [comment]
Of course it _could_ be done in `scale_`. However, to me it seems that given all the other`label` options in `guide_legend` (`label.position`, `label.theme`, `label.hjust`, `label.vjust`) and rather "complicated" stuff like `override.aes`,  I find it quite natural to include also a seemingly simple function to turn labels off.
