### ISSUE TITLE
Eliminate default_geom, default_stat, and default_pos function

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1185]
The only place they're needed is if you do `layer(geom = "point")`, but you shouldn't be creating layers this way anyway.  Otherwise we're recording the default stat/geom in both the layer creation function (e.g. `geom_point()`) and in the geom object (e.g. `GeomPoint$default_stat()`)

**Comment by wch** [comment]
`Layer$new()` should throw an error if the stat, geom, or pos are `NULL`.

**Comment by wch** [comment]
Also remove `desc`.

**Comment by wch** [comment]
And `examples`.
