### ISSUE TITLE
Refactor legend functions to remove self

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1192]
I think this means they need name and default_aes arguments.

**Comment by wch** [comment]
I was also thinking that `draw_legend_point` would be a better name than `legend_point`.

**Comment by hadley** [comment]
(@wch the function actually draws just a single key in a legend - do you think `draw_key_point()` is ok?)

* [ ] rename `guide_geom` to `draw_key`
* [ ] move `aesdefaults(data, self$default_aes, list(...))` into whatever function calls the legends
* [ ] rename `legend_*()` to `draw_key_*()`

**Comment by wch** [comment]
`draw_key_*` sounds good to me.

It would be possible to make `self` an optional argument for proto2 methods, by checking the formals of the method when `Geom$foo` is accessed. It would require another condition inside of this one:
https://github.com/hadley/ggplot2/blob/0fa165beaa954d736947a5abc270590f38ffc297/R/proto2.r#L78
