### ISSUE TITLE
Coord$expand_defaults shouldn't be accessed directly

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1202]
`Coord$expand_defaults` is called from `expand_default` and a couple other places, but those functions shouldn't be reaching into the `Coord` object.

**Comment by hadley** [comment]
Why is that a problem?

**Comment by hadley** [comment]
Although the whole design of `expand_defaults` is a disaster. See also #969

**Comment by wch** [comment]
Because `expand_default` is a top-level function, so it shouldn't need to know anything about the `Coord` object.

I just migrated the code over from the old system -- it had a similar structure before the ggproto changes.

**Comment by hadley** [comment]
Oh I think you mean it's called from `train_cartesian`

**Comment by wch** [comment]
Oh yeah, sorry about that.

**Comment by hadley** [comment]
Oh I see how this happened - I just pulled out previously internal functions. Will fix as part of #1207
