### ISSUE TITLE
Text labels on a stacked bar plot

### ISSUE THREAD

**Issue by sjackman** [hadley/ggplot2#1205]
I'd like to place text labels on a stacked bar plot, so that each text is over its respective bar. The simple solution (see below) doesn't work as expected with a stacked bar plot, because the labels are placed at the position of value, not the cumulative sum of the value. Creating the cumulative sum manually works. Is there any easier way to accomplish this task?

```r
foo <- data.frame(Foo = c(11, 12, 13))
# Text labels are not above their respective bars.
ggplot(foo) + aes(x = 0, y = Foo, fill = Foo, label = Foo) + geom_bar(stat = "identity") +
    geom_text()
# Text labels are above their respective bars.
ggplot(foo) + aes(x = 0, y = Foo, fill = Foo, label = Foo) + geom_bar(stat = "identity") +
    geom_text(y = cumsum(foo$Foo))
```

**Comment by sjackman** [comment]
# Have

![image](https://cloud.githubusercontent.com/assets/291551/8891826/7ccdeb72-32ed-11e5-874f-b885c07a696d.png)

# Want

![image](https://cloud.githubusercontent.com/assets/291551/8891831/95de4e90-32ed-11e5-9c99-85116145ea8b.png)

**Comment by hadley** [comment]
```R
ggplot(foo) + aes(x = 0, y = Foo, fill = Foo, label = Foo) + 
  geom_bar(stat = "identity") +
  geom_text(position = "stack")
```

?

**Comment by sjackman** [comment]
Ah, fantastic. I should have figured that it was this easy. Thanks, Hadley.

**Comment by sjackman** [comment]
Just saw this comment. Heh. Doc Hadley, it hurts when I raise my arm above my head. =)

> Please don't. It's not a good idea to try and improve a confusing visualisation by adding text labels. Either make a table or use a better display of the data.

http://stackoverflow.com/questions/6644997/showing-data-values-on-stacked-bar-chart-in-ggplot2#comment7870900_6644997
