### ISSUE TITLE
Position adjustment for a stacked bar plot

### ISSUE THREAD

**Issue by sjackman** [hadley/ggplot2#1214]
Is there an aesthetic to adjust the vertical position of a `coord_flip` stacked bar plot, as in this figure?

![QUAST](http://bioinf.spbau.ru/sites/default/files/alignment.png)

**Comment by hadley** [comment]
That looks more like a `geom_tile()` to me

**Comment by sjackman** [comment]
`geom_tile` and `facet_grid` worked great. Thanks again, Hadley.

**Comment by sjackman** [comment]
I'm pretty happy with the resulting figure. [Code](https://github.com/sjackman/pgmtdna/blob/master/genes.rmd#genes-by-scaffold-and-strand)
Colour are selected using [i want hue](http://tools.medialab.sciences-po.fr/iwanthue/). See https://github.com/sjackman/pgmtdna/issues/1
![genes-by-scaffold-1](https://cloud.githubusercontent.com/assets/291551/9020089/8bba67e8-37af-11e5-8d95-26a6cfc3c69b.png)
