### ISSUE TITLE
Regression: facet_grid shows integer values instead of names for factors

### ISSUE THREAD

**Issue by krlmlr** [hadley/ggplot2#1216]
```
import::from(dplyr, mutate)
import::from(magrittr, "%>%")

mtcars %>%
  mutate(cyl = factor(cyl),
         gear = factor(gear)) %>%
  ggplot(aes(x=mpg, y=wt)) +
  geom_point() +
  facet_grid(cyl~gear)
```

![rplot01](https://cloud.githubusercontent.com/assets/1741643/8953010/079e6d76-35dc-11e5-9388-588e92930c77.png)

Note how the grid labels read 1, 2, 3, but the values of cyl and gear are different.

This doesn't happen in the current CRAN version.

Also, using `labeller = label_both` seems to show correct factor levels.

**Comment by hadley** [comment]
@lionel- can you please take a look?
