### ISSUE TITLE
function with ggplot and aes_

### ISSUE THREAD

**Issue by Nicolabo** [hadley/ggplot2#1227]
HI,
I just read hadley's article: http://rpubs.com/hadley/97970 Really cool!

Because of that I want to prepare some simple function. When I want to create a plot and use one more variable to distinguish all objects we generally use `color` or `fill` parameter. I always have a problem to remember that I should use `color` parameter in scatterplot and `fill` in e.g. boxplot.
Therefore, when I do not use `color` parameter I want to use red color default:

```R
point <- function(data, x, y, color = NULL){
  if (is.null(color)){
    ggplot(data, aes_(x = substitute(x),y = substitute(y)))+
      geom_point(color = 'red')
  }
  else{
    ggplot(data, aes_(x = substitute(x),y = substitute(y),color = substitute(color)))+
      geom_point()
  }
}
```

In this case, `point(mtcars, qsec, mpg)` works correctly but function with color paramer does not work at all - `point(mtcars, qsec, mpg, factor(cyl))`. Why?

**Comment by hadley** [comment]
Because `is.null(color)` forces evaluation. You need to use `missing(color)` instead.
