### ISSUE TITLE
Place the facet labels on the left side (feature request)

### ISSUE THREAD

**Issue by sjackman** [hadley/ggplot2#1231]
I would like to place the facet labels of `facet_grid` on the left side next to the y axis labels.
I see this feature is a FAQ:
https://github.com/hadley/ggplot2/wiki/Frequently-asked-questions
> Is it possible to place the strip labels on the left side?
Not currently. See r-help http://www.mail-archive.com/r-help@r-project.org/msg105950.html for a hack that might work in some cases.

**Comment by sjackman** [comment]
I found a workaround. Replace `facet_grid` with `facet_wrap` and use `theme(strip.text = element_text(hjust = 0))`

**Comment by backlin** [comment]
As of ggplot2 v2.0.0 this can be done properly using the `switch` argument of the faceting functions.

**Comment by ywebbvar** [comment]
Hi! Thanks for making the 'switch' available! Is it possible to tinker with the code to have the label be outside of the y-axis?

**Comment by AlfredUg** [comment]
sjackman's suggestion works fine for me even with facet_grid, playing around with values for `hjust` and `vjust` gives a desired alignment of the labels.

**Comment by kivison** [comment]
This solved it for me: -
`theme(strip.placement = "outside") +`

**Comment by orb16** [comment]
This doesn't work if you are using `facet_grid()` with one variable and want to switch the facet labels from the top to the left. It only works to switch from the top of the plot to the bottom. Can't use `facet_wrap()` when you also need the `space = "free"` argument that's only in `facet_grid()`. But can't think of an easy fix
