### ISSUE TITLE
geom_hex and stat_hex does not work

### ISSUE THREAD

**Issue by Nicolabo** [hadley/ggplot2#1232]
Hi,
I installed latest version of ggplot2 yesterday and try to prepare plot with hex (I used an example from the documentation):

`devtools::install_github('hadley/ggplot2')`
`library(ggplot2)`
`d <- ggplot(diamonds, aes(carat, price))`
`d + stat_binhex()`
`d + geom_hex()`

I got an error:  

Computation failed in `stat_binhex()`:
`'hexBin' is not export object with 'namespace:hexbin' `

**Comment by profyao** [comment]
I also have this problem.

Warning message:
Computation failed in `stat_binhex()`:
there is no package called ‘hexbin’

**Comment by hadley** [comment]
@profyao try installing the hexbin package.
