### ISSUE TITLE
Add labeller parameter to facet_wrap (feature request)

### ISSUE THREAD

**Issue by sjackman** [hadley/ggplot2#1233]
`facet_grid` has the `labeller` parameter, but oddly `facet_wrap` does not have this same parameter. Please add the `labeller` parameter to `facet_wrap`. Thank you!

See http://stackoverflow.com/questions/11979017/changing-facet-label-to-math-formula-in-ggplot2#comment15970770_11979017
> @TylerRinker in won't work because facet_wrap doesn't has a labeller param. Only facet_grid does, and I don't know why. –  Luciano Selzer Aug 16 '12 at 0:29

**Comment by hadley** [comment]
Install the dev version ;)

**Comment by sjackman** [comment]
Thanks, Hadley.
