### ISSUE TITLE
facet_wrap (facet_flow?): Arrange unevenly sized plots (feature request)

### ISSUE THREAD

**Issue by sjackman** [hadley/ggplot2#1234]
Hi, Hadley. I have this arrangement with `facet_wrap`:
![genes-by-scaffold-1](https://cloud.githubusercontent.com/assets/291551/9020089/8bba67e8-37af-11e5-8d95-26a6cfc3c69b.png)

I'd like this arrangement:

![screenshot 2015-08-02](https://cloud.githubusercontent.com/assets/291551/9027183/dcef1e5a-38ff-11e5-8e68-04a524b2cc0d.png)

Your thoughts?

**Comment by hadley** [comment]
It would be cool, but I think it would need a completely new facetting system (I think you want the `facet_wrap()` equivalent to `facet_grid(scales = "free", space = "free")` . And writing new facetting systems is really quite hard, so it's unlikely I'll ever get to it.

**Comment by sjackman** [comment]
This plot could be laid out manually on a six-by-six grid, which got me thinking that `facet_wrap` would handle this case quite well if the individual plot elements had the equivalent of HTML `colspan` attribute to specify how wide they should be. Could a `colspan` attribute be added to `facet_wrap?

**Comment by hadley** [comment]
It _could_ be, but I think it would be quite complex. Take a look at the existing facetting code to see all the special cases that already need to be handled.
