### ISSUE TITLE
purpose of `validate_element`?

### ISSUE THREAD

**Issue by baptiste** [hadley/ggplot2#1240]
[validate_element](https://github.com/hadley/ggplot2/blob/0913ac3d0db68dd0bfe62a10660281060d0d94bd/R/theme-elements.r#L288) makes it hard to use a custom grob instead of the default theme element, say, replacing a facet strip text with [a grob](http://stackoverflow.com/a/16491363/471093) that handles multiple lines and plotmath expressions, or [an axis with an arrow](http://stackoverflow.com/a/27149233/471093), etc.

Is there a strong argument to maintain this internal check?

**Comment by hadley** [comment]
Yes, because otherwise you'll get an obscure error when the plot is drawn, not when you set the theme. The prior version of themes let you have custom grobs, but no one ever used its not a common request. 
But it's just a test for inheritance, so if your custom grob implements the text protocol, why don't you inherit from `element_text`?

**Comment by hadley** [comment]
In other words, make it work like the other element functions:

```R
library(ggplot2)

element_custom <- function() {
  structure(list(), class = c("element_custom", "element_text"))
}

element_grob.element_custom <- function(element, label="", ...)  {
  disect <- strsplit(label, "\\n")[[1]]
  g1 <- gridExtra::tableGrob(as.matrix(disect), 
    parse = TRUE,
    theme = gridExtra::theme.list(
      gpar.corefill = grid::gpar(fill = NA, col = NA), 
      core.just = "center")
  )
  grid::gTree(
    children = grid::gList(g1), 
    height = grid::grobHeight(g1), 
    cl = "custom_strip"
  )
}
# gTrees don't know their size and ggplot would squash it, so give it room
grobHeight.custom_strip <- function(x, ...) x$height
heightDetails.custom_axis <- function(x, ...) x$height

title <- c(
  "First*line \n italic('see that second')", 
  "this~is~boring",
  "integral(f(x)*dx, a, b)"
)

iris2 <- iris
iris2$Species <- factor(iris$Species, labels = title)
ggplot(iris2, aes(Sepal.Length, Sepal.Width)) +
  geom_line() + facet_grid(.~Species) +
  theme(strip.text.x = element_custom())
```

**Comment by hadley** [comment]
Ooh, but that doesn't work because of the way themes elements are merged. This works, but is a bit clunky:

```R
ggplot(iris2, aes(Sepal.Length, Sepal.Width)) +
  geom_line() + facet_grid(. ~ Species) + 
  (theme_grey() %+replace% theme(strip.text.x = element_custom()))
```

@wch is there a way to override/replace a theme element on the current plot?

**Comment by baptiste** [comment]
> The prior version of themes let you have custom grobs, but no one ever used its not a common request.

Maybe, but another way to look at it is that if it's too difficult/hacky, no-one will think it's possible in the first place. I posted about ~10 answers over the years on the mailing list and SO, with the old and new theme systems; most of them would otherwise be unanswered, or involve heavy post-processing. 
Other examples I can remember included replacing the axis labels with small images, chemical formulas, or tables.

> But it's just a test for inheritance, so if your custom grob implements the text protocol, why don't you inherit from element_text?

it doesn't work, unfortunately, for reasons I don't understand.

**Comment by hadley** [comment]
@baptiste I provided an example that works for me

**Comment by baptiste** [comment]
it works, but the `%+replace%` workaround is still not very intuitive, is there a way to get `+ theme(strip.text.x = element_custom())` to work?
