### ISSUE TITLE
relative placement of annotations

### ISSUE THREAD

**Issue by gdkrmr** [hadley/ggplot2#1244]
Feature request:
It would be really useful if annotations could be placed like legends indicating their relative position (```legend.placement = c(1,0)```) in the plot area.

Coordinate limits can be extracted after building the plot:
https://gist.github.com/tomhopper/9076152

Being able to do this before building the plot would be a really neat feature, e.g. for placing regression formulae nicely in a corner.
Something like:
```R
g + annotate("text", x = get_xlim()[2], y = get_ylim()[2], label = "y = 3 + 4x")
```

**Comment by hadley** [comment]
You can already do it :) (for that special case)

```R
library(ggplot2)
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  annotate("text", -Inf, Inf, label = "Top-left", hjust = 0, vjust = 1)
```

**Comment by gdkrmr** [comment]
Thanks, I wasn't aware of that!

**Comment by gdkrmr** [comment]
@hadley btw. this feature is missing in the documentation

**Comment by hadley** [comment]
It's in the book ;)

**Comment by baptiste** [comment]
the trick also applies to [`annotation_custom`](http://stackoverflow.com/a/31736633/471093)

**Comment by kendonB** [comment]
Making this explicit and separated by axis would be a welcome addition. For example, I'd like to be able to choose the x-value of an annotation explicitly and have the y-value 50% up the plot.

**Comment by baptiste** [comment]
@kendonB `qplot(1:10,1:10, geom="blank") + annotation_custom(textGrob("y centered"),xmin=3,xmax=3)`

**Comment by kendonB** [comment]
Thanks so much @baptiste. Is there any way to also have hjust/vjust in this?

**Comment by colinbrislawn** [comment]
>It would be really useful if annotations could be placed like legends indicating their relative position (legend.placement = c(1,0)) in the plot area.

I agree!

>annotate("text", -Inf, Inf, ...

That solution will place a annotation into every facet, where `legend.placement` places a single annotation based on the relative position in the graph, regardless of the other geoms or facets being used. 

I would like to see something like `annotate_relative` or `annotate_global` to provide this functionality.

**Comment by baptiste** [comment]
`annotation_custom` provides a way by wrapping an arbitrary grob in a gTree that spans the full panel. The syntax is not super convenient, especially since one has to load grid to use `unit` and `gTree`, but there could be a convenience function around this.
```
library(ggplot2)
library(grid)

g <- grobTree(textGrob('here', x=unit(0.8, "npc"), y=unit(0.5,"npc")))
qplot(0:10,0:10) +
  annotate("point",x=8,y=5,col="red") +
  annotation_custom(g)
```

To specify specific facets, one would need a `geom_custom`, which exists as proof-of-principle in `egg`, but not on CRAN because ggplot2 internal changes in layout.
