### ISSUE TITLE
vjust in axis.title does not work

### ISSUE THREAD

**Issue by Nicolabo** [hadley/ggplot2#1252]
Hi,
I installed the latest version of ggplot2 today - `ggplot2_1.0.1.9003`.

I tried to use `vjust` parameter in `axis.tilte.x` in `theme` function, but it didn't work:

`ggplot(mtcars, aes(qsec, mpg))+`
`  geom_point()+`
`  theme(axis.title.x = element_text(vjust = -2))`

**Comment by hadley** [comment]
1. You shouldn't be using vjust outside the range of 0--1 (and it doesn't mean anything for horizontal text anyway).
2. You should adjust the margins instead.

**Comment by Nicolabo** [comment]
maybe you're right but when I use `ggplot2` CRAN version `axis.title.x = element_text(vjust = -2)` change postion of x-axis.

**Comment by Myfanwy** [comment]
Hi Hadley, sorry, I'm having a similar issue - adjusting the plot.margin theme element increases the space around the plot, but I can't find a way to increase the space between the axis titles and the axis tick labels.  The workaround I'm running now is to add a "\n" in front of my x axis label (i.e. ggplot() + xlab("\nTreatment).  Which margins are you referring to?

**Comment by hadley** [comment]
The new margin parameter to `element_text()`
