### ISSUE TITLE
Add examples to geom_text: text together with geom_bar

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1254]
In `?geom_text` all examples concern scatterplot-oid plots, with or without points. There are no examples of `geom_text` together with `geom_bar`. Given the large number of questions on SO of how to position `geom_text` in relation to dodged or stacked bars I believe this gap in the help text should be filled. Here is a suggestion with some toy data and code which may be a start for additional examples.

Some data:
    
    df <- data.frame(x = factor(c(1, 1, 2, 2)), y = c(1, 3, 2, 1), grp = c("a", "b", "a", "b"))

`position = "dodge"` only set for `geom_bar` obviously doesn't work [a common "error" in SO questions]

    ggplot(data = df, aes(x = x, y = y, fill = grp, label = y)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text() 

Then set `position = "dodge"` for both `geom_bar` and `geom_text` [a highly sensible attempt, and why it doesn't work is not very intuitive]
    
    ggplot(data = df, aes(x = x, y = y, fill = grp, label = y)) +
       geom_bar(stat = "identity", position = "dodge") +
       geom_text(position = "dodge")

The solution:

    dodge <- position_dodge(width = 0.7)

    ggplot(data = df, aes(x = x, y = y, fill = grp, label = y)) +
      geom_bar(stat = "identity", position = dodge) +
      geom_text(position = dodge, vjust = -0.3) # *

(* why do we need to use a  _negative_ `vjust` to move the text in a _positive_ direction (up)?)

----

The `dodge <- position_dodge(width = 0.7)` trick is described in `?geom_errorbar`, but I must say that I don't quite understand the explanation for its use:
     
    # Because the bars and errorbars have different widths
    # we need to specify how wide the objects we are dodging are
Is it really about the width of the `geom`s? Consider some long labels and try to dodge them with `"dodge"` only. Same lack of dodging of the text:

    df$lab = c("loooooooong", "tadaaaaaaaa", "o la laaaaaaa", "yeeeeeeees")

    ggplot(data = df, aes(x = x, y = y, fill = grp, label = lab)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text(position = "dodge")

It seems to me that it is something else than "different width" of the `geom`s that causes the default `"dodge"` dodge to differ between `geom`s. Anyway, a possible wording which doesn't address the underlying cause could be something like:
"when dodging two different `geom`s, we need to explictly specify the same`width` in `position_dodge` of both `geom`s.". Perhaps preceeded by the explanation.

Anyway, given the common usage of `dodge <- position_dodge(width = 0.7)` when using `geom_text` , I believe it should be mentioned in `geom_text` as well.

----

A potential example on how to put `geom_text` on the midpoints of stacked bars. Something like:

    # place text in the middle of each bar in a stacked barplot
    # first, calculate midpoints of bars:
    df <- transform(df, mid_y = ave(df$y, df$x, FUN = function(val) cumsum(val) - (0.5 * val)))

    ggplot(data = df, aes(x = x, y = y, fill = grp, label = y)) +
        geom_bar(stat = "identity") +
        geom_text(aes(y = mid_y))

**Comment by hadley** [comment]
* `position_dodge()` now emits a warning when the items being dodged have unknown width. Hopefully this will make the problem more obvious

* Instead of hacky hjust and vjust, you can use `nudge_x` and `nudge_y`

**Comment by hadley** [comment]
Oh bummer, you can't use `nudge_x`/`nudge_y` with `position_dodge` :/

**Comment by hadley** [comment]
I should explain that from ggplot2's perspective the width of a text label is the same as the width of a point: 0 (this is the same reason that axes don't expand to include labels). Obviously text does have a width, but ggplot2 only understands dimensions as measured in the data space. The width of text is constant in visual space, but variable in data space, because as you change the size of the plot the physical  size of text stays the same, but the physical size of the axes changes

**Comment by hadley** [comment]
Let me know what you think of the changes, and if there are other geoms you think need similar treatment. Thanks!

**Comment by Henrik-P** [comment]
Thanks for the updated help text. I have a few comments. In general, I think you could be more explicit. 

----
Current:

    # ggplot2 doesn't know you want to give the labels the same virtual width
    # as the bars:

My suggestion:

    # Setting position = "dodge" dodges the bars.
    # However, because the virtual width of a text element is zero (see Details above),
    # the same command does not result in dodging for geom_text:
----

Current:
    
    # So tell it:
    # ...snip...
    geom_text(position = position_dodge(0.9))

My suggestion:

    # Thus, in order to dodge geom_text, we need to use position_dodge and explictly specify the width:
    # ...snip...
    geom_text(position = position_dodge(width = 0.9))

----

Current:

    # Use you can't nudge and dodge text, so instead adjust the y postion
    ggplot(data = df, aes(x, y, fill = grp, label = y)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text(aes(y = y + 0.05), position = position_dodge(0.9), vjust = 0)

My suggestion:

    # You can't use nudge_x/nudge_y with position_dodge, so use vjust instead to adjust the y position
    ggplot(data = df, aes(x, y, fill = grp, label = y)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_text(aes(y = y + 0.05), position = position_dodge(width = 0.9), vjust = 0)

----

Current:

    # To place text in the middle of each bar in a stacked barplot, you
    # need to do the computation yourself

My suggestion:

    # To center text in each bar in a stacked barplot, you need to calculate the midpoints yourself


----

Small typo in **Details**:
Note **that** the "width" and "height" of a text element are 0
