### ISSUE TITLE
geom 

### ISSUE THREAD

**Issue by assaforon** [hadley/ggplot2#1259]
I just upgraded to the GitHub version from the CRAN version in order to be able to ggsave() composite plots. In the process, the following geom-stat combination, that used to draw color-coded horizontal lines at group means, seemed to stop working.

geom_errorbar(stat = "hline", yintercept ="mean", width=0.8, aes(ymax=..y..,ymin=..y.., color=factor(dose)),size=1)

The error message is "object 'StatHline' not found". I tried replacing the geom_errorbar layer with a geom_segment, but it's hard to emulate the behavior.

Any insight?

Thanks!

**Comment by hadley** [comment]
I think you should just use geom_hline. I have no idea what that code does, but I think the fact that it worked is just luck.

**Comment by assaforon** [comment]
I didn't invent that code. I took it off a stackoverflow Q&A and it worked
seamlessly. So there seems to have been such a stat associated with
geom_errobar(), and now it's gone.

How would you create color-coded mean group lines using geom_hline() ? Thus
far I couldn't not find any example online, and my efforts to hack one have
not succeeded.

Thanks, Assaf

**Comment by wch** [comment]
I believe we removed `StatHline` (and similar) because with the recent refactoring, they were no longer necessary for `geom_hline` (and similar).

I think you can probably use `stat="summary"`, or the `stat_summary` function instead.

**Comment by aosmith16** [comment]
@assaforon I think code to add a horizontal line per group to represent the mean would be:

```
geom_errorbar(stat="summary", fun.y="mean", width=0.8, 
		    aes(ymax=..y.., ymin=..y.., color=factor(dose)), size=1)
```

**Comment by assaforon** [comment]
On Wed, Aug 12, 2015 at 2:37 PM, aosmith16 <notifications@github.com> wrote:

> geom_errorbar(stat="summary", fun.y="mean", width=0.8, aes(ymax=..y..,
> ymin=..y.., color=factor(dose)), size=1)



Thank you, it worked!

Assaf
