### ISSUE TITLE
geom_vline messes up geom_line legend, if show_guide = TRUE

### ISSUE THREAD

**Issue by maxheld83** [hadley/ggplot2#1267]
Let's say I have some line graph via `geom_line` and would like to add some `geom_vline`s as thresholds.
Let's further say that I have *several* such `geom_vline`s and would therefore require a **legend**.

Here's the **base layer** plot:

```r
library(ggplot2)
data(mpg)

# base plot
g <- ggplot()
g <- g + geom_line(data = mpg, mapping = aes(y = cty, x = year, color = manufacturer), stat = "summary", fun.y = mean)
g
```

So far, so good:

![baseplot](https://cloud.githubusercontent.com/assets/5372770/9293911/416f952a-443c-11e5-9f9a-1d9c6cb79799.png)

---

Now let's try and add the threshold **via `geom_hline` with a custom legend**:

```r
# add threshold via geom_hline()
g + geom_vline(aes(xintercept = 2004, linetype = "Funny Law"), show_guide = TRUE) + scale_linetype_manual(values = c("Funny Law" = "dashed"))  # screws up all geom_line legends
```

Not so great, the base-layer legends are all screwed up:

![geomhline](https://cloud.githubusercontent.com/assets/5372770/9293919/7983362e-443c-11e5-8ee2-606355392693.png)

---

Ok, let's see whether we can make this work **via `geom_linerange()` with separate dataframes**:

```r
thresholds <- data.frame(threshold = "Funny Law", year = 2004, ymin = 0, ymax = 35)
g + geom_linerange(data = thresholds, mapping = aes(x = year, ymin = ymin, ymax = ymax, linetype = threshold))  # works ok
```
Works ok, except that the `geom_linerange` doesn't fill the entire y-height of the plot, but ok:

![linerange](https://cloud.githubusercontent.com/assets/5372770/9293925/cc48354e-443c-11e5-80a8-d096266de376.png)

---

Then wouldn't we expect the same approach to work **via `geom_vline()` with a separate dataframe?**

```r
# add threshold via geom_hline() WITH separate data
g + geom_vline(data = thresholds, mapping = aes(xintercept = year, linetype = threshold), show_guide = TRUE)  # screws up all geom_line legends
```

Nope, the same problem with screwed up legends returns:

![vlinesep](https://cloud.githubusercontent.com/assets/5372770/9293937/fe9b8e24-443c-11e5-98ad-835162344b35.png)

---

Bug or my mistake?

---

May be related:
- http://stackoverflow.com/questions/5027016/missing-legend-with-ggplot2-and-geom-line
- http://stackoverflow.com/questions/30807890/add-geom-hline-legend-without-screwing-up-geom-line-legend

**Comment by maxheld83** [comment]
updated, because earlier version was too complicated.

**Comment by hadley** [comment]
Here's an even simpler example:

```R
df <- data.frame(x = c(1, 2), y = c(1, 2), z = c("a", "b"))

threshold <- data.frame(x = c(1.2, 1.5), name = c("bar", "foo"))
ggplot(df, aes(x, y, colour = z)) + 
  geom_point() + 
  geom_vline(aes(xintercept = x, linetype = name), show.legend = TRUE, data = threshold)
```

**Comment by hadley** [comment]
There are a couple of problems here. There's a bug in the legend generation code which means that the legends where inheriting aesthetics when they shouldn't. There's another problem that `show.legend = TRUE` forces inclusion on _every_ legend. But that problem goes away if `geom_vline()` defaults to `show.legend = NA`.

Both these cases now work:

```R
df <- data.frame(x = c(1, 2), y = c(1, 2), z = c("a", "b"))
ggplot(df, aes(x, y, colour = z)) + 
  geom_point() + 
  geom_vline(xintercept = 1.5))

threshold <- data.frame(x = c(1.2, 1.5), name = c("bar", "foo"))
ggplot(df, aes(x, y, colour = z)) + 
  geom_point() + 
  geom_vline(aes(xintercept = x, linetype = name), data = threshold)
```

**Comment by rdcomineor** [comment]
Hello, Unfortunately the problem persists in the legends of the lines if you also have to add a horizontal line: 
` threshold <- data.frame(x = c(1.2, 1.5), name = c("bar", "foo"))
 ggplot(df, aes(x, y, colour = z)) + 
 geom_point() + 
    geom_vline(aes(xintercept = x, linetype = name), data = threshold)+geom_hline(aes(yintercept = 2, linetype = name), data = threshold)`

Do you have a suggestion? Many thanks

**Comment by cyberang3l** [comment]
Is there any solution to the _cross_ problem demonstrated by @rdcomineor when using both geom_hline and geom_vline?

**Comment by ptoche** [comment]
@cyberang3l, I couldn't run the example given by @rdcomineor, but I had a similar problem with ``geom_linerange()`` and solved it by inserting ``show.legend=FALSE``: ``geom_linerange(aes(ymin = y, ymax = x, color = "vline"), show.legend=FALSE) ``

**Comment by fmassicano** [comment]
The problem still persists if you have hline and vline in the same chart.

**Comment by ptoche** [comment]
@fmassicano, as this issue is closed, why don't you post a new issue with a working, minimal example. Also, please post screenshot with the reprex package. 

https://github.com/tidyverse/reprex
