### ISSUE TITLE
Native handling of spatial data

### ISSUE THREAD

**Issue by Robinlovelace** [hadley/ggplot2#1269]
Currently the user must `fortify()` spatial data before plotting it.

It would make life easier others if ggplot2 did this internally.

The additional advantage would be that using the data slot (`sp_obj@data`) would have a purpose - to differentiate between the data and the spatial information.

Would it be possible to fortify inside the function? Or would you suggest an alternative approach?
Understand that there may be good reasons for keeping it as-is, due to ggplot2's emphasis on data frames.

Would have implications for [ggmap](https://github.com/dkahle/ggmap).

This also relates to the [tmap](https://github.com/mtennekes/tmap) package.

Just an idea. Happy to help if I can with this. Thanks!

**Comment by hadley** [comment]
ggplot2 already does automatically fortify the data if needed?

**Comment by Robinlovelace** [comment]
Not that I can see after a brief test and searching the [ggplot2](https://github.com/hadley/ggplot2/search?utf8=%E2%9C%93&q=fortify) and [ggplot2 book](https://github.com/hadley/ggplot2-book/search?utf8=%E2%9C%93&q=fortify) repos.

Here's a dumb reproducible example that may provide a basis for enlightening me:

```
downloader::download("https://github.com/johan/world.geo.json/raw/master/countries.geo.json", "world.geojson")
wrld <- geojsonio::geojson_read("world.geojson", what = "sp")
plot(wrld)
```
![rplot](https://cloud.githubusercontent.com/assets/1825120/9306794/66c4a1ec-44f2-11e5-941a-f1691c6cd528.png)

```
qplot(wrld)

## Don't know how to automatically pick scale for object of type SpatialPolygonsDataFrame. Defaulting to continuous
Error: stat_bin requires the following missing aesthetics: x
```

**Comment by hadley** [comment]
Well, you obviously need to know the variables that fortify creates, which highlights why auto-fortification is not that useful.

**Comment by Robinlovelace** [comment]
Thanks for the clarification - I'll not use the 'auto-fortification' method in my teaching materials.

If 'auto-fortification' is not that useful, that explains why it seems to be rather undocumented. Would it not would be better if it were either in there and worked well (i.e. made column variables available) or not in there at all? It's an issue problem that I imagine many people will encounter given the popularity of ggmap.

Really grateful that ggplot2 exists in any case - will keep exploring its spatial capabilities.

**Comment by BrianDiggs** [comment]
@Robinlovelace This is somewhat the problem that `autoplot` was supposed to solve: to plot the generally right thing using the conventions of (possibly auto-)fortified data. Basically to set reasonable aesthetic mappings, scales, and geoms/stats. It never quite got to the level of acceptance that it might have.
