### ISSUE TITLE
environment Parameter to Geoms Silently Ignored

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1273]
Although the geoms accept `environment` without complaint, they don't use it, which means local variables can't be used, such as in the `switch` statements in the example code. This problem was described a long time ago on the mailing list. Could there be a satisfactory solution before the next version of **ggplot2**? The least that the geoms could do is print a message to the user that the `environment` is being ignored, so the user knows that it is happening.

This problem is limiting, as shown in this runnable, short example : 

    f <- function()
    {
      Xvar <- "comp"
      oneData <- data.frame(algorithm = LETTERS[1:3], computer = factor(c("IBM", "MAC", "Tablet")),  error = runif(3))
     otherData <- data.frame(algorithm = rep(LETTERS[1:3], 3), computer = rep(c("X", "Y", "Z"), 3),  error = runif(9))
      fillColour <- "comp"
  
      g = ggplot() + scale_y_continuous(limits = c(0, 1)) +
                     scale_fill_manual(values = scales::hue_pal()(6)) +
                     scale_colour_manual(values = scales::hue_pal()(6)) + theme(legend.position = "none")
  
      g = g + geom_bar(data = oneData, stat = "identity", aes(x = switch(Xvar, algo = algorithm, comp = computer), y = error, fill = switch(fillColour, algo = algorithm, comp = computer)), environment = environment()) +
              geom_boxplot(data = otherData, aes(x = switch(Xvar, algo = algorithm, comp = computer), y = error, fill = switch(fillColour, algo = algorithm, comp = computer)), environment = environment())
      print(g) # Error message. object 'Xvar' not found
  
      # Setting environment does work in ggplot function, however.
      h = ggplot(data = oneData, aes(x = switch(Xvar, algo = algorithm, comp = computer), y = error), environment = environment()) + geom_point()
      print(h)
    }

    f()

I suppose the user could make all necessary variables global with `<<-` and delete them at the end of the function, although that's bad practice.

With version 1.0.1.

**Comment by hadley** [comment]
Geoms take ..., so I don't think you should assume an `environment` argument does anything. See http://rpubs.com/hadley/97970 for more details. You should be able to avoid most of your problems with the new `aes_`. If you can't figure it out, please file a _minimal_ example that causes a problem.
