### ISSUE TITLE
dir = "v" also needs to swap nrow and ncol

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1279]
```R
mpg2 <- subset(mpg, cyl != 5 & drv %in% c("4", "f") & class != "2seater")

base <- ggplot(mpg2, aes(displ, hwy)) + 
  geom_blank() + 
  xlab(NULL) + 
  ylab(NULL)

base + facet_wrap(~class, nrow = 3)
base + facet_wrap(~class, nrow = 3, dir = "v")
```

**Comment by chrismerkord** [comment]
There's a bug here that is not apparent unless you use an nrow other than what it defaults to when NULL. For example, try:

    base + facet_wrap(~class, nrow = 2, dir = "v")

The problem is that the swap code always results in nrow and ncol being equal or both being NULL, depending on which argument is defined:

    # swap
    nrow <- sanitise_dim(ncol)
    ncol <- sanitise_dim(nrow)  # nrow here is not what you thought it was!

You'll have to create a dummy variable to swap them, e.g.:

    # swap
    nrow_swap <- ncol
    ncol_swap <- nrow
    nrow <- sanitise_dim(nrow_swap)
    ncol <- sanitise_dim(ncol_swap)

**Comment by chrismerkord** [comment]
I wasn't as specific about the diagnosis of the bug as I could have been. When you run:

    mpg2 <- subset(mpg, cyl != 5 & drv %in% c("4", "f") & class != "2seater")
    base <- ggplot(mpg2, aes(displ, hwy)) + 
      geom_blank() + 
      xlab(NULL) + 
      ylab(NULL)
    base + facet_wrap(~class, nrow = 2, dir = "v")

you should get a figure with 2 rows. Instead the figure has 3 rows. Inspecting the plot shows that nrow and ncol both have a value of NULL.

Likewise when you run

    base + facet_wrap(~class, ncol = 2, dir = "v")

both nrow and ncol are 2 when it should be nrow == 2 and ncol == NULL.

**Comment by hadley** [comment]
Please file a new bug

**Comment by chrismerkord** [comment]
I filed a new bug: hadley/ggplot2#1417
