### ISSUE TITLE
psych has namespace conflict with ggplot2: %+%

### ISSUE THREAD

**Issue by maxheld83** [hadley/ggplot2#1284]
This is not so much a bug, but just something I wanted to log for people so they don't waste time on figuring this out as myself:

The [`psych`](https://cran.r-project.org/web/packages/psych/index.html) package also exports `%:%` into the namespace, so if you `import` it too liberally, you end up with namespace warnings on `R CMD check`:

```
replacing previous import by ‘ggplot2::%+%’ when loading ‘qmethod’
```

**Comment by maxheld83** [comment]
This is, of course, easily fixed, like so, for example:

```
importFrom("psych", "principal")  # that's the function we were using
```

I've also told the psych author, William Revelle, about this.

Here's the Stackexchange question and answer: http://stackoverflow.com/questions/28662289/pesky-ggplot2-namespace-conflict-when-using-ggplot2-in-package

**Comment by hadley** [comment]
In general, I think it's a bad idea to import an entire namespace to avoid exactly this problem.
