### ISSUE TITLE
data frame issue in ggmap following ggplot2 1.0.1.9003 installation

### ISSUE THREAD

**Issue by two-uwl** [hadley/ggplot2#1285]
Following installation of ggplot2 1.0.1.9003 (R 3.2.1, Mac OS; issue also occurred with 1.0.1.9002), ggmap (2.5.2) produces the following error:

**Error in if (empty(data)) return(data.frame()) : 
  missing value where TRUE/FALSE needed**
The issue did not occur under ggplot2 1.0.1 with R 3.2.1 or 3.2.2.

``` r
library(ggmap)
myLocation <- c(-130, 30, -105, 50)
myMap <- get_map(location = myLocation, source = "google", maptype = "terrain", crop = FALSE)
ggmap(myMap)
```

**Comment by hadley** [comment]
This is more of a ggmap issue. It'll need to be updated for the changes to ggplot2 internals
