### ISSUE TITLE
Create alias for `colors=` in `scale_color_gradientn()`

### ISSUE THREAD

**Issue by beroe** [hadley/ggplot2#1290]
Not sure if this has been addressed before, or if it is by design: It works if you spell `colours=` as an argument for `scale_color_gradientn`  but not if you put `colors=`

       + scale_color_gradientn(colors = rainbow(4))  # fails      
       + scale_color_gradientn(colours = rainbow(4))  # works

**Comment by kellieotto** [comment]
Aha. I just had the same problem.
