### ISSUE TITLE
Set default aesthetics in theme?

### ISSUE THREAD

**Issue by and3k** [hadley/ggplot2#1294]
Hi!

I was looking for a way to globally set the default size of geom_points, and I don’t think that’s possible. Seems pretty hard coded in  `R/geom-point-.r`. Would it make sense to set all these default aesthetics in `theme_*`? Not only for size/points but everything? Font size is also themed, why not point/line size? Panel colour is themed, so why not line/point colour?

Just an idea…

Thanks,
Bela

**Comment by hadley** [comment]
It's not possible unfortunately.

**Comment by and3k** [comment]
OK Thanks!
