### ISSUE TITLE
ggplot2 can't pass ... to fortify

### ISSUE THREAD

**Issue by GuangchuangYu** [hadley/ggplot2#1300]
`ggtree` is designed by extending `ggplot2` and implemented several `fortify` methods for tree objects.

I compile `ggtree` with newest version of `ggplot2`, it throw the following error:

```
Error: processing vignette 'ggtree.Rmd' failed with diagnostics:
Unknown parameters: time_scale, yscale_mapping
```

This is due to I pass these two parameters to `ggplot` via `...`, and these two parameters were defined in the parameter list of `fortify` method. 

It works fine with release version of ggplot2 but throw error with newest one.

For `ggtree`, the issue can be solved by passing these two parameters explicitly via `ggplot`, but I think `...` is a good mechanism and hope it's supported.

**Comment by GuangchuangYu** [comment]
I found that in the source code you mentioned `fortify` may deprecated.

Please keep it. It's really a good feature to keep `ggplot` extensible. 

It has no harm, user can call `df <- fortify(object)` followed by `ggplot(df)`. The structure is very clean with data tidy process separating from graphing.

**Comment by hadley** [comment]
I think this is a different problem, because nothing to do with `ggplot()` has been changed:

```R
ggplot.default <- function(data = NULL, mapping = aes(), ...,
                           environment = parent.frame()) {
  ggplot.data.frame(fortify(data, ...), mapping, environment = environment)
}
```

But layers now check their parameters, so it's likely that you've been supplying parameters to a layer that have been silently ignored until now.

**Comment by GuangchuangYu** [comment]
Yes, it was passed to other layer since `ggtree` is a shortcut and passes `...` to both `ggplot` and `geom_tree`.

```r
ggtree <- function(...) ggplot(...) + geom_tree(...)
```

Thanks for your reply.  Very clear now.
