### ISSUE TITLE
geom_jitter inconsistency

### ISSUE THREAD

**Issue by val77** [hadley/ggplot2#1307]
Hi
I found that the result of geom_jitter varies depending on what is printed beforehand:
```R
library(ggplot2)
dat <- data.frame(a = rep(1:100, 2), b = sqrt(rep(1:100, 2)))

p <- ggplot(dat, aes(a, b)) + 
  geom_jitter(shape = 1)


p_linear <- p +
  scale_x_continuous(limits = c(0, 100)) + 
  scale_y_continuous(limits = c(0, 10))

p_sqrt <- p +
  scale_x_sqrt(limits = c(0, 100)) + 
  scale_y_sqrt(limits = c(0, 10))


png("plot_linear.png")
print(p_linear)
dev.off()

png("plot_sqrt.png")
print(p_sqrt)
dev.off()
```
plot_sqrt.png:
![plot_sqrt](https://cloud.githubusercontent.com/assets/14051936/9575738/2cedfffa-4fd2-11e5-92e5-f8d364f9fc72.png)

```R
p <- ggplot(dat, aes(a, b)) + 
  geom_jitter(shape = 1)

p_linear <- p +
  scale_x_continuous(limits = c(0, 100)) + 
  scale_y_continuous(limits = c(0, 10))


p_sqrt <- p +
  scale_x_sqrt(limits = c(0, 100)) + 
  scale_y_sqrt(limits = c(0, 10))


png("plot_sqrt_only.png")
print(p_sqrt)
dev.off()
```
plot_sqrt_only.png:
![plot_sqrt_only](https://cloud.githubusercontent.com/assets/14051936/9575734/271919de-4fd2-11e5-88bb-9346fdbca88f.png)

The only difference between the two code snippets are these three lines:

```R
png("plot_linear.png")
print(p_linear)
dev.off()
```

Note that there is jittering in both cases, but just must less in the second figure.

One of the two must be wrong, or I missed an important part of how ggplot works (absolutely possible as well). In my opinion, the first plot is the correct behavior.

**Comment by hadley** [comment]
I think there's something else going on in your R session because I get identical results.

**Comment by val77** [comment]
Thanks for your reply. This is strange. I run the above script from the command line with Rscript --vanilla. Thus, I don't see what could be interfering. I use R 3.2.0 & ggplot2 1.0.1. Could the R version be an issue?

**Comment by hadley** [comment]
It's possible it was a bug that was fixed in the dev version

**Comment by val77** [comment]
true, this behavior disappears when using the dev version. thanks for your help!
