### ISSUE TITLE
legend for `geom_line` colour disappears when `alpha` < 1.0

### ISSUE THREAD

**Issue by nutterb** [hadley/ggplot2#1313]
I started seeing some odd behavior from `geom_line` this morning.  When I set `alpha` to a value less than 0, the lines in the legend are disappearing.

Issue exists with ggplot2 1.0.1 and 1.0.1.9003.
I'm using R 3.2.1

This example works as expected
```r
ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line() + 
  geom_point()
```

It also works when I set `alpha = 1.0`
```r
ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line(alpha = 1.0)
```

But as soon as I change `alpha` to any value less than 1.0, look at the change in the legend.
```r
ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line(alpha = .99) + 
  geom_point(alpha = .99)
```

It seems to affect only `geom_line`.  I've looked at `geom_point` and `geom_text`, and neither of those appear to be affected.

**Comment by hadley** [comment]
Works for me.

**Comment by kaushiklakshman** [comment]
Hi,

This seems to be an error with me too. 

ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line(alpha = .99) 

takes away the colour in the legend

ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line(alpha = 1)

shows the colour in the legend

ggplot(mtcars,
       aes(x = qsec,
           y = mpg,
           colour = factor(am))) + 
  geom_line(alpha = .99) + 
 geom_point(alpha = .99)

 shows the colour in the legend

My R version is 3.2.2 and ggplot version is 1.0.1

**Comment by technocrat** [comment]
I get colour in the legend in all three with the same versions on an older Mac Air both in the R Console and RStudio. Perhaps its a graphics driver issue?

**Comment by kaushiklakshman** [comment]
Probably is. There is a work around though, if I use the zoom button on Rstudio or write it to a file, the lines are back. Thank you.
