### ISSUE TITLE
dev version 1.0.1.9003 has some breaking changes

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1316]
I have a package that [adds marginal plots to ggplot2 scatterplots](https://github.com/daattali/ggExtra), and I'm seeing many breaking changes when updating to the latest version. Only the first two seem like actual "bugs" from your point of view, but the rest are behaviour changes that are frustrating enough that I wanted to see if you could give them some attention :)

## geom_bar() looks completely different

The following code produces very different plots in 1.0.1 vs 1.0.1.9003

```
ggplot(mtcars, aes(wt)) + geom_bar()
```

Old version:

![rplot](https://cloud.githubusercontent.com/assets/952340/9618855/fb447ef0-50be-11e5-8085-a14c202f64fa.png)

New version:

![rplot](https://cloud.githubusercontent.com/assets/952340/9618866/093f152e-50bf-11e5-9390-2f107fd0f980.png)

## Providing a binwidth to geom_bar doesn't work anymore

Previously this worked

```
ggplot(mtcars, aes(wt)) + geom_bar(binwidth = 5)
```

The new version throws an error

```
Error: Unknown parameters: binwidth
```

I did see the NEWS said there was a change to do with geom_bar having its own stat_bar, but I didn't think this is the same issue

The NEWS also mentions that  "It's now obvious that you can set the `binwidth` parameter for ...", but that doesn't tell me why it no longer works for a layer that used to work.

## Providing unused params to a layer throws an error

This is documented in the NEWS, but it'd be nice to be able to suppress these error messages. A simple example could be: If I have a function that takes in the name of a layer and accepts a list of arguments to pass to the layer, and it just uses a default list of arguments, previously it was easy enough to just say "call whatever layer you want, and use this list of arguments". But now this throws an error and you'd have to check which layer exactly is used and filter all the arguments.  Maybe I'm alone on this one, but if I'm getting errors from it, I assume there are others who will also all of a sudden get errors when updating.

## Possible to suppress "warning" messages?

It looks like the scales were completely changed internally, and this (or some other change) is causing my code to now produce a message every time

```
Scale for 'x' is already present. Adding another scale for 'x', which will replace the existing scale.
```

Previously the "stat:bin: binwidth default to ..." message used to appear all the time without an easy way of suppressing it.  I think it's be great if there was a way to suppress these types of messages directly from ggplot2, maybe with a global option or something like that, because it's a bit annoying to keep seeing these messages appear, and I'm not sure when exactly they get printed.

Again, this may be just an issue for me.

**Comment by hadley** [comment]
1. Use `geom_histogram()` not `geom_bar()`

2. I think being strict about `layer()` arguments is going to be painful in the short-term, but it's very important in the long-term because it prevent spelling mistakes from going unnoticed. If you share exactly what you're doing, I can probably offer some workarounds.

3. You can use `suppressMessages()` to suppress messages ;)  (But the scales warning has been there for a while)

There will be a length formal release process to make sure as many of these problems become known before ggplot2 is released on CRAN

**Comment by daattali** [comment]
1. Suppressing messages:  The binwidth message still shows up even with `suppressMessages()`

```
> suppressWarnings(ggplot(mtcars, aes(wt)) + geom_histogram())
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

And I know the scale warning existed before too, but in my code it doesn't show up previously but now it does. Must be something to do with the new internals of scales.

2. The issue with arbitrary parameters to layers: I definitely see your point, but yes it is going to be painful in the short term. I have a function that can be reduced to the following:

```
# ... can be any arguments to pass to the respective layer
foo <- function(p, plot_type = c("line", "boxplot"), ...) {
  plot_type <- match.arg(plot_type)
  params <- list(...)

  # some default layer arguments
  if (is.null(params[['colour']])) {
    params[['colour']] <- "black"
  }
  if (is.null(params[['fill']])) {
    params[['fill']] <- "grey"
  }
  
  layer <- do.call(sprintf("geom_%s", plot_type), params)
  p + layer
}
```

Previously this would work. In the new version, I would need to know which layers exactly accept a 'fill' argument.  One thing that makes this a bit harder is that I don't even know how to tell what arguments are allowed for a specific layer. Is there a way to know exactly all the arguments allowed for `geom_line`?

**Comment by hadley** [comment]
1. Are you sure you have the latest version of Rcpp and plyr?

1. Hmmmm, you can get the aesthetics to a geom with (e.g.) `GeomLine$aesthetics()`

**Comment by daattali** [comment]
Latest dev versions of both, just installed a minute ago. 

```
> suppressWarnings(ggplot(mtcars, aes(wt)) + geom_histogram())
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1.9003

loaded via a namespace (and not attached):
[1] labeling_0.3     colorspace_1.2-6 scales_0.3.0     plyr_1.8.3.9000  tools_3.2.2     
[6] gtable_0.1.2     Rcpp_0.12.0.5    grid_3.2.2       munsell_0.4.2   
```

This isn't a big issue, just wanted to maybe have a way to tell ggplot to not report all such messages

Good to know about the GeomFoo$aesthetics()

**Comment by daattali** [comment]
re: GeomFoo: Looks like there isn't a one-to-one mapping though, I was hoping every `geom_foo()` would have a corresponding `GeomFoo`, but I see there is no `GeomHistogram`.

**Comment by timelyportfolio** [comment]
Related https://github.com/cttobin/ggthemr/issues/4

**Comment by hadley** [comment]
If I've missed anything in this discussion, can you please open individual issues?
