### ISSUE TITLE
dev version 1.0.1.9003: theme_bw() has very different margins than without

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1317]
In CRAN version:  `ggplot(mtcars,aes(wt,mpg)) + geom_point() + theme_bw(50)` and `ggplot(mtcars,aes(wt,mpg)) + geom_point() + theme(text = element_text(size = 50))` produced identical plots (except for the background colour and text colour)

In dev version, the call with theme_bw has huge plot margins

**Comment by hadley** [comment]
Yes, because margins should scale with text size
