### ISSUE TITLE
Documentation error on %+replace% ?

### ISSUE THREAD

**Issue by sethchandler** [hadley/ggplot2#1318]
The ggplot2 documentation for +.gg {ggplot2} (the addition operator) reads as follows:

The + operator completely replaces elements with elements from e2.

In contrast, the %+replace% operator does not replace the entire element; it only updates element properties which are present (not NULL) in the second object.

And, yet, when one runs the examples in the documentation that purport to illustrate this point, it appears to me that precisely the opposite is true. That is, the + operator really amounts to inheritance, the result inherits from the LHS side of the + but changes only that found on the RHS. Whereas the %+replace% operator basically kills off the LHS side by NULLing out anything for which there is no value on the RHS.

So my questions are: 1) am I misunderstanding what is going on? 2) is there an error in the documentation 3) assuming I understand the role of %+replace% correctly, why would one ever use it?

**Comment by hadley** [comment]
Fixed in dev version.
