### ISSUE TITLE
Request: support theme axis.ticks.length.x and axis.ticks.length.y

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1319]
I'm wondering if there is a deliberate reason why `axis.ticks.length` exists but you can't customize it for the X and Y axes?

If I want to have long tickmarks on the Y axis but very short ones on the X, it feels like this should be possible.

```
ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  theme(axis.ticks.length.x = unit(2, "cm"), axis.ticks.length.y = unit(2, "mm"))
```

**Comment by hadley** [comment]
I'd be willing to review a PR, but it's sufficiently low priority that I'm unlikely to ever implement myself.
