### ISSUE TITLE
stat_bar() gets confused with numeric discrete data?

### ISSUE THREAD

**Issue by lionel-** [hadley/ggplot2#1320]
it seems that `geom_bar()` with discrete numeric data does not produce correct output:

```r
mtcars$carb %>% table()
##  1  2  3  4  6  8 
##  7 10  3 10  1  1 
```
```r
ggplot(mtcars, aes(carb)) + geom_bar()
```
![geom_bar](https://cloud.githubusercontent.com/assets/4465050/9658496/0a0faa7c-524a-11e5-8af1-7ea0cab98e1a.png)

**Comment by hadley** [comment]
You mean the counts are wrong? Hmmmm

**Comment by lionel-** [comment]
yes. Coercing to factor beforehand make it right.

**Comment by dannguyen** [comment]
@lionel- I get the right plot with the exact same code snippet (using ggplot2 1.0.1) without coercion to factor:

           ggplot(mtcars, aes(carb)) + geom_bar()

![image](https://cloud.githubusercontent.com/assets/121520/9796659/2c7ab978-57ac-11e5-80af-5ba4648f06ec.png)

**Comment by lionel-** [comment]
The bug is with the dev version which uses a new Stat.
