### ISSUE TITLE
Problem with geom_bar position=fill and faceting

### ISSUE THREAD

**Issue by neggert** [hadley/ggplot2#1322]
After updating to the development version (master), I'm getting incorrect plots when I try to make a `geom_bar` plot with `position='fill'` and facets. Here's an example:

```
ggplot(diamonds) +
  aes(x=color, fill=cut) +
  geom_bar(position='fill') +
  facet_wrap( ~ clarity)
```

And the result:
![image](https://cloud.githubusercontent.com/assets/1271014/9663174/ba522b34-5228-11e5-9982-2202b15f6d76.png)

**Comment by hadley** [comment]
Works for me - probably fixed in the interim.
