### ISSUE TITLE
Non-interactive calls to ggsave() can have irritating side effects

### ISSUE THREAD

**Issue by jennybc** [hadley/ggplot2#1326]
Posting an issue sort of on behalf of @cscheid because I am so thrilled at the prospect of this getting fixed! (Please correct me if I'm mangling your problem, @cscheid.)

Calls to `ggsave()` that don't specify device width and height cause a graphics device to be opened and consulted for dimensions. In non-interactive settings, this can have irritating side effects, such as leaving an (empty or corrupt) `Rplots.pdf` file behind.

Reprex: put these commands in `foo.R`:

``` r
library(ggplot2)
p <- ggplot(mtcars, aes(x=cyl,y=mpg)) + geom_point()
ggsave("cars.png", p)
```

and run `Rscript foo.R`. This produces `cars.png` AND `Rplots.pdf`, at least on my Mac.

Other places people where people have vented about this: stackoverflow thread [How to stop R from creating empty Rplots.pdf file when using ggsave and Rscript](http://stackoverflow.com/questions/17348359/how-to-stop-r-from-creating-empty-rplots-pdf-file-when-using-ggsave-and-rscript), ggplot2 board thread [ggsave always opens a graphics window on Mac OS](https://groups.google.com/forum/#!msg/ggplot2/ZGevTRMz9iE/xz8PjlR4KMEJ)

**Comment by cscheid** [comment]
:+1: This is exactly what's been happening with me as well. Notice the silly, overspecified (but necessary) `width` and `height` in [rplot](https://github.com/cscheid/rplot/blob/master/rplot)

**Comment by cscheid** [comment]
(Incidentally, thank you, @jennybc, for filing the reprex and getting this off of my todo list! :))

**Comment by jennybc** [comment]
I may or may not have encountered this problem before :grin:

**Comment by hadley** [comment]
Well in the dev version this produces:

```R
Desktop : Rscript test.R 
Error: No graphics device is open. Please supply height and width
Execution halted
```

but I think we can do a bit better ;)

**Comment by jennybc** [comment]
Here's a pretty funny [GitHub search](https://github.com/search?utf8=✓&q=rm+Rplots.pdf+filename%3AMakefile&type=Code&ref=searchresults). Sure there are lots of false positives but I still think the ggplot2 world will rejoice.

**Comment by cscheid** [comment]
@jennybc that's a brilliant use of GitHub search, you're blowing my mind here.
