### ISSUE TITLE
stat_binhex() not rendering when using  coord_map() to project coordinates

### ISSUE THREAD

**Issue by dannguyen** [hadley/ggplot2#1331]
I'm posting this here in the possible chance that it's just a small fix, or a completely obvious snafu that I've missed...It *seems* like the error would originate from ggplot2. On the other hand, `stat_binhex()` seems to require the hexbin package, so I initially [posted the issue there](https://github.com/edzer/hexbin/issues/1#issuecomment-139127132). The maintainer believes the error is in ggplot2. I haven't taken the time to look through both codebases but will hopefully have time later this week. But since I already wrote out the bug report...might as well paste it here.

Original text:

When using ggplot2's `coord_map()` to project a geospatial plot, the `stat_binhex()` method doesn't appear to accommodate the projection when rendering the plot. I thought that this might be just an issue with statbinning in general, but `stat_density2d()` and `stat_bin2d()` seem to work without problem.

I'm currently using:

- R version 3.2.1
- ggplot2_1.0.1
- hexbin_1.27.1

Full [sessionInfo at the bottom of this post](#sessioninfo)

### Data downloading and prep code

Here's the code to get some (public) data for example purposes:

__Note:__ This script creates a local directory named ./data

~~~R
dir.create('./data')

library(ggplot2)
library(rgdal)
library(hexbin)

theme_set(theme_bw())
# Downloads map to ./data
m_fname <- "./data/cb_2014_us_state_20m.zip"
download.file("http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_us_state_20m.zip", m_fname)
unzip(m_fname, exdir = "./data/shp")
us_map <- readOGR("./data/shp/cb_2014_us_state_20m.shp", "cb_2014_us_state_20m")
# just keep lower 48
us_map <- subset(us_map, !(us_map$STUSPS %in% c('AK', 'HI', 'AS', 'DC', 'GU', 'MP', 'PR', 'VI')))

# Download earthquake data
q_fname <- "./data/all_week.csv"
download.file("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.csv", q_fname)
quakes <-read.csv(q_fname, stringsAsFactors = FALSE)

########################
# Data filtering
# make the sp data frame
xsp <- SpatialPointsDataFrame(data = quakes,
                                    coords = quakes[,c("longitude", "latitude")])
xsp@proj4string <- us_map@proj4string
# filter out non-us quakes
us_quakes <- as.data.frame(xsp[us_map,])

p_map <- ggplot(data = us_quakes, aes(x = longitude, y = latitude)) +
         geom_polygon(data = us_map, aes(x = long, y = lat, group = group),
               fill = NA, color = "#888888", size = 0.3)
~~~

### Default projection hex-binned map:

~~~R
p_map + stat_binhex(bins = 30, color = "white") +
        scale_fill_gradientn(colours = c("pink", "red")) +
        coord_equal()
~~~

![image](https://cloud.githubusercontent.com/assets/121520/9773717/c408caf0-56f8-11e5-8a14-01423cde9a2e.png)

### Albers-projected, rect-binned map:

~~~R
p_map + stat_bin2d(bins = 30, color = "white") +
        scale_fill_gradientn(colours = c("pink", "red")) +
        coord_map("albers", lat0 = 39, lat1 = 42)
~~~

![image](https://cloud.githubusercontent.com/assets/121520/9773721/d133f56a-56f8-11e5-9168-98cf377812f2.png)

### Albers-projected, density map:

~~~R
p_map + stat_density2d() +
        coord_map("albers", lat0 = 39, lat1 = 42)
~~~

![image](https://cloud.githubusercontent.com/assets/121520/9773740/eb823a08-56f8-11e5-8558-d9c40df61b37.png)

### Albers-projected, hexbinned map

~~~R
p_map + stat_binhex(bins = 30, color = "orange") +
        scale_fill_gradientn(colours = c("pink", "red")) +
        coord_map("albers", lat0 = 39, lat1 = 42)
~~~

![image](https://cloud.githubusercontent.com/assets/121520/9773756/03dd80f8-56f9-11e5-8872-3d0816b431eb.png)

Note that I set the `color` to `orange` so that you might make out the dots that each hexbin reduces to (if you squint).

### Not using coord_map()

FWIW, I can get a properly hexbinned map by not using `coord_map()`...but if `stat_bin2d()` works without the following workaround, I figured maybe there was a bug in `hexbin`:

```R
albers_crs <- CRS("+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs")

# Apply Albers projection to earthquakes data
# note: `us_quakes` is a data frame and needs to be re-spatialized
ysp <- SpatialPointsDataFrame(data = us_quakes,
                                    coords = us_quakes[,c("longitude", "latitude")])
ysp@proj4string <- us_map@proj4string

albers_quakes <- as.data.frame(spTransform(ysp, albers_crs))

# Apply the Albers projection to usc_map
albers_map <- spTransform(us_map, albers_crs)

# Note: We have to use longitude.2` and `latitude.2` in the aesthetic 
# due to the way SpatialPointsDataFrame constructor avoids naming collisions 
ggplot(data = albers_quakes, aes(x = longitude.2, y = latitude.2)) +
    geom_polygon(data = albers_map, aes(x = long, y = lat, group = group),
                 fill = NA, color = "#888888", size = 0.3) +
    stat_binhex(bins = 30, color = "white") +
    scale_fill_gradientn(colours = c("pink", "red"))
```

![image](https://cloud.githubusercontent.com/assets/121520/9774018/c1ac2eee-56fa-11e5-97f1-e5e4cfc8ad9d.png)
    

<a id="sessioninfo"></a>

#### My full sessionInfo()

```
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin14.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] hexbin_1.27.1 rgdal_1.0-6   sp_1.1-1      ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0      lattice_0.20-31  digest_0.6.8     MASS_7.3-40      grid_3.2.1       plyr_1.8.3      
 [7] gtable_0.1.2     magrittr_1.5     scales_0.3.0     stringi_0.5-5    reshape2_1.4.1   proto_0.3-10    
[13] tools_3.2.1      stringr_1.0.0    munsell_0.4.2    colorspace_1.2-6
```

**Comment by hadley** [comment]
Minimal reprex:

```R
ggplot(mpg, aes(displ, hwy)) + 
  geom_hex() + 
  coord_polar()
```

**Comment by hadley** [comment]
Looks like this never worked and would require considerable effort to make it work, so I'll just make a better warning message.
