### ISSUE TITLE
Average numeric aesthetics in stat_summary_bin()

### ISSUE THREAD

**Issue by lionel-** [hadley/ggplot2#1332]
Currently aesthetics such as colour and size are ignored.

**Comment by lionel-** [comment]
That would also make sense for `StatCount` and maybe even for `StatBin`. This way we can colour the bars according to a numeric aes to look for patterns.

**Comment by hadley** [comment]
This isn't high enough priority for me to tackle right now. I'd be happy to review a PR for the next version of ggplot2, which will probably go out 3-6 months after 1.1.0.
