### ISSUE TITLE
What ggproto helpers should be exported?

### ISSUE THREAD

**Issue by lionel-** [hadley/ggplot2#1333]
Opening this issue so people can report what they need when creating custom ggproto objects. So far I'm using:

* `make_summary_fun()` for creating summary Stats.
* `transform_position()` for Positions

Hadley already mentioned `ggname()` shouldn't be exported for now.

**Comment by hadley** [comment]
`element_grob()` from #1339

**Comment by hadley** [comment]
* `make_summary_fun()`: I'm no longer a big fan of this approach, so I'd prefer not to export it.
* `transform_position()`: done
* `element_grob()`: done
