### ISSUE TITLE
ggplot2 breaks Hmisc installation

### ISSUE THREAD

**Issue by jthetzel** [hadley/ggplot2#1335]
I can't tell if ggplot2 or Hmisc are at fault, but am posting here so others are aware of the problem and a workaround.

Installing the development ggplot2 breaks subsequent installation of Hmisc:
```R
> devtools::install_github("hadley/ggplot2")
> install.packages("Hmisc")
** R
** inst
** preparing package for lazy loading
Warning: replacing previous import by ‘ggplot2::unit’ when loading ‘Hmisc’
Warning: replacing previous import by ‘ggplot2::arrow’ when loading ‘Hmisc’
Warning: replacing previous import by ‘scales::alpha’ when loading ‘Hmisc’
Error in eval(expr, envir, enclos) : could not find function "eval"
Error : unable to load R code in package ‘Hmisc’
ERROR: lazy loading failed for package ‘Hmisc’
```
As a workaround, revert to ggplot2 release, install Hmisc, then install ggplot2 dev. Warning messages appear when loading Hmisc, but everything works:
```R
> install.packages("ggplot2")
> install.packages("Hmisc")
> devtools::install_github("hadley/ggplot2")
> require("Hmisc")
Warning messages:
1: replacing previous import by ‘ggplot2::unit’ when loading ‘Hmisc’ 
2: replacing previous import by ‘ggplot2::arrow’ when loading ‘Hmisc’ 
3: replacing previous import by ‘scales::alpha’ when loading ‘Hmisc’ 
```
As previously discussed ([ggthemes #35](https://github.com/jrnold/ggthemes/issues/35)) the warning messages arise because Hmisc's NAMESPACE imports grid, ggplot2, and scales, causing `unit`, `arrow`, and `alpha` to be imported twice:
```R
import(methods)
import(stats)
import(survival)
import(Formula)
import(grid)
import(lattice)
import(ggplot2)
import(proto)
import(scales)
```
Arguably, Hmisc should change how it imports its namespace. However, given that there are probably a number of packages importing ggplot2 along with grid or scales, these warning messages might spook users.

I don't know what causes`Error in eval(expr, envir, enclos) : could not find function "eval"` during lazy loading, but it looks like the community is aware of the issue: [ggthemes #36](https://github.com/jrnold/ggthemes/issues/36) and [ggmap #65](https://github.com/dkahle/ggmap/issues/65)

**Comment by hadley** [comment]
This is Hmisc's fault really, but it will be solved during the release process.

**Comment by stephlocke** [comment]
So to clarify if we get these warnings in our packages, we can ignore as they'll go away? Or should we (as package devs) be changing the way we import grid & scales?

**Comment by hadley** [comment]
Package developers need to fix those warnings, by being more selective with imports (i.e. don't import all of scales, just import the functions that you need)
