### ISSUE TITLE
Legend key borders can become too large when rescaled

### ISSUE THREAD

**Issue by andrewheiss** [hadley/ggplot2#1338]
Using ggplot2 1.0.1.9003, the border around legend keys is now inherited from the size of the border in the plot. This poses a problem when legend keys are scaled down—the border does not scale correspondingly.

Here's an example:

    library(ggplot2)

    # Example data from ggplot::geom_map documentation
    ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3"))

    values <- data.frame(
      id = ids,
      value = c(3, 3.1, 3.1, 3.2, 3.15, 3.5)
    )

    positions <- data.frame(
      id = rep(ids, each = 4),
      x = c(2, 1, 1.1, 2.2, 1, 0, 0.3, 1.1, 2.2, 1.1, 1.2, 2.5, 1.1, 0.3,
            0.5, 1.2, 2.5, 1.2, 1.3, 2.7, 1.2, 0.5, 0.6, 1.3),
      y = c(-0.5, 0, 1, 0.5, 0, 0.5, 1.5, 1, 0.5, 1, 2.1, 1.7, 1, 1.5,
            2.2, 2.1, 1.7, 2.1, 3.2, 2.8, 2.1, 2.2, 3.3, 3.2)
    )

    # Thick border set outside of aes() makes legend keys borders gigantic
    p <- ggplot(values, aes(map_id = id, fill = id)) + 
      geom_map(map = positions, size = 2, colour = "black") +
      expand_limits(positions)
    p

<img width="554" alt="screen shot 2015-09-11 at 14 27 38" src="https://cloud.githubusercontent.com/assets/73663/9822947/60edc872-5891-11e5-94d1-2584214c474e.png">

    # Shrinking the legend.key.size down makes the legend keys unusable
    p + theme(legend.key.size=unit(0.65, "lines"))

<img width="554" alt="screen shot 2015-09-11 at 14 27 48" src="https://cloud.githubusercontent.com/assets/73663/9822944/60e0ee22-5891-11e5-8ad2-3bd1b8f10aeb.png">

    # This is also the case when using guide_legend()
    p + guides(fill = guide_legend(keywidth = 0.65, keyheight = 0.65))

<img width="558" alt="screen shot 2015-09-11 at 14 27 56" src="https://cloud.githubusercontent.com/assets/73663/9822943/60e0d16c-5891-11e5-8940-30e35397aa7e.png">

    # Current workaround is to use override.aes inside guide_legend()
    p + theme(legend.key.size=unit(0.65, "lines")) + 
      scale_fill_discrete(guide = guide_legend(override.aes=list(size = 0.3)))

<img width="559" alt="screen shot 2015-09-11 at 14 28 03" src="https://cloud.githubusercontent.com/assets/73663/9822946/60e74f92-5891-11e5-9592-2b1267ac2586.png">

    # Alternatively...
    p + guides(fill = guide_legend(keywidth = 0.65, keyheight = 0.65,
                                   override.aes=list(size = 0.3)))

<img width="557" alt="screen shot 2015-09-11 at 14 28 16" src="https://cloud.githubusercontent.com/assets/73663/9822945/60e14b42-5891-11e5-8a2b-e6c886a3e627.png">

**Comment by technocrat** [comment]
I had a similar problem. See aes_linetype_size_shape {ggplot2} "
    # Size examples
    # Should be specified with a numerical value (in millimetres),
    # or from a variable source

In https://github.com/hadley/ggplot2/issues/1337 HW said "that's too late to change now" and noted it also applies to text size. I'm not sure whether he meant this version or baked in until whenever. My workaround is going to be a function to take set size for full and thumbnail versions
