### ISSUE TITLE
element_grob perhaps should be exported?

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/ggplot2#1339]
I'm finally getting some time to work on `coord_proj` and I ended up having to use my local copy of the new ggplot2 to export `element_grob` in `theme-elements.r` : 

https://github.com/hadley/ggplot2/blob/ec3cd49b6ad74a7d2ce5d6979e5e1bb73a73ab65/R/theme-elements.r#L122

to get it to work. (I can PR it if the short or final answer is "it shld have been exported").

I'll probably have a larger discussion issue to file this weekend since I ended up having to copy quite a bit of code (e.g. the entire contents of `guide-axis.r` and `grob-absolute.r`) over to `ggalt` from `ggplot2` to get the new `coord_proj` to work (it's based on `coord_map` / `GeomMap`, still), so I think some other functions could also be exported since that many `:::` references (if I didn't clone source contents) are not going to go quietly/easily into CRAN and that amount of code duplication may not have the fullest of efficacy. Then again, how many others are going to try to make a new `coord_` / `Coord` that is similar to `coord_map`? (i.e. it might not be worth the trouble.)

But, I wanted to at least get this out there first since it was the easiest, may be an oversight and I doubt it makes sense for me to clone the contents of `theme-elements.r` into `ggalt`.

**Comment by hadley** [comment]
Can you please file any others at 1333? But user derived coords probably aren't quite ready for prime time yet (although I'm happy to export small things as needed)

**Comment by hrbrmstr** [comment]
will do. thx.
