### ISSUE TITLE
default position for geom_histogram()

### ISSUE THREAD

**Issue by romunov** [hadley/ggplot2#1342]
The default behavior of `geom_histogram(position = "stack")` may be a bit unexpected (alternatively, I would love to hear the reasoning behind the choice). I would expect, when plotting a histogram of `n` levels, to have `n` "self contained" histograms, overlapping for better or worse. On the other hand, doing `geom_density` plots the data "as expected" which is conceptually very similar to `geom_histogram`. My suggestion would be to consider changing the default position in `geom_histogram` to `position = "identity"`.

```{r}
xy <- data.frame(pop = sample(letters[1:2], 100, replace = TRUE), value = c(rnorm(50, mean = 5), rnorm(50, mean = 10)))

library(ggplot2)

# overlapping histograms
ggplot(xy, aes(x = value, fill = pop)) +
  theme_bw() +
  geom_histogram(color = "black", position = "identity", alpha = 0.75) +
  scale_fill_brewer(palette = "Set1")

# stacked histogram, not very histogram-y anymore
ggplot(xy, aes(x = value, fill = pop)) +
  theme_bw() +
  geom_histogram(color = "black", alpha = 0.75) +
  scale_fill_brewer(palette = "Set1")

# density graphs do overlap
ggplot(xy, aes(x = value, fill = pop)) +
  theme_bw() +
  geom_density(alpha = 0.75) +
  scale_fill_brewer(palette = "Set1")
```

**Comment by zx8754** [comment]
:+1:

**Comment by hadley** [comment]
All bar geoms in ggplot2 stack - I think it's really misleading to plotting overlapping.  I don't understand why anyone would want overlapping histograms, which depending on the order of the bars, is likely to hide data.

**Comment by romunov** [comment]
For example, as a precursor to a two-sample _t_-test, I would plot two distributions and see how well they overlap.

**Comment by hadley** [comment]
Use a frequency polygon which is much better suited for that sort of problem.
