### ISSUE TITLE
Bug in grid_text() when parse = TRUE

### ISSUE THREAD

**Issue by rpruim** [hadley/ggplot2#1343]
In the two examples below, the first writes "1" and the other correctly writes a subscripted alpha.  When `parse = FALSE`, both write `"alpha[1]"` as expected.

 ```r
# version 1.0.1.9003
  ggplot() +
    geom_text(
      data = data.frame(x = 0, y = 0, label = "alpha[1]"),
      parse = TRUE,
      aes(x=x, y=y, label=label)
    ) 

  ggplot() +
    geom_text(
      data = data.frame(x = 0, y = 0),
      parse = TRUE,
      aes(x=x, y=y, label=label),
      label = "alpha[1]"
    ) 
```

**Comment by baptiste** [comment]
stringsAsFactors, probably

**Comment by rpruim** [comment]
Indeed, switching from `data.frame()` to `data_frame()` fixes things.  But perhaps this should still be considered a bug especially given the output that `parse = FALSE` produces.  

If not, there should at least be a warning in the documentation indicating that factors will not work when using `parse = TRUE`.
