### ISSUE TITLE
geom_errorbar width incorrect when grouped and position dodged

### ISSUE THREAD

**Issue by ericwatt** [hadley/ggplot2#1346]
Reproducible simplified example:

```R
library(ggplot2)
dat <- data.frame(category = c(rep("a", 3), rep("b", 6)),
                  item = c(1:9),
                  value = c(2.9,3.3,3.2,5.4,5.6,7,6.2,6,6.7),
                  error = c(0.1,0.12,0.09,0.3,0.32,0.33,0.45,0.26,0.24))

pos <- position_dodge(width=0.25)
p <- ggplot(dat, aes(x=category,
                     y=value,
                     ymin = value - error,
                     ymax = value + error, 
                     group = item)) +
  geom_point(size=2, position=pos, stat="identity") +
  geom_errorbar(position=pos, aes(width=0.5), show_guide=FALSE) 
```

![ggplot_error_bar_2](https://cloud.githubusercontent.com/assets/7646415/10004774/85f59e5e-6081-11e5-828a-ce0b155a78a1.png)

The value for the width of the error bars is being divided by the number of items grouped at the x position. Category 'b' has twice as many items as 'a' and its error bars are half the width.

I can work around the issue by making a column with value equal to the number of grouped values, and multiply width by that:

```R
dat <- data.frame(category = c(rep("a", 3), rep("b", 6)),
                  item = c(1:9),
                  value = c(2.9,3.3,3.2,5.4,5.6,7,6.2,6,6.7),
                  error = c(0.1,0.12,0.09,0.3,0.32,0.33,0.45,0.26,0.24),
                  number =c(3,3,3,6,6,6,6,6,6))

pos <- position_dodge(width=0.25)
p <- ggplot(dat, aes(x=category,
                     y=value,
                     ymin = value - error,
                     ymax = value + error, 
                     group = item)) +
  geom_point(size=2, position=pos, stat="identity") +
  geom_errorbar(position=pos, aes(width=number*0.5), show_guide=FALSE) 
```

This gives a warning, but the plot is correct:

![ggplot_error_bar_3](https://cloud.githubusercontent.com/assets/7646415/10004804/be55c7f6-6081-11e5-8b8b-066310144048.png)

> Warning message:
> position_dodge requires non-overlapping x intervals

However, this is a bit more work and can cause possible bugs (count wrong, the value changes later, etc.)

The same behaviour happens if I take the width=0.5 out of aes(), but it needs to be in aes() if I want to use the width=number*0.5 workaround.

If I remove group=item from the first aes() the error bar widths are ok, but the points and the error bars do not dodge.

For reference I am using R 3.2.1 and ggplot2 1.0.1

**Comment by hadley** [comment]
It's not clear to me that this a bug - dodging, by definition, divides the width by the number of elements in each group.

**Comment by ericwatt** [comment]
Hmm. I guess for me it was not an expected behaviour and took me some time to figure out what was going on. In my case I had a larger range of numbers in the groups which made the error bar differences quite pronounced. For example:

```R
dat <- data.frame(category = c(rep("a", 1), rep("b", 10)),
                  item = c(1:11),
                  value = c(2.9,7.3,7.2,5.4,5.6,7,6.2,6,6.7,6.1,5.78),
                  error = c(0.1,0.12,0.09,0.3,0.32,0.33,0.45,0.26,0.24,0.11,0.7))

pos <- position_dodge(width=0.25)
p <- ggplot(dat, aes(x=category,
                     y=value,
                     ymin = value - error,
                     ymax = value + error, 
                     group = item)) +
  geom_point(size=2, position=pos, stat="identity") +
  geom_errorbar(position=pos, aes(width=0.2), show_guide=FALSE)
```
![ggplot_example_4](https://cloud.githubusercontent.com/assets/7646415/10005531/b9899226-6085-11e5-907b-407fa0906121.png)

Is there a reason you would want the width to be a function of the number of elements rather than the value specified? I can see the utility if you have an error bar width of 1 and you dodge a sizeable amount; the error bars from different groups could start to overlap. But then the solution could be to manually reduce the width of the error bars or the size of the dodge.

**Comment by hadley** [comment]
That looks like desired behaviour to me - it follows from how dodging works with bars, boxplots, ...
