### ISSUE TITLE
aitoff projection clips data

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1350]
From the visual tests:
https://github.com/hadley/ggplot2/blob/710991b/visual_test/coord-map.r#L30-L42

```R
library(maps)
world_map <- map_data("world")
pworld <- ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon()

pworld + coord_map(projection = "aitoff") +
  scale_y_continuous(breaks = (-2:2) * 30) +
  scale_x_continuous(breaks = (-4:4) * 45, limits = c(-180, 180))
# Warning message:
# Removed 82 rows containing missing values (geom_polygon). 
```
![image](https://cloud.githubusercontent.com/assets/86978/10087101/a58de73c-62d7-11e5-809f-a5ceec2237fc.png)

```R
pworld + coord_map(projection = "aitoff", orientation = c(90, 180, 0)) +
  scale_y_continuous(breaks = (-2:2) * 30) +
  scale_x_continuous(breaks = (0:8) * 45, limits = c(0, 360))
# Warning message:
# Removed 11818 rows containing missing values (geom_polygon). 
```
![image](https://cloud.githubusercontent.com/assets/86978/10087099/a350523e-62d7-11e5-8747-c7a040125923.png)

I believe the clipping happened previously, since the visual tests have comments to that effect. I'm not sure if it issued warnings though.

See results at: http://sync.stdout.org/vtest-html/coord-map.html

**Comment by hadley** [comment]
I think this is a long standing problem that I'm unlikely to solve in the near future
