### ISSUE TITLE
Paths are connected when they shouldn't be

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1351]
I believe path segments should be separated when there's an `NA` in the data, but they're not.

```R
library(maps)
library(mapproj)

nz <- data.frame(map("nz", plot = FALSE)[c("x", "y")])
qplot(x, y, data = nz, geom = "path")
# Warning message:
# Removed 21 rows containing missing values (geom_path). 
```

![image](https://cloud.githubusercontent.com/assets/86978/10087236/5759677a-62d8-11e5-9bc2-bb50fcf1f595.png)

**Comment by wch** [comment]
`GeomPath$draw_panel()` recognizes that `NA`s indicate breaks in the path, but all the `NA`s are removed beforehand, by `Geom$draw_layer()`. Perhaps `GeomPath` needs its own version of `draw_panel`, without the `remove_missing`?
https://github.com/hadley/ggplot2/blob/9ea6cc4/R/geom-.r#L63-L66

**Comment by hadley** [comment]
Oh damn, I forgot about that problem.
