### ISSUE TITLE
With multiple legends, order of legends has changed

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1353]
```R
dat <- data.frame(x = LETTERS[1:3], y = 1)
p2 <- ggplot(dat, aes(x, y, fill = x, colour = 1:3)) +
  geom_bar(stat = "identity") +
  theme(legend.background = element_rect(colour = "black")) +
  guides(color = "colorbar")
p2
```

Old version:

![image](https://cloud.githubusercontent.com/assets/86978/10087824/1362bde2-62dc-11e5-9a98-ca23372bbcd1.png)

New version:

![image](https://cloud.githubusercontent.com/assets/86978/10087829/18282470-62dc-11e5-9428-80c18b286f05.png)

See results at:
http://sync.stdout.org/vtest-diff/guide-position.html

**Comment by hadley** [comment]
Do we care?

**Comment by wch** [comment]
Hm, maybe not. According to `?guide_legend`:

> order: positive integer less that 99 that specifies the order of this guide among multiple guides. This controls the order in which multiple guides are displayed, not the contents of the guide itself. If 0 (default), the order is determined by a secret algorithm.

I guess it's just that the secret algorithm has changed. :)

And it's still possible to change the order using `order`. For example:

```R
dat <- data.frame(x = LETTERS[1:3], y = 1)
p <- ggplot(dat, aes(x, y, fill = x, colour = 1:3)) +
  geom_bar(stat = "identity") +
  theme(legend.background = element_rect(colour = "black")) 

# These two are the same
p +
  guides(
    color = guide_colorbar(order = 0),
    fill = guide_legend(order = 0)
  )
p + 
  guides(
    color = guide_colorbar(order = 0),
    fill = guide_legend(order = 1)
  )
```
![image](https://cloud.githubusercontent.com/assets/86978/10445071/68d19176-7133-11e5-9ab4-ed61f3339068.png)

```R
# And we can reverse the order
p + guides(
    color = guide_colorbar(order = 1),
    fill = guide_legend(order = 0)
  )
```

![image](https://cloud.githubusercontent.com/assets/86978/10445066/6021f6e2-7133-11e5-94b2-2ecc38dea961.png)

**Comment by kohske** [comment]
yes, by default the order is determined by hash of object, so it's definitely unpredictable.

**Comment by wch** [comment]
@kohske Thanks for that information!

**Comment by hrbrmstr** [comment]
i just ran across this again, trying to make an animation that needs both legends to be in predictable locations. i'll poke at a mod to make `order` actually work. or just move all my vis to D3 ;-p

**Comment by rcorty** [comment]
I am making a plotting function.  I would love to be able to guarantee to the user that, e.g., the fill aesthetics will be above the shape aesthetic in the legend.  Seems like this is not possible, since the hash of the object will differ depending on the data the user is plotting?

**Comment by hadley** [comment]
@rcorty just set `order` as shown above
