### ISSUE TITLE
facet_grid() error in ggplot2 version 1.0.1

### ISSUE THREAD

**Issue by andersgs** [hadley/ggplot2#1354]
Hello.

I am having trouble getting facet_grid() to work with my own data and with the examples. I have not had this problem in the past --- but, I haven't used the function in a while. Here is an example:

>    p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
>    p + facet_grid(. ~ cyl)
>    Error in rep.int("", ncol(r)) : incorrect type for second argument

When running with two variables, I get the following error:

>    p + facet_grid(vs ~ am)
>    Error in if (ncol(y) == 0) return(x) : argument is of length zero

I have tried facet_wrap() and that works, but I want facet labels on both sides of the plot.

I am running R version 3.2.1 (2015-06-18); RStudio Version 0.99.467; OS X 10.10.5; and ggplot2 (1.0.1).

Thank you.

Anders.

**Comment by hadley** [comment]
Works for me. Must've been a transient problem

**Comment by andersgs** [comment]
Hi Hadley.

I have tracked it down to an incompatibility between ggplot2 and another package I use called chopsticks (https://www.bioconductor.org/packages/release/bioc/html/chopsticks.html). Not sure why that happens --- although, detaching the package does not correct the issue. So, it looks like it is having some other side effects. But, in any case, it is recorded here in case others run into the same issue.

All the best, and thank you for ggplot2! It forms the basis of a lot of what I do.

Anders.
