### ISSUE TITLE
Feature request: ability to add plot add-ons

### ISSUE THREAD

**Issue by rpruim** [hadley/ggplot2#1358]
I'd like to be able to do something like
```r
my_scales <- 
  scale_colour_manual(...) +
  scale_shape_manual(...) +
  scale_alpha_manual(...)
plot1 + my_scales
plot2 + my_scales
```
Is there a way to make this possible?

As is, I end up doing things like
```r
my_scales <- function(plot) {
  p +
  scale_colour_manual(...) +
  scale_shape_manual(...) +
  scale_alpha_manual(...)
plot1 %>% my_scales()
plot2 %>% my_scales()
```
Of course, similar things hold for other plot add-ons as well as the scales.

**Comment by hadley** [comment]
Yes, just put them in a list.

**Comment by rpruim** [comment]
I guess I was asking that `+` be defined to create this list rather than to complain that the addition isn't possible.

**Comment by hadley** [comment]
I don't think that's possible because of the way `+` works (without a lot of extra changes, anyway)
