### ISSUE TITLE
geom_dotplot() ignores `fill` and `color`, when `group` is set

### ISSUE THREAD

**Issue by maxheld83** [hadley/ggplot2#1359]
There seems to be some weird incompatibility between `fill`/`color`  and `group` in `geom_dotplot()`.

The full MWE is on StackExchange (not by me): http://stackoverflow.com/questions/31557973/how-to-use-ggplot2s-geom-dotplot-with-both-fill-and-group

I can confirm that this is still an issue with `ggplot2 1.0.1`.

Not sure this is a bug, but it sure was unexpected behavior for me.

**Comment by hadley** [comment]
Is this #1096?
