### ISSUE TITLE
Is there a reason why geom_smooth() doesn't have a group aesthetic?

### ISSUE THREAD

**Issue by rpruim** [hadley/ggplot2#1361]
Suppose I have 10 groups and want to highlight one of them.  I'd like to use 

```r
aes( color = one_or_the_rest, group = one_of_ten_groups)
```

This works for `geom_line()`, but not for `geom_smooth()`.

**Comment by hadley** [comment]
Can you provide a reprex?

**Comment by rpruim** [comment]
I _think_ I know what is going on, or at least an approximation to it.

 1) `group` is not listed as an aesthetic in the help file, so when things weren't working, I thought it was because using `group` wasn't supported.

 2) In other examples, using `group` does indeed work.

 3) I think my particular problem is that missing data sometimes leaves some of the groups with very few points.  Unfortunately, this makes things fail completely instead of rendering the smoothers for the groups that have sufficient data.   Perhaps I need to create a stat that does something sensible on a small number of points and uses loess when there are more.

Perhaps the issue can be modified to recommend that `group` be listed as an optional aesthetic in the help file.

**Comment by hadley** [comment]
This should be (a little) better in the dev version
