### ISSUE TITLE
plot background on pdf

### ISSUE THREAD

**Issue by mrkwht** [hadley/ggplot2#1362]
Running the code below, adapted from ggsave documentation, graphics that show up within Rstudio look as expected, but pdf files all have grey background in plotting area, which is unexpected for theme_bw.  Besides the plot background, other aspects of bw theme (e.g. black labels on axes) show up in pdf file.  The problem remains whether pdf() or ggsave is used to create pdf files.  No where in documentation does it suggest that this should be normal behavior.  I was surprised that I could find no mention of this problem elsewhere online.
Mark

require(ggplot2)
qplot(rating, data=movies, geom="histogram") #displays default theme on screen
qplot(rating, data=movies, geom="histogram")+theme_bw() # Shows bw theme on screen
pdf("ratings2.pdf")
qplot(rating, data=movies, geom="histogram") # pdf shows default theme
qplot(rating, data=movies, geom="histogram")+theme_bw() # pdf shows default theme plot background and black rather than grey labels
qplot(rating, data=movies, geom="histogram")+theme(panel.background=element_rect(fill="White")) # pdf shows default theme
dev.off()
ratings <- qplot(rating, data=movies, geom="histogram")+theme_bw() 
ggsave("ratings.pdf", ratings) # pdf shows default theme plot background and black rather than grey labels

**Comment by technocrat** [comment]
If you are looking to create 

![rplot](https://cloud.githubusercontent.com/assets/74648/10254339/d8905ac2-68f7-11e5-9cb0-3564fcb3bfdc.png)

or similar overrides to the default, it's easier to get exactly what you want by rolling your own theme
    
    require(ggplot2)
    ratings <- qplot(rating, data=movies, geom="histogram")
    plain_theme <- theme(panel.background = element_blank(), panel.grid = element_blank(), axis.ticks = element_blank())
    ratings + plain_theme

**Comment by mrkwht** [comment]
Thank you for the suggestion. I had an accessibility "feature" turned on in my pdf reader which was causing the issue... Everything works as it should with the feature turned off.
