### ISSUE TITLE
Print method for Layer objects should be more informative

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1363]
Currently, it looks like this:

```
> geom_bar()
geom_bar: width = NULL
stat_count: width = NULL
position_stack 
```

At the very least, it should say that the object is a `Layer`. Additionally, it would be helpful to indicate that there are fields named `geom`, `stat`, and `position`.

**Comment by hadley** [comment]
This is designed to work with `summary()` to show a human readable view of a plot. I know some people really like this, so I'd prefer not to mess with it at the moment.
