### ISSUE TITLE
Inconsistent facet_grid behavior

### ISSUE THREAD

**Issue by lkuchenb** [hadley/ggplot2#1364]
When I generated a heat map of pairwise numerical values

    library(ggplot2)
    data = dget(url("https://git.io/vCTpG"))
    ggplot(data = data, mapping = aes(x=labelA, y=labelB)) + geom_tile(mapping = aes(fill=ol))

... I get two very different plots when I apply a `facet_grid()`, depending on the ordering in the formula. I would expect the 10x10 output in both cases:

    last_plot() + facet_grid(facetA~facetB, scales = "free", as.table = F)

[![AB][1]][1]

    last_plot() + facet_grid(facetB~facetA, scales = "free", as.table = F)

[![BA][2]][2]

  [1]: http://i.stack.imgur.com/O0x6U.png
  [2]: http://i.stack.imgur.com/W5lN1.png

**Comment by hadley** [comment]
I think you also have to swap x and y to be equivalent:

```R


ggplot(data, aes(labelA, labelB)) + 
  geom_tile(mapping = aes(fill=ol)) +
  facet_grid(facetB~facetA, scales = "free")

ggplot(data, aes(labelB, labelA)) + 
  geom_tile(mapping = aes(fill=ol)) +
  facet_grid(facetA~facetB, scales = "free")
```
