### ISSUE TITLE
Breaking change: " Aesthetics must be either length…"

### ISSUE THREAD

**Issue by briatte** [hadley/ggplot2#1366]
Hello,

Using the current CRAN version of `ggplot2`, the following code produce the plot below it:

```R
reprex = data.frame(label = 1:6,
           group = rep(letters[1:3], 2),
           x = runif(6),
           y = runif(6))

ggplot(data = reprex, aes(x, y)) +
  geom_point(alpha = 1, size = 9) +
  aes(color = group) +
  geom_text(label = 1:6, size = 6, color = "white")
```

![rplot](https://cloud.githubusercontent.com/assets/322533/10421616/2ab32a3a-70ac-11e5-96ed-88d473ffda67.png)

Using version 1.0.1.9003 of `ggplot2`, the same code now throws in an error:

```
Error: Aesthetics must be either length 1 or the same as the data (3): label, colour, size
```

The strange thing is that setting `show.legend` to `FALSE` makes the error goes away:

```R
ggplot(data = reprex, aes(x, y)) +
  geom_point(alpha = 1, size = 9) +
  aes(colour = group) +
  geom_text(label = 1:6, size = 6, colour = "white", show.legend = FALSE)
```

I'm not sure I get the logic behind this error, so I'm reporting it with that very uninformative title (sorry).

**Comment by heike** [comment]
two solutions, that might shed some light on what's going on:
It seems that the new version of ggplot2 checks variable lengths more
strictly. One workaround is to include the labeling in an aes statement -
that adds a letter in the legend. Another option is to use annotations ...

ggplot(data = reprex, aes(x, y)) +
  geom_point(alpha = 1, size = 9) +
  aes(colour=group) +
  geom_text(aes(label = label), size = 6, colour = "white")



ggplot(data = reprex, aes(x, y)) +
  geom_point(alpha = 1, size = 9) +
  aes(colour=group) +
  annotate(geom="text", x=reprex$x, y=reprex$y, label = 1:6, size = 6,
colour = "white")


best,
Heike

On Mon, Oct 12, 2015 at 12:00 AM, François Briatte <notifications@github.com

**Comment by has2k1** [comment]
This is a bug caused by a clash between `colour` and `label` when the legend is being created.
`+ aes(colour=group)` creates a group of size 3, while `label=1:6` makes 6 labels. The number of items in the legend is determined by the mappings, `colour` in this case and the other aesthetics must be of this size or have a single value.

Another solution is restrict the colour mapping to geom_point, i.e

```R
ggplot(data = reprex, aes(x, y)) +
  geom_point(aes(colour=group), alpha = 1, size = 9) +
  geom_text(label, size = 6, colour = "white")
```

**Comment by hadley** [comment]
I agree with @has2k1's analysis - this is the fundamental problem with using non-data aesthetics.

**Comment by briatte** [comment]
Thanks for the feedback.

It is true that the problem could have been avoided entirely by sticking the colour mapping into `geom_point`, but the real code that generated this error is a workflow that selects between different `geom_point` configurations, and where the `aes` does not always happen. That explains the use of a non-data aesthetic.

**Comment by hadley** [comment]
Regardless of your workflow, it's always possible to put your data in a data frame.

**Comment by briatte** [comment]
My data is in a data frame, but [the code](https://github.com/briatte/ggnet/blob/master/ggnet.R) runs like this:

```R
function(data, config = 1, group = FALSE, label = NULL) {

  p <- ggplot(data, aes(x, y))

  # ... tons of stuff here ...

  if (config == 1) { p <- p + geom_point( ... ) + ... } # configuration 1
  if (config == 2) { p <- p + geom_point( ... ) + ... } # configuration 2
  if (config == 3) { p <- p + geom_point( ... ) + ... } # configuration 3, etc.
 
 if (isTRUE(group)) { p <- p + aes(color = group) } # optional

  if (!is.null(label) { p <- p + geom_text(label = label) }

  return(p)
}
```
