### ISSUE TITLE
Use alpha for lines of geom_density(), geom_bar(), and so on

### ISSUE THREAD

**Issue by yutannihilation** [hadley/ggplot2#1371]
Hi, thanks for this great package!

I saw many people (including me) are confused at the behavior of `alpha` when used in Geoms which draw areas or rects (e.g. `geom_desity()`). So, let me ask if this is your design decision or not.

When I draw a chart with `alpha`, I expect that the whole layer, the line and fill, will become transparent. But the line stays clear red.

```r
ggplot(diamonds, aes(carat)) +
    geom_density(fill = "red", colour = "red", alpha = 0.1)
```
![plot3](https://cloud.githubusercontent.com/assets/1978793/10501293/cf987d82-731a-11e5-8ade-a8a462af878b.png)

I expect the one like this.

![plot1](https://cloud.githubusercontent.com/assets/1978793/10501292/cb700022-731a-11e5-8c30-db8ff67ff6d0.png)

I know we can draw the latter chart by using `colour=alpha("red", 0.1)`, but I believe `alpha` is a transparency param for **the entire layer**, not only for the line or the fill. For me, this is a matter of semantics. Are there any reason not to use `alpha` for `colour`?

The possible implementation is very simple. We just need to change those two lines to `col = alpha(aes$colour, aes$alpha)`:

https://github.com/hadley/ggplot2/blob/bbc1b5ad3c0f55e8809d4fe1a9bd2783eb9fa29c/R/geom-rect.r#L55
https://github.com/hadley/ggplot2/blob/bbc1b5ad3c0f55e8809d4fe1a9bd2783eb9fa29c/R/geom-ribbon.r#L95

If this looks good to you, I'm happy to submit PR :smile:

**Comment by hadley** [comment]
It was a deliberate design decision. But now I can't remember why :frowning: I think I had a good reason though.

**Comment by yutannihilation** [comment]
Hmm..., thanks for your quick answer, anyway.

I found the behavior of `alpha` have been this way from the time it was born, but no background is described in the commit message.

https://github.com/hadley/ggplot2/commit/36d5ad2e2a0a3d9df2c527ddfa7452ed030beb7d

Okay, I trust in you this time. You always have a good reason; the very fact can be a good reason for me to close this issue :+1:. Please close this issue anytime!

But, I hope you will occasionally remember that [not](http://stackoverflow.com/questions/14411270/ggplot-lines-transparency) [a](http://stackoverflow.com/questions/19474552/adjust-transparency-alpha-of-stat-smooth-lines-not-just-transparency-of-confi) [few](https://groups.google.com/forum/#!topic/ggplot2/4pPRe7BjtqE) people are confused at this. At least, this should be included in [ggplot2 book](https://github.com/hadley/ggplot2-book).

**Comment by hadley** [comment]
You're right - it's more consistent to affect both. Done!

**Comment by yutannihilation** [comment]
Wow!!! Thanks for your decision! You are always great :+1:

**Comment by antoine-lizee** [comment]
I am so sorry to see this! You should believe in yourself more hadley :-).
As a result, there is no way to separately tune the line and the fill without using two geoms now, one with `fill = NA` and another with `color = NA`. My very common use case is to have a transparent filing with a solid line - it is now impossible:
```
ggplot(diamonds %>% filter(cut %in% c("Very Good", "Ideal")), aes(x = price, fill = cut)) + theme_bw() + 
  geom_histogram(binwidth = 1000) +
  geom_density(aes(x = price, y = ..count.. * 1000), color = "black", alpha = 0.3) +
  geom_density(aes(x = price, y = ..count.. * 1000), color = "black", fill = NA) +
  facet_grid(cut ~ ., scales = "free_y")
```
While if you wanted to get the line lighter, you can always change its `color`!

Could we revert this? I'm pretty sure it's breaking more code now than it would if reverted for 2.1...

**Comment by hadley** [comment]
@antoine-lizee can you please file a new issue? I'm likely to lose track of an old issue with a comment.

**Comment by antoine-lizee** [comment]
Of course. #1523

**Comment by joanwa** [comment]
yes, please revert back. I totally back antoine-lizee

**Comment by hadley** [comment]
@joanwa please keep conversation on the new issue
