### ISSUE TITLE
ggplot() breaks when using difftime

### ISSUE THREAD

**Issue by petermeissner** [hadley/ggplot2#1377]
# ggplot() breaks when using difftime

### the problem

ggplot() does not accept values with class difftime ... 

```
library(ggplot2)

df <- 
  data.frame(
    date1 = as.Date(1:10, origin="1970-01-01"),
    date2 = as.Date(31:40, origin="1970-01-01")
  )
df$ddate <-  df$date2 - df$date1

ggplot(data = df, aes(x = date1, y = ddate)) + geom_point()

## Don't know how to automatically pick scale for object of type difftime. Defaulting to continuous
## Error: Discrete value supplied to continuous scale
```

While there is a (straightforward) workaround for the problem it is not clear to me why `ggplot()` should refuse class `difftime` values. To put it in other words: I think it would be nice if `ggplot()` might accept `difftime` values without complaint. 

### workaround

Transform values to numeric ... 

```
ggplot(data = df, aes(x = date1, y = as.numeric(ddate) )) + geom_point()
```

### version infos

```
R version 3.2.2 Patched (2015-10-09 r69501)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1.9003

loaded via a namespace (and not attached):
[1] colorspace_1.2-6 scales_0.3.0     plyr_1.8.3       tools_3.2.2      gtable_0.1.2    
[6] Rcpp_0.12.1      grid_3.2.2       munsell_0.4.2  
```

**Comment by technocrat** [comment]
The behavior in this case is no different than for other classes that emit discrete, rather than continuous values. "The scatterplot is useful for displaying the relationship between two continuous variables, although it can also be used with one continuous and one categorical variable, or two categorical variables." Different geom functions have different expectations concerning whether they are rendering discrete or continuous data, so it wouldn't be just geom_point and datediff objects.

**Comment by petermeissner** [comment]
Nope, not convinced.

- if  geom_point accepts only true continuous variables I think machine becomes master over man - I want to shoot myself in the foot if I want to
- while there are of cause very discrete values for difftime in my example difftimes are however continuous / metric; consider: ` ( Sys.Date() - Sys.Date() - 1  ) / 33333 ` ... it still a difftime but not so discrete anymore

So still -- I think -- it would be great -- for the sake of completeness --  to allow difftimes to be handled just as any other metric / continuous variable.

**Comment by hadley** [comment]
Probably the definition of is.discrete needs tweaking

**Comment by technocrat** [comment]
Having is.discrete treating anything that **can** be continuous but just happens to be in integer increments would be a huge win for we in the clueless class who have otherwise struggled with the error message about discrete/continuous.

**Comment by hadley** [comment]
It's hard to get the logic right because of things like factors which are clearly discrete but are implemented with integers.

**Comment by has2k1** [comment]
This is issue a little more complicated. The proper way is to create a new scale, `scale_difftime` (I did something similar for the python port a `scale_timedelta` in this case).

However for a `scale_difftime`, I encountered two hiccups:

1. All difftimes in a frame are pegged to a common unit e.g seconds, days, ...
2. The "ordinal" form of a difftime is just the plain number stripped of the unit.

The first implies that once you have a difftime column that is in days, if you insert a difftime that is in seconds it becomes days. i.e

```R
> df <- data.frame(
+     date1 = as.Date(1:10, origin="1970-01-01"),
+     date2 = as.Date(31:40, origin="1970-01-01"))
> df$ddate <-  df$date2 - df$date1
> df$ddate

Time differences in days
 [1] 30 30 30 30 30 30 30 30 30 30

> secs <- (Sys.time() - Sys.time() + 5)
> secs

Time difference of 4.999967 secs

> df$ddate[1] <- secs
> df$ddate

Time differences in days
 [1]  4.999967 30.000000 30.000000 30.000000 30.000000 30.000000 30.000000 30.000000 30.000000
[10] 30.000000

# The seconds have become days !!!
```

The second means that if you create a `trans` the transform to ordinal (`as.numeric`) you lose the information(units) required for the inverse.

My notes on this say "look into auto" but I do not remember what that is about. My understanding of R is limited so I don't know if there is a simple solution.

**Comment by hadley** [comment]
Ah yes, it's very difficult to build anything on top of `difftime()` because the units argument isn't just presentational, but it affects how the underlying vector needs to be interpreted. This means adding ggplot2 support is quite a big job and hence unlikely to happen.
