### ISSUE TITLE
stat_smooth(method="glm", family=binomial, ...) no longer works

### ISSUE THREAD

**Issue by friendly** [hadley/ggplot2#1378]
I'm testing the code in my new book with ggplot 1.1.0.  The following chunk used to work, but now generates the `Error: Unknown parameters: family`:

    data("Donner", package="vcdExtra")
    donner.mod <- glm(survived ~ age, data=Donner, family=binomial)
    library(ggplot2)
    ggplot(Donner, aes(age, survived)) + theme_bw() +
      geom_point(position = position_jitter(height = 0.02, width = 0)) +
    	stat_smooth(method = "glm", family = binomial, formula = y ~ x,
                  fill="blue", alpha = 0.3, size=2)

I believe this is a bug -- stat_smooth() should allow `family=` with `method="glm"`.  There may be more discussion on https://github.com/friendly/VCDR/issues/57

Is there a workaround?

**Comment by hadley** [comment]
You now need:

```R
ggplot(Donner, aes(age, survived)) + theme_bw() +
  geom_point(position = position_jitter(height = 0.02, width = 0)) +
    stat_smooth(method = "glm", method.args = list(family = binomial), formula = y ~ x,
              fill="blue", alpha = 0.3, size=2)
```

This will cause a bit of pain in the short-term but I believe on the balance it's better than the current behaviour where misnamed arguments that are silently ignored.

Note that you can now simplify the geom point call to:

```R
geom_jitter(height = 0.02, width = 0)
```

**Comment by friendly** [comment]
Your suggested change now generates a different error:

    Error in add_ggplot(e1, e2, e2name): could not find function "is.coord"

    d> traceback()
    2: add_ggplot(e1, e2, e2name)
    1: `+.gg`(ggplot(Donner, aes(age, survived)) + theme_bw(), geom_point(position = position_jitter(height = 0.02, 
           width = 0)))

**Comment by hadley** [comment]
Works for me - are you sure you have the latest ggplot2 from github?
