### ISSUE TITLE
Using Switch to Return NULL in aes No Longer Works

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1379]
I have

    aes(x = method, y = performance, fill = switch(boxFillColouring, validation = validation, datasetName = dataset, classificationName = analysis, None = NULL))

Previously, this worked, but in version 1.0.1.9003 causes an error when the value is `NULL`.

    Error: Aesthetics must be either length 1 or the same as the data (9): x, y, fill

What's the recommended change to make ?

**Comment by hadley** [comment]
Could you please provide a minimal reproducible example?

**Comment by DarioS** [comment]
Here is an example which works in 1.0.1, but not any longer in 1.1.0.

    install.packages("ggplot2")
    library(ggplot2)
    fillVar <- "cylinders"
    colourVar <- "None"
    mtcars[, "cyl"] <- factor(mtcars[, "cyl"])

    ggplot() + geom_boxplot(data = mtcars, aes(x = cyl, y = mpg, fill = switch(fillVar, cylinders = cyl, None = NULL), colour = switch(colourVar, cylinders = cyl, None = NULL)))

    detach("package:ggplot2", unload = TRUE)
    devtools::install_github("hadley/ggplot2")
    library(ggplot2)

    ggplot() + geom_boxplot(data = mtcars, aes(x = cyl, y = mpg, fill = switch(fillVar, cylinders = cyl, None = NULL), colour = switch(colourVar, cylinders = cyl, None = NULL)))

    Error: Aesthetics must be either length 1 or the same as the data (32): x, y, fill, colour

**Comment by wch** [comment]
It's not the `NULL` itself that's causing the problems. For example:

```R
ggplot() + geom_boxplot(data = mtcars, aes(x = factor(cyl), y = mpg, fill = NULL, colour = NULL))
```
I think the `switch` statement is doing something strange. I'm actually surprised it worked at all in earlier versions, because of the non-standard evaluation that happens in `aes()`.

For programmatic assignment of aesthetic mappings, you should be using `aes_string()` instead of `aes()`, and that will let you avoid this kind of problem.

**Comment by hadley** [comment]
In this version of ggplot2, you should probably be using `aes_()` which does everything that `aes_string()`  does, and more.
