### ISSUE TITLE
Adding annotation_raster increases axis scale limits

### ISSUE THREAD

**Issue by bleutner** [hadley/ggplot2#1381]
I tested the upcoming ggplot2 version 1.0.1.9003 with my package and noticed substantially increased axis limits when adding annotation_raster objects. In the old versions this was not the case: Annotations did not influence scales and I don't think they should or is this on purpose?

Here's an example:
A plot with the usual axis expansion and limits

```{r}
df  <- data.frame(x = c(0,1), y = c(0,1))
p  <- ggplot(df, aes(x,y)) + geom_point() 
p
```
![selection_060](https://cloud.githubusercontent.com/assets/1650314/10612347/b19f44de-7750-11e5-97df-f07161f374ba.png)

Now, we add an annotation object of the same value range and the axis limits increase substantially
```{r}
mat <- matrix("blue", ncol = 10, nrow = 10)
p + annotation_raster(mat, 0,1,0,1) 
```
![selection_061](https://cloud.githubusercontent.com/assets/1650314/10612343/a7695306-7750-11e5-8d33-5a691c8dffcc.png)

**Comment by hadley** [comment]
Why are the axes so messed up?

**Comment by bleutner** [comment]
they are just screenshots from eclipse+statet (rj.gd device). They are fine once they're plotted in another devive, e.g. X11()

**Comment by hadley** [comment]
Slightly simpler reprex:

```R
df  <- data.frame(x = c(0,1), y = c(0,1))
mat <- matrix("blue", ncol = 10, nrow = 10)

ggplot(df, aes(x,y)) + 
  geom_point()
  
ggplot(df, aes(x,y)) + 
  geom_point() +
  annotation_raster(mat, 0,1,0,1) 
```

Is ok in 1.0.0
