### ISSUE TITLE
Simplifying of %>% chaining and qplot()

### ISSUE THREAD

**Issue by elmar-hinz** [hadley/ggplot2#1382]
Hello,

I am new with R programming, having no overview what has been discussed, is in the pipe and the spirit of the community. The combination of **dplyr**, **chaining** and **qplot** is perfect for quickly evaluating data like this:

`iris %>% filter(Species == "versicolor") %>% qplot(Petal.Length, Sepal.Length, data = .)`

The user experience would almost be perfect, if I could write it as sparse as this:

`iris > filter(Species == "versicolor") > plot(Petal.Length, Sepal.Length)`

This ticket is about the `qplot()` part only. I like to suggest a function `dplot()`, a modification of `qplot()` to spare the data parameter, by putting it in first position like in `ggplot()`.

`iris %>% filter(Species == "versicolor") %>% dplot(Petal.Length, Sepal.Length)`

The **d** would serve as memo, that it is an adapter for the *dplyr* chain as well as data is first.

If this is welcome, it would be a chance for me, to learn the contributing cycle of R and ggplot in special.

Regards

Elmar

**Comment by hadley** [comment]
Hi Elmar,

I think the request is reasonable, but I'm unlikely to accept a patch because I'm continuing to downplay the importance of `qplot()`, and I don't plan to make any further changes to it.

Hadley

**Comment by elmar-hinz** [comment]
Thank you Hadley for your immediate response. 

I understand your reasoning. The importance of having a clean grammar is of more importance, than having the shortest language. You did so much good with this, that I don't want to question it.

Elmar
