### ISSUE TITLE
Update plot's data with pipes

### ISSUE THREAD

**Issue by lionel-** [hadley/ggplot2#1387]
There's currently no easy way to update a data frame in a pipeline.

The data frame pipeline needs to be on the RHS, which does not feel natural, and wrapped in parentheses:
```r
p <- ggplot(mtcars, aes(wt, mpg, colour = hp)) + geom_point()

p %+% (mtcars %>%
  mutate(wt = wt + 10) %>%
  slice(1:10))
```

So how about adding an updating function?
```r
ggupdate <- function(data, plot) {
  plot %+% data
}

mtcars %>%
  mutate(wt = wt + 10) %>%
  slice(1:10) %>%
  ggupdate(p)
```

**Comment by hadley** [comment]
Hmmm, that doesn't feel super natural to me, because in the context of ggplot, I expect the thing being manipulated to be a plot. But I'd accept a PR (if you can do it by Friday) if you want to implement and document.
