### ISSUE TITLE
geom_violin not respecting facet_grid's scale='free*'

### ISSUE THREAD

**Issue by mmulvahill** [hadley/ggplot2#1388]
geom_violin won't use free scales with facet_grid.  It works for boxplot, but not violin.  Tested with ggplot2_1.0.1.9003.  Here is an example.  

    library(ggplot2)
    
    dat <- 
      data.frame(statistic = rep(c("stat1", "stat2"), each = 100),
                 scenario  = rep(rep(c("scenario1", "scenario2"), each = 50),
                                 times = 2),
                 group     = rep(rep(c("control", "treatment"), each = 25), 
                                 times = 4),
                 value     = c(rnorm(100, 0.5, 0.25), rexp(100, 0.5)))
    
    ggplot(dat, aes(x = group, y = value, fill = group)) +
      geom_boxplot() +
      facet_grid(statistic ~ scenario, scales = "free")
    
    ggplot(dat, aes(x = group, y = value, fill = group)) +
      geom_violin() +
      facet_grid(statistic ~ scenario, scales = "free")

**Comment by hadley** [comment]
Simpler reprex:

```R
df <- data.frame(x = c("a", "b"), y = c(runif(99), 3))

ggplot(df, aes(1, y)) + 
  geom_violin() + 
  facet_grid(x ~ ., scales = "free")
```

Ok in ggplot2 1.0.0.  Probably `stat_ydensity()` is failing to remove zero density points.

**Comment by mmulvahill** [comment]
Works great -- thanks.
