### ISSUE TITLE
geom_dotplot method "dotdensity" fails with NA values, "histodot" removes without warning.

### ISSUE THREAD

**Issue by Ax3man** [hadley/ggplot2#1390]
```` r
library(ggplot2)

mtcars2 <- mtcars
mtcars2[1, "disp"] <- NA

# Complete data works fine
ggplot(mtcars, aes(x = as.factor(gear), y = disp)) + 
  geom_dotplot(binaxis = "y", stackdir = "center")
# Missing value produces a warning and an empty plot
ggplot(mtcars2, aes(x = as.factor(gear), y = disp)) + 
  geom_dotplot(binaxis = "y", stackdir = "center")
# Method "histodot" removes NA's (without a warning!)
ggplot(mtcars2, aes(x = as.factor(gear), y = disp)) + 
  geom_dotplot(binaxis = "y", stackdir = "center", method = "histodot")
````
In either case, this is not documented behavior, as the default of `na.rm = FALSE` should remove missing values with a warning.

I'm on Windows 10, using R v3.2.2 with the 1.1.0 pre-release of ggplot2 (1.0.1.9003).

**Comment by Ax3man** [comment]
Also note that in the CRAN version (v.1.0.1) both options work, and both give a warning for missing values. Although that warning was generated by `stat_bindot` which has now been removed.

**Comment by hadley** [comment]
@wch could you please take a look?
