### ISSUE TITLE
Add support for sub-second plotting

### ISSUE THREAD

**Issue by joshmyzie2** [hadley/ggplot2#1395]
It would be very useful to be able to plot a sub-second POSIXct interval with ggplot2 without having to convert to a floating point representation.

For example, I often plot high frequency market data with ggplot2 using shiny to interactively zoom in, but if I zoom in too far, I get the error:

```
Error: range too small for 'min.n'
```

**Comment by hadley** [comment]
Please provide a reproducible example.

**Comment by joshmyzie2** [comment]
Here you go:

```
> ggplot(aes(x=Sys.time() + 1e-3*1:10, y=cumsum(rnorm(10))), data=NULL) + geom_step()
Error in prettyDate(x = x, n = n, min.n = min.n, sep = sep, ...) :
  range too small for 'min.n'
```
