### ISSUE TITLE
Double vision on facet grid graph

### ISSUE THREAD

**Issue by gormfull** [hadley/ggplot2#1398]
Hi,

I have the dataset  on the bottom (sorry, could not attach the file and I do not know what the minimal dataset is, where the problem appears):

I load this via
data <- read.csv("NAMEOFFILE")

then I source the following script:

require(ggplot2)

#plot
plot <- ggplot(data=data, aes(x=factor(Segment), y=Speed))
plot <- plot + geom_boxplot() + geom_point(position=position_jitter(width=0.2, height=0)) + facet_grid(.~Type + Anzahl.der.Zellen + Date +Sample) + xlab("Segment") + ylab("speed(px/px)")

and finally draw the graph via 
>plot

Unfortunately, I get some, but not all, data points to appear twice (jittered).
For an example output, please check specifically the maximal point(s) of boxplot 2,4, and 7 in the attached png. (E.g. the doubled maxima in boxplot 2 is datapoint 123 in the data below, with no other data point sharing the same factors in the facet_grid, and the same value for speed.)
 
![doublevision](https://cloud.githubusercontent.com/assets/1145158/10885661/975a1e90-817e-11e5-9d3a-9d436fc097c8.png)

This happened under both ggplot2 0.9.3.1 and the newly installed 1.0.1

Thanks, and here the data:

"","Anzahl.der.Zellen","Segment","Date","Sample","Type","Width","Height","Speed"
"1",1,1,2015-10-12,"1","Kontrolle",413,39,10.5897435897436
"2",1,1,2015-10-12,"1","Kontrolle",416,29,14.3448275862069
"6",1,1,2015-10-12,"1","Kontrolle",412,40,10.3
"7",1,1,2015-10-12,"1","Kontrolle",416,38,10.9473684210526
"9",1,1,2015-10-12,"1","Kontrolle",411,37,11.1081081081081
"10",1,1,2015-10-12,"1","Kontrolle",415,44,9.43181818181818
"11",1,1,2015-10-12,"1","Kontrolle",414,35,11.8285714285714
"13",1,1,2015-10-12,"1","Kontrolle",415,25,16.6
"16",1,11,2015-10-12,"1","Kontrolle",415,38,10.9210526315789
"17",1,11,2015-10-12,"1","Kontrolle",413,33,12.5151515151515
"19",1,1,2015-10-12,"1","Kontrolle",413,40,10.325
"23",1,1,2015-10-13,"1","Kontrolle",416,44,9.45454545454546
"24",1,1,2015-10-13,"1","Kontrolle",415,39,10.6410256410256
"25",1,1,2015-10-13,"1","Kontrolle",411,33,12.4545454545455
"26",1,1,2015-10-13,"1","Kontrolle",412,40,10.3
"28",1,1,2015-10-13,"1","Kontrolle",416,40,10.4
"31",1,1,2015-10-13,"2","Kontrolle",413,40,10.325
"32",1,1,2015-10-13,"2","Kontrolle",413,44,9.38636363636364
"33",1,1,2015-10-13,"3","Kontrolle",410,37,11.0810810810811
"34",1,1,2015-10-13,"3","Kontrolle",413,24,17.2083333333333
"35",1,1,2015-10-13,"3","Kontrolle",414,38,10.8947368421053
"36",1,1,2015-10-13,"3","Kontrolle",409,29,14.1034482758621
"38",1,1,2015-10-13,"3","Kontrolle",411,29,14.1724137931034
"39",1,1,2015-10-13,"3","Kontrolle",412,24,17.1666666666667
"40",1,1,2015-10-13,"3","Kontrolle",411,36,11.4166666666667
"41",1,1,2015-10-13,"3","Kontrolle",415,21,19.7619047619048
"44",1,1,2015-10-13,"3","Kontrolle",414,34,12.1764705882353
"46",1,1,2015-10-13,"3","Kontrolle",415,31,13.3870967741935
"47",1,11,2015-10-13,"3","Kontrolle",412,33,12.4848484848485
"48",1,11,2015-10-13,"3","Kontrolle",412,33,12.4848484848485
"52",1,11,2015-10-13,"3","Kontrolle",412,20,20.6
"53",1,11,2015-10-13,"3","Kontrolle",412,24,17.1666666666667
"54",1,11,2015-10-13,"3","Kontrolle",413,33,12.5151515151515
"57",1,1,2015-10-13,"4","Kontrolle",415,38,10.9210526315789
"63",1,11,2015-10-13,"4","Kontrolle",414,33,12.5454545454545
"67",1,1,2015-10-13,"5","Kontrolle",417,33,12.6363636363636
"69",1,1,2015-10-13,"5","Kontrolle",417,35,11.9142857142857
"74",1,1,2015-10-13,"5","Kontrolle",385,41,9.39024390243902
"75",1,1,2015-10-13,"5","Kontrolle",418,32,13.0625
"78",1,1,2015-10-13,"5","Kontrolle",414,37,11.1891891891892
"79",1,1,2015-10-13,"5","Kontrolle",417,46,9.06521739130435
"80",1,11,2015-10-13,"5","Kontrolle",417,40,10.425
"82",1,11,2015-10-13,"5","Kontrolle",415,33,12.5757575757576
"83",1,1,2015-10-18,"1","Kontrolle",412,37,11.1351351351351
"84",1,11,2015-10-18,"1","Kontrolle",411,37,11.1081081081081
"85",1,1,2015-10-18,"2","Kontrolle",416,32,13
"86",1,1,2015-10-18,"2","Kontrolle",416,35,11.8857142857143
"87",1,1,2015-10-18,"2","Kontrolle",416,36,11.5555555555556
"88",1,1,2015-10-18,"2","Kontrolle",417,37,11.2702702702703
"89",1,1,2015-10-18,"2","Kontrolle",417,38,10.9736842105263
"90",1,11,2015-10-18,"2","Kontrolle",415,31,13.3870967741935
"91",1,11,2015-10-18,"2","Kontrolle",415,31,13.3870967741935
"92",1,11,2015-10-18,"2","Kontrolle",415,34,12.2058823529412
"94",1,1,2015-10-18,"2","Kontrolle",414,37,11.1891891891892
"95",1,1,2015-10-18,"2","Kontrolle",417,35,11.9142857142857
"96",1,11,2015-10-18,"2","Kontrolle",414,41,10.0975609756098
"97",1,11,2015-10-18,"2","Kontrolle",413,31,13.3225806451613
"98",1,11,2015-10-18,"2","Kontrolle",415,35,11.8571428571429
"99",1,1,2015-10-18,"2","Kontrolle",416,39,10.6666666666667
"100",1,1,2015-10-18,"2","Kontrolle",416,41,10.1463414634146
"105",1,1,2015-10-20,"1","CytoD",415,38,10.9210526315789
"106",1,1,2015-10-20,"1","CytoD",415,39,10.6410256410256
"107",1,1,2015-10-20,"1","CytoD",416,37,11.2432432432432
"109",1,11,2015-10-20,"1","CytoD",409,31,13.1935483870968
"110",1,11,2015-10-20,"1","CytoD",413,36,11.4722222222222
"111",1,11,2015-10-20,"1","CytoD",413,31,13.3225806451613
"114",1,11,2015-10-20,"1","CytoD",419,33,12.6969696969697
"115",1,1,2015-10-20,"1","CytoD",414,34,12.1764705882353
"116",1,1,2015-10-20,"1","CytoD",415,34,12.2058823529412
"118",1,11,2015-10-20,"1","CytoD",414,31,13.3548387096774
"121",1,1,2015-10-20,"1","CytoD",416,42,9.90476190476191
"123",1,11,2015-10-20,"1","CytoD",412,26,15.8461538461538
"124",1,11,2015-10-20,"1","CytoD",412,33,12.4848484848485
"125",1,11,2015-10-20,"1","CytoD",348,25,13.92
"126",1,1,2015-10-21,"1","WFA",418,42,9.95238095238095
"127",1,1,2015-10-21,"1","WFA",418,41,10.1951219512195
"128",1,1,2015-10-21,"1","WFA",415,36,11.5277777777778
"129",1,11,2015-10-21,"1","WFA",418,39,10.7179487179487
"130",1,11,2015-10-21,"1","WFA",416,31,13.4193548387097
"133",1,1,2015-10-26,"1","CytoD",419,21,9.97619047619048
"135",1,1,2015-10-26,"1","CytoD",419,18,11.6388888888889
"136",1,1,2015-10-26,"1","CytoD",418,20,10.45
"137",1,1,2015-10-26,"1","CytoD",419,16,13.09375
"139",1,1,2015-10-26,"1","CytoD",418,15,13.9333333333333
"140",1,1,2015-10-26,"1","CytoD",417,21,9.92857142857143
"141",1,1,2015-10-26,"1","CytoD",418,18,11.6111111111111
"142",1,1,2015-10-26,"1","CytoD",419,20,10.475
"146",1,1,2015-10-26,"1","CytoD",418,20,10.45
"149",1,11,2015-10-26,"1","CytoD",417,18,11.5833333333333
"151",1,11,2015-10-26,"1","CytoD",419,18,11.6388888888889
"152",1,11,2015-10-26,"1","CytoD",419,16,13.09375
"153",1,11,2015-10-26,"1","CytoD",420,19,11.0526315789474
"154",1,1,2015-10-26,"1","CytoD",418,15,13.9333333333333
"155",1,1,2015-10-26,"1","CytoD",418,25,8.36
"156",1,1,2015-10-26,"1","CytoD",419,20,10.475
"157",1,1,2015-10-26,"1","CytoD",418,19,11
"158",1,1,2015-10-26,"1","CytoD",419,17,12.3235294117647
"159",1,11,2015-10-26,"1","CytoD",416,15,13.8666666666667
"160",1,1,2015-10-26,"1","CytoD",418,15,13.9333333333333
"161",1,11,2015-10-26,"1","CytoD",417,18,11.5833333333333
"162",1,11,2015-10-26,"1","CytoD",417,18,11.5833333333333
"163",1,1,2015-10-26,"1","WFA",415,19,10.9210526315789
"164",1,1,2015-10-26,"1","WFA",415,15,13.8333333333333
"165",1,1,2015-10-26,"1","WFA",415,23,9.02173913043478
"166",1,1,2015-10-26,"1","WFA",414,18,11.5
"168",1,1,2015-10-26,"1","WFA",414,19,10.8947368421053
"169",1,1,2015-10-26,"1","WFA",414,17,12.1764705882353
"170",1,1,2015-10-26,"1","WFA",415,17,12.2058823529412
"173",1,1,2015-10-26,"1","WFA",415,20,10.375
"174",1,1,2015-10-26,"1","WFA",411,18,11.4166666666667
"175",1,11,2015-10-26,"1","WFA",413,14,14.75
"177",1,11,2015-10-26,"1","WFA",412,16,12.875
"178",1,11,2015-10-26,"1","WFA",413,17,12.1470588235294
"179",1,11,2015-10-26,"1","WFA",411,18,11.4166666666667
"182",1,11,2015-10-26,"1","WFA",413,19,10.8684210526316
"183",1,11,2015-10-26,"1","WFA",414,15,13.8
"184",1,1,2015-10-26,"2","WFA",415,27,7.68518518518519
"185",1,1,2015-10-26,"2","WFA",413,23,8.97826086956522
"186",1,1,2015-10-26,"2","WFA",415,20,10.375
"187",1,1,2015-10-26,"2","WFA",414,21,9.85714285714286
"188",1,1,2015-10-26,"2","WFA",413,21,9.83333333333333
"189",1,1,2015-10-26,"2","WFA",413,25,8.26
"190",1,1,2015-10-26,"2","WFA",414,27,7.66666666666667
"191",1,11,2015-10-26,"2","WFA",417,16,13.03125
"192",1,11,2015-10-26,"2","WFA",418,18,11.6111111111111
"193",1,11,2015-10-26,"2","WFA",415,16,12.96875
"194",1,11,2015-10-26,"2","WFA",417,17,12.2647058823529
"195",1,11,2015-10-26,"2","WFA",417,17,12.2647058823529
"196",1,11,2015-10-26,"2","WFA",404,15,13.4666666666667
"197",1,11,2015-10-26,"2","WFA",404,19,10.6315789473684
"198",1,1,2015-10-26,"2","WFA",413,25,8.26
"199",1,1,2015-10-26,"2","WFA",413,22,9.38636363636364
"200",1,1,2015-10-26,"2","WFA",414,20,10.35
"201",1,11,2015-10-26,"2","WFA",418,23,9.08695652173913
"202",1,11,2015-10-26,"2","WFA",419,19,11.0263157894737
"203",1,1,2015-10-30,"1","CytoD",413,36,11.4722222222222
"204",1,1,2015-10-30,"1","CytoD",407,35,11.6285714285714
"205",1,1,2015-10-30,"1","CytoD",413,38,10.8684210526316
"206",1,1,2015-10-30,"1","CytoD",412,39,10.5641025641026
"207",1,11,2015-10-30,"1","CytoD",412,34,12.1176470588235
"208",1,11,2015-10-30,"1","CytoD",413,34,12.1470588235294
"209",1,11,2015-10-30,"1","CytoD",413,39,10.5897435897436
"212",1,1,2015-10-30,"1","WFA",413,48,8.60416666666667
"218",1,1,2015-10-30,"2","WFA",412,39,10.5641025641026
"219",1,1,2015-10-30,"2","WFA",411,46,8.93478260869565
"220",1,1,2015-10-30,"2","WFA",413,37,11.1621621621622
"221",1,1,2015-10-30,"2","WFA",413,43,9.6046511627907
"222",1,1,2015-10-30,"2","WFA",413,42,9.83333333333333
"223",1,11,2015-10-30,"2","WFA",415,40,10.375
"226",1,1,2015-10-30,"2","WFA",413,47,8.78723404255319
"228",1,11,2015-10-30,"2","WFA",415,36,11.5277777777778

**Comment by hadley** [comment]
You're getting points from the boxplot outliers and your jittered points.
