### ISSUE TITLE
outlier.colour in geom_boxplot

### ISSUE THREAD

**Issue by Kirk3gaard** [hadley/ggplot2#1400]
It would be great if it was possible to make outliers automatically inherit the colours of the boxplot as an alternative to the default: outlier.colour = "black".

"hadley commented on 3 Dec 2011
I'd suggest that when outlier.colour = NULL it defaults to the same colour as the boxes."
(https://github.com/hadley/ggplot2/issues/146)

This issue seems to have been raised and closed before (https://github.com/hadley/ggplot2/issues/146 ) and posts on stackoverflow (http://stackoverflow.com/questions/15273148/coloring-boxplot-outlier-points-in-ggplot2/16035956#16035956) indicate that there has been a solution to set outlier.color=NULL. 

```{r}
library(ggplot2)
point_size=10
ggplot(mtcars, aes(x=factor(cyl), y=mpg, col=factor(cyl))) +
    geom_boxplot(outlier.size = point_size)
```

![image](https://cloud.githubusercontent.com/assets/4373417/10925327/c4b54a6c-82d8-11e5-8933-14164cd9e444.png)

Gives black outliers.

and 

```{r}
ggplot(mtcars, aes(x=factor(cyl), y=mpg, col=factor(cyl))) +
    geom_boxplot(outlier.size = point_size,outlier.colour = NULL)
```

Gives the following error:
"Error: Aesthetics must be either length 1 or the same as the data (3): outlier.colour, outlier.shape, outlier.size, outlier.stroke"

```{r}
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.1.9003
```

Thanks for an awesome package!

**Comment by hadley** [comment]
@wch do you remember why you made this change?

**Comment by wch** [comment]
I think we were moving as many arguments as we could into function arguments so that they were transparent to the user.

**Comment by Kirk3gaard** [comment]
Cool it works nicely! Thank you very much.
