### ISSUE TITLE
Feature Request: Option to Modify Legend Wrapping Behaviour

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1401]
If a legend is wrapped into more than one row, the legend's elements are ordered into columns. It'd be nice to have an option to allow it to order the elements into rows.

For example,

    qplot(data = mtcars, x = factor(cyl), y = mpg, colour = factor(hp)) + theme(legend.position = "top")

I'd like 52, 62, 65, ... to appear in the first row, from left to right.

**Comment by hadley** [comment]
I'd consider a pull request to implement this, but I'm unlikely to do it myself.
