### ISSUE TITLE
Facet Grid Error if First Plot Layer Data Frame is Empty

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1402]
An obscure error message is printed if the data frame of the first layer has no rows.

    empty <- diamonds[0, ]
    plot <- ggplot(empty, aes(color, depth)) + geom_boxplot()
    plot <- plot + geom_bar(data = diamonds[1:100, ], aes_string("color", "depth"), stat = "identity")
    plot + facet_grid(. ~ clarity)

Which results in `Error in FUN(X[[i]], ...) : subscript out of bounds`.

The bug is **not** present in version 1.0.1. It occurs when using version 1.0.1.9003.

**Comment by technocrat** [comment]
I don't see an error message in ggplot2_1.0.1 under R version 3.2.1


DarioS wrote:
>
> |empty<- diamonds[0, ]
> plot<- ggplot(empty, aes(color, depth)) + geom_boxplot()
> plot<- plot + geom_bar(data = diamonds[1:100, ], aes_string("color", 
> "depth"), stat = "identity")
> plot + facet_grid(. ~ clarity)
> |


DarioS wrote:
> |empty<- diamonds[0, ]
> plot<- ggplot(empty, aes(color, depth)) + geom_boxplot()
> plot<- plot + geom_bar(data = diamonds[1:100, ], aes_string("color", "depth"), stat = "identity")
> plot + facet_grid(. ~ clarity)
> |

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by hadley** [comment]
Simpler reprex:

```R
empty <- diamonds[0, ]

ggplot(empty, aes(color, depth)) + 
  geom_bar(data = diamonds[1:100, ], stat = "identity") +
  geom_boxplot() +
  facet_grid(. ~ cut)
```

Only occurs when both bar and boxplot are on plot.
