### ISSUE TITLE
speed of ggplot

### ISSUE THREAD

**Issue by mikejiang** [hadley/ggplot2#1404]
ggplot2 is a well documented and has abundant community supports, which is why I decided to write the new visualization package [ggcyto](https://github.com/RGLab/ggcyto) for flow cytometry data to replace the existing  R package [flowViz](https://www.bioconductor.org/packages/release/bioc/html/flowViz.html) that was based on [lattice](https://cran.r-project.org/web/packages/lattice/index.html) since its syntax and interface makes it difficult to use nowadays.

However, the internal usage of `data.frame` and `plyr` of `ggplot` makes `ggcyto` package spend almost twice as much time as `flowViz` to plot any two dimensional scatter plot (after binned).

I looked into `ggvis` as a possible solution but it seems to lack some key features such as facetting, hexbin. 

I wonder if there is any plan for improving the speed of `ggplot` by taking advantage of `dplyr` or `data.table`?

**Comment by hadley** [comment]
Yes, hopefully next year.
