### ISSUE TITLE
Boxplot Edges Overlap

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1405]
When boxplots are grouped by a second factor, the left edge of a boxplot draws over the right edge of the boxplot to the left of it. This gives an inconsistent appearance for adjacent boxes with overlapping y-value ranges and others which are well-separated. Should the boxes be adjacent with no gap, but not have any overlapping edges ?

    ggplot(diamonds, aes(x = color, y = depth, colour = cut)) + geom_boxplot()

**Comment by hadley** [comment]
See the width argument to `position_dodge()`
