### ISSUE TITLE
facet and coord_flip interaction produces incorrect scales

### ISSUE THREAD

**Issue by baptiste** [hadley/ggplot2#1406]
I'll try to produce a more minimal example when I find the time, but looking at my answer to this question,

http://stackoverflow.com/q/33654787/471093

the resulting plot has an incorrect scale on the x-axis, as the two facets should have different range (0 to 1 vs 0 to 20).

It's quite possible that one shouldn't use different position functions for different facets, but it's still a surprising (incorrect) result.

**Comment by hadley** [comment]
Yes, this has never worked, unfortunately.
