### ISSUE TITLE
Font Size Inconsistency Between geom_annotate and theme's element_text()

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1408]
`geom_annotate` is useful for adding text labels to a plot, but to make the font sizes comparable to other text elements, such as axes titles, the [`size` argument of `geom_annotate` needs to be multiplied by 5/14](http://stackoverflow.com/a/25062509). Could this workaround be added to the documentation of `geom_annotate` or otherwise the sizes made equivalent throughout the package ?

**Comment by hadley** [comment]
This is as documented: font sizes in the plot are in mm, font sizes in the theme are in pts.
