### ISSUE TITLE
Better Error Messages for Missing Values

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1410]
The example fails because `fontSizes` only has two elements, but the plot makes reference to `fontSizes[3]`.

    fontSizes <- c(12, 10)
    ggplot(diamonds, aes(x = color, y = depth)) + geom_boxplot() + facet_grid(reformulate("cut", '.')) + theme(plot.title = element_text(size = fontSizes[1]), axis.title = element_text(size = fontSizes[2]), axis.text = element_text(size = fontSizes[3]))

This produces an obscure error message.

    (process:8754): Pango-CRITICAL **: pango_font_description_set_size: assertion 'size >= 0' failed

which is unclear to users. Could input checking be performed in this case and an error message that clearly explains the problem provided?

**Comment by hadley** [comment]
I think this is a bug in grid.

**Comment by pmur002** [comment]
It possibly goes deeper than that - GEText() in the graphics engine might not be protecting itself from NA graphical parameters as well as it should

**Comment by pmur002** [comment]
BTW, a simpler test case is just this ...

library(grid)
grid.text("test", gp=gpar(fontsize=NA))

**Comment by DarioS** [comment]
This is fixed in R-devel.
