### ISSUE TITLE
Unused factor levels are still shown on legend even though drop=TRUE

### ISSUE THREAD

**Issue by Nilas7** [hadley/ggplot2#1418]
For example if I want to have consistent colours across a set of graphs that have different subsets and a different number of categorical variables I can use `scale_colour_hue` with `limits` set to the factor levels. Since I do not want to show unused factor levels on the legend I can set `drop=TRUE`. But this option does not seem to work:
```R
require(ggplot2)

# Generating data
data<-data.frame(x=1:4,y=1:4,type=factor(c("a","b","c","d")))

# Setting colours for factor levels
colscale<-scale_colour_hue(limits=levels(data$type),drop=TRUE)
```
### Plot for all data
```R
# Plot for all data
p<-ggplot(data,aes(x=x,y=y,colour=type))+
  geom_point()+
  colscale
p
```
![all](https://cloud.githubusercontent.com/assets/16062130/11453833/ee36be5c-961a-11e5-88ed-148b0109a253.png)
### Plot for subset
```R
# Plot for subset
p<-ggplot(data[1:3,],aes(x=x,y=y,colour=type))+
  geom_point()+
  colscale
p
```
![subset](https://cloud.githubusercontent.com/assets/16062130/11453858/b9d48760-961b-11e5-83f2-6238009b459d.png)
As seen the factor level `"d"` appears on the plot for the subset even though `drop=TRUE`. Is this an intended behaviour?

**Comment by has2k1** [comment]
Whatever you pass in the `limits` parameter has precedence. `drop` tells the scale not to consider unused factor levels, then `limits` says to the legend make entries for all these "levels".
