### ISSUE TITLE
Issue loading ggplot2

### ISSUE THREAD

**Issue by chethanjjj** [hadley/ggplot2#1419]
Hi,

I keep getting the following error when running:
library(ggplot2)

----------------------------

Error in unloadNamespace(package) : 
  namespace ‘ggplot2’ is imported by ‘GGally’ so cannot be unloaded
Error in library(ggplot2) : 
  Package ‘ggplot2’ version 1.0.1 cannot be unloaded

----------------------------

and only a weeks ago, it was running fine.

**Comment by hadley** [comment]
Maybe you need to re-install in a clean R session?
