### ISSUE TITLE
In development version can't move titles

### ISSUE THREAD

**Issue by sarahfbrooks** [hadley/ggplot2#1425]
In development version, theme element settings which worked in stable version no longer work for moving axis and plot titles, such as 
  theme(plot.title = element_text(vjust=20)) + 
  theme(axis.title.x = element_text(vjust=-0.5)) + 
  theme(axis.title.y = element_text(vjust=1.5))

**Comment by hadley** [comment]
No, because those were hacks that never should've worked. Use the new margins parameter instead.
