### ISSUE TITLE
na.rm default for stat_identity()?

### ISSUE THREAD

**Issue by garrettgman** [hadley/ggplot2#1427]
The documentation for `stat_identity()` says it has a `na.rm = FALSE` default, but this does not appear to be the case. As a result, `stat_identity()` fails with a cryptic message when `na.rm` is not set.
````
f <- ggplot(mpg, aes(cty, hwy))
f + stat_identity()
##  Error: is.logical(na.rm) is not TRUE 

f + stat_identity(na.rm = TRUE)
## Works

f + stat_identity(na.rm = FALSE)
## Works
````

**Comment by hadley** [comment]
Fixed in 035e6ff8
