### ISSUE TITLE
position_nudge defaults do not nudge 

### ISSUE THREAD

**Issue by garrettgman** [hadley/ggplot2#1429]
The defaults of position nudge are `x = 0`, `y = 0`, which means that calling `position_nudge()` does not actually nudge anything:

````
df <- data.frame(
  x = c(1,3,2,5),
  y = c("a","c","d","c")
)

# no nudge
ggplot(df, aes(x, y)) +
  geom_point() +
  geom_text(aes(label = y), position = position_nudge())

# no nudge (if it worked)
ggplot(df, aes(x, y)) +
  geom_point() +
  geom_text(aes(label = y), position = "nudge")
````

(At the moment the second code doesn't seem to work for other reasons, #1428).

I urge you to set the defaults to `x = 0.1`, and `y = 0.1`, so the `position = "nudge"` syntax will become a simple way to do something useful. Also, I'd prefer to work once to not nudge after I call position nudge, e.g. `position = position_nudge(x = 0)`, than to work twice each time I want to nudge (first by calling nudge then by setting a nudge, e.g. `position = position_nudge(x = 0.1)`. This would be similar to how `position_jitter` will jitter even if you do not set width and height.

**Comment by hadley** [comment]
But then you'd have to explicitly do `x = 0` if you just wanted to nudge y.

**Comment by garrettgman** [comment]
But typing `x = 0` is no more work than typing `y = 0.1` (less actually). If nudging only y is a common case, the defaults `x = 0` and `y = 0.1` would make `position = "nudge"` useful and teachable.
