### ISSUE TITLE
stat_sum() ..prop.. request

### ISSUE THREAD

**Issue by garrettgman** [hadley/ggplot2#1430]
The `..prop..`variable of `stat_count()`/`stat_sum()` would be easier to use and demo if it grouped by the $x$ variable by default, e.g. if the two calls below did the same thing

````
ggplot(data = diamonds) + 
  geom_count(mapping = aes(x = cut, y = clarity, size = ..prop..))
````

````
ggplot(data = diamonds) + 
  geom_count(mapping = aes(x = cut, y = clarity, size = ..prop.., group = cut))
````

If the extra work for you and computation for R is slight, this would help the user as no one would currently make the first plot: it just makes equally sized points. One could override the default by setting group.

**Comment by hadley** [comment]
It follows the same grouping rules as everything else in ggplot2 - I think it would be a mistake to make give it special rules.
