### ISSUE TITLE
2.0.0 geom_hline not backward compatible with aes(x=<bla>)

### ISSUE THREAD

**Issue by gdbassett** [hadley/ggplot2#1441]
```
gg <- ggplot()
gg <- gg + geom_hline(data=data.frame(x=0), aes(x=x), colour="black", size=0.3)
gg
Error: geom_hline requires the following missing aesthetics: yintercept
```
Maintaining backwards compatibility would allow mixed (1.x.x/2.x.x) ggplot environments while transitioning to v2.x.x

**Comment by eibanez** [comment]
Why would `geom_hline` need `x`?

**Comment by gdbassett** [comment]
I don't think it is needed, just that, since it works, it should be phased out slowly to help with migration.

**Comment by eibanez** [comment]
The problem there is that you have not set `yintercept` (the error is very descriptive).

This works:
```
ggplot() +
  geom_hline(data=data.frame(x=0, y = 1), aes(x=x, yintercept=1), colour="black", size=0.3)
```

**Comment by gdbassett** [comment]
While that works, so does: 
```
gg <- ggplot()
gg <- gg + geom_line(data=data.frame(x=c(1:5), y=c(1:5)), aes(x, y))
gg <- gg + geom_hline(data=data.frame(x=0), aes(x=x), colour="black", size=0.3)
gg
```

**Comment by eibanez** [comment]
Again, you are trying to set `x` on a horizontal line.

FWIW, I like the fact that autocompleting for aesthetics is deprecated
