### ISSUE TITLE
Peculiar environment Issue in ggplot2_2.0.0: "Error in list2env(members, envir = e) " running R 3.1.1

### ISSUE THREAD

**Issue by anesthetize** [hadley/ggplot2#1444]
Error in ggplot2 running R 3.1.1:
```
install.packages("ggplot2")
library(ggplot2)

a<-1:3
b<-4:6
c <- as.data.frame(cbind(a,b))

qplot(a,b,data=c)
```

This yields the following error:

```
Error in list2env(members, envir = e) : 
  names(x) must be a character vector of the same length as x
```

Please note that I'm running R on a Windows Machine with mapped network drives, as such UNC paths are not supported in R and I made appropriate changes in the .Renviron file using R_LIBS.

Session Info as below:

```
sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    
LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       
LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.0.0

loaded via a namespace (and not attached):
[1] colorspace_1.2-6 grid_3.1.1       gtable_0.1.2     munsell_0.4.2
    plyr_1.8.3       Rcpp_0.12.2      scales_0.3.0     tools_3.1.1    
```

**Comment by anesthetize** [comment]
Works on R 3.2.3, just not on 3.1.1

**Comment by snafu123** [comment]
I just noticed that this is the same problem I had installing on 3.0.2:

Error in list2env(members, envir = e) : 
  names(x) must be a character vector of the same length as x

i reported it yesterday so. the difference is that for me, the error occurred which prevented ggplot installation, not the runtime.

**Comment by jonrobinson2** [comment]
Hm any update on why this is happening? I am seeing this on R 3.1.1 as well.

**Comment by hadley** [comment]
I think this means we've accidentally made ggplot2 only work in 3.2.2. @wch did we do this in ggproto?

**Comment by wch** [comment]
I tested this on 3.1.0. It looks like the source of the problem is that `list2env` errors if you give it an empty list:

```R
 list2env(list())
# Error in list2env(list()) : 
#   names(x) must be a character vector of the same length as x
````

We can work around it by adding a check in `ggproto` for empty lists.

**Comment by kenkcchew** [comment]
when you create the list of dataframe, you must give a name to each dataframe within the list
