### ISSUE TITLE
stat_summary error when missing ymin/ymax in facet

### ISSUE THREAD

**Issue by tpall** [hadley/ggplot2#1445]
stat_summary gives error with ggplot2_2.0.0  when missing data for ymin/ymax in at least one facet to calculate errorbars/pointrange. 
ggplot2 1.0.1 robustly plotted just points without bars in such facet. 

Taavi

Minimal  example:
```R
library(ggplot2)
library(dplyr)
mtcars %>% 
   group_by(gear, cyl) %>%
   summarise(hp = mean(hp)) %>%
   ggplot(aes(gear, hp)) + 
   stat_summary(fun.data = mean_se, geom = "pointrange") +
   facet_wrap(~cyl)
Error in FUN(X[[i]], ...) : subscript out of bounds
In addition: Warning message:
Removed 8 rows containing missing values (geom_pointrange). 
```

**Comment by hadley** [comment]
More minimal reprex:

```R
df <- data.frame(x = c(1, 2, 1), y = c(2, 2, 2), g = c(1, 1, 2), se = c(1, 1, NA))

ggplot(df, aes(x, y)) + 
  stat_summary(fun.data = mean_se, geom = "pointrange") +
  facet_wrap(~g)
```

**Comment by hadley** [comment]
This eliminates the error, but I'm not sure if this is what you expected. Did pointrange use to display just the points if ymin/ymax were missing?

**Comment by tpall** [comment]
I am happy, my code produces a plot again. Error appeared after upgrade
when I reused my stat_summary line/errorbar plot on a dataset where
errorbars could not be calculated for none of the x value (N=1),
originally, just line was displayed. After upgrade, completely missing
ymin/ymax produced error.

Taavi
