### ISSUE TITLE
vjust not working in ggplot2

### ISSUE THREAD

**Issue by utzryan** [hadley/ggplot2#1446]
Hi,

I cannot for the life of me get my axis titles to adjust vertically in a ggplot. I've seen several posts about this and have tried everything: keeping vjust within 0 and 1, adjusting the margins, etc. hjust is behaving just as it should but vjust just mocks me in silence. No error message is produced.

Here's a sample code:

x=data.frame(sample(1:10))
x[,2]=sample(1:10)

ggplot(data=x,aes(x=V2,y=V2))+theme(axis.title.y=element_text(vjust=.1,hjust=0.6),
            plot.margin=unit(c(1,1,2,2),'cm'))

No matter what I put into vjust, nothing happens. Am I missing something obvious??

Thanks,
Ryan

**Comment by hadley** [comment]
See #1435
