### ISSUE TITLE
Fortify is not working anymore when parameter 'region' is specified

### ISSUE THREAD

**Issue by matteodefelice** [hadley/ggplot2#1447]
I load a shapefile:
> test = readOGR('.', 'countries_EU')
> head(test)
  CNTR_ID  SHAPE_AREA SHAPE_LEN
0      AD  0.05113435   1.04459
1      AE  6.32022050  23.10413
2      AL  3.05409305  10.99885
3      AM  3.14251031  13.45487
4      AT 10.02825446  24.85974
5      AZ  9.18575578  28.15200
> test_f = fortify(test)
Regions defined for each Polygons

Instead:
> test_f = fortify(test, region = 'CNTR_ID')
Error in get("rgeos", envir = .MAPTOOLS_CACHE) : object 'rgeos' not found

The same code has been working for weeks with the previous version of ggplot2.

**Comment by matteodefelice** [comment]
I was wrong, it's not about ggplot2. I close this issue.

**Comment by davben** [comment]
I've run into the same error message and had to resort to using an older version of ggplot2. I'd greatly appreciate it, if you could you explain what caused the issue and how you've solved it.

**Comment by matteodefelice** [comment]
Unfortunately I don't remember what I did but I remember for sure that it wasn't due to ggplot2.

**Comment by hrbrmstr** [comment]
It's broken in `broom::tidy` (which copied the `fortify` code for spatial objects) as well. I'll see if I can poke at it.

**Comment by hrbrmstr** [comment]
OK, all you have to do is `library(maptools)`. It probably has something to do with the new base map packages. I recommend closing the issue.

**Comment by rpecchia** [comment]
Thanks for this solution! @hrbrmstr
