### ISSUE TITLE
No way to specify number of bins in stat_density_2d 

### ISSUE THREAD

**Issue by ecoRoland** [hadley/ggplot2#1448]
`stat_density2d` used to pass the ellipses to `stat_contour`. That way one could specify the number of bins.

Pre-v2.0.0:

    m <- ggplot(faithful, aes(x = eruptions, y = waiting)) +
      geom_point() +
      xlim(0.5, 6) +
      ylim(40, 110)
    m + geom_density2d(bins = 3)

 Since `stat_density_2d` doesn't do that anymore, I don't see a way to specify the number of bins. If I'm  not missing something that seems like a regression.

**Comment by has2k1** [comment]
There is an inconsistency in the API. Use `n = 3`.

**Comment by ecoRoland** [comment]
@has2k1 I don't follow. `n = 3` is passed to `kde2d` and does not specify the number of bins.

**Comment by has2k1** [comment]
@ecoRoland, maybe I do not understand what you mean by `bins`, but `n` does partition the grid and that is equivalent to `bins`. In 2nd example from the bottom at http://docs.ggplot2.org/dev/geom_density_2d.html, that is `n=100` which is 100 bins.

**Comment by MikeWise2718** [comment]
Can you replicate this http://stackoverflow.com/questions/19329318/how-to-correctly-interpret-ggplots-stat-density2d effect with the `n=4`  parameter? I couldn't...

**Comment by has2k1** [comment]
Oh. Okay, you cannot do that anymore. The `2.0` clean up means parameters do not fall through any more. I'll submit a PR.
