### ISSUE TITLE
aes within stats failing for y aesthetic

### ISSUE THREAD

**Issue by aphalo** [hadley/ggplot2#1452]
This issue may be related to #1431.
The following snippet demonstrates the problem I run into.

```{r}
library(ggplot2)
my.df <- data.frame(a = 1:20, b = 1:20)
# o.k.
ggplot(my.df, aes(a, b)) + stat_identity(geom = "text", aes(label = b, y = b))
# o.k.
ggplot(my.df, aes(a, b)) + stat_identity(geom = "text", aes(label = ..y.., y = b))
# error
# Error in eval(expr, envir, enclos) : object 'y' not found
# Called from: eval(expr, envir, enclos)
ggplot(my.df, aes(a, b)) + stat_identity(geom = "text", aes(label = ..y.., y = ..y..))
```
This is probably the most helpful example, but the error is also triggered when using other stats and other geoms like "label" and "point".

The simplest example is:
```{r}
library(ggplot2)
my.df <- data.frame(a = 1:20, b = 1:20)
# o.k.
ggplot(my.df, aes(a, b)) + stat_identity(geom = "point", aes(y = b))
# error
# Error in eval(expr, envir, enclos) : object 'y' not found
# Called from: eval(expr, envir, enclos)
ggplot(my.df, aes(a, b)) + stat_identity(geom = "point", aes(y = ..y..))
```

**Comment by aphalo** [comment]
Another example that may shed some light...
```{r}
library(ggplot2)
d <- ggplot(mtcars, aes(cyl, y = mpg))
# triggers error 
## Error in eval(expr, envir, enclos) : object 'x' not found
## Called from: eval(expr, envir, enclos)
d + stat_identity(aes(x = ..x.., y = ..y..), color = "red")
# gives the plot I would had expected from the previous statement
d + stat_identity(aes(cyl = ..x.., mpg = ..y..), color = "red")
```

**Comment by technocrat** [comment]
In ggplot2 v.2, 

    d <- ggplot(mtcars, aes(x = cyl, y = mpg))
    d + stat_identity(colour = "red")

works

because **cyl** has been assigned to **x** and because **data** and **aes** were both declared in **d**, they don't need to be repeated in **stat_identity. The line

    d + stat_identity(aes(x = ..x.., y = ..y..), color = "red")

has no idea which of the columns in the df to use for **x**

**Comment by aphalo** [comment]
Yes, in this case it works. The point is that if ..y.. is actually the result of a calculation rather than the original value, it cannot be remapped to y for the geom used "within" the stat. There is no "normal" way that I have found of plotting the result or overriding it for a geom that requires the same aesthetic that has been declared in d. Maybe my expectations for the behaviour are wrong, but the behaviour is rather inconsistent, and is affected by the variable names used internally by the stat, and by the original names of the variables, while within stats it would be best to be able to have code that works only in terms of data$x and data$y.

**Comment by aphalo** [comment]
I close this issue for now, as it does not seem to be a real issue, but rather a misunderstanding from my part.
