### ISSUE TITLE
2.0.0 install error with R 3.0.2

### ISSUE THREAD

**Issue by snafu123** [hadley/ggplot2#1453]
current ubuntu 14.04 version of R is 3.0.2. ggplot2 2.0.0 does not install in this version.  appears ok on other modern versions (on other platforms - 3.2.2 macos)

==================================================
downloaded 1.5 Mb

* installing *source* package ‘ggplot2’ ...
** package ‘ggplot2’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in list2env(members, envir = e) : 
  names(x) must be a character vector of the same length as x
Error : unable to load R code in package ‘ggplot2’
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/usr/local/lib/R/site-library/ggplot2’
* restoring previous ‘/usr/local/lib/R/site-library/ggplot2’

The downloaded source packages are in
	‘/tmp/RtmpAmbtfw/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘ggplot2’ had non-zero exit status

**Comment by snafu123** [comment]
duplicate

**Comment by wxlu718** [comment]
Hey @snafu123 , I had the same problem. How did you solve it at last?
