### ISSUE TITLE
2.0.0 install error with R 3.0.2

### ISSUE THREAD

**Issue by snafu123** [hadley/ggplot2#1454]
current ubuntu 14.04 version of R is 3.0.2. ggplot2 2.0.0 does not install in this version.  appears ok on other modern versions (on other platforms - 3.2.2 macos)

```
==================================================
downloaded 1.5 Mb

>* installing *source* package ‘ggplot2’ ...
>** package ‘ggplot2’ successfully unpacked and MD5 sums checked
>** R
>** data
>*** moving datasets to lazyload DB
>** inst
>** preparing package for lazy loading
>Error in list2env(members, envir = e) : 
>  names(x) must be a character vector of the same length as x
>Error : unable to load R code in package ‘ggplot2’
>ERROR: lazy loading failed for package ‘ggplot2’
>* removing ‘/usr/local/lib/R/site-library/ggplot2’
>* restoring previous ‘/usr/local/lib/R/site-library/ggplot2’

The downloaded source packages are in
	‘/tmp/RtmpAmbtfw/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘ggplot2’ had non-zero exit status
```

**Comment by snafu123** [comment]
just noticed that this may be the same issue as #1444, except i get this on install, not runtime

**Comment by hadley** [comment]
Can you confirm if the fix there works?

**Comment by wch** [comment]
@hadley even with the fix, it won't install on 3.0, because plyr requires >=3.1.0. Also, in the development version, we bumped the version requirement for ggplot2 to match plyr.

**Comment by hadley** [comment]
@wch but there's probably a version of plyr that does work on 3.1.0

**Comment by sriaditya** [comment]
I have the same error on a new debian 8 stable installation. I manually installed the newer release R-3.2.3 "Wooden Christmas-Tree". The problem does not exist in the newer version.
