### ISSUE TITLE
Error: Unknown parameters: outlier.color

### ISSUE THREAD

**Issue by GabrielHoffman** [hadley/ggplot2#1455]
In R 3.2.3 the argument outlier.color from geom_boxplot does not work with ggplot2 2.0.0 after working fine with 1.0.1.  In v1.0.1 both the American and British spellings were accepted, but in v2.0.0 the American spelling throws the error: "Error: Unknown parameters: outlier.color"

Here is some code to reproduce the error:

```R
library(ggplot2)
packageVersion("ggplot2")

# Basic figure
fig = ggplot(sleep, aes(x=group, y=extra)) 

# colour: British usage
fig + geom_boxplot(outlier.colour='black')

# color: American usage
fig + geom_boxplot(outlier.color='black')
```

I don't know if this color/colour issue is a problem in other contexts.

**Comment by technocrat** [comment]
I think it's an oversight; it's come up in previous versions and has been made Yank-friendly and the NEWS files mentions scale_color as an example. I took a look at the code and didn't see an obvious fix, which isn't surprising at my level of non-expertise. We just have to be patient until a getaroundtoit shows up.
