### ISSUE TITLE
geom-errorbar missing from dev Docs

### ISSUE THREAD

**Issue by bhive01** [hadley/ggplot2#1456]
Pointed out in an email to the documentation mailer:
http://docs.ggplot2.org/dev/index.html is missing geom_errorbar

Sure enough, there are no examples shown in 
https://github.com/hadley/ggplot2/blob/master/R/geom-errorbar.r

I've never done package development myself so I'm unsure how to get it right, but based upon the errorbarh docs I flipped the axes and the examples seem to work (xmax to ymax, and xmin to ymin)
```r
#' Vertical error bars
#'
#' @section Aesthetics:
#' \Sexpr[results=rd,stage=build]{ggplot2:::rd_aesthetics("geom", "errorbar")}
#'
#' @seealso \code{\link{geom_errorbarh}}: horizontal error bars
#' @inheritParams geom_point
#' @export
#' @examples
#' df <- data.frame(
#'   trt = factor(c(1, 1, 2, 2)),
#'   resp = c(1, 5, 3, 4),
#'   group = factor(c(1, 2, 1, 2)),
#'   se = c(0.1, 0.3, 0.3, 0.2)
#' )
#'
#' # Define the top and bottom of the errorbars
#'
#' p <- ggplot(df, aes(trt, resp, colour = group))
#' p + geom_point() +
#'   geom_errorbar(aes(ymax = resp + se, ymin = resp - se))
#' p + geom_point() +
#'   geom_errorbar(aes(ymax = resp + se, ymin = resp - se, width = .2))
```

I do note that it links to geom_linerange()
```r
#' @export
#' @rdname geom_linerange
```
But, for some reason this link is not preserved in the documentation.

**Comment by hadley** [comment]
All the "interval" geoms are documented together in http://docs.ggplot2.org/dev/geom_linerange.html

**Comment by bhive01** [comment]
@hadley thanks, I see it now. Is it possible for these functions to be split out on individual lines? 

From a user perspective, at least one user couldn't see the function they were looking for, and I looked and didn't see it either (I'm on vacation though, so I paid less attention than I should've).
