### ISSUE TITLE
Version 2.0.0 broke scale_x_date

### ISSUE THREAD

**Issue by peopleradius** [hadley/ggplot2#1459]
This breaks: 

myGraph <- myGraph + scale_x_date(labels=date_format("%b '%y"),breaks="1 month", minor_breaks = "1 week")

Was working fine, now returns an error as follows when attempting to render myGraph. 

Error in strsplit(unitspec, " ") : non-character argument

**Comment by hadley** [comment]
Can you please provide a reproducible example?

**Comment by peopleradius** [comment]
Hadley,

 

Thank you very much for your quick response.  I attach a reproducible example which will need a time series, which is also attached.  In case you cannot get the attachments, I have posted them at http://pareek.org/rjid_files.zip.

 

Best regards and thank you again, and for doing everything you do for the community.

 

Mukul

 

#---------------

#Load the xts time series.  File rjidxts.RData attached.

 

load("rjidxts.RData")

 

#Build graph

rjid <- ggplot(rjidxts, aes(x=as.Date(index(rjidxts)),y=Aggregate_Scaled)) + geom_line(size=1, colour="blue")

rjid <- rjid + theme_bw()

rjid <- rjid + theme(axis.text.x = element_text(angle=90, hjust = 1, vjust = 0.5, colour="darkred", size=7))

rjid <- rjid + theme(axis.text.y = element_text(size=9))

 

#Upto this point, everything works.  The plot for rjid renders correctly.  The next line gives no error but rjid 

#refuses to render with the error "Error in strsplit(unitspec, " ") : non-character argument"

 

rjid <- rjid + scale_x_date(labels=date_format("%b '%y"),breaks="1 month", minor_breaks = "1 week")

#---------------

Best regards,

Mukul

**Comment by hadley** [comment]
Can you please provide a minimal reprex using a built-in dataset?

**Comment by peopleradius** [comment]
Thanks.  Try this, based on the built-in AirPassengers dataset:

 

------

MyData = as.xts(AirPassengers)

 

MyPlot <- ggplot(MyData, aes(x=as.Date(index(MyData)),y=MyData[,1])) + geom_line(size=1, colour="blue")

 

#Upto here, I can render a plot (though 

#there is a 'pick scale' warning).  After 

#the next line I get an error if I try to plot.

 

MyPlot <- MyPlot + scale_x_date(labels=date_format("%b '%y"),breaks="1 month", minor_breaks = "1 week")

MyPlot

 

-------------

**Comment by peopleradius** [comment]
MyData = as.xts(AirPassengers)

    MyPlot <- ggplot(MyData, aes(x=as.Date(index(MyData)),y=MyData[,1])) + geom_line(size=1, colour="blue")
    
    #Upto here, I can render a plot (though 
    #there is a 'pick scale' warning).  After 
    #the next line I get an error.
    
    MyPlot <- MyPlot + scale_x_date(labels=date_format("%b '%y"),breaks="1 month", minor_breaks = "1 week")

**Comment by hrbrmstr** [comment]
The help on `ggplot2.zoo` gives an example on how to do xts plots. You should be doing something more like this:

    library(xts)
    library(ggplot2)

    dat <- as.xts(AirPassengers)

    gg <- ggplot(fortify(dat, melt=TRUE), aes(x=Index, y=Value))
    gg <- gg + geom_line(size=1, colour="blue")
    gg <- gg + scale_x_yearmon(format="%b %y", n=10) 
    gg

**Comment by peopleradius** [comment]
Thanks Bob.  There are of course alternative ways to do it - in fact this changes the problem by using yearmon in place of a continuous date.  What if the data had a continuous date, and we had to use `scale_x_date` and not `scale_x_yearmon`?

Anyway, I was just reporting something that broke with a strange error message (while having worked fine before).

**Comment by hadley** [comment]
Once I convert this to a correct aes specification, the warnings seem pretty self explanatory to me:

```R
library(ggplot2)
library(xts)
MyData <- as.xts(AirPassengers)

ggplot(MyData, aes(x=Index, MyData)) + 
  geom_line(size=1, colour="blue") + 
  scale_x_date(labels = "%b '%y",breaks = "1 month", minor_breaks = "1 week")
# Don't know how to automatically pick scale for object of type yearmon. Defaulting to continuous
# Don't know how to automatically pick scale for object of type xts/zoo. Defaulting to continuous
```
