### ISSUE TITLE
ggplot2 always crashes RStudio

### ISSUE THREAD

**Issue by thomiko** [hadley/ggplot2#1461]
Hi all,

I have a severe constant problem with ggplot2 in RStudio on my desktop computer at work (Windows 7, quite powerful spec: 8GB RAM, Intel i7 CPU). I would like to ask if anyone else had similar problems and if so, what you did to solve the problem.

The description of the problem is very easy: ggplot2 crashes RStudio always, even with simple scripts

library(ggplot2)
data("mtcars")
ggplot(mtcars, aes(mpg, wt)) + geom_point()  

As soon as I execute the script line where the ggplot should be generated (here the third script line), RStudio shuts down after about 0.2 seconds.
It happened with ggplot2 v1 and it happens as well with ggplot v2. I never had this problem on another computer. And I never had such a problem with another R package on my desktop computer at work.

I am currently running R version 3.2.2 (not the latest version 3.2.3 for compatibility reasons in the company) and RStudio 0.99.491 (latest stable version from the RStudio website).

Here's a short screencast: https://drive.google.com/open?id=0B-1aywTKlhBlcDJVY3lWVU5oYTA
RStudio just "disappears". I haven't found any useful log information in ..\AppData\Local\RStudio-Desktop\log  

Cheers,

Thomas

**Comment by hadley** [comment]
Closed - see discussion on mailing list for more info
