### ISSUE TITLE
With coord_flip(), the default behavior should be to invert the old x-scale with Factors

### ISSUE THREAD

**Issue by davidpham87** [hadley/ggplot2#1466]
Dear ggplot2 developers,

First of all, thanks a lot for your contribution for this wonderful packages. I think it taught a lot of people around the world the way of creating graphics and its grammar. 

I would like to make suggestion with `coord_flip()`: when the original variable on the x-scale is a factor, then it would be beneficial to inverse the order on the new y scale. The reason is people expect alphabetical variable to be sorted starting from the top and it would match the order in the legend.

I know there are tricks to force the ordering on ggplot2, but I think, this could be an easy improvement. 

Thanks a lot for your time!

**Comment by hadley** [comment]
Because scales and coords are independent, this isn't possible, sorry.
