### ISSUE TITLE
Default ECDF behavior is not empirical

### ISSUE THREAD

**Issue by BrandanW** [hadley/ggplot2#1467]
I've found that when plotting an ecdf with ggplot, the two points at y=0 and y=1 are undesirable and frankly arbitrary. This is especially true for distributions with certain properties (eg, strictly positive or only in a specific range). Is there a way to get around this default behavior, or any plans to change it?

Example:
```
ggplot(data.frame(x = exp(1:10)),
       aes(x)) +
  geom_line(stat = "ecdf")
```
![rplot](https://cloud.githubusercontent.com/assets/16543315/12094458/9c05258c-b2bd-11e5-8ea9-89eaea1f18f4.png)

**Comment by felasa** [comment]
I believe stat_ecdf is meant to be used with geom_step

```r
ggplot(data.frame(x = exp(1:10)),  aes(x)) +
 stat_step()
```

or

```r
ggplot(data.frame(x = exp(1:10)),  aes(x)) +
 geom_step(stat="ecdf")
```
both produce this 

![image](https://cloud.githubusercontent.com/assets/11998685/12176294/765be9bc-b52c-11e5-8ab5-54c4c812a0d2.png)

**Comment by BrandanW** [comment]
Even the step has two unneeded points, though, at about (-2000, 0) and (23700, 1). Wouldn't more rational endpoints be (min(x), 0) and (max(x), 0)? I don't see what the horizontal lines at top and bottom add.

**Comment by felasa** [comment]
While I personally have no problem with that (it's not wrong and base R does the same although with a different visualization) I see what you mean. 

This can be certainly be adressed with a few changes. If if the devs don't want it implemented you can create a custom stat: 

```r
stat_myecdf <- function(mapping = NULL, data = NULL, geom = "step",
                      position = "identity", n = NULL, na.rm = FALSE,
                      show.legend = NA, inherit.aes = TRUE, direction="vh", ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = StatMyecdf,
    geom = geom,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      n = n,
      na.rm = na.rm,
      direction=direction,
      ...
    )
  )
}

StatMyecdf <- ggproto("StatMyecdf", Stat,
                    compute_group = function(data, scales, n = NULL) {
                      
                      # If n is NULL, use raw values; otherwise interpolate
                      if (is.null(n)) {
                        xvals <- unique(data$x)
                      } else {
                        xvals <- seq(min(data$x), max(data$x), length.out = n)
                      }
                      
                      y <- ecdf(data$x)(xvals)
                      x1 <- max(xvals)
                      y0 <- 0                      
                      data.frame(x = c(xvals, x1), y = c(y0, y))
                    },
                    
                    default_aes = aes(y = ..y..),
                    
                    required_aes = c("x")
)

````

then any of:

```r
ggplot(data=data.frame(x = exp(1:10)), aes(x)) + geom_step(stat="myecdf")
ggplot(data=data.frame(x = exp(1:10)), aes(x)) + stat_myecdf()
```
![image](https://cloud.githubusercontent.com/assets/11998685/12178545/a8db7848-b537-11e5-80cc-195290acef40.png)
