### ISSUE TITLE
scales = "free_y" not working on faceted bar chart

### ISSUE THREAD

**Issue by gregorbj** [hadley/ggplot2#1470]
Following is some test data to be plotted in comparison bar charts of two measures that will each occupy a facet. The scale of one measure (Mixed Use) is 0 to 10 while the other measure (Walking) is 0 to 50. Individual x-axis scales are desired for the facets.

Test_df <- data.frame(Policy = rep(c("A", "B", "C", "D"), 4),
                      Measure = rep(c("Mixed Use", "Walking"), each = 8),
                      PctChg = c(10 * runif(8, 0, 1), 50 * runif(8, 0, 1)),
                      Model = rep(rep(c("RPAT", "RSPM"), each = 4), 2)
                      )

The scales = "free_y" (or "free_x", or "free") don't produce individualized scales

ggplot(data = Test_df, aes(x=Policy, y = PctChg, fill = Model)) + 
  geom_bar(stat = "identity", position=position_dodge()) +
  facet_grid(. ~ Measure, scales = "free") +
  coord_flip() +
  theme_bw() + 
  labs(y = "% Change from Reference") +
  labs(x = "") +
  theme(axis.title = element_text(size = 10))

**Comment by hadley** [comment]
Free scales don't work with `coord_flip()`, unfortunately.
