### ISSUE TITLE
geom_bar fill order not maintained with stat='identity'

### ISSUE THREAD

**Issue by rcavalcante** [hadley/ggplot2#1472]
Before v2.0.0 I ordered the `fill` of `geom_bar()` using the `order` aesthetic in addition to making the column used as `fill` a `factor` with the `levels` ordered as desired, and it worked (even though doing both was probably redundant). However, in `ggplot2` v2.0.0 the `order` aesthetic is deprecated. Now code that used to work produces out of order `fill`s.

Below is code (using `data(mpg)`) and corresponding plots that seem to indicate that ordering the `levels` of the `factor` works in the case of `stat='bin'`, but not in the case of `stat='identity'`. It's worth noting that the legend is correctly ordered, but the fill is not (which, based on Stack Exchange questions pre-v2.0.0, was solved with the `order` aesthetic).

It's entirely possible that I've missed something and that this isn't actually a bug, but I've tried everything I can think of to remedy the misordering of `fill`, and can't figure it out.

The `scale_fill_brewer()` and `theme()` statements are extraneous with respect to the bug, but it made the graphs easier for me to read and to notice the fill was out of order.

```{r}
library(ggplot2)
library(dplyr)
data(mpg)

##############
# Example 1

  # Simple geom_bar with manufacturer on the x with class as fill
  # Ordering is alphabetical by ggplot2 default
  # Everything is fine here
  g = ggplot(mpg, aes(manufacturer))
  g = g + geom_bar(aes(fill = class)) + scale_fill_brewer() + theme(axis.text.x = element_text(angle = 30, hjust = 1))
```

![df_defaults](https://cloud.githubusercontent.com/assets/626455/12122613/2932da48-b3aa-11e5-825f-56ea86529f61.png)

```{r}
##############
# Example 2

  # Change the order of manufacturer to reverse, and class as in the df
  mpg2 = mpg
  mpg2$manufacturer = factor(mpg2$manufacturer, levels = rev(unique(mpg$manufacturer)))
  mpg2$class = factor(mpg2$class, levels = unique(mpg2$class))

  # The plot reflects this change in order
  # Everything is fine here
  g2 = ggplot(mpg2, aes(manufacturer))
  g2 = g2 + geom_bar(aes(fill = class)) + scale_fill_brewer() + theme(axis.text.x = element_text(angle = 30, hjust = 1))

  # Check out the levels of class
  levels(g2$data$class)
```

![df_ordered](https://cloud.githubusercontent.com/assets/626455/12122621/30aefe1e-b3aa-11e5-9ebf-c7135b26c083.png)

```{r}
##############
# Example 3

  # Instead create the same plot based on the tallied data with stat='identity'
  mpg_counts = tally(group_by(mpg, manufacturer, class))
  mpg_counts[['manufacturer']] = factor(mpg_counts[['manufacturer']], levels = rev(unique(mpg_counts[['manufacturer']])))
  mpg_counts[['class']] = factor(mpg_counts[['class']], levels = unique(mpg$class))

  # The plot reflects the change in x-axis order, but *not* fill order
  # although the legend appears to display the correct ordering
  g3 = ggplot(mpg_counts, aes(x = manufacturer, y=n, fill=class))
  g3 = g3 + geom_bar(stat = 'identity') + scale_fill_brewer() + theme(axis.text.x = element_text(angle = 30, hjust = 1))

  # Check out the levels of class
  levels(g3$data$class)
```

![tally_ordered](https://cloud.githubusercontent.com/assets/626455/12122626/38eacf90-b3aa-11e5-95c7-86a43a13d68b.png)

**Comment by hadley** [comment]
Could you please make a more minimal reproducible example by using a toy dataset with just a couple of levels?

**Comment by laoyang945** [comment]
same problem here. with stat='identity', I cannot change the order of 'fill' in geom_bar. Any workarounds?

**Comment by laoyang945** [comment]
so i need to re-order the data to arrange the order in the filling process.

**Comment by cuixueqin** [comment]
Hi @hadley ,

I have the same problem.
Given the following dataset named "dat":
   region  year  value
1  A  2012           11460
2  B  2012            7431
3  C  2012           -8121
4  D  2012           15719
5  E  2012             364
6  A  2011           12211
7  B  2011            6290
8  C  2011           -2657
9  D  2011           14657
10 E  2011            1257
11 A  2010           12895
12 B  2010            5381
13 C  2010           -2408
14 D  2010           11849
15 E  2010             517

I ran the following code:
`dat1 <- subset(dat, value >= 0)
dat2 <- subset(dat, value < 0)
ggplot() + 
  geom_bar(data = dat1, aes(x = year, y = value, fill = region, order = rev(region)), stat = "identity") +
  geom_bar(data = dat2, aes(x = year, y = value, fill = region, order = rev(region)), stat = "identity") +
  scale_fill_brewer(type = "seq", palette = 1)`

[http://i.stack.imgur.com/EMtpn.png](url)

I want to stack regions in a reversed order, but the "order = rev(region) " function doesn't work in ggplot v2.0.0 as it does in previous versions. 

So could you please help to check this? Thanks very much

**Comment by hadley** [comment]
With `stat = "identity"`, the data is not manipulated in any way, so the bars will appear in the order in the original data frame.

**Comment by cuixueqin** [comment]
But if I want to change the order, what should I do?

**Comment by ilarischeinin** [comment]
You can simply reorder the data.frame. And you don't need to modify the original, you can just reorder on-the-fly while piping to ggplot():

```r
my_data %>%
  arrange(some_column) %>%
  ggplot(...)
```

I wrote a little [blog post](http://ilari.scheinin.fi/ggplot-2-0-and-the-missing-order-aesthetic/) about this when I was missing the order aesthetic myself.

**Comment by joranE** [comment]
Would you consider a small pull request adding a note to the docs in `?geom_bar` that describes this behavior and makes it clear that the order of filled segments in a stacked bar chart will not respect the factor level ordering when `stat = "identity"` and instead the respect the order of the data in the data frame?

There's _lots_ SO questions with very high Google juice that are either are old and incorrectly describe the behavior when `stat = "identity"` or handle a case when `stat` is not `"identity"` but make no note of the distinction, which is bound to be confusing. I'll tackle cleaning up the SO questions, but that will take some time so it would be nice for the docs to be explicit about this in the meantime...

**Comment by hadley** [comment]
@joranE can you please file a new issue? It's unlikely I'll remember to re-read this closed issue when I next work on ggplot2.

**Comment by kathy0305** [comment]
Did this problem get solved? 
I arranged my data in desc order and still when I plot geom_bar (stat= "identity") 
the x-axis gets re-arranged in alphabetical order. I want them arranged in the same order in df
Thanks

**Comment by hadley** [comment]
@kathy0305 please send a minimal reproducible example to the ggplot2 mailing list

**Comment by kathy0305** [comment]
Sure I'll do that and I will put one here too:

```{r create a df, warning=FALSE,message=FALSE}
library(tidyverse)
##create a simple data frame
Region <- c("SouthEast","CentralWest","SouthWest","NorthWest","CentralEast","NorthCentral","NorthEast","Central", NA)
Attendance <- c(63448129,60835672,37126096,32870237,29031014,25861016,18620807,16083103,1729)
SimpleDF <- data_frame(Region,Attendance)

```

Lets see what the df looks like
```{r view}
SimpleDF
```

Plot 

```{r plot}

ggplot(SimpleDF,aes(x=Region, y=Attendance))+
        geom_bar(stat ="identity")
```
![Image of plot](https://github.com/kathy0305/Personal-Project/blob/master/Rplot.png)

it re-arranges the order of x values  
How do I maintain the rank/order??   
Thanks

**Comment by alox** [comment]
@kathy0305 I have experienced the same issue. I used the workaround of converting `Region` to a `factor` in the interim.

tibble to plot:

`SimpleDF %>% mutate(Region = factor(Region, levels = Region))`

**Comment by sarahgrogan** [comment]
I'm also having a similar problem, but unfortunately can't create a reproducible toy example, or share the code that's causing the problem. But, might be helpful to document in case it can be better documented in the future. 

This toy example is similar to my real code, except that the toy example works fine. As expected, the bars are filled in-order with the colors in color.list (bars are always red, white, black). 

`
df <- as.data.frame(cbind(c("F", "B", "C", "D", "E", "A"), c(10, 12, 14, 16, 18, 11)))
colnames(df) <- c("Sample", "Value")
keep <- c("A", "B", "C")
keep <- c("C", "B", "A")

df2 <- droplevels.data.frame(subset(df, Sample %in% keep))
df2 <- arrange(df2, Sample)
color.list <- c("red", "white", "black")
ggplot(aes(x=Sample, y=Value), data=df2) + geom_bar(stat="identity", col="black", fill=color.list)

myplot <- function(df, keep, color.list){
     df <- droplevels.data.frame(subset(df, Sample %in% keep))
     ggplot(aes(x=Sample, y=Value), data=df) + geom_bar(stat="identity", col="black", fill=color.list)
}

myplot(df, keep, color.list)
`

In my real work, the subset df always has the same number of rows (e.g., always three rows, which match to three colors in color.list), and the same sample levels. Most of the time the colors are filled correctly (red-white-black); but some of the time the colors are rearranged (white-black-red; or black-red-white).
