### ISSUE TITLE
[FR] Set "stat" in geom_bar() through a global variable

### ISSUE THREAD

**Issue by eibanez** [hadley/ggplot2#1474]
Would it be possible to set a global variable that tells the default value for `stat` in `geom_bar()`? This would make the code less verbose if I only want to provide `y` values (i.e., I don't have to set `stat="identity"` for every single plot).

**Comment by hadley** [comment]
Global variables are a really really really bad idea.

**Comment by hadley** [comment]
Instead do something like `geom_bar2 <- function(...) geom_bar(..., stat = "identity')`

**Comment by eibanez** [comment]
Thanks for the tip!
