### ISSUE TITLE
Issue with element_text()

### ISSUE THREAD

**Issue by pozelei** [hadley/ggplot2#1479]
Hi,
trying to create a new theme. Got this far:
    
      theme_udue <- function(base_size = 12, base_family = "CMU Sans Serif") {
      theme(
        line =               element_line(colour = "black", size = 0.25, linetype = 1,
                                      lineend = "butt"),
        rect =               element_rect(fill = "white", colour = "black", size = 0.5, linetype = 1),
        text =               element_text(family = base_family, face = "plain",
                                      colour = "black", size = base_size,
                                      hjust = 0.5, vjust = 0.5, angle = 0, lineheight = 0.9, margin=0, debug=FALSE),
        axis.text =          element_text(size = rel(0.8), colour = "white"),
        strip.text =         element_text(size = rel(0.8), colour = "white"),
    
        axis.line =          element_blank(),
        axis.text.x =        element_text(),
        ............

The last line throws the following error:

    Error in unit.c(margin[1], unit(1, "grobheight", text_grob), margin[3]) : 
      it is invalid to combine 'unit' objects with other types

Already tried installing the dev verisons of ggplot2 and ggthemes.

**Comment by hadley** [comment]
Can you please provide a minimal reproducible example?

**Comment by pozelei** [comment]
Im sorry. I thought this is a pretty general issue so it should be replicated easily. Here is a RE:  
 
    library(ggplot2)

    x <- data.frame(X = 1:1000, Y = cumsum(rnorm(1000)))

    theme_udue <- function(base_size = 12, base_family = "CMU Sans Serif") {
      theme(
        line =               element_line(colour = "black", size = 0.25, linetype = 1,
                                      lineend = "butt"),
        rect =               element_rect(fill = "white", colour = "black", size = 0.5, linetype = 1),
        text =               element_text(family = base_family, face = "plain",
                                      colour = "black", size = base_size,
                                      hjust = 0.5, vjust = 0.5, angle = 0, lineheight = 0.9, margin=0, debug=FALSE),
        axis.text =          element_text(size = rel(0.8), colour = "white"),
        strip.text =         element_text(size = rel(0.8), colour = "white"),
    
        axis.line =          element_blank(),
        axis.text.x =        element_text(),
        axis.text.y =        element_text(hjust = 1),
        axis.ticks =         element_line(colour = "white", size = 0.2),
        axis.title =         element_text(colour = "white"),
        axis.title.x =       element_text(vjust = 1),
        axis.title.y =       element_text(angle = 90),
        axis.ticks.x =       element_line(colour = "black", size = 0.2),
        axis.ticks.y =       element_line(colour = "black", size = 0.2),
    
        legend.background =  element_rect(colour = NA),
        legend.margin =      unit(0.2, "cm"),
        legend.key =         element_rect(fill = "black", colour = "white"),
        legend.key.size =    unit(1.2, "lines"),
        legend.key.height =  NULL,
        legend.key.width =   NULL,
        legend.text =        element_text(size = rel(0.8), colour = "white"),
        legend.text.align =  NULL,
        legend.title =       element_text(size = rel(0.8), face = "bold", hjust = 0, colour = "white"),
        legend.title.align = NULL,
        legend.position =    "right",
        legend.direction =   "vertical",
        legend.justification = "center",
        legend.box =         NULL,
    
        panel.background =   element_rect(fill = "black", colour = NA),
        panel.border =       element_rect(fill = NA, colour = "white"),
        panel.grid.major =   element_line(colour = "grey20", size = 0.2),
        panel.grid.minor =   element_line(colour = "grey5", size = 0.5),
        panel.margin =       unit(0.25, "lines"),
    
        strip.background =   element_rect(fill = "grey30", colour = "grey10"),
        strip.text.x =       element_text(),
        strip.text.y =       element_text(angle = -90),
    
        plot.background =    element_rect(colour = "black", fill = "black"),
        plot.title =         element_text(size = rel(1.2)),
        plot.margin =        unit(c(1, 1, 0.5, 0.5), "lines"),
        complete = TRUE
      )
    }
    attr(theme_udue(), "complete")

    ggplot(data = x) + geom_line(aes(x=X, y=Y)) + theme_udue()


The line starting with `axis.text.x` is the first where the error occurs.

**Comment by hadley** [comment]
Can you please make a _minimal_ RE. The smaller you can make it, the faster I can find the underlying bug.

**Comment by pozelei** [comment]
Oooook. I'll give my best. I can boil it down to this code chunk. Interestingly, the error disappears if I delete `complete = TRUE`. Also, if I comment out the line `text = ...` I get rid of the error as well.

    library(ggplot2)

    x <- data.frame(X = 1:1000, Y = cumsum(rnorm(1000)))

    theme_udue <- function(base_size = 12, base_family = "CMU Sans Serif") {
      theme(
        text =               element_text(family = base_family, face = "plain", colour = "black", size = base_size,  hjust = 0.5, vjust = 0.5, angle = 0, lineheight = 0.9, margin=0, debug=FALSE),
        axis.line   =        element_blank(),
        axis.text.x =        element_text(),
        complete = TRUE
      )
    }
    attr(theme_udue(), "complete")
    ggplot(data = x) + geom_line(aes(x=X, y=Y)) + theme_udue()

**Comment by hadley** [comment]
Use `margin = margin(0)` - that constructs an object of the correct type.
