### ISSUE TITLE
theme(axis.text = ... causes problems with text overlapping

### ISSUE THREAD

**Issue by shirewoman2** [hadley/ggplot2#1480]
Just updated both R and ggplot2 to versions 3.2.3 and 2.0.0, respectively, and I'm having an issue I haven't seen before. Say G is a ggplot2 object. When you add anything to the axis.text and/or the axis.title using theme(...) it causes spacing issues and the axis text and the axis title text can overlap. In other words, G by itself will be fine, but then

     G + theme(axis.text = element_text(colour = "black"), axis.title.x = element_text(colour = "black"))

has text that is spaced differently and a little too close together, even though nothing has adjusted the text spacing or font size.

**Comment by hadley** [comment]
Can you please provide a reproducible example?

**Comment by shirewoman2** [comment]
Sure. At least on my system, I get different results when I do these two things:
     ThemeOne <- function (base_size = 12, base_family = "") {
      theme_gray(base_size = base_size, base_family = base_family) %+replace% 
            theme(
                  axis.text = element_text(colour = "black"),
                  axis.title.x = element_text(colour = "black"),
                  axis.title.y = element_text(colour = "black", angle=90),
                  panel.background = element_rect(fill="white", color=NA),
                  panel.border = element_rect(color="black", fill=NA),
                  strip.background = element_rect(color=NA, fill="white"),
                  legend.background = element_rect(color=NA, fill=NA),
                  legend.key = element_rect(color=NA, fill=NA)
            )   
}

theme_set(ThemeOne())


myStdCurve <- data.frame(Mass = c(0, 0.1, 0.25, 0.50, 1.00, 2.50, 5.00, 10.00,
                                  10.00, 25.00, 50.00, 100.00, 100.00, 
                                  250.00, 500.00),
                         Signal = c(0.00000000, 0.00000000, 0.02380952, 
                                    0.04236006, 0.06858711, 0.19642857, 
                                    0.35042735, 0.64062500, 0.66830065, 
                                    1.59297218, 3.26132931, 6.47978437, 
                                    6.64285714, 16.15973378, 34.33390411))


G1 <- ggplot(myStdCurve, aes(x = Mass, y = Signal)) +
      geom_point() + 
      xlab("Long title for x axis so it's more obvious that things may be tight") +
      ylab("Long title for y axis so it's more obvious that things may be tight")
G1
ggsave("G1 ThemeOne.jpg", width = 8, height = 8)

ThemeTwo <- function (base_size = 12, base_family = "") {
      theme_gray(base_size = base_size, base_family = base_family) %+replace% 
            theme(
#                   axis.text = element_text(colour = "black"),
#                   axis.title.x = element_text(colour = "black"),
#                   axis.title.y = element_text(colour = "black", angle=90),
                  panel.background = element_rect(fill="white", color=NA),
                  panel.border = element_rect(color="black", fill=NA),
                  strip.background = element_rect(color=NA, fill="white"),
                  legend.background = element_rect(color=NA, fill=NA),
                  legend.key = element_rect(color=NA, fill=NA)
            )   
}

theme_set(ThemeTwo())

G1
ggsave("G1 ThemeTwo.jpg", width = 8, height = 8)

G1 ThemeOne:
![g1 themeone](https://cloud.githubusercontent.com/assets/7586238/12311429/ce1daabc-ba0b-11e5-8916-58537a97b768.jpg)


G1 ThemeTwo:
![g1 themetwo](https://cloud.githubusercontent.com/assets/7586238/12311439/dcbcb838-ba0b-11e5-8d31-2a7c59ff2ad6.jpg)

**Comment by hadley** [comment]
The problem is that the default theme has:

```R
    axis.title.x =       element_text(
                           margin = margin(t = 0.8 * half_line, b = 0.8 * half_line / 2)
                         ),
    axis.title.y =       element_text(
                           angle = 90,
                           margin = margin(r = 0.8 * half_line, l = 0.8 * half_line / 2)
                         ),
```

so you're effectively blowing away the margins. You'll need to set them to something that works for you.

**Comment by shirewoman2** [comment]
Ok. Why did it change with this version of ggplot2? You really don't have to answer that, but this does still seem like a bug to me because the issue with the margins didn't happen with previous versions and because this problem arises without the user specifying anything about the margins. It's nice to see what's happening under the hood, so thank you for explaining it, but this is pretty arcane and is likely to be a problem for other people, too.

An aside: I can't say thank you enough for all your R packages. I use at least one of ggplot2, plyr, dplyr, and stringr in almost every script I write in my research.

**Comment by hadley** [comment]
Basically a combination of hacks made things look ok for the default case, but blew apart if you adjusted the fonts.  Most people don't make their own themes, so I figured it wouldn't affect too many people (plus once you get the idea of margins it gives you much more control)
