### ISSUE TITLE
setting default scale for aesthetics in a new stat_ function

### ISSUE THREAD

**Issue by dnacombo** [hadley/ggplot2#1481]
I created a new `stat_topo()` requiring `x `, `y`, and `val` aesthetics, plotting a simple `geom_raster` of interpolated `val` mapped to `fill`.

    library(ggplot2)
    library(dplyr)
    library(akima)
    
    cpt_grp <- function(data, scales) {
      #interpolate data in 2D
      itrp <- akima::interp(data$x,data$y,data$val,linear=F,extrap=T)
      out <- expand.grid(x=itrp$x, y=itrp$y,KEEP.OUT.ATTRS = F)%>%
        mutate(fill=as.vector(itrp$z))
      # str(out)
      return(out)
    }
      
    StatTopo <- ggproto("StatTopo", Stat,
                        compute_group = cpt_grp,
                        required_aes = c("x","y","val")
    )
    
    stat_topo <- function(mapping = NULL, data = NULL, geom = "raster",
                           position = "identity", na.rm = FALSE, show.legend = NA, 
                           inherit.aes = TRUE, ...) {
      layer(
        stat = StatTopo, data = data, mapping = mapping, geom = geom, 
        position = position, show.legend = show.legend, inherit.aes = inherit.aes,
        params = list(na.rm = na.rm, ...)
      )
    }
    
    set.seed(1)
    nchan <- 30
    d <- data.frame(val = rnorm(nchan), # some random values to be mapped to fill color
             x = 1:nchan*cos(1:nchan), # the x and y position of the points to interpolate
             y = 1:nchan*sin(1:nchan))
    plot(d$x,d$y)
    
    ggplot(d,aes(x=x,y=y,val=val)) +
      stat_topo() +
      geom_point()

When I run this, I get the following error:

    Error: numerical color values must be >= 0, found -1

I understand that this is because somehow the values I pass to the `fill` aesthetic are interpreted as color values. If the `fill` values are all positive it works but the scale is discrete by default.

If I enter this: 

    ggplot(d,aes(x=x,y=y,val=val)) +
      stat_topo() +
      scale_fill_continuous() +
      geom_point()

I get what I wanted: the expected raster with a continuous color scale, as I want the `stat_` to do by default...

A puzzling behavior is the following:

    dd <- cpt_grp(d)
    ggplot(dd,aes(x=x,y=y,fill=fill)) +
        geom_raster()

Which does what I expect, setting a continuous color scale...

So I guess the question is: 
How can I prevent ggplot from setting a discrete scale here, and ideally set a default scale within the call to my new `stat_` function. Can I do this in `setup_params`?

**Comment by has2k1** [comment]
You should do as follows, maybe there is a better name for `z`

```R
cpt_grp <- function(data, scales) {
  #interpolate data in 2D
  itrp <- akima::interp(data$x,data$y,data$val,linear=F,extrap=T)
  out <- expand.grid(x=itrp$x, y=itrp$y,KEEP.OUT.ATTRS = F)%>%
    mutate(z=as.vector(itrp$z))
  # str(out)
  return(out)
}

StatTopo <- ggproto("StatTopo", Stat,
                    compute_group = cpt_grp,
                    required_aes = c("x","y","val"),
                    default_aes = aes(fill = ..z..)
)
```
Tell ggplot that it is a calculated aesthetic and it will pick a scale based on the data type. If you create a `fill` column in the `stat` then you have to make sure it has values that can be interpreted as colours.
To understand what you are doing wrong try this:

```R
ggplot(d,aes(x=x,y=y,val=val)) +  geom_point(fill=d$x)
```
it will fail.

On the otherhand, this

```R
default_aes = aes(fill = ..z..)
```
says, map the computed column `z` onto the `fill` aesthetic and it is comparable to,

```R
ggplot(d,aes(x=x,y=y,val=val)) +  geom_point(aes(fill=x))
```
