### ISSUE TITLE
scale_fill* doesn't see NaN as NA

### ISSUE THREAD

**Issue by cmcoffman** [hadley/ggplot2#1482]
Had some weirdness in my plots and eventually tracked it down. the `<na.value>` parameter in the various scale_fill* scales doesn't recognize `<NaN>` and instead fills them white.

Example:
```R
# four points, top ones are NA and NaN
df <- data.frame(
  x = c(1, 2, 1, 2),
  y = c(1, 1, 2, 2),
  z = c(1, 2, NA, NaN)
)

# ggplot sees top left as NA and colors red,
# but the NaN on top right colors white (which
# is invisible if the background is white)
ggplot(df, aes(x, y)) +
  geom_point(aes(colour = z), size = 50) +
  scale_colour_gradient(na.value = "red")
```
![image](https://cloud.githubusercontent.com/assets/1226866/12231673/eed212b4-b81e-11e5-9f56-ab868689167b.png)

I don't *think* this is the desired behavior.

It's also difficult to debug why this is happening because many R functions will  put `<NaN>` where a user might expect `<NA>`.  For example `<mean(c(NA, NA), na.rm = TRUE)>` returns `<NaN>`. I ran into this when doing some ddply on a large dataset. The problem was difficult to isolate because `<all.equal()>` can't always tell `<NA>` from `<NaN>`:
```R
all.equal(
  a <- mean(c(NA, 10), na.rm = FALSE),
  b <- mean(c(NA, NA), na.rm = TRUE)
)
```
returns `<TRUE>`.

Also, while the View() function in Rgui will show `<NaN>` the View function in R-Studio will replace it with `<NA>`. The `<write.csv()>` function will also convert `<NaN>` to `<NA>`.

**Comment by hadley** [comment]
This is definitely a bug
