### ISSUE TITLE
Colour Aesthetic Causes Unnecessary Blank Page in PDF File

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1490]
If `colour` is not assigned, the PDF has one page, as expected.

    pdf("cars.pdf")
    plot <- ggplot(mtcars, aes(drat, wt, colour = cyl)) + geom_point()
    grob <- ggplotGrob(plot)
    plot(1:10)
    dev.off()

**Comment by hadley** [comment]
@pmur002 any thoughts on how to track this down? Presumably something in the legend code needs an active graphics device. Is there a hook I can use?

**Comment by pmur002** [comment]
I tracked this down using gdb (break on GEcurrentDevice and then track 
back up the call stack).

Looks like ggplotGrob() is calling convertWidth() (at least) to 
determine sizes of things and that triggers 'grid' initialisation (as 
the first grid activity on the device), which triggers the new page.

But I think the bigger issue here is that the code example is a mix of 
'grid' and 'graphics' drawing.  This is always fraught and one general 
rule if you are doing this sort of thing is always to start with a 
'graphics' plot and then add 'grid' output.  For example, here are some 
variations that work ok ...

# Remove colour aesthetic (remove legend creation)
pdf("cars-ok.pdf")
plot <- ggplot(mtcars, aes(drat, wt)) + geom_point()
grob <- ggplotGrob(plot)
plot(1:10)
dev.off()

# Remove ggplotGrob()
pdf("cars-ok-too.pdf")
plot <- ggplot(mtcars, aes(drat, wt, colour = cyl)) + geom_point()
plot(1:10)
dev.off()

# Put ggplotGrob() call AFTER plot() call
pdf("cars-ok-three.pdf")
plot <- ggplot(mtcars, aes(drat, wt, colour = cyl)) + geom_point()
plot(1:10)
grob <- ggplotGrob(plot)
dev.off()

Hope that helps.

Paul

On 26/01/16 05:33, Hadley Wickham wrote:
> @pmur002 <https://github.com/pmur002> any thoughts on how to track this
> down? Presumably something in the legend code needs an active graphics
> device. Is there a hook I can use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/ggplot2/issues/1490#issuecomment-174570710>.
>

-- 
Dr Paul Murrell
Department of Statistics
The University of Auckland
Private Bag 92019
Auckland
New Zealand
64 9 3737599 x85392
paul@stat.auckland.ac.nz
http://www.stat.auckland.ac.nz/~paul/

**Comment by hadley** [comment]
Thanks @pmur002!  I'm going to close for now since it seems like a general problem with mixing grid and base graphics.

**Comment by DarioS** [comment]
I doubt it is caused by a mix of graphics frameworks. Consider deleting the line `plot(1:10)` from the example. If the colour is present, the PDF has 1 page, if not, it has 0 pages. `ggplotGrob` adds a new page, if the plot has colour, which I think is unintended and undocumented.
