### ISSUE TITLE
theme_classic Causes Strange Appearance of Facet Grid

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1491]
The lack of x-axis and y-axis lines, except for the panels at the bottom and on the left, makes the plot difficult to interpret.

    theme_set(theme_classic())
    ggplot(mtcars, aes(mpg, wt)) + geom_point() + facet_grid(carb ~ cyl)

Perhaps it should be more like `theme_bw` ?

**Comment by hadley** [comment]
I'd be happy to review a PR.
