### ISSUE TITLE
Hook in Stat to modify data after scales has been applied

### ISSUE THREAD

**Issue by thomasp85** [hadley/ggplot2#1493]
For some of the geoms/stats I'm developing I'm missing a way to intercept data after scales has been applied but before they are passed to `draw_layer`. Kind of like `Geom$setup_data` but attached to `Stat` and called after

```r
if (npscales$n() > 0) {
    lapply(data, scales_train_df, scales = npscales)
    data <- lapply(data, scales_map_df, scales = npscales)
}
```

in `ggplot_build`

If you're willing to have this hook in ggplot2 I'll se to it that it gets implemented...

**Comment by has2k1** [comment]
Out of curiosity, what kind of modifications do you want to do at that point?

**Comment by thomasp85** [comment]
My personal use case is the geom_link2 implementation in [ggforce](https://github.com/thomasp85/ggforce). It works now by modifying GeomPath to interpolate size and colour after scales have been applied, but this should be the work of a Stat (in my view). Currently the Stat can't do anything to the data after scales have been applied.

It works now but I feel that it is wonky...

**Comment by hadley** [comment]
@thomasp85 this seems reasonable to me. Do you want to have a go at a PR? Documenting how this works will be the hard part.

**Comment by thomasp85** [comment]
I'll make a PR. My general line of thought is to add a finish_data method to the Stat base class that gets called as one of the last things in ggplot_build. The default will be to just return the data unmodified so it's up to adventurous developers (me) to use it for anything...
