### ISSUE TITLE
ggplot2 0.9.3.1 does not allow to put a mean line to each group

### ISSUE THREAD

**Issue by Mcb91** [hadley/ggplot2#1504]
Hi everyone,

Before actualizing ggplot2, to design a mean line for each group i just needed to put:

geom_errorbar(stat="hline",yintercept="mean",width=0.8,aes(ymax=..y..,ymin=..y..)) 

Now, I already try:

stat_summary(fun.y = "mean", geom="line") 

and it doesn't work. If I change the geom to "point", "bar" or "errorbar", it works but not with line. 

If I use the geom_hline function, it is impossible to work unless I calcul the means of each group before which is not what I want to do. I would like ggplot to compute itselfs the means, as it was doing before...

**Comment by hadley** [comment]
Yeah, you'll need to use dplyr or similar to compute the means yourself.
