### ISSUE TITLE
Inheritance of Theme Elements Fails

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1505]
Although `axis.text` inherits from `text`, it is not updated.

    Q <- qplot(1:10, rnorm(10), colour = runif(10)) + theme(axis.text = element_text(size = 10))
    Q + theme(text = element_text(size = 20)) # Should make all text elements be size 20.

The axis titles are increased in size, but not the axis text.

**Comment by hadley** [comment]
Because you've specifically requested size 10. Maybe you want:

```R
qplot(1:10, rnorm(10), colour = runif(10)) + 
  theme(axis.text = element_text(size = rel(0.8))) + 
  theme(text = element_text(size = 20))
```

**Comment by DarioS** [comment]
I found that if I increase the font, the axis text and title do both increase, but the axis text is always smaller than the axes titles. Why doesn't 

    qplot(1:10, rnorm(10), colour = runif(10)) + theme(text = element_text(size = 20))

cause the axis titles and axis text to be the same size but

    qplot(1:10, rnorm(10), colour = runif(10)) + theme(axis.text = element_text(size = rel(1)), text = element_text(size = 20))

does ? `axis.text` is a subclass of `text` so it should inherit its properties. That's the impression I get from the documentation of `theme`, which states "All text elements inherit directly or indirectly from `text`".

**Comment by hadley** [comment]
Because the default is to make the axes text slightly smaller than the main text (i.e. `rel(0.8)`)
