### ISSUE TITLE
Boxplot Outlier Colour Contradicts Documentation

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1506]
The documentation has in the Examples section :  

    # By default, outlier points match the colour of the box. Use
    # outlier.colour to override

However,

    ggplot(mpg, aes(x = class, y = hwy, fill = class)) + geom_boxplot()

shows otherwise.

**Comment by hadley** [comment]
They do match the "colour" in the ggplot2 sense; they don't match the fill.
