### ISSUE TITLE
geom(outlier.size = 0.1) does not reduce point size

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1507]
Setting `outlier.size` to a different value has no effect

    mileage <- ggplot(mpg, aes(x = class, y = hwy)) + geom_boxplot()
    mileage
    mileage + geom_boxplot(outlier.size = 0.1)

But it works for `lwd`

    mileage + geom_boxplot(lwd = 0.1)

Also, why doesn't `outlier.size = 0` hide outliers from the plot ? Setting `lwd` to 0 removes most box lines, although some are left behind, causing an ugly plot.

    mileage + geom_boxplot(lwd = 0)

**Comment by hadley** [comment]
You can't see the difference because you're doing:

```R
ggplot(mpg, aes(x = class, y = hwy)) + 
  geom_boxplot() + 
  geom_boxplot(outlier.size = 0.1)
```
