### ISSUE TITLE
Examples using geom_smooth(), particularly method.args...

### ISSUE THREAD

**Issue by brennanpincardiff** [hadley/ggplot2#1510]
Hello, 
    Further to feedback and an email, I have included below some code that has the potential to be used as examples for geom_smooth() particularly using method.args. 
    If useful that's great. If you want me to change or develop these I could do that - suggestions welcome. 
Best wishes, 
Paul

```
library(ggplot2)

# example of plotting tranforming data within the aesthetics
# and using geom_smooth with lm method. 
ggplot(msleep, aes(log(brainwt), log(bodywt))) +
  geom_point(na.rm = TRUE) +
  geom_smooth(method="lm")


# example of plot from the msleep dataset 
ggplot(msleep, aes(sleep_rem, sleep_total)) +
  geom_point()

# draw plot with geom_smooth defaults
# because h n < 1000 default smoothing method is loess.
ggplot(msleep, aes(sleep_rem, sleep_total)) +
  geom_point() +
  geom_smooth()
# line is feasable but doesn't make a huge amount of sense. 

# we can try applying the linear model (lm) method
ggplot(msleep, aes(sleep_rem, sleep_total)) +
  geom_point() +
  geom_smooth(method = "lm")
# it works but it's not a great fit...

# check a non linear least squares method (nls)
# note the use of the method.args
ggplot(msleep, aes(sleep_rem, sleep_total)) +
  geom_point() +
  geom_smooth(method = "nls", 
              se = FALSE, 
              method.args = list(formula = y ~ sleepMax * x / (halfREM + x), 
                                start = list(sleepMax = 22, halfREM = 1.5)))


# extended example using data from enzymes

# the data (from Dr C Bennett, University of Bath, http://www.jbc.org/content/285/44/33701.full)
enz <- c("WT","WT","WT","WT","WT","WT","WT","WT","WT","WT", "WT","WT","WT",
         "mutant","mutant","mutant","mutant","mutant","mutant", "mutant","mutant")
substrateConc <- c(2.00, 1.00, 0.60, 0.50, 0.40, 0.30, 0.20, 0.10, 0.09, 0.08, 0.06, 0.04, 0.02, 
         0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 1.00, 2.00)
velocity <- c(59.01, 58.29, 54.17, 51.82, 49.76, 45.15, 36.88, 26.10, 23.50, 22.26, 
         16.45, 13.67, 6.14, 11.8, 19.9, 30.3, 36.6, 40.2, 42.1, 47.8, 50.0)

# assemble the data into a data.frame
enzdata <- data.frame(enz, substrateConc, velocity)

# first simple plot with just the points
ggplot(data=enzdata,        
       aes(x=substrateConc,            
           y=velocity,            
       colour = enz)) +  
       geom_point()             

# add the lines with geom_smooth, nls method and method.args
ggplot(data=enzdata,        
       aes(x=substrateConc,            
           y=velocity,            
           colour = enz)) +  
  geom_point() +
  geom_smooth(method = "nls",
              se = FALSE,
              size = 0.5,
              method.args = list(formula = y ~ Vmax * x / (Km + x), 
                                start = list(Vmax = 50, Km = 0.2)))

# add facet_wrap to create two graphs if you prefer...
ggplot(data=enzdata,        
       aes(x=substrateConc,            
           y=velocity,            
           colour = enz)) +  
  geom_point() +
  facet_wrap(~enz) + 
  geom_smooth(method = "nls",
              se = FALSE,
              size = 0.5,
              method.args = list(formula = y ~ Vmax * x / (Km + x), 
                                 start = list(Vmax = 50, Km = 0.2))) 
```

**Comment by hadley** [comment]
I think it's worth include maybe including two more simple examples with `method.args` but I think it would be better to build off the existing examples. I'd be happy to review a PR.

**Comment by Darwinita** [comment]
Hi,
I have a dataframe similar to yours, with two columns of data and a third column with a factor.  I'm trying to fit a MM curve to my data using geom_smooth(method = "nls"... and the following code:

`ggplot(subFunctable5noNA, aes(x = , y = v, color=TopvsBottom)) +
  ggtitle("Michaelis-Menten kinetics") +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "nls", 
                        formula = v ~ Vmax * S/(Km+dS), 
                        start = list(Km = Km, Vmax = Vmax),
                        se = F, size = 0.5, 
                        data = subset(subFunctable5noNA, TopvsBottom=="top")) +
  geom_smooth(method = "nls", 
                        formula = v ~ Vmax * dS/(Km+dS), 
                        start = list(Km = Km, Vmax = Vmax),
                        se = F, size = 0.5, 
                        data = subset(subFunctable5noNA, TopvsBottom=="bottom"))`

The plot with the points is just fine, but I get the following error message at the end.

**Error: Unknown parameters: start**

I also tried this other code inserting the formula and the start data as method.args:

`ggplot(subFunctable5noNA, aes(x = dS, y = v, color=TopvsBottom)) +
  ggtitle("Michaelis-Menten kinetics") +
  geom_point(alpha = 0.5) + 
  geom_smooth(method = "nls", 
                        se = F, size = 0.5,
                        method.args = list(formula = v ~ Vmax * dS/(Km+dS),start = list(Km = Km, Vmax = Vmax)),
                        data = subset(subFunctable5noNA, TopvsBottom=="top")) +
  geom_smooth(method = "nls", 
                        se = F, size = 0.5,
                        method.args = list(formula = v ~ Vmax * dS/(Km+dS),start = list(Km = Km, Vmax = Vmax)),
                        data = subset(subFunctable5noNA, TopvsBottom=="bottom"))`

Againg the plot of the data points looks just fine, but the geom_smooth lines won't plot, returning instead the following error message:
Warning messages:
**1: Computation failed in `stat_smooth()`:
parameters without starting value in 'data': Cornet_corr, dS 
2: Computation failed in `stat_smooth()`:
parameters without starting value in 'data': Cornet_corr, dS **

Also, I tried your code and it worked, so there shouldn't be any version compatibility. Please, see below the session info.
Any ideas?
Best
___________________________________________________________________________________

sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gridExtra_2.2.1 ggplot2_2.1.0  

loaded via a namespace (and not attached):
 [1] labeling_0.3         colorspace_1.2-6     scales_0.4.0         Matrix_1.2-4         plyr_1.8.3           tools_3.2.4         
 [7] gtable_0.2.0         scatterplot3d_0.3-36 Rcpp_0.12.3          grid_3.2.4           knitr_1.12.3         digest_0.6.9        
[13] munsell_0.4.3        lattice_0.20-33

**Comment by brennanpincardiff** [comment]
Hi, 
    Second piece of code with method.args is correct for this version of ggplot2. 
    I can't really troubleshoot the rest of the plot without the data, I'm afraid. 
    Might be worth simplifying your data rather than having to identify the data in the geom_smooth( ) function. 
    Is it possible that your data doesn't fit a standard Michaelis-Menten curve? Could your enzymology be more complex? Does your code work with my data frame?
     I have a little more detail on this above enzymology script here: http://rforbiochemists.blogspot.co.uk/2015/06/plotting-two-enzyme-plots-with-ggplot.html
     Best wishes, 
Paul

**Comment by Darwinita** [comment]
Thanks for your answer Paul, It worked after simplifying the data as you suggested (formula = y ~ Vmax * x/(Km+x)). However, I'm afraid my data does not fit well a M&M curve. Actually, it's not from an enzimology. Cheers, Lorenzo
