### ISSUE TITLE
Stat issue

### ISSUE THREAD

**Issue by GuangchuangYu** [hadley/ggplot2#1512]
I create a [`Stat`](https://github.com/GuangchuangYu/ggtree/blob/master/R/geom_tree.R#L80-L104) object in [ggtree](https://github.com/GuangchuangYu/ggtree):

```r
StatTreeHorizontal <- ggproto("StatTreeHorizontal", Stat,
                              required_aes = c("node", "parent", "x", "y"),
                              compute_panel = function(self, data, scales, params, layout, lineend) {
                                  .fun <- function(data) {
                                      df <- setup_tree_data(data)
                                      x <- df$x
                                      y <- df$y
                                      parent <- df$parent
                                      df$xend <- x
                                      df$yend <- y
                                      df$x <- x[parent]
                                      ii <- is.na(x)
                                      df$x[ii] <- NA
                                      return(df)
                                  }
                                  
                                  if ('.id' %in% names(data)) {
                                      ldf <- split(data, data$.id)
                                      df <- do.call(rbind, lapply(ldf, .fun))
                                  } else {
                                      df <- .fun(data)
                                  }
                                  return(df)
                              }
                              )
```

I use the following data.frame, __df2__, to test the `Stat`.

| node| parent| branch.length|  x|         y|label |isTip | branch|       angle|
|----:|------:|-------------:|--:|---------:|:-----|:-----|------:|-----------:|
|    1|     20|             4| 48| 10.000000|A     |TRUE  |   46.0| -242.307692|
|    2|     20|             4| 48| 11.000000|B     |TRUE  |   46.0| -270.000000|
|    3|     19|             5| 43|  9.000000|C     |TRUE  |   40.5| -214.615385|
|    4|     18|             6| 36|  8.000000|D     |TRUE  |   33.0| -186.923077|
|    5|     17|            21| 48|  7.000000|E     |TRUE  |   37.5| -159.230769|
|    6|     22|             4| NA|        NA|F     |TRUE  |    0.0| -103.846154|
|    7|     22|            12| NA|        NA|G     |TRUE  |    0.0| -131.538462|
|    8|     21|             8| NA|        NA|H     |TRUE  |    0.0|  -76.153846|
|    9|     24|             5| 56|  2.000000|I     |TRUE  |   53.5|   48.461539|
|   10|     24|             2| 53|  3.000000|J     |TRUE  |   52.0|   20.769231|
|   11|     25|            11| 34|  4.000000|K     |TRUE  |   28.5|  -20.769231|
|   12|     25|            11| 34|  5.000000|L     |TRUE  |   28.5|  -48.461539|
|   13|     14|            56| 56|  1.000000|M     |TRUE  |   28.0|   62.307692|
|   14|     14|             0|  0|  3.117188|NA    |FALSE |    0.0|    6.923077|
|   15|     14|             4|  4|  5.234375|NA    |FALSE |    2.0|  -62.307692|
|   16|     15|            13| 17|  6.968750|NA    |FALSE |   10.5| -145.384615|
|   17|     16|            10| 27|  7.937500|NA    |FALSE |   22.0| -173.076923|
|   18|     17|             3| 30|  8.875000|NA    |FALSE |   28.5| -200.769231|
|   19|     18|             8| 38|  9.750000|NA    |FALSE |   34.0| -228.461538|
|   20|     19|             6| 44| 10.500000|NA    |FALSE |   41.0| -256.153846|
|   21|     16|            13| 30|  6.000000|NA    |TRUE  |   23.5|  -90.000000|
|   22|     21|            14| NA|        NA|NA    |FALSE |    0.0| -117.692308|
|   23|     15|            17| 21|  3.500000|NA    |FALSE |   12.5|   -6.923077|
|   24|     23|            30| 51|  2.500000|NA    |FALSE |   36.0|   34.615385|
|   25|     23|             2| 23|  4.500000|NA    |FALSE |   22.0|  -34.615385|

`compute_panel` do the right thing:
```r
StatTreeHorizontal=ggtree:::StatTreeHorizontal
df3 <- StatTreeHorizontal$compute_panel(df2)
ggplot() + geom_segment(df3, mapping=aes(x, y, xend=xend, yend=yend))
```
![unnamed-chunk-1-2](https://cloud.githubusercontent.com/assets/626539/12544171/50d6dcb6-c372-11e5-9550-cc0fda108f9f.png)

But if I use it in layer, the output is wrong.
```r
ggplot(df2) + layer(stat=StatTreeHorizontal, geom='segment', position='identity', params=list(na.rm=F), mapping=aes(x, y, node=node, parent=parent))
```
![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/626539/12544168/4a7d62fe-c372-11e5-9157-52ce012fa378.png)

Any idea?

**Comment by GuangchuangYu** [comment]
[df2.rda.zip](https://github.com/hadley/ggplot2/files/102849/df2.rda.zip)

I upload the `df2` for testing. Thanks!

**Comment by thomasp85** [comment]
What happens if you replicate the exact call that happens in geom_segment? After all, geom_segment is just a wrapper around layer, so try gradually changing the layer call in geom_segment into the one that creates a wrong output and see where it messes up...

**Comment by has2k1** [comment]
One mistake you are making is in mapping to `xend` and `yend`. You should map to 
`..xend..` and `..yend..`.

**Comment by GuangchuangYu** [comment]
@has2k1 
```
> ggplot() + geom_segment(df3, mapping=aes(x, y, xend=xend, yend=yend))
Warning message:
Removed 4 rows containing missing values (geom_segment).
> ggplot() + geom_segment(df3, mapping=aes(x, y, xend=..xend.., yend=..yend..))
Error in eval(expr, envir, enclos) : object 'xend' not found
```

**Comment by GuangchuangYu** [comment]
@thomasp85 

The geom_segment layer can be reproduce using

```r
ggplot() + layer(data=df3, stat='identity', geom=GeomSegment, position='identity', 
   params=list(na.rm=T), 
   mapping=aes(x, y, xend=xend, yend=yend))
```
and it do output the correct graph.

The only thing I change is using `df2`, `stat=StatTreeHorizontal` and aes mapping (node and parent for deriving xend and yend from x and y needed by StatTreeHorizontal).

```r
ggplot() + layer(data=df3, stat=StatTreeHorizontal, geom=GeomSegment, position='identity', 
   params=list(na.rm=T), 
   mapping=aes(x, y, node=node, parent=parent))
```

**Comment by has2k1** [comment]
Sorry. I misunderstood how you were testing. Now looking at it, it should not be a problem. Do some debugging, insert a print statement(s) and verify what comes in and what comes out. Unfortunately you cannot put break points in `ggproto`. May be temporarily put the code into a function where you can put break points.

**Comment by GuangchuangYu** [comment]
@has2k1 What do you mean for `break points`? Sorry I can't understand that.

**Comment by GuangchuangYu** [comment]
I have got some idea. 

```r
StatTreeHorizontal <- ggproto("StatTreeHorizontal", Stat,
                              required_aes = c("node", "parent", "x", "y"),
                              compute_panel = function(self, data, scales, params, layout, lineend) {
                                  .fun <- function(data) {
                                  	print(nrow(data))
                                      df <- setup_tree_data(data)
                                      x <- df$x
                                      y <- df$y
                                      parent <- df$parent
                                      df$xend <- x
                                      df$yend <- y
                                      df$x <- x[parent]
                                      ii <- is.na(x)
                                      df$x[ii] <- NA
                                      print(nrow(df))
                                      return(df)
                                  }
                                  
                                  if ('.id' %in% names(data)) {
                                      ldf <- split(data, data$.id)
                                      df <- do.call(rbind, lapply(ldf, .fun))
                                  } else {
                                      df <- .fun(data)
                                  }
                                  #print(df)
                                  return(df)
                              }
                              )


ggplot() + layer(data=df2, stat=StatTreeHorizontal, geom=GeomSegment, position='identity', 
   params=list(na.rm=F), 
   mapping=aes(x, y, node=node, parent=parent))
```

It ouput:
```
[1] 21
[1] 21
```

The df2 data frame has 25 rows, but when passing it to compute_panel, it only contains 21 (NA was removed even I passed `params=list(na.rm=F)`.

So that the `x[parent]` subsetting was wrong and then output the wrong graph.

The question is how to pass the whole dataset to `compute_panel`?

**Comment by thomasp85** [comment]
na.rm only governs whether NA rows should be removed silently or with a warning. Why do you have NA values in x and y in your dataset? To take full control over how NA is handled, override the handle_na method in stat...

Keep in mind that your stat object does not get the full unmodified dataset handed to it as you do when you call `StatTreeHorizontal$compute_panel()`. All sorts of stuff have been done to it in advance...

**Comment by GuangchuangYu** [comment]
na value happened when collapsing clade.

I add the following code in `StatTreeHorizontal`

```
                              handle_na = function(data, params) {
								data
  							  },
```

But NA was still removed when passing to `compute_panel` .

**Comment by thomasp85** [comment]
My bad - handle_na is a Geom method. Sorry about that...

**Comment by thomasp85** [comment]
You need to override compute_layer in your Stat object and remove the `remove_missing` call that is there by default...

**Comment by GuangchuangYu** [comment]
thanks @thomasp85, it works after remove the `removing_missing` in `compute_layer`.

I also work out another way by considering this issue in `compute_layer`.
