### ISSUE TITLE
New scale_color_gradient no trans parameter

### ISSUE THREAD

**Issue by nlhuong** [hadley/ggplot2#1517]
The new version of ggplot2, 2.0.0 does not seem to support the trans parameter that was very useful in the old versions 0.8.3. Is there a way to simply get the same results as

scale_color_gradient(trans = "log10")

used to produce?

**Comment by hadley** [comment]
Can you please provide a reproducible example? It should still work

**Comment by nlhuong** [comment]
Thanks, I checked and it seems to still work. Probably the error was elsewhere previously.
