### ISSUE TITLE
AsIs aesthetics

### ISSUE THREAD

**Issue by schloerke** [hadley/ggplot2#1518]
I'm trying to use aesthetics with the AsIs function to use values as they are.

```{r}
library(ggplot2)

ggplot(data = iris, aes(Sepal.Length, Sepal.Width)) + geom_point(aes(size = I(5)))
# Error in data.frame(size = 5, PANEL = c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L,  : 
  arguments imply differing number of rows: 1, 150
```

```{r}
# thought process... produces error.  ok, I can make it longer.  trying again.
ggplot(data = iris, aes(Sepal.Length, Sepal.Width)) + geom_point(aes(size = I(rep(5, nrow(iris)))))
```
![screenshot 2016-01-25 14 20 15](https://cloud.githubusercontent.com/assets/93231/12561539/c8662ec0-c36e-11e5-8eaf-d383ac9ccd47.png)

This produces a plot that is treated as a true value, rather than AsIs.

How can I make something a 'parameter' through the use of aes()? 

- Barret

**Comment by hadley** [comment]
You can't, unless you use ggvis.   

You have to either move it outside of the `aes()` or use `scale_size_identity()`

**Comment by hadley** [comment]
Oh hmm, I made it work because it turned out to be easy
