### ISSUE TITLE
median_hilow broken in stat_summary examples

### ISSUE THREAD

**Issue by smouksassi** [hadley/ggplot2#1520]
many examples involving hmisc functions just does not work as is:
http://docs.ggplot2.org/current/stat_summary.html 
It is not clear whether support for hmisc functions is still planned if yes we need a fix.

**Comment by hadley** [comment]
Already fixed in dev: http://docs.ggplot2.org/dev/stat_summary.html

**Comment by smouksassi** [comment]
there is something weird happening with the median line
loaded the dev version

require(nlme)# for Oxboys
require(ggplot2)

stat_sum_df <- function(fun, geom="smooth", ...) {
  stat_summary(fun.data=fun,  geom=geom,  ...)
}

# this gives correct median line
ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
    stat_summary( fun.y = "median", geom = "line",size=3,col="red")

# this gives wrong median line ordering probelm ? used to work fine before 2.0
ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
  stat_sum_df("median_hilow",geom = "smooth",col="red",fill="red",alpha=0.1,size=2)









R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nlme_3.1-122       dplyr_0.4.3        ggplot2_2.0.0.9001 devtools_1.9.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3         RColorBrewer_1.1-2  plyr_1.8.3          tools_3.2.3        
 [5] rpart_4.1-10        digest_0.6.9        memoise_0.2.1       gtable_0.1.2       
 [9] lattice_0.20-33     DBI_0.3.1           curl_0.9.4          parallel_3.2.3     
[13] proto_0.3-10        gridExtra_2.0.0     httr_1.0.0          stringr_1.0.0      
[17] knitr_1.12.3        cluster_2.0.3       grid_3.2.3          nnet_7.3-11        
[21] R6_2.1.1            survival_2.38-3     foreign_0.8-66      latticeExtra_0.6-26
[25] Formula_1.2-1       reshape2_1.4.1      magrittr_1.5        Hmisc_3.17-0       
[29] scales_0.3.0.9000   splines_3.2.3       assertthat_0.1      colorspace_1.2-6   
[33] labeling_0.3        stringi_1.0-1       acepack_1.3-3.3     lazyeval_0.1.10    
[37] munsell_0.4.2

**Comment by hadley** [comment]
Can you please create a reproducible example that I can easily copy and paste into R?

**Comment by hadley** [comment]
Also, please don't provide `sessionInfo()` unless explicitly asked - it just clutters the display.

**Comment by smouksassi** [comment]
library(devtools)
dev_mode(TRUE)
library(ggplot2)
require(nlme)# for data Theoph  Oxboys

stat_sum_df <- function(fun, geom="smooth", ...) {
  stat_summary(fun.data=fun,  geom=geom,  ...)
}




ggplot(Theoph ,aes(Time,conc))+
  geom_line(aes(group=Subject) ) +
  geom_smooth(se=F,size=2)

ggplot(Theoph ,aes(Time,conc))+
  stat_sum_df("mean_cl_boot")

ggplot(Oxboys ,aes(age,height))+
    stat_sum_df("median_hilow",geom = "smooth",fill="red")


ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
    stat_summary( fun.y = "median", geom = "line",size=3,col="red")


ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
  stat_sum_df("median_hilow",geom =
"smooth",col="red",fill="red",alpha=0.1,size=2)

Oxboys$heightmed <-
cut(Oxboys$height,c(0,median(Oxboys$height),max(Oxboys$height)))

ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
  stat_sum_df("median_hilow",geom = "smooth",alpha=0.1,size=2,
              mapping = aes(col=heightmed,fill=heightmed))


ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
  stat_sum_df("median_hilow",geom = "smooth",alpha=0.1,size=2,
              mapping = aes(col=heightmed,group=heightmed,fill=heightmed))

**Comment by hadley** [comment]
Could you please make your example more minimal, and use ```` ```R ```` to make an R code block?

**Comment by smouksassi** [comment]
```R
library(ggplot2)
require(nlme)# for data Theoph  Oxboys

stat_sum_df <- function(fun, geom="smooth", ...) {
  stat_summary(fun.data=fun,  geom=geom,  ...)
}
ggplot(Oxboys ,aes(round(age,1),height))+
  geom_line(aes(group=Subject))+
  geom_point()+
  stat_sum_df("median_hilow",geom =
"smooth",col="red",fill="red",alpha=0.1,size=2)

**Comment by hadley** [comment]
That works fine for me with the latest ggplot2 and Hmisc.

**Comment by smouksassi** [comment]
This is what I get with ggplot2_2.0.0.9001 and Hmisc_3.17-1
The median line is wrong what should I load to get the right results ?

![rplot](https://cloud.githubusercontent.com/assets/5131281/12616766/b856969c-c4da-11e5-95d4-45a4fb7e4517.png)

what is expected is like this:

![rplot02](https://cloud.githubusercontent.com/assets/5131281/12617021/d55ae544-c4db-11e5-8a06-3d9b02002bfa.png)

**Comment by hadley** [comment]
Ok, now I see what you're talking about. This is why making the most minimal possible example is helpful.

**Comment by smouksassi** [comment]
Hi Hadley many thanks for the  fast response and fix. Thank you for making R awesome.
