### ISSUE TITLE
Text labels too close to geoms after adjusting with `vjust`

### ISSUE THREAD

**Issue by sjPlot** [hadley/ggplot2#1521]
When using text labels to label geoms, they are very close at the geoms, even (or: especially) when vertically adjusting.

    dummy <- data.frame(table(ChickWeight$Time))
    ggplot(dummy, aes(x = Var1, y = Freq, label = Freq)) + 
      geom_bar(stat = "identity") + 
      scale_x_discrete() + geom_text(vjust = "bottom")

![rplot](https://cloud.githubusercontent.com/assets/4901179/12576643/8074ea78-c415-11e5-8191-c6944e3284e7.png)

Especially when using percentage values or braces, parts of the labels are inside the geoms. I would prefer a small distance from labels to geoms as default when vertically / horizontally adjusting the label position.

**Comment by sjPlot** [comment]
This is even more problematic with dodged bars, because you then would have to use `position_dodge` for text labels and `position_nudge` for slight vertical adjustments - this combination cannot be done yet?

**Comment by hadley** [comment]
Use `nudge_y` for the first problem.  For the second, you can just manually add a little offset to the y position.

**Comment by sjPlot** [comment]
Yes, I could (and will) do some workarounds - but this is not what I would expect as default behaviour from a package dedicated to make plots. :-)
