### ISSUE TITLE
breaking change: alpha now impacts the line of stat_ based geoms.

### ISSUE THREAD

**Issue by antoine-lizee** [hadley/ggplot2#1523]
This has changed following #1371, and I think (personally) that this is the wrong decision. 
Pros: it's slightly more 'natural' to have alpha impacting both the line and fill (?)
Cons: the line texture is modified by the alpha parameter in a way that is irreversible, and thus you need a different geom for the common use case (to me) of having a solid line with a transparent filling.
Here is an example:
```
ggplot(diamonds %>% filter(cut %in% c("Very Good", "Ideal")), aes(x = price, fill = cut)) + theme_bw() + 
  geom_histogram(binwidth = 1000) +
  geom_density(aes(x = price, y = ..count.. * 1000), color = "NA", alpha = 0.3) +
  geom_density(aes(x = price, y = ..count.. * 1000), color = "black", fill = NA) +
  facet_grid(cut ~ ., scales = "free_y", space = "free_y")
```
I would vote for reverting this behavior, as I'm pretty sure it's breaking more graphing code now than it would if reverted for 2.1.

The downside of the old behavior is that you need to change the color directly if you want something lighter.

**Comment by antoine-lizee** [comment]
A solve-it-all solution would be to have two different `alpha` parameters?

**Comment by joanwa** [comment]
yes, please either revert or two different alpha parameters. This change broke many of my graphs...

**Comment by antoine-lizee** [comment]
Thanks!

**Comment by yutannihilation** [comment]
I'm sorry for those who suffered with the change I proposed :sob:
Hope someday some great person will discover some great solution which has more easier `alpha` semantics both for beginners and those who already got used to ggplot2....

**Comment by dhimmel** [comment]
+1 for separate parameters for `line_alpha` and `fill_alpha` (or just `alpha` as it is currently).

**Comment by antoine-lizee** [comment]
To answer requests from @dhimmel and others that needs lines representing densities *with alpha*, `geom_density` is the wrong tool as it is designed to mainly show an area. To get a line, use directly `stat_density(geom = "line", alpha = 0.1, ...)`:
```
ggplot(diamonds %>% filter(cut %in% c("Very Good", "Ideal")), aes(x = price, fill = cut)) + theme_bw() + 
  geom_histogram(binwidth = 1000) +
  stat_density(aes(x = price, y = ..count.. * 1000), geom = "line", color = "black", alpha = 0.3) +
  facet_grid(cut ~ ., scales = "free_y", space = "free_y")
```

**Comment by dhimmel** [comment]
@antoine-lizee thanks for the [workaround](#issuecomment-212530398). I had to add `position='identity'` in `ggplot2::stat_density` so the distributions were not stacked.
