### ISSUE TITLE
Changing height of strip text background in ggplot2 does not work as expected

### ISSUE THREAD

**Issue by shekeine** [hadley/ggplot2#1525]
When trying to adjust the height of the strip text background, the additional space seems to be distributed above and below the strip text background instead of being added to it. The problem seems to occur only in Mac Os X (El Capitan). A minimal reproduction of the problem: 

Load libraries

    library(ggplot2)
    library(gtable)

Build plot

    d <- ggplot(mtcars, aes(x=gear)) + 
                geom_bar(aes(y=gear), stat="identity", position="dodge") +
                facet_wrap(~cyl)
Change height of strip text

    g <- ggplotGrob(d)
    g$heights[[3]] = unit(2,"in")
    grid.newpage()
    grid.draw(g)

Obtained result (on Mac OS X El Capitan)
[![enter image description here][1]][1]
Expected result (From Linux & http://www.r-fiddle.org)
[![enter image description here][2]][2]

  [1]: http://i.stack.imgur.com/VLsRS.png
  [2]: http://i.stack.imgur.com/VGswJ.png

**Comment by hadley** [comment]
Unfortunately I'm unlikely to ever figure this out.  I'd recommend setting the height with the theme instead.

**Comment by shekeine** [comment]
Hello Hadley, no problem and thanks.
