### ISSUE TITLE
ggplot2 2.0.0 failed to label counts in geom_text for geom_bar

### ISSUE THREAD

**Issue by zyqfrog10** [hadley/ggplot2#1531]
Previously, we could label count for each bar by using `aes(label=..count..)` for `stat="bin"`, just like the following:

```R
x <- data.frame(y = c(1,1,1,2,2,3,rep(c(1,2,3,4), 10))
ggplot(x, aes(factor(y))) +
  geom_bar(fill = 2) +
  geom_text(stat="bin", aes(label = ..count.., y=(..count..-..count..)+5))
```

But in ggplot2 2.0.0, `stat="bin"` changed to `stat="count"` and `aes(label=..count..)` was not recognized. 
So I am wondering if there is a new way to label the counts for bars. Thank you!

**Comment by hadley** [comment]
This works for me:

```R
df <- data.frame(y = rep(1:4, 1:4 * 10))

ggplot(df, aes(factor(y))) +
  geom_bar() +
  geom_text(stat = "count", aes(label = ..count.., y = ..count..))
```

**Comment by prerit912** [comment]
Why do we need to have stat = "count" doesn't geom_bar = stat_bar + geom_bar?
