### ISSUE TITLE
na.rm not defaulted in layer()

### ISSUE THREAD

**Issue by oneilsh** [hadley/ggplot2#1532]
Not sure if this is considered an issue or not, but I noticed that while `na.rm` recently defaults to `FALSE` for some stats (035e6ff8aa5d056059df9b6c82ec2a8c037eaa8b, 067e09690e570b4653a79dc5bd5b1ddf91f94502) the `layer()` function doesn't have a default, resulting in `Error: is.logical(na.rm) is not TRUE` if `params` is unspecified.

Just checking to see if this is the intended behavior/will stay that way going forward. (Same with no default for `position`?)

```R
p <- ggplot() +
  layer(data = diamonds, 
        stat = "bin",
        geom = "bar",
        mapping = aes(x = price),
        position = "identity")
plot(p)
```

**Comment by hadley** [comment]
Fixed in 7d6778574e8ab6d0f0d8cade5a09a97cb6582c45

I don't see how `position` could default to anything other than NULL though. It would be inconsistent with `geom` and `stat`
