### ISSUE TITLE
geom_path() plots across NA gaps when color is mapped and NA.

### ISSUE THREAD

**Issue by Ax3man** [hadley/ggplot2#1533]
I'm suspecting this is a bug (at least it is surprising behavior to me). Consider the following example:

```
df <- data.frame(x = c(1:10), y = c(1:10), z = 'a')
df[5:7, ] <- NA
ggplot(df, aes(x, y)) + geom_path()                        #plot1
ggplot(df, aes(x, y, color = z)) + geom_path()         #plot2
```
In plot 1, the gap in the path in rows 5:7 is left open. However, when a color is mapped, the gap get's filled.

However, this is only the case if the color mapped is NA at those positions. If only x and y are NA, the gap is left open again:

```
df2 <- data.frame(x = c(1:10), y = c(1:10), z = 'a')
df2[5:7, 1:2] <- NA
ggplot(df2, aes(x, y, color = z)) + geom_path()
```

My version is 2.0.0.9001. Thanks!

**Comment by smouksassi** [comment]
ok another issue we can face is when we have a colored line and we difine a linetype even when we say it is solid line we get the error message that we cannot use dotted or dahsed !
a third issue is suppose you have mapped a continuous color scale and then you want to add a categorical color scale for something else this also issue an error 

```r
df2 <- data.frame(x = c(1:10), y = c(1:10), z = 'a')
df2[5:7, 1:2] <- NA
ggplot(df, aes(x, y, color = y)) + geom_path()         #plot works when mapped to continous color
ggplot(df, aes(x, y, color = y)) +
 geom_path() +
 geom_path(aes(x, y, color = z))
Error: Discrete value supplied to continuous scale

ggplot(df, aes(x, y, color = y)) + geom_path(linetype="solid")         #plot2

Error: geom_path: If you are using dotted or dashed lines, colour, size and linetype must be constant over the line

**Comment by Ax3man** [comment]
Mixing linetype and color is clearly documented to not work, so I don't see that as a bug.

**Comment by smouksassi** [comment]
to me it is a bug since the error complains about using dashed or dotted while we are specifying we want solid, the same code works if you use linetype =1 , it shoudl deal interchangibly with 1 or "solid"

**Comment by hadley** [comment]
@smouksassi this is a completely different bug. Please file a new issue

**Comment by hadley** [comment]
Hmmmm, I think this behaviour is correct because you don't have one line here - you have two lines, because of the missing colour. It's a bit easier to see what's going on with a simpler example:

```R
df <- data.frame(
  x1 = c(1, NA, NA, 4), 
  x2 = 1:4,
  y1 = c(1, NA, NA, 4), 
  y2 = c(1, 2.1, 3.1, 4),
  z = c("a", NA, NA, "a")
)
ggplot(df, aes(x2, y2, colour = z)) + geom_path() + geom_point()
ggplot(df, aes(x1, y1, colour = z)) + geom_path() + geom_point()
```

i.e. you actually have two lines, one which contains missing values and one that doesn't. ggplot2 doesn't group `colour = NA` with `colour = "z"`.

**Comment by Ax3man** [comment]
Thanks Hadley, that clears things up perfectly.
