### ISSUE TITLE
Feature request: Function to combine distinct plots on same x-axis 

### ISSUE THREAD

**Issue by ewallace** [hadley/ggplot2#1535]
Hi,
Apologies if this has already been discussed, but for time series and genomic plot amongst other things it is very convenient to be able to combine multiple disparate plots on exactly the same x-axis.

There are various recipes online for how to do this, including the ggplot website:
http://www.exegetic.biz/blog/2015/05/r-recipe-aligning-axes-in-ggplot2/
http://blog.drskippy.com/2012/05/29/r-e-g-grid-of-aligned-time-series-plots-in-r/
http://chrischizinski.github.io/rstats/2014/05/07/multiple-plots/
https://github.com/hadley/ggplot2/wiki/Align-two-plots-on-a-page

However the most convenient solution I've found is the tracks function in the ggbio package:
http://www.tengfei.name/ggbio/docs/man/tracks.html

This takes a series of ggbio/ggplot2 plots and puts them on the same x-axis, automatically handling facet names and axes, and allows scale_x_... arguments (although issues a warning).

Could something like that be in base ggplot2?

Many thanks
Edward

**Comment by hadley** [comment]
I don't think it's a bad idea, but there are a lot of details to get right, so it's unlikely I'll ever have the time unfortunately.

**Comment by ewallace** [comment]
Reasonable!

If I learn to be a good ggplot developer (~1 month's work), would you be open to having this as a pull request?

Otherwise I'll ask Claus about getting it in Cowplot.

**Comment by hadley** [comment]
@ewallace possibly, but I suspect it's going to be sufficiently complex that I'd think it would be better in an external package so I didn't have to maintain it.
