### ISSUE TITLE
"plyr_split_indices" error when running ggplot command

### ISSUE THREAD

**Issue by gaiusjaugustus** [hadley/ggplot2#1537]
I am using R Studio running R 3.2.3 on Windows 7.

I am trying to create a plot using ggplot2. I've used ggplot2 for about a year now and never had issues until this started.

Suddenly, I've started getting this error whenever I run a ggplot() command:
```

Error in .Call("plyr_split_indices", PACKAGE = "plyr", group, n) : 
  "plyr_split_indices" not available for .Call() for package "plyr"
```

**What I've tried:**
I uninstalled all my packages and reinstalled them.  Everything (including the problem script) worked for a few days. Then today, I pulled up the script I was working with when the issue started, and the issue just started happening again. I'd rather not have to uninstall all my packages and reinstall every time I work on this.
I also renamed the hidden RStudio-Desktop folder so it would remake it, but that hasn't solved it either.

**Some info about the script:** I read in a file, do manipulations using dplyr (filter, group_by, tally), subset, and plot. I haven't created any functions. And I've detached any other packages that I thought could be making an issue. My data.frames are not small (20,000 rows x 6 columns), but I've dealt with more data in the past without issue.

I can email the script if it will help, or give you whatever information you need.  Let me know what I can provide so that I can figure out what's happened and fix it.

Session Info:
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] grDevices datasets  parallel  stats     graphics  utils     methods   base     

other attached packages:
[1] reshape2_1.4.1      ggplot2_2.0.0       BiocGenerics_0.14.0

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 scales_0.3.0     magrittr_1.5     plyr_1.8.3       tools_3.2.3      gtable_0.1.2     Rcpp_0.12.3     

 [8] Biobase_2.28.0   stringi_1.0-1    grid_3.2.3       stringr_1.0.0    packrat_0.4.4    munsell_0.4.2   
```

**Comment by hadley** [comment]
It's almost certainly a problem with your setup. Make sure you've quit and restarted R and that ggplot2 and plyr are not loaded. Then run `install.packages("ggplot2", dep = T)`

**Comment by hadley** [comment]
If that doesn't help, I'd recommend either the ggplot2 mailing list or stackoverflow.
