### ISSUE TITLE
How to make the y axis start from zero?

### ISSUE THREAD

**Issue by edyanzhang** [hadley/ggplot2#1538]
I used the following code to limit the range of y axis to (5, 7.5), please see the 1st plot. But there still be grey color below the 5 tick. Any suggestions to make a plot like the 2nd one?
`> bp<-ggplot(PlantGrowth, aes(x=group,y=weight))+geom_boxplot()
> bp
> bp+coord_cartesian(ylim=c(5,7.5))`

![p1](https://cloud.githubusercontent.com/assets/16956678/12880275/dd400a26-ce79-11e5-96e4-3402c9080bb1.png)
![p2](https://cloud.githubusercontent.com/assets/16956678/12880278/e8f345fe-ce79-11e5-90b4-d38cf7cd1c56.png)

**Comment by hadley** [comment]
Have a look at the documentation for `coord_cartesian()` :wink:

**Comment by edyanzhang** [comment]
Thank you very much for your reminder ! I solved it
