### ISSUE TITLE
scale_x_date does not have sensible default label format and several different, incorrect labels are plotted on top of each other

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1540]
df <- data.frame(x = as.Date(c("2016-02-09", "2016-02-10")), y = 1)

    ggplot(data = df, aes(x = x, y = y)) +
       geom_point() +
       scale_x_date()

    # save as pdf to enable zooming
    ggsave("test.pdf")

I believe the labels have a non-sensible format, i.e. datetime `%b %d %H:%S` instead of date. Wouldn't the most sensible default for a _date_ scale be a date in "a standard unambiguous format" , i.e. `"%Y-%m-%d"`?

In addition, the labels seem to consist of several different labels plotted on top of each other. In the example, the first label seem to have two different `%H`. The second label have two (or more?) different `%d`, and at least three different `%H`.

    R version 3.2.3
    ggplot2_2.0.0 
    scales_0.3.0

**Comment by hadley** [comment]
This is also a problem with the base pretty function: 

```R
x <- as.Date(c("2016-02-09", "2016-02-10"))
pretty(x)
```

I'll pass it along to Martin Maechler.
