### ISSUE TITLE
Let datetime scale pick a sensible default to enable plot with only one datetime value

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1541]
If there is only one unique datetime value in the data, an error is generated. 

    df <- data.frame(x = as.POSIXct("2016-02-05 08:00:00"),
                               y = 1:2)

    ggplot(data = df, aes(x = x, y = y)) +
      geom_point() +
      scale_x_datetime()

    # Error in prettyDate(x = x, n = n, min.n = min.n, sep = sep, ...) : 
    #  range too small for 'min.n'

Perhaps it would be better to pick a default label in a "standard unambiguous format", i.e `"%Y-%m-%d %H:%M:%S"` than to throw an error?

    R version 3.2.3
    ggplot2_2.0.0 
    scales_0.3.0

**Comment by hadley** [comment]
This is a bug in `prettyDate` in base R

**Comment by Henrik-P** [comment]
OK. I take the liberty to reference [Add support for sub-second plotting](https://github.com/hadley/ggplot2/issues/1395) and [https://github.com/hadley/scales/issues/65](https://github.com/hadley/scales/issues/65) to make it easier to see that you already have taken action to solve the problem ("I've emailed Paul Murrell").
