### ISSUE TITLE
Adding scale_*_discrete() to date variable can crash R

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2#1542]
With **scales** 0.3, this code will error:

```r
x <- c(Sys.Date(), Sys.Date() - 1e4)
y <- c(3, 4)
d <- data.frame(x, y)
library(ggplot2)
ggplot(d, aes(x, y)) + geom_line() + scale_x_discrete()
#> Error: Discrete value supplied to continuous scale
```

Running this code using the latest dev version of **scales** doesn't result in error, and ggplot tries to draw a plot with 1e4 ticks. I know this is a cornercase, but I would prefer an error since it can easily wreak havoc on an R session, especially with date-times.

**Comment by cpsievert** [comment]
Here is the relevant change -- https://github.com/hadley/scales/commit/cd0395de74af429a7151b7e7cedfcdb72fa96215

**Comment by hadley** [comment]
Are you sure that's the change? It seems weird that a check in continuous scales would break discrete scales

**Comment by cpsievert** [comment]
Yes, it appears both `scale_x_discrete()`/`scale_y_discrete()` use a continuous range. I'm not sure whether or not that is intentional, but it does seem odd:

```r
> scale_x_discrete
function (..., expand = waiver()) 
{
    sc <- discrete_scale(c("x", "xmin", "xmax", "xend"), "position_d", 
        identity, ..., expand = expand, guide = "none")
    sc$super <- ScaleDiscretePosition
    class(sc) <- class(ScaleDiscretePosition)
    sc$range_c <- continuous_range()
    sc
}
```

Just for demonstrate that the change I refer to above is relevant, you can install https://github.com/hadley/scales/pull/70 to see that the example now throws an error.

**Comment by hadley** [comment]
Ah, that makes sense.  But I'd rather fix it by handing the poor performance with many levels

**Comment by hadley** [comment]
Hmmm, something is seriously messed up with code that handles the combination of discrete and continuous ranges. I need to think through exactly how this should behave - the reason why discrete scale also have a continuous component is so that this sort of plot can work:

```R
ggplot(mtcars, aes(factor(cyl), mpg)) + geom_jitter()
```
