### ISSUE TITLE
Add subtitle object

### ISSUE THREAD

**Issue by alistaire47** [hadley/ggplot2#1543]
Would it be possible to add a subtitle object à la `ggtitle`? Right now, the approaches I've seen to add subtitles are  
- adding `\n` in the title text, but
   - they can't be themed differently, as typical for a subtitle;
- hacking with `atop`, but
   - some formatting (e.g. justification) is hard,
   - it's inconsistent, erroring out sometimes but not always, and
   - syntax is not obvious;
- using `annotation_custom` and `grid` to create grobs for title and subtitle, but
   - it requires more code than most plots.  

None of the approaches are really consistent with ggplot's style of plotting by adding simple objects.

Thus, given this is a very common task while plotting, would it be possible to  
- add a themable `ggsubtitle` object with reasonable default formatting, or
- allow inline control of `ggtitle`'s theme so two could be arranged suitably?

As ever, thank you for making R awesome.

**Comment by hadley** [comment]
I'd possibly review a pull request to implement this, but it's a lot of work, so I'm unlikely to do it myself.
