### ISSUE TITLE
Train and map non-position scales within layers?

### ISSUE THREAD

**Issue by cpsievert** [hadley/ggplot2#1544]
It seems like it should be possible to map multiple variables to the same aesthetic (as long as the mapping is one-to-one within each layer). However, I don't think it is currently.

```r
ggplot(mtcars, aes(x = mpg, y = wt)) + 
  geom_line(aes(color = cyl)) + 
  geom_point(aes(color = factor(vs))) 
#> Error: Discrete value supplied to continuous scale
```

This is a bit counter-intuitive considering these two plots could be combined together:

```r
ggplot(mtcars, aes(x = mpg, y = wt)) + 
  geom_line(aes(color = cyl))
  
ggplot(mtcars, aes(x = mpg, y = wt)) + 
  geom_point(aes(color = factor(vs))) 
```

**Comment by hadley** [comment]
You can do it, provided that the default scales all work.

```R
ggplot(mtcars, aes(x = mpg, y = wt)) + 
  geom_line(aes(color = cyl)) + 
  geom_point(aes(color = vs)) 
```

I don't see how it would make sense to try and combine a continuous and discrete variable on the same scale.
