### ISSUE TITLE
annotate() does not support expressions in label argument

### ISSUE THREAD

**Issue by dgromer** [hadley/ggplot2#1548]
This fails:
```r
ggplot(data.frame(x = 1, y = 1), aes(x, y)) +
  geom_point() +
  annotate("text", x = 1, y = 1.1,
           label = expression(paste(Delta, italic("i"))), parse = TRUE)
```

This works:
```r
ggplot(data.frame(x = 1, y = 1), aes(x, y)) +
  geom_point() +
  annotate("text", x = 1, y = 1.1, label = "Delta~italic('i')", parse = TRUE)
```

However, in `labs`, objects of type `expression` don't throw an error.
```r
ggplot(data.frame(x = 1, y = 1), aes(x, y)) +
  geom_point() +
  labs(x = expression(paste(Delta, italic("i"))))
```

**Comment by hadley** [comment]
Yes, annotate is built on top of `geom_text()`

**Comment by dgromer** [comment]
So is there any way to make annotations by passing an expression? Because there are is stuff that cannot be expressed with a string in plotmath syntax (small example: `"Delta~italic('i')"` has a whitespace in between, whereas with `expression(paste(Delta, italic("i")))` it is possible to omit it)

**Comment by hadley** [comment]
Put the paste in the string

**Comment by dgromer** [comment]
Ah yeah, thanks a lot!
