### ISSUE TITLE
Regression: NA values not being handled correctly in GeomRibbon

### ISSUE THREAD

**Issue by MikeWise2718** [hadley/ggplot2#1549]
There seems to be a missing **handle_na** function in **GeomRibbon**. I answered a question with a workaround here: http://stackoverflow.com/questions/35454277/can-you-make-geom-ribbon-leave-a-gap-for-missing-values/35461050#35461050

**Comment by hadley** [comment]
Can you please include a minimal reproducible example inline?

**Comment by MikeWise2718** [comment]
Sure. The following program should have a gap at **x==4**, (where there is an NA in the data). But it does not. 

However it does if I create a new **GeomRibbon** identical to the first but with a **handle_na** default function doing nothing.

# R Script
require(dplyr)
require(ggplot2)
require(grid)

set.seed(1)

test <- data.frame(x = rep(1:10, 3), y = abs(rnorm(30)), z = rep(LETTERS[1:3], 10)) %>% arrange(x, z)

test[test$x == 4, "y"] <- NA

test$ymax <- test$y
test$ymin <- 0
zl <- levels(test$z)
for (i in 2:length(zl)) {
    zi <- test$z == zl[i]
    zi_1 <- test$z == zl[i - 1]
    test$ymin[zi] <- test$ymax[zi_1]
    test$ymax[zi] <- test$ymin[zi] + test$ymax[zi]
}

ggplot(test, aes(x = x, y = y, ymax = ymax, ymin = ymin, fill = z)) +
  geom_ribbon() +
  scale_x_continuous(breaks = 1:10)](url)
