### ISSUE TITLE
Class of gtable heights/widths is inconsistent across facet types

### ISSUE THREAD

**Issue by infotroph** [hadley/ggplot2#1550]
In v1.0.1 `ggplotGrob(some_ggplot)$heights` was always a `unit.list` and I was able to use it to [calculate dimensions of fixed-aspect plots](https://github.com/infotroph/DeLuciatoR/blob/master/man/get_dims.Rd) as a workaround for #1163. 

In v2.0.0, the class of `heights` & `widths` depends how the plot is facetted:
```
p <- ggplot(mtcars, aes(wt,mpg))
class(ggplotGrob(p + facet_null())$heights)
# [1] "unit.list" "unit" 
class(ggplotGrob(p + facet_wrap(~cyl))$heights)
# [1] "unit"
class(ggplotGrob(p + facet_grid(.~cyl))$heights)
# [1] "unit"
```

I realize this isn't really API-supported territory, but it does provide (maybe the only?) access to rendered plot dimensions and I suggest keeping it accessible, and making it consistent between facet types, if that's practical.

**Comment by hadley** [comment]
They're both "units" so you should still be ok

**Comment by infotroph** [comment]
You're right. I guess my complaint is with the Grid API and not ggplot. Sorry for the noise. 

(Any Grid maintainers who see this, my complaint is that Grid stores attributes differently for each `unit` subclass, and AFAIK doesn't provide accessors for the `unit` attributes, which makes it hard to answer questions like "which of these heights are in null units and which are in cm?" )

**Comment by hadley** [comment]
Can't you use `widthDetails()` etc?

**Comment by infotroph** [comment]
* widthDetails() fails on my first example: with still returns a mix of null and non-null units (`sum(16points, 0cm, 0.5null, sum(-8points, 1grobheight), 1grobheight, 16points)`)

**Comment by infotroph** [comment]
"Yes, but":

1. With gtable 0.1.2 and ggplot2 2.0.0, widthDetails fails on my first example:
    ```
    > widthDetails(ggplotGrob(ggplot(mtcars, aes(wt, mpg))))
    Error in UseMethod("absolute.units") : 
      no applicable method for 'absolute.units' applied to an object of class "unit"
    ```
    This [may be fixed already](https://github.com/hadley/gtable/pull/53), and `gtable_width` also works and returns a unit.arithmetic object from any facets, so my claimed "inconsistent ggplot behavior" is doubly invalid.

2. These methods still return a mix of units. If I want to know which units will change when the device resizes,  they need to be parsed carefully to get at their individual unit attributes  -- picture something like a `unitOnly` inverse of convertUnit's `valueOnly` argument, with all the caveats and ambiguities that implies.

    …When I put it that way, it's clear why such a function might not exist yet :)

**Comment by baptiste** [comment]
see http://stackoverflow.com/questions/34032621/element-replacement-in-grid-unit-vector
