### ISSUE TITLE
Stacked area charts not stacking

### ISSUE THREAD

**Issue by karawoo** [hadley/ggplot2#1552]
When I try to create a stacked area chart using the following code the segments don't stack, and they occlude each other instead.

```r
library("ggplot2")
library("dplyr")

## Create data
set.seed(40)
dat <- data.frame(x = rep(c(1:10), 3),
                  var = rep(c("a", "b", "c"), 10),
                  y = round(runif(30, 1, 5)))

## Plot
ggplot(dat, aes(x = x, y = y, fill = var)) +
  geom_area(position = "stack")
```

![unstacked_area](https://cloud.githubusercontent.com/assets/4452678/13201283/ad983c40-d81e-11e5-9ea1-5cdcc975c65c.png)

However if I reorder the rows so all of the `var` values are grouped together, it does create a stacked chart:

```r
dat %>%
  arrange(var, x) %>%
  ggplot(aes(x = x, y = y, fill = var)) +
  geom_area(position = "stack")
```

![stacked_area](https://cloud.githubusercontent.com/assets/4452678/13201284/b32f823a-d81e-11e5-838c-2d1ff4366410.png)

Is this a bug, or is the ordering of the rows meant to matter like this?

**Comment by thomasp85** [comment]
It sort of makes weird sense as the order at each x-value follows the order it occurs in in the data. I would suggest we add a sorting step to `position_stack` - In this way we can also get the stacking order to follow the legend order...

@hadley thoughts? It might change the appearance of some plots, though I would argue that the benefit of the bug fix and sorting would alleviate that...

**Comment by hadley** [comment]
I like the idea of matching the stacking order to the legend order.  That would also help with #1593

**Comment by thomasp85** [comment]
It would not be bulletproof, i.e. it is only possible to match the stacking to the default legend order and not to any modified order defined in scale_*, that is, we can sort only by the data itself as position doesn't have access to the scale object...

**Comment by hadley** [comment]
Oh that's true - and it would mean that to change the stacking order you'd be forced to change the levels of a factor. Hmmm.

**Comment by thomasp85** [comment]
I think this is reasonable. If well documented it is not too much to ask that they reorder factor levels to achieve their desired stacking...
