### ISSUE TITLE
%>% operator in ggplot2

### ISSUE THREAD

**Issue by twolodzko** [hadley/ggplot2#1554]
Dplyr and ggplot2 are often used jointly. This makes existence of two functions that _seem_ to work similarly be confusing for some users (see https://stackoverflow.com/questions/35332861/what-is-the-difference-between-the-operator-in-ggplot2-and-the-operato). As ggplot2 user I also noticed that from time to time I write `%>%` instead of `+` when using ggplot2.

Why not define another alias for `+` in form:

`"%>%.gg" <- +.gg`

Similar approach was taken in dplyr where `summarise` and `summarize` can be used for the same function because of such user mistakes.

The linked SO thread also suggests that at this moment behaviour of `%>%` with gg objects is ambiguous and so such action should not interfere with any valid ggplot2 user behaviour.

**Comment by hadley** [comment]
It's not possible because that's not how `%>%` works.

**Comment by yutannihilation** [comment]
@twolodzko 
FYI: If you wonder why `%>%` is not a generic function, you can read some discussion here: https://github.com/smbache/magrittr/issues/101
