### ISSUE TITLE
Can't map colour to geom_abline

### ISSUE THREAD

**Issue by ateucher** [hadley/ggplot2#1558]
I can't seem to map colour to `geom_abline` and create a corresponding legend for it like I can with other geoms. I may be going crazy, but I'm sure I could do this before:

``` r
library(ggplot2)
df <- data.frame(a = 0:10, b = 0:10)

ggplot(df, aes(x = a, y = b)) + 
  geom_point() + 
  geom_abline(mapping = aes(colour = "foo"), slope = 1, intercept = 2, show.legend = TRUE) + 
  scale_colour_manual(name = "Legend", values = c("foo" = "red"))
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/2816635/13304020/679f1556-db07-11e5-96b0-f1119eb4e2d8.png)

Though it does work for other geoms:

``` r
ggplot(df, aes(x = a, y = b)) + 
  geom_point(aes(colour = "foo")) + 
  geom_abline(slope = 1, intercept = 2) + 
  scale_colour_manual(name = "Legend", values = c("foo" = "red"))
```

![unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/2816635/13304023/6a44d0a2-db07-11e5-952e-7715af0c7266.png)

**Comment by hadley** [comment]
For various complicated reasons you unfortunately have to do:

```R
library(ggplot2)
df <- data.frame(a = 0:10, b = 0:10)

ggplot(df, aes(x = a, y = b)) + 
  geom_point() + 
  geom_abline(mapping = aes(colour = "foo", slope = slope, intercept = intercept), data.frame(slope = 1, intercept = 2)) + 
  scale_colour_manual(name = "Legend", values = c("foo" = "red"))
```

**Comment by ateucher** [comment]
Ok, thanks!
