### ISSUE TITLE
yend of geom_segment doesn't respect position='stack' 

### ISSUE THREAD

**Issue by yahiaelgamal** [hadley/ggplot2#1562]
I was trying to use `position='stack'` in conjunction with `geom_segment` but I found that only the `y` aesthetic respects the position paramter, but `yend` behaves like `position='identity'`

Here is a small reproducible sample

```
nums = data.frame(names=c(1,2,3,), vals = c(5,4,2,))

p = ggplot(nums) + geom_bar(aes(x=1, y=vals, fill=names), stat='identity')

p1 = p + geom_segment(aes(x=0.5, xend=1.5,y=vals, yend=vals, linetype='position(stack)'), position='stack') 
p1 + geom_segment(aes(x=0.5, xend=1.5,y=vals, yend=vals, linetype='position(identity)'), position='identity') 
```
and here is a screenshot

<img width="1187" alt="screen shot 2016-02-27 at 12 48 37 pm" src="https://cloud.githubusercontent.com/assets/1324481/13372553/7520c666-dd50-11e5-96bf-5cc2b7adeacf.png">

**Comment by hadley** [comment]
Yeah, stacking only affects the y axis.  Unfortunately you'll have to stack yourself using a groupwise cumsum.
