### ISSUE TITLE
Omit legend using `show.legend = FALSE` does not work when aesthetic is continuous

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1568]
`show.legend = FALSE` works as expected when the fill variable is discrete. However, when the `aes`thetic is mapped to a continuous variable, `show.legend = FALSE` does not drop the legend.

    df <- data.frame(x = 1:3, y = 1)

Discrete `fill` or `color` `aes`:
    
    ggplot(df, aes(x = x, y = y, color = factor(x))) +
      geom_point(size = 20, shape = 21, show.legend = FALSE)
    
    ggplot(df, aes(x = x, y = y, fill = factor(x))) +
      geom_point(size = 20, shape = 21, show.legend = FALSE)

Continuous `fill` or `color` `aes`:

    ggplot(df, aes(x = x, y = y, color = x)) +
      geom_point(size = 20, shape = 21, show.legend = FALSE)

    ggplot(df, aes(x = x, y = y, fill = x)) +
      geom_point(size = 20, shape = 21, show.legend = FALSE)

`ggplot2_2.1.0`

**Comment by hadley** [comment]
@thomasp85 can you please take a look at this one?

**Comment by thomasp85** [comment]
@hadley I'm unsure why you closed #1575? This is how I was planning to fix this (without having looked into the PR)... It generally seems like a slip when implementing colorbar legends rather than an overarching design problem? In any way I think we should fix it as done in #1575 for now and wait with any grand changes to the legend system until the day they see a ggproto rewrite.

**Comment by hadley** [comment]
Just that the code should be hoisted up at least one level higher so that the contents of `guide_geom.legend` aren't basically copied and pasted somewhere else.

**Comment by thomasp85** [comment]
I think that is better done once/if guides are ported to ggproto. Currently, the optimal place to handles this is at the level it is currently handled in `guide_legend` as it is an operation that needs to be done for each layer in each guide... I'm not saying it can't be done - just that it wouldn't be pretty...

**Comment by hadley** [comment]
It seems like at least you could have a function? Most of the work would be similar I think.   But if you think a quick copy-and-paste job is the way to go, that's fine too.

**Comment by thomasp85** [comment]
I've refactored a bit in #1782
