### ISSUE TITLE
aes(color = "x") gets legend label "colour"

### ISSUE THREAD

**Issue by tjmahr** [hadley/ggplot2#1571]
When using the new aesthetic = "constant" trick for differentiating layers, the aes `color` is labelled as "colour". I hate to be the one to file an issue over spelling and I know it's trivial to relabel the color legend, but ideally the label "color" would be used because that's what the user wrote. 

```r
ggplot() + 
  aes(x = 1:10) + 
  geom_line(aes(y = .5, color = "L1")) + 
  geom_line(aes(y = .75, color = "L2"))
```

![image](https://cloud.githubusercontent.com/assets/1890315/13548223/fecaa76e-e2b0-11e5-91e0-3a85fd5e31d7.png)

**Comment by ptoche** [comment]
I don't get "colour" I get "L1". ``ggplot v.2.0.0``

**Comment by tjmahr** [comment]
The behavior was added in 2.1.0.

**Comment by has2k1** [comment]
Solution

```R
ggplot() + 
  aes(x = 1:10) + 
  geom_line(aes(y = .5, color = "L1")) + 
  geom_line(aes(y = .75, color = "L2")) + labs(colour='color')
```

**Comment by hadley** [comment]
Yeah, sorry. If you don't want correct spelling you'll need to add your own title :wink:
