### ISSUE TITLE
Plot has Tops of Capital Letters Missing when Plot Margins are 0

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1573]
For example,

    library(ggplot2)
    ggplot(mtcars, aes(wt, mpg)) + geom_point() + ggtitle("CSRQB") + theme(plot.margin = unit(c(0, 0, 0, 0), "lines"), plot.title = element_text(size = 36))
The top of the capital letters C,S,Q is visibly cut off.

**Comment by hadley** [comment]
Don't set margins to 0. Unfortunately R's text metrics don't make it easier to do better.
