### ISSUE TITLE
stat_summary error when trying to pass function argument as parameter, rather than hard-coding

### ISSUE THREAD

**Issue by eipi10** [hadley/ggplot2#1574]
I'm getting an error when I try to pass a parameter into the `round` function within `stat_summary` (even though the analogous code works with, say, `geom_text`). Here's an example:
```
# Fake data
set.seed(5)
dat = data.frame(group=rep(c("A","B"),each=10), val=rnorm(20))

# Set the number of decimal places for value labels using a parameter, rather than hard-coding it:
places = 2

ggplot(dat, aes(group, val)) +
  stat_summary(fun.y=mean, geom="text", aes(label=round(..y.., places)))
```
>Error in eval(expr, envir, enclos) : object 'places' not found

The following two examples work fine, however.

```
ggplot(dat, aes(group, val)) +
  stat_summary(fun.y=mean, geom="text", aes(label=round(..y.., 2)))

ggplot(dat, aes(group, val)) +
  geom_text(aes(label=round(val, places)))
```

I ran into this problem while trying to write a ggplot function. At first I thought the problem involved ggplot not getting the parameter from the function environment, but the example above suggests that's not the issue. For completeness, below is a simplified example of the function, along with the error message. The function works fine if I hard-code the `digits` argument to `round`, rather than trying to pass the `places` parameter.

```
pp = function(data, group, var, places=2, e=1.5) {
  ggplot(data, aes_string(group, var)) +
    geom_boxplot() +
    stat_summary(fun.y=mean, geom="text", aes(label=round(..y.., places))) +
    scale_y_continuous(limits = e * range(data[,var]))
}

pp(dat, "group","val")
```
>Error in eval(expr, envir, enclos) : object 'places' not found

[I asked this question on StackOverflow](http://stackoverflow.com/questions/35806038/ggplot2-stat-summary-throws-error-when-trying-to-pass-function-argument-as-para) and user @alistaire diagnosed this as a non-standard evaluation issue. Here is the fix he came up with:

```
eval(substitute(ggplot(dat, aes(group, val)) +
                  stat_summary(fun.y=mean, geom="text", aes(label=round(..y.., places))), 
                list(places = places)))
```

This works, but I assume it can't be intended that `eval(substitute...` is necessary to pass a parameter to `stat_summary`. So I thought I'd post this here as an issue to see if it's a bug, if I'm doing something wrong, or if there's a better way to deal with this issue.

**Comment by hadley** [comment]
This is basically an example of the fundamental broken-ness that's at the heart of ggplot2 NSE. Unfortunately I really didn't understand NSE at the time I wrote ggplot2, and I haven't had the time to fix it.  I'll probably have another go when I attempt to integrate the new lazyeval work into ggplot2 and dplyr. 

In the meantime, a better work around would be to use a little helper function:

```{r}
round2 <- function(x) round(x, 2)
```

**Comment by eipi10** [comment]
Thanks Hadley.
