### ISSUE TITLE
Feature request: implement stat = "stepribbon" for geom_ribbon

### ISSUE THREAD

**Issue by kendonB** [hadley/ggplot2#1576]
I've used the code here and it works fine:

https://groups.google.com/forum/?fromgroups=#!topic/ggplot2/9cFWHaH1CPs

**Comment by hadley** [comment]
I'm not currently adding new geoms to ggplot2 unless they're really fundamentally. I'd recommend inquiring with one of the ggplot2 extension packages.

**Comment by kendonB** [comment]
Are you adding new functionality (i.e new layer types) like this to ggvis?

**Comment by hadley** [comment]
One day

**Comment by hrbrmstr** [comment]
this is now in`ggalt`
