### ISSUE TITLE
Possible bug in default method for geom_smooth

### ISSUE THREAD

**Issue by cjones84** [hadley/ggplot2#1583]
It looks like the default method in geom_smooth is chosen by the number of rows in dataframe, not by the number of rows of data used to create the smoothed line. The example below should clarify the problem.

#Generate some noisy time series
set.seed(1)
z = data.frame("Index"=1:101, "Person"=rep(letters[1:10], each=101), "Distance"=as.vector(replicate(10, rnorm(101) + cumsum(rnorm(101)))))

#Plot smoothed lines for ALL of the time series
#geom_smooth uses method gam
library(ggplot2)
ggplot(data=z, aes(x=Index, y=Distance)) + geom_smooth() + facet_wrap(~Person)

#Plot smoothed lines for 9 out of 10 of the time series (so fewer than 1000 rows in the data)
#geom_smooth uses method loess
win.graph()
ggplot(data=subset(z, Person!="j"), aes(x=Index, y=Distance)) + geom_smooth() + facet_wrap(~Person, ncol=4)

Notice that the smoothed lines look different in the two charts. That's because if you use geom_smooth on the whole dataframe z, then it defaults to method gam, even though each facet where we are drawing the smoothed line has far fewer than 1000 rows of data. If you look at a subset of z with only 909 rows, it defaults to loess. 

Once you see what is going on this problem is easy to correct (just specify the method in the geom_smooth function) but it took me a long time to figure out. Is it possible for the default method used by geom_smooth to be based on the # of rows of data actually used for the line, not for all the dataframe i.e. taking faceting and grouping into account? It might save someone some trouble in the future.

**Comment by hadley** [comment]
I think this would be better fixed by making every facet use the same smoother as in #1652
