### ISSUE TITLE
NAs should be excluded from the level of discrete X-axis by default

### ISSUE THREAD

**Issue by yutannihilation** [hadley/ggplot2#1584]
When the variable for `x` is character, `NA`s are not treated as a break of X axis. But when the variable is factor, `NA`s are included.

```r
library(ggplot2)

set.seed(1)
d <- c("A", "B", NA)
x <- sample(d, size = 100, replace = TRUE, prob = c(0.7, 0.2, 0.1))
y <- rnorm(100)
df <- data.frame(x, y)

ggplot(df) + geom_boxplot(aes(x, y), na.rm = TRUE)

ggplot(df) + geom_boxplot(aes(as.character(x), y), na.rm = TRUE)
```

![na_included](https://cloud.githubusercontent.com/assets/1978793/13749315/23048e20-ea44-11e5-96a3-722a2d8e120b.png) ![na_not_included](https://cloud.githubusercontent.com/assets/1978793/13749319/25cdc0a4-ea44-11e5-974a-e73b9efb4664.png)

I feel this behaviour is inconsistent. `NA`s should be included only when `NA` is intentionally included in the level of the factor variable.

```r
levels(df$x)
[1] "A" "B"
```

I guess this is simply because `scales:::clevels()` treats them differently. But, I'm wondering if this is by design... Why do we have to force `NA`s included, while we can include `NA` in the factor level by ourselves?

```r
set.seed(1)
d <- c("A", "B", NA)
x <- sample(d, size = 100, replace = TRUE, prob = c(0.7, 0.2, 0.1))

scales:::clevels(x, drop = FALSE)
#> [1] "A" "B"

scales:::clevels(as.factor(x), drop = FALSE)
#> [1] "A" "B" NA 
```

Is it possible to eliminate NA from factor X-axis by default? (But I'm afraid this suggestion is too late and many people may already rely on this behaviour)

**Comment by hadley** [comment]
They absolutely should be included by default. The bug is that they aren't in the character case.

**Comment by hadley** [comment]
Here's a minimal reprex of the 2x2 combinations:

```R
df <- data.frame(
  x = c("a", "b", NA),
  y = 1:3,
  stringsAsFactors = FALSE
)

# OK
ggplot(df, aes(x, y)) + geom_point(na.rm = TRUE)
ggplot(df, aes(factor(x), y)) + geom_point()

# Incorrect: NA can be plotted
ggplot(df, aes(x, y)) + geom_point()
# Incorrect: NA should be removed
ggplot(df, aes(factor(x), y)) + geom_point(na.rm = TRUE)
```

**Comment by thomasp85** [comment]
As per the docs `na.rm` should not alter the plot or the data but merely controls whether a warning is issued. Your reprex suggest a different (but in my opinion more sensible) interpretation entirely...

The reason for the discrepancy is that NA is just another level in factors and at the time the data arrives at geom point it is encoded with the integer mapping, whereas characters are still characters and NA thus persists.

@hadley Can you comment on the true purpose of `na.rm` before I fix this..?

**Comment by hadley** [comment]
The goal should always be to display missing values on the plot, where possible. That's not possible for continuous scales, so the best we can do is display a warning. It is possible for categorical scales, so `na.rm` should control the appearance.

**Comment by thomasp85** [comment]
In that case we need to change the doc wording a bit...

`na.rm`:
If `FALSE` (the default), removes missing values with a warning. If `TRUE` silently removes missing values.

**Comment by hadley** [comment]
Something like: If `TRUE`, silently removes missing values. If `FALSE` (the default), will remove missing continuous values with a warning; will show missing categorical values.

**Comment by hadley** [comment]
Is it clear what's needed?

**Comment by thomasp85** [comment]
Yeah - I just need to find the best way to fix this

**Comment by thomasp85** [comment]
Hmm this problem really sits on an intersection between ranges, scales, and gems, in terms of where responsibility should be placed - lets talk about it in person to find out how it can be solved best...

**Comment by hadley** [comment]
I think we should fix this for character vector by fixing `scales::clevels()` (which is a very simple change).

We then need to make sure there's some way to actually drop these NA values, because the `na.rm` to the layers can not work, because by the time the layer sees the data the missingness has been removed (as it's be converted to an integer position). This means we need a `na.rm` argument to `scale_x_discrete()` and `scale_y_discrete()`, and we need to clarify that `na.rm` argument to the layers only affects continuous missing values.

**Comment by hadley** [comment]
I'll handle this one — I think it also needs some minor changes to non-positional discrete scales for consistency.

**Comment by hadley** [comment]
@yutannihilation I know I didn't implement what you requested, but hopefully now the principles are obvious, and they're consistently implemented for the three types of discrete missing value and both types of scale.

**Comment by yutannihilation** [comment]
@hadley Thanks for your great fix! (and sorry for being quiet as I couldn't follow this complicated discussion...) I love this consistency 👍
