### ISSUE TITLE
[feature request] axis break/independent axis

### ISSUE THREAD

**Issue by GuangchuangYu** [hadley/ggplot2#1588]
It's very common to associate one dataset to another and visualize them side by side.
For example in ggtree:
![x](https://cloud.githubusercontent.com/assets/626539/13910666/b985c578-ef60-11e5-907c-306f0ac66dbf.png)

It's great if we can break the x-axis (or have 2 independent x-axis) for tree scale and genotype table.

In `base` plotting system, it's quite easy to have multiple axis via `axis` function. Maybe we can have a `geom_axis` that work similar to `axis` with a function call of `geom_axis(side, at, labels)`.

```r
library(ape)
set.seed(123)
 tr=rtree(30)
plot(tr, x.lim=10)
axisPhylo()
segments(rep(5, 30), 1:30, rep(5, 30) + abs(rnorm(30, 5)), 1:30, lwd=3)
axis(1, at=c(5, 7.5, 10), labels=c(0, 2.5, 5))
```

![screenshot 2016-03-21 12 33 48](https://cloud.githubusercontent.com/assets/626539/13910701/3579e6e6-ef61-11e5-97b2-92f5e115983a.png)

**Comment by hadley** [comment]
I think this is out of scope for ggplot2 - I just can't imagine any way to specify this sort of compound position scale.
