### ISSUE TITLE
scale_[xy]_discrete() causes removal of breaks/labels

### ISSUE THREAD

**Issue by gfiumara** [hadley/ggplot2#1589]
# Summary

Using `scale_[xy]_discrete()`, regardless of arguments, causes axis labels and breaks to disappear without warning.

# Example

```
library(ggplot2)
xyDF <- data.frame(x = 1:10, y = 1:10)
ggplot(data = xyDF, mapping = aes(x = x, y = y)) +
    geom_line() +
    geom_point() +
    scale_x_discrete()

```
# Expected results

Plot showing breaks and labels at 1:10 on the X axis.

![ggplot2_101](https://cloud.githubusercontent.com/assets/419642/13954722/5bc532bc-f018-11e5-8b54-7d513eacc60b.png)
_Created with ggplot2 1.0.1, as I cannot reproduce with 2.1.0._

# Actual results

Plot with no breaks or labels on the X axis (as if `scale_x_discrete(labels = NULL, breaks = NULL)` was added to the plot instead of the default `waiver()`).
![ggplot2_2](https://cloud.githubusercontent.com/assets/419642/13954713/5285d3a0-f018-11e5-9926-9c6294edbce0.png)

# Notes

* Regression since ggplot2 <s>1.0.1 (last major version I've been using)</s> fb3931c4e925272ddba607b81ada998df630bc10.
* Present in devtools and CRAN version as of 22 March 2016.

**Comment by gfiumara** [comment]
Appears to have broken in commit 89893c71ea575e198240e008ba2f42c9cbb7c6b7 (#1542), confirmed by running sample with different `devtools` installs:

```
# Works
devtools::install_github("hadley/ggplot2", ref="fb3931c4e925272ddba607b81ada998df630bc10")

# Broken in subsequent commit
devtools::install_github("hadley/ggplot2", ref="89893c71ea575e198240e008ba2f42c9cbb7c6b7")
```

**Comment by thomasp85** [comment]
This is an by design, as conversion from continuous to discrete data is not well-defined. It is easy to end up with thousands of breaks so it is up to the user to either provide the breaks explicitly or convert their data to a discrete format

**Comment by geotheory** [comment]
Is this the same issue:

```
dat = data.frame(x = 1:4, y = ordered(c(4,'>5',1,1), levels = c(1:5, '>5')), grp = 1)
ggplot(dat, aes(x, y, group=grp)) + geom_step(size=1) + 
  scale_y_discrete(breaks = levels(dat$y), labels = levels(dat$y))
```
![image](https://cloud.githubusercontent.com/assets/1282581/24445604/5ec5f70c-1462-11e7-8bae-dca302fc9e24.png)

I'd say that's a problem.
