### ISSUE TITLE
Click interaction with shiny

### ISSUE THREAD

**Issue by detule** [hadley/ggplot2#1591]
Hi folks,

Haven't looked through all issues open and closed, but was wondering if anyone reported click event listeners breaking in shiny with ggplot 2.1.

I was experiencing a problem (clicks not being reported) that went away post downgrade to 1.0.1.

If you are unaware of this issue, I will attempt to create a minimal example.
Thanks

**Comment by wch** [comment]
https://github.com/rstudio/shiny/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ggplot2

**Comment by detule** [comment]
Thanks Winston: #962 it is.
