### ISSUE TITLE
geom_hline and geom_vline legend issues

### ISSUE THREAD

**Issue by rdcomineor** [hadley/ggplot2#1594]
Hello, Unfortunately a problem persists in the legends of the lines if you also have to add a horizontal line: 

```R
threshold <- data.frame(x = c(1.2, 1.5), name = c("bar", "foo")) ggplot(df, aes(x, y, colour = z)) + geom_point() + geom_vline(aes(xintercept = 1.25, linetype = "dotted"), data = threshold)+geom_hline(aes(yintercept = 1.75, linetype = "1F"), data = threshold)
```

Do you have a suggestion how to have just a vertical line, or horizontal line and not a cross in the legends? Many thanks

![image](https://cloud.githubusercontent.com/assets/17405263/13990053/260bb7f8-f113-11e5-9083-6014ce4668c2.png)

**Comment by hadley** [comment]
Please provide a reproducible example

**Comment by thomasp85** [comment]
The 'problem' is that the two geoms share the same aesthetic and the legend is therefore combined. hline brings the horizontal key and vline brings the vertical together forming a cross. This is difficult to avoid as the key makes sense in all cases where the aesthetic is not directly related to the geom. Imagine a case where you map linetype to a value that could be present in the data for both the horizontal and vertical line - in that case you want the merged legend to indicate that the linetype can be related to either geom...

There will need to be a thorough rewrite of the legend merging if this is to be addressed and I'm not sure it is even possible - guides/legends have no clue about how their data is represented across layers...

**Comment by thomasp85** [comment]
Having looked a bit more into this I'm quite sure that this is not doable with the current division of concern between layers, scales, and guides. The scale only knows about the levels across all layers, and the guide only knows about the scale.

Voting to close.

**Comment by rdcomineor** [comment]
Many thanks for the clarification and for looking into this! Yes, indeed, it should be closed if there is no a foreseeable solution.
