### ISSUE TITLE
[Feature Request] allow customized spacing for legend items

### ISSUE THREAD

**Issue by luke-m-olson** [hadley/ggplot2#1595]
Consider adding two-ish arguments to guide(guide_legend()) that allow the
users to control the spacing between
1. the key and the label and
2. between key-label pairs

The second request is discussed here:
[stackoverflow: change spacing between legend items](http://stackoverflow.com/questions/11366964/is-there-a-way-to-change-the-spacing-between-legend-items-in-ggplot2)

Here is a working example:
``` R
# build silly data.frame
temp <- data.frame("year"=rep(2000:2010, 2), 
"category"=c(rep("puppies", 11), rep("kittens", 11)), 
"smiles"=c(ceiling(runif(11)*100), ceiling(runif(11)*80)))

# stacked area plot
ggplot(temp, aes(x=year, y=smiles)) + geom_area(aes(group=category, fill=category), position="stack") + 
ggtitle("Which Critter Gets the Most Smiles?") + xlab("Year") + ylab("Smiles") + labs(fill="Critter") + 
scale_color_discrete(name="Smiles") +
guides(fill=guide_legend(title.position="top", keywidth=0.2, keyheight=0.2, default.unit="inch")) +
theme(legend.text = element_text(size=10), legend.title = element_text(size=12), legend.position="bottom", legend.title.align=0.5)
```

Each key and legend label are fairly close to one another and it would be great to add some padding in between. More importantly, the key-label pairs are somewhat squished together. The winning stackoverflow answer is to add additional spaces to the end of the kitten elements: "kitten" -> "kitten<4 spaces>". While this hack works, in addressing the second issue it does not seem optimal.

**Comment by thomasp85** [comment]
@hadley do you have any feelings regarding whether this should be supported and if yes, what the interface should be?

**Comment by hadley** [comment]
It'd be fine to implement, but it's not at all high on my priority list.

**Comment by hadley** [comment]
I'd be happy to review a PR for these features, but it's not high enough on my priority list to implement directly.
