### ISSUE TITLE
Allow expressions in facet formulas

### ISSUE THREAD

**Issue by dgrtwo** [hadley/ggplot2#1596]
I'd like to be able to put expressions in faceted formulae instead of just column names.

For example, I'd like to be able to facet by a "cut" of a column:

```r
ggplot(mtcars, aes(qsec, mpg)) +
  geom_point() +
  facet_wrap(~ cut(wt, c(0, 2, 4, 6)))
```

rather than needing to do something like:

```r
mtcars$cut <- cut(mtcars$wt, c(0, 2, 4, 6))

ggplot(mtcars, aes(qsec, mpg)) +
  geom_point() +
  facet_wrap(~ cut)
```

**Comment by DanRuderman** [comment]
Great feature. Syntax-wise, how would you handle the overloading of `+` as both an arithmetic operation and a separator in the formula?

**Comment by hadley** [comment]
It would have to be handled the same way as modelling formulas — if you want addition you need to surround in `I()`

**Comment by DanRuderman** [comment]
First attempt in #1722. Will be shelved until some infrastructure changes take place.

**Comment by thomasp85** [comment]
#1722 has now been ported to the new facet implementation in #1633
