### ISSUE TITLE
geom_rect does not honour alpha value

### ISSUE THREAD

**Issue by richierocks** [hadley/ggplot2#1601]
To reproduce:

```{r}
library(ggplot2)
p <- ggplot(cars) + geom_point(aes(speed, dist))
p + geom_rect(xmin = 10, xmax = 15, ymin = 10, ymax = 50, alpha = 0.5)
```

I see an opaque rectangle.

![geom_rect_no_alpha](https://cloud.githubusercontent.com/assets/197589/14231835/f1785470-f99a-11e5-8ab8-729a6719cb17.png)

The `geom_tile` equivalent is giving me an error, though this looks like a separate issue.

```{r}
p + geom_tile(x = 12.5, width = 2.5, y = 30, height = 20, alpha = 0.5)
## Error in eval(expr, envir, enclos) : object 'x' not found
```

**Comment by hadley** [comment]
Because you're plotting one rectangle for each row in `cars`

**Comment by yutannihilation** [comment]
@richierocks I guess annotation_raster() is what you want :)

**Comment by steveharoz** [comment]
It took me a long time to figure this out when I first started using ggplot. The function you want is `annotate()`.

```
p <- ggplot(cars) + geom_point(aes(speed, dist))
p + annotate("rect", xmin = 10, xmax = 15, ymin = 10, ymax = 50, alpha = 0.5)
```
