### ISSUE TITLE
Facets break grouping of data points

### ISSUE THREAD

**Issue by juliangehring** [hadley/ggplot2#1602]
Using facets seems to ignore the correct grouping of data points for variables in the global environment:

Generate data (x, y), two distinct groups:
```R
library(ggplot2)
n = 10
x = c(rnorm(n), rnorm(n, 5))
y = c(rnorm(n), rnorm(n, 5))
group = rep(c("a", "b"), each = n)
```

Randomize the order of data points and assignment to the respective groups:
```R
idx = sample.int(length(x))
x_s = x[idx]
y_s = y[idx]
group_s = group[idx]
```

Irrespective of the order of data points, I would expect to get a plot where color and facets distinguish the two groups of data points:

![expected](https://cloud.githubusercontent.com/assets/302566/14234121/cf11d536-f9d2-11e5-9289-704cc6b208c0.png)

This is returned both by

```R
qplot(x, y, color = group, facets = ~group)
```

```R
df = data.frame(x = y_s, y = y_s, group = group_s)
qplot(x, y, color = group, facets = ~group, data = df)
```

However, the assignment is incorrect when the "shuffled" data is taken from the global environment: 

```R
qplot(x_s, y_s, color = group_s, facets = ~group_s)
```

![observed](https://cloud.githubusercontent.com/assets/302566/14234123/d73f0800-f9d2-11e5-8e81-f1d5eadf6e9b.png)

Using facets causes the problem here, color has just been added in the examples for better illustration and can also be omitted for reproducing the example. It seems to me that the ordering of the facet variable is not correctly taken into account in the last example. The issue is reproducible with ggplot2 2.1.0 and the latest github master.

**Comment by hadley** [comment]
Yes, don't refer to data in the global environment.

**Comment by juliangehring** [comment]
The [documentation of qplot](http://docs.ggplot2.org/current/qplot.html) suggests otherwise:

> data
> Data frame to use (optional). If not specified, will create one, extracting vectors from the current environment.
