### ISSUE TITLE
Conditional examples are not rendered

### ISSUE THREAD

**Issue by krlmlr** [hadley/ggplot2#1603]
Scroll to the end of http://docs.ggplot2.org/current/geom_histogram.html, only the last plot created by the block starting in if(require("ggplot2movies")) is rendered.

Same when running examples with example().

Most examples (except translate_qplot_lattice) can be handled with an early exit:

```
if (!requireNamespace(...)) stop("Install ... to run example")
```

Can the translate_qplot_lattice example be rewritten to use mtcars only?

**Comment by krlmlr** [comment]
Change examples to not use ggplot2movies.

**Comment by hadley** [comment]
That feels like a staticdocs bug to me

**Comment by krlmlr** [comment]
To me, it looks more like R's default "auto-print only for top-level expressions" feature:

```r
> 1; 2; 3
[1] 1
[1] 2
[1] 3
> { 1; 2; 3 }
[1] 3
```

**Comment by hadley** [comment]
Yeah, but it's a common pattern in examples, so maybe staticdocs should handle it?

**Comment by krlmlr** [comment]
@mmaechler posted a [message](https://stat.ethz.ch/pipermail/r-devel/2016-September/073045.html) to R-devel suggesting a base solution for this problem; I'm not sure what the outcome was.

**Comment by krlmlr** [comment]
`withAutoprint()` is now in R-devel, haven't tried it yet, though. I think examples should always auto-print indeed, at least that's probably what staticdocs should do.

**Comment by hadley** [comment]
Let's move this discussion to staticdocs
