### ISSUE TITLE
Online documentation: HTML table not properly generated from Latex doc 

### ISSUE THREAD

**Issue by dutri001** [hadley/ggplot2#1604]
The HTML table documenting theme options in the current [online doc](http://docs.ggplot2.org/current/theme.html) appears not to be formatted properly (one `<td>` per `<tr>` while Latex table has 2 columns).
I did not manage to track what causes the issue (ggplot2, staticdocs, ...)

**Comment by hadley** [comment]
It's staticdocs, which will probably get an overhaul sometime in the next year
