### ISSUE TITLE
Allow a Vector of Numbers for label_wrap_gen's Width Parameter

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1606]
If `scales = "free"` and `space = "free"` for a faceted plot, it is best to use different label wrapping widths for each factor level. Could a vector of maximum line widths be allowed as input to `width`, or perhaps even better the value `"auto"`, which would choose the best wrapping width for each factor level that minimises the number of lines used but ensures that no lines are too long to fit in the bounding box?

**Comment by hadley** [comment]
I don't really understand what you're asking for, but it sounds complicated, so I'm unlikely to have time to do it.
