### ISSUE TITLE
geom_hex no longer recognizes ..density.. in 2.1.0

### ISSUE THREAD

**Issue by whao89** [hadley/ggplot2#1608]
In 2.1.0:

```
DF <- data.frame(x=rnorm(1000), y=rnorm(1000))
ggplot(DF) + geom_hex(aes(x=x, y=y, fill=..density..))
```

causes error:

```
Error in eval(expr, envir, enclos) : object 'density' not found
```

But in 2.0.0 (or other older versions), we get (random seeds notwithstanding):

![rplot01](https://cloud.githubusercontent.com/assets/5931197/14408000/03a6c73a-feaf-11e5-9aa0-cc655c3350ab.png)

**Comment by mikebirdgeneau** [comment]
I'm also running into this issue; it looks to be related to changes to the file `R/stat-binhex.r` in commit f7cb8986a35f68e62a39991a6e19e071fe02c7ec

The previous code used to return: 
```
# Convert to data frame
  data.frame(
    hexbin::hcell2xy(hb),
    count = hb@count,
    density = hb@count / sum(hb@count, na.rm = TRUE)
  )
```

whereas it now calls: `hexBinSummarise()` which ends up returning the results of `hexbin::hcell2xy()`.

I'm not sure what the most elegant fix for this is to allow the previous functionality to remain.

**Comment by martinschmelzer** [comment]
I really like to have the old functionality back as well. Especially if you work with large samples and you want to plot gradient plots for all observations hexagon binning with `alpha=..count..` was very useful! :)

**Comment by mikebirdgeneau** [comment]
This commit fixes it; but I'm not familiar with the reasons behind the change, so I'm apprehensive to submit a pull request until I understand the implications. 
https://github.com/mikebirdgeneau/ggplot2/commit/cf990038ffd66983a1ad2760f51c73049dcf56da

I basically just added back these lines when preparing the `data.frame` output in `hexBinSummarize()`:
```r
out$count = as.vector(hb@count)
out$density = as.vector(hb@count / sum(hb@count, na.rm = TRUE))
```

**Comment by hadley** [comment]
@mikebirdgeneau looks like just an accidental omission. Can you please subset a PR?
