### ISSUE TITLE
annotate() won't expand when position aesthetics are length 1

### ISSUE THREAD

**Issue by HughParsonage** [hadley/ggplot2#1609]
Min reprex:
```
ggplot() + 
  annotate("text", x = 1, y = 1, label = c("a", "b"))
# Error: Aesthetics must be either length 1 or the same as the data (1): label
```
I am not sure whether it is intentional or not, but it seems the test for lengths only includes the position vectors, when it is reasonable that non position vectors may vary. (Also the error message can be a bit opaque.)

I encountered this issue when debugging some code where the distinction between position and non-position vectors in this test wasn't clear. But a possible genuine application could be a compass rose:

`ggplot() + annotate("text", x = 0, y = 0, label = c("N", "S", "E", "W"), hjust = c(0.5, 0.5, 0, 1), vjust = c(0, 1, 0.5, 0.5))`

 I tried to fork the repo and change the `unequal` definition in `annotation.r`, but it seems this applies to `check_aesthetics` too. I didn't want to change too much without raising the issue.

**Comment by thomasp85** [comment]
See discussion in #1709
