### ISSUE TITLE
Contour labels using direct.label

### ISSUE THREAD

**Issue by luczkovichj** [hadley/ggplot2#1611]
I'm trying to use ggplot2 stat_contour() to make salinity contours on a ggmap object. It is working, but I want the contour lines to have labels.    Here is what I tried using direct.labels() with the Direct labels package: 
ASdata <- read.csv("~/APNEP_SAV/AS_RA/AS_RA_analysis/ASdata.csv") # reads the data from a csv file
ASmap<-get_map(location= c(lon= -75.7,lat=35.9)) #this gets a Google satellite map of Albemarle Sound and stores it 

x=ASdata$longitude # reads in the longtitude stores in x for the contour plot
y=ASdata$latitude # reads in the latitude stores in y for the contour plot
z=ASdata$salinity # reads in salinity stores in z for the contour plot 
gridder <- function(x, y, z, grid.x, grid.y, h.x, h.y) {
  
  # error checking and filling in default values
  
  n <- length(x)
  stopifnot(length(y)==n, length(z)==n)
  
  if(missing(grid.x)) {
    grid.x <- seq(min(x),max(x),length=n)
  }
  
  if(missing(grid.y)) {
    grid.y <- seq(min(y),max(y),length=n)
  }
  
  if(missing(h.x)) {
    h.x <- 1.06*sd(x)/n^(1/5) # silverman's univariate rule of thumb
  }
  
  if(missing(h.y)) {
    h.y <- 1.06*sd(y)/n^(1/5) # silverman's univariate rule of thumb
  }

grid.out <- expand.grid(grid.x,grid.y)  # make a regular grid
x.out <- grid.out[,1]                   # extract the x values
y.out <- grid.out[,2]                   # extract the y values
n.out <- length(x.out)
z.out <- c(NA,n.out)                    # set up a vector for the z values

h.x <- 1.06*sd(x)/n^(1/5) # silverman's univariate rule of thumb
h.y <- 1.06*sd(y)/n^(1/5) # silverman's univariate rule of thumb
for (i in 1:n.out) {                    # fill in the z's using a 2-dim
xdiffs <- x - x.out[i]                # gaussian kernel regression est
ydiffs <- y - y.out[i]
weights <- dnorm(xdiffs,sd=h.x)*dnorm(ydiffs,sd=h.y)
z.out[i] <- sum(z*weights)/sum(weights)
}
return(data.frame(x=x.out,y=y.out,z=z.out))
}
gridded.data <- gridder(x,y,z)
names(gridded.data)<-c("Longitude","Latitude","Salinity")
finalmap<-ggmap(ASmapc)+geom_point(aes(x=longitude,y=latitude,size=pac),color="green",data=ASdata)+
  labs(x="Longitude",y="Latitude")+
  stat_contour(aes(x=Longitude, y=Latitude,z=Salinity,color=..level..), binwidth=0.5,data=gridded.data)+
  scale_color_gradient(low='yellow',high="red")
direct.label(finalmap, "bottom.pieces")

However, I get an error: 
Error: 'ggproto' is not an exported object from 'namespace:ggplot2'

The default for this direct label position setting is also throwing an error:
direct.label(finalmap)
Error in (function (geom, p, L, colvar, ...)  : 
  No default label placement for this type of ggplot.

Is there an alternative way to do this within ggplot2?

**Comment by thomasp85** [comment]
Can you create a reproducible example? (we don't have access to your data)
