### ISSUE TITLE
Plotting SpatialLinesDataFrame connects all of the individual lines

### ISSUE THREAD

**Issue by gcpoole** [hadley/ggplot2#1614]
When I create a SpatialLinesDataFrame using the "sp" package and add it to a ggplot using geom_path(), the end of each Lines object in the SpatialLinesDataFrame is connected to the beginning of the next Lines object.  

    #The following code uses "sp" and "ggplot2" packages
    
    #Make 3 Line objects in a list.
    lineList <- lapply(
      1:3,
      function(.x) {
        m = matrix(data = c(seq(1:30), runif(30)+.x), ncol=2, dimnames = list(character(0), c("long","lat")))
        sp::Line(m)
      }
    )
    
    #create a List of three Lines object, with each Line in a separate Lines object
    LinesList = mapply(sp::Lines, lineList, ID = letters[1:3], SIMPLIFY = F)
    
    #create a SpatialLines object from 
    SL = sp::SpatialLines(LinesList)
    SLDF = sp::SpatialLinesDataFrame(SL, data.frame(ID = c(1,2,3)), match.ID = F)
    
    # plot() renders as expected
    plot(SLDF)
    
    # ggplot() connects the end of each line to the beginning of the following line.
    ggplot2::ggplot(mapping = aes(x = long, y = lat)) + geom_path(data = SLDF)

**Comment by bleutner** [comment]
You need to set the group aesthetic:

```r
ggplot2::ggplot(mapping = aes(x = long, y = lat, group = group)) + geom_path(data = SLDF)

```
