### ISSUE TITLE
geom_dotplot negates free y scale from facet_wrap

### ISSUE THREAD

**Issue by aosmith16** [hadley/ggplot2#1618]
When binning the dotplot on the y axis, the `facet_wrap` free y scale is negated.  This is new behavior - is it by design?
```
library(ggplot2)

p1 = ggplot(mtcars, aes(factor(cyl), mpg)) +
	geom_boxplot() +
	facet_wrap(~am, scales = "free_y")
p1
```
![rplot](https://cloud.githubusercontent.com/assets/11638312/14713723/0b8525a0-0797-11e6-8db6-47ef16359540.png)
`p1 + geom_dotplot(binaxis = "y")`

![rplot01](https://cloud.githubusercontent.com/assets/11638312/14713725/10c5a74c-0797-11e6-89cf-0c32c0576f9d.png)

**Comment by has2k1** [comment]
This is probably due to the removal of `stat_dotplot`. Now the binning is happening across the entire `layer` i.e in `setup_data` instead of happening per `panel`.
