### ISSUE TITLE
Ordering of multiple legends is seemingly random

### ISSUE THREAD

**Issue by DarwinAwardWinner** [hadley/ggplot2#1620]
I am producing a series of plots in a loop that include both a fill legend and a color legend. Oddly, it seems that each plot has the order of the two legends selected randomly, <strike>as you can see here: https://www.dropbox.com/s/rba4qx1g4751ghb/H3K4me3%20Selected%20Sample%20MA%20Plots.pdf?dl=0 </strike> (Example no longer available because I fixed it with the advice below)

Here is the ggplot2 code that I'm using to generate these plots (densdata is a table of pre-computed kernel density estimates):

```R
ggplot(densdata) +
    ## MA Plot density
    geom_raster(aes(x=A, y=M, fill=Density, alpha=AlphaDens),
                interpolate=TRUE) +
    scale_fill_gradientn(colors=suppressWarnings(brewer.pal(Inf, "Blues")),
                         trans=power_trans(1/8),
                         name="Density") +
    scale_alpha_continuous(trans=power_trans(1/40), guide=FALSE) +
    ## Normalization lines
    geom_hline(data=linedata, aes(yintercept=NormFactor, color=NormType)) +
    scale_color_discrete(name="Norm Type") +
    ## Scales
    scale_x_continuous(expand=c(0,0)) +
    scale_y_continuous(expand=c(0,0)) +
    coord_fixed(0.5)
```

(This code is part of a large complex script and running on a large data set. Let me know if you want a reduced test case for reproduction, and I will put in the effort to do so.)

**Comment by has2k1** [comment]
As a work around you can use the `order` parameter of the `guide_legend` & `guide_colobar`  methods.

**Comment by thomasp85** [comment]
Don't think it is a workaround, but the actual vetted approach
