### ISSUE TITLE
geom_contour throws error when ggplot aes uses shape

### ISSUE THREAD

**Issue by huelf** [hadley/ggplot2#1628]
Hi,
the following code
```
library(ggplot2)

testPts <- transform(expand.grid(x=1:10,y=1:5),z=sin(x*y))
testPts$z2 <- as.numeric(testPts$z > 0.5)
testPts$z3 <- as.factor(testPts$z2)

ggplot(data=testPts, aes(x, y, z=z, colour=z, shape=z3)) + geom_point() + 
  geom_contour(data=testPts, aes(x, y, z=z2), colour="blue")
```
produces the error
```
Warning messages:
1: Not possible to generate contour data 
2: In grDevices::contourLines(x = sort(unique(data$x)), y = sort(unique(data$y)),  :
  all z values are equal
3: Not possible to generate contour data 
```
while the following code (with shape=NULL) works fine
```
ggplot(data=testPts, aes(x, y, z=z, colour=z, shape=z3)) + geom_point() + 
  geom_contour(data=testPts, aes(x, y, z=z2, shape=NULL), colour="blue")
```
When I detected the error, I had different data in ggplot and geom_contour. Using testPts in both is just for simplification.
Watch out for the different z-Values in both.
I think geom_contour should work regardless of the shape of ggplot. At least the error message is confusing.
Best Regards
Hans

**Comment by thomasp85** [comment]
This is expected behaviour. `geom_contour ` doesn't understand the shape aesthetic so this should either not be set globally, or turned off as you've done in your working example...

Agree that the error message doesn't convey this very succinctly though

**Comment by hadley** [comment]
Not sure why this isn't triggering the usual error message

**Comment by hadley** [comment]
Oh this is because a discrete shape will cause automatically group, and cause each individual layer to be constant, which is basically what the error message tells you.
