### ISSUE TITLE
stat_binhex weight aesthetic is undocumented

### ISSUE THREAD

**Issue by tdsmith** [hadley/ggplot2#1629]
As of f7cb8986a, stat_binhex accepts a weight aesthetic, but it is effectively undocumented because geom_binhex does not (yet?) explicitly accept a weight aesthetic and stat_binhex does not have independent documentation.

I think it makes sense for geom_binhex to accept a weight aesthetic, unless that's a false promise about other stats?

**Comment by hadley** [comment]
I honestly have no idea how `rd_aesthetics` comes up with the list, but it seems to be correct for the boxplot: `rd_aesthetics("geom", "boxplot")`
