### ISSUE TITLE
posit: new axis.title.[x|y].position option

### ISSUE THREAD

**Issue by hrbrmstr** [hadley/ggplot2#1630]
cc: @janschulz 

(apologies for making even more e-mail notifications for you, Hadley)

Ref: https://twitter.com/janschulz/status/729731091553259520

and 

![image](https://cloud.githubusercontent.com/assets/509878/15122624/f98a7b56-15ed-11e6-8a91-7f5e09233366.png)

(there are others out there with that y-axis-title style and also x-axis ones on lower-right but inside)

this is becoming a new "thing" and—while it's not hard to do with `geom_text|label()` might there be an appetite for

`axis.title.[x|y].position="[in|out]"`

That would make it way easier to specify the titles at the cost of some complexity (I grok that it's easier to place the titles in their own grid element than what would be required in implementing this suggestion).

Is this nouveau labeling style a fad or is it worth supporting? There are also some detractors for these inner labels (my book co-author is one of them).

Opening up a discussion more than anything else.

**Comment by thomasp85** [comment]
So `axis.title.x.position = "in"` would mean that the title would be place on the other side of the axis? And then additional axis theming would determine the placement within the plot area?

Some thoughts: 
- This would not work particularly well with faceting, but people are of course free to make ugly plots so this is not a deal breaker. 
- How should `axis.title.x = element_text(hjust = 1, just = 1), axis.title.x.position = "in"` be interpreted? Place the title in the top right corner of the plot area or still close to the axis?
  * In general we would need to very clearly define what the title is being measured against when in and out
- Placing the title in a fully separate grid element would make the internals very cumbersome. Better to shift the position within the axis grow and unclip if possible

**Comment by hadley** [comment]
I like the basic idea, but agree with Thomas' points.  (i.e. I'd like to see this implemented, but it might be a lot of work)

**Comment by hadley** [comment]
I'm going to close this, but I'd be happy to review a PR if anyone figured out how to implement it
