### ISSUE TITLE
Logarithmic data in a heatmap & accessing the grobs of ggplot2 legends

### ISSUE THREAD

**Issue by phil334** [hadley/ggplot2#1631]
# Logarithmic data in a heatmap & accessing the grobs of ggplot2 legends

## my question:  
Is there still a nice way to convert all the graphic objects of the ggplot2 to a gTree for editing?

## my suggestion:
I use a logarithmic scale in more than half of the figures I produce during my research so I would love to have the support for this transformation on the whole real line in the plots. And of course I'm also willingly to contribute for this.

## the problem
Lets assume we want to plot data ranging from negative to positive values drawn from a long tailed distribution using a heatmap.
```{r}
library( ggplot2 )
library( extRemes )
series.length <- 40
x.data <- y.data <- 1 : series.length
intensity.data <- extRemes::revd( n = series.length^ 2, 0, 100, -.2, type = "GEV" )

plot.data <- data.frame( x = expand.grid( x.data, y.data )[ , 1 ],
                        y = expand.grid( x.data, y.data )[ , 2 ],
                        intensity = intensity.data )
ggplot( data = plot.data, aes( x = x, y = y, fill = intensity ) ) + geom_tile()
```

Usually the bulk of the data is quite interesting but the plot is dominated by the bigger values. Therefore its common to plot them data using a logarithmic scale.

## solution using the alpha value
Since its not possible to perform the logarithm on negative data one has to use the absolute value or have to plot the positive and the negative part separately (using distinct sets of colors.) One way of doing this I found in forums and blogs is using the alpha value of a block in the heatmap to encode the information.

```{r}
plot.data.2 <- plot.data
plot.data.2$sign <- "pos"
plot.data.2$sign[ plot.data.2$intensity < 0 ] <- "neg"
plot.data.2$intensity <- abs( plot.data.2$intensity )
ggplot( data = plot.data.2, aes( x = x, y = y, alpha = intensity, fill = sign ) ) + geom_tile() +
    scale_alpha( trans = "log" ) + scale_fill_manual( values = c( "red", "blue" ) )
                                                     
```

**Issue:**  
- This is not really the most beautiful way of representing the data  
- Its more complicated because there are two legends now  
- The legend for the alpha value is misleading since its a continuous quantity and not a discrete one (and I don't know how to change this)

## my solution by combining two plots
Instead I perform two different plots: one logarithmic for the positive values while setting all negative to NA and one for the absolute values of the negative data while setting all positive to NA. Then I combine all fill values after removing the NA contributions and finally I "combine" the legends using different viewports.

```{r}
## Plot of the positive values
plot.data.pos <- plot.data.neg <- plot.data
plot.data.pos$intensity[ plot.data.pos$intensity < 0 ] <- NA
plot.data.neg$intensity[ plot.data.neg$intensity > 0 ] <- NA
plot.data.neg$intensity <- abs( plot.data.neg$intensity ) 
gg1 <- ggplot( data = plot.data.pos, aes( x = x, y = y, fill = intensity ) ) + geom_tile() +
    scale_fill_gradientn( trans = "log", colours = RColorBrewer::brewer.pal( 6, "Blues" ),
                         na.value = "#000000", label = function( x ) {
                             options( digits = 2 )
                             format( x, scientific = TRUE ) } )
##3 Plot of the negative values
gg2 <- ggplot( data = plot.data.neg, aes( x = x, y = y, fill = intensity ) ) + geom_tile() +
    scale_fill_gradientn( trans = "log", colours = RColorBrewer::brewer.pal( 6, "Reds" ),
                         na.value = "#000000", label = function( x ) {
                             options( digits = 2 )
                             format( -x, scientific = TRUE ) } ) +
    guides( fill = guide_colourbar( reverse = TRUE, title = element_blank() ) )
ggcomb <- gg1 + guides( fill = FALSE )

## combining the fills of the two plots
ggcomb.build <- ggplot_build( ggcomb )
gg2.build <- ggplot_build( gg2 )
ggcomb.fill <- ggcomb.build$data[[ 1 ]]$fill # Fill values for all boxes in the heatmap
gg2.fill <- gg2.build$data[[ 1 ]]$fill
ggcomb.fill[ ggcomb.fill == "#000000" ] <- gg2.fill[ gg2.fill != "#000000" ] #combination
ggcomb.build$data[[ 1 ]]$fill <- ggcomb.fill
ggcomb <- ggplot_gtable( ggcomb.build )

## extracting the legends
legend.1 <- ggplotGrob( gg1 )$grobs[[ 8 ]]
legend.2 <- ggplot_gtable( gg2.build )$grobs[[ 8 ]]

## plotting both the legends and the combined heatmap
grid.newpage()
top.viewport <- viewport( 
    layout = grid.layout( 4, 2, width = unit( c( 1, 5 ), c( "null", "lines" ) ),
                         height = unit( c( 1, 7, 7, 1 ),
                                       c( "null", "lines", "lines", "null" ) ) ) )
heatmap.vp <- viewport( layout.pos.col = 1, layout.pos.row = 1 : 4,
                       name = "heatmap.vp" )
legend.1.vp <- viewport( layout.pos.col = 2, layout.pos.row = 2, name = "legend.1.vp" )
legend.2.vp <- viewport( layout.pos.col = 2, layout.pos.row = 3, name = "legend.2.vp" )
pushViewport( vpTree( top.viewport, vpList( heatmap.vp, legend.1.vp, legend.2.vp ) ) )
seekViewport( "heatmap.vp" )
grid.draw( ggcomb )
seekViewport( "legend.1.vp" )
grid.draw( legend.1 )
seekViewport( "legend.2.vp" )
grid.draw( legend.2 )

```

Looks quite good up to this point and certainly better than the alpha value solution.

## accessing the grobs of the legends
But one thing is bothering me: *I would love to have a solid scale in the legend*.

I tried a lot using ggplotGrob() and read a lot about the underlying grid grob concept. But unfortunately the grobs in the ggplot2 plot are not nicely represented as a gTree object so I can't just take the legend of the negative plot and place it seamlessly below the plot of the positive data.

I found this [https://github.com/hadley/ggplot2/wiki/Editing-raw-grid-objects-from-a-ggplot](description for editing the raw objects) but its deprecated and does not work anymore.

Cheers,
Philipp

**Comment by thomasp85** [comment]
While I have not tried this, It seems that writing a new Scales subclass with a build-in transformation could alleviate you from a lot of the grid mangling?

Maybe even just a custom transformation object?

**Comment by hadley** [comment]
Yes, the right solution to this is a new scale or a new transformation.  I suspect a transformation that does `sign(x) * log(abs(x))`  + `scale_fill_gradient2()` is what you want.
