### ISSUE TITLE
update_geom_defaults does not remove outline for geom bar?

### ISSUE THREAD

**Issue by sjPlot** [hadley/ggplot2#1632]
When I use `update_geom_defaults('bar', list(colour = NULL, size = 0))`, I can't remove the outline for `geom_bar`s. I recall that this worked in older ggplot-versions. Is there something I have missed?

**Comment by ptoche** [comment]
Can you give a MWE? The following works as expected:

    update_geom_defaults("point", list(colour = "red", size = 8))
    ggplot(mtcars, aes(mpg, wt)) + geom_point(colour = "blue")

    update_geom_defaults("bar", list(colour = "red", size = 8))
    ggplot(mtcars, aes(mpg)) + geom_bar(colour = "blue")

I didn't know about ``update_geom_defaults()``. Useful.

It seems that the syntax ``last_plot() + update_geom_defaults(blabla)``, while intuitive,  is not correct.

**Comment by ptoche** [comment]
If you're talking about the vertical lines in ``geom_bar()``, note that ``ggplot(mtcars, aes(mpg)) + geom_bar(color = "red", size = 0)`` , so whatever is causing them to appear, it is not related to ``update_geom_defaults()``, I think.

**Comment by sjPlot** [comment]
Ok, got it. I called `update_geom_defaults('bar', list(colour = NULL, size = 0))` from inside a function, however, when updating this function to work with ggplot > =2.0, I probably made a mistake...
