### ISSUE TITLE
title not centered in the latest commit

### ISSUE THREAD

**Issue by robinlee93** [hadley/ggplot2#1635]
I installed the latest github dev version of ggplot2. Then I found that the title is not centered. Should I do something with hjust?

`devtools::install_github("hadley/ggplot2")`
Skipping install for github remote, the SHA1 (59c503b8) has not changed since last install.

`p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
p + labs(title = "New plot title")`
![image](https://cloud.githubusercontent.com/assets/5751563/15272261/f2f90ce4-1a3e-11e6-8a38-576d1e8e0e00.png)

**Comment by robinlee93** [comment]
Realized the change in the commit. closing it...

**Comment by tr8dr** [comment]
I have pulled the latest from the official CRAN repo and also pulled the latest from source.   I see the same problem, getting the exact same behavior as seen above.

**Comment by thomasp85** [comment]
As described in the release notes the left justification is intentional
