### ISSUE TITLE
annotate_custom png- grob becomes tiled in exported svg

### ISSUE THREAD

**Issue by Athanasiamo** [hadley/ggplot2#1639]
Hey. I have a plot where I import a png through annotate_custom. The plot looks fine, until i open it in inkscape for some minor tweaking. When I ungroup the plot, and try to move the png, it's like just the cropping window moves, with the png underneath being fixed. The image underneath has the png tiled, which I can see when I release the clipping of the image.

Does ggplot tile png's to fill the window? It's making it a hassle to tweak my plots the way I'd like them. I can't repositions the pngs as I would like...

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment]
Unfortunately I have very little control over that.
