### ISSUE TITLE
Changing xlim automatically changes ylim for geom_density

### ISSUE THREAD

**Issue by HeidiSeibold** [hadley/ggplot2#1643]
I have asked this question on stackoverflow:

http://stackoverflow.com/questions/37540592/changing-xlim-automatically-changes-ylim-for-geom-density

The more I think about it the more I think it might be a bug.

Is it enough to have the link to the question or should I post the code here as well?

**Comment by has2k1** [comment]
The area under the curve must sum to 1. So if the tails of the curve (when the x limits are expanded) have small but non-zero density, then the peak density should go down.

**Comment by HeidiSeibold** [comment]
So I guess what is happening is that the bandwidth which stays the same leads to a difference when I change the axis? As a user I find that pretty confusing.

`trim=TRUE` does what I want though, thanks :)
