### ISSUE TITLE
set all geom defaults to a value that means “take from theme”

### ISSUE THREAD

**Issue by flying-sheep** [hadley/ggplot2#1647]
```r
ggplot(d, aes(x, y, shape = s, colour = c)) + geom_point() + theme_something()
```

this will result in everything looking fine except for the “shape” legend, which will be black-colored due to this:

```r
GeomPoint$default_aes$colour == 'black'
```

is there any reason why this color is hardcoded instead of being taken from the theme?

if not, i propose to replace the `colour` default value of all geoms that currently have `"black"` with `waiver()`, and make a `waiver()` in this position mean “take from the theme”

(via jrnold/ggthemes#63)

**Comment by hadley** [comment]
Yes, because currently the defaults are applied when the layer is created, not when the plot is drawn. Changing this would be a lot of work.

**Comment by flying-sheep** [comment]
too bad. i wonder, though: why does “it’s a lot of work to do the right/obvious thing” prompt you to close the issue? shouldn’t it stay open until someone finds the time to do all this work?

**Comment by flying-sheep** [comment]
hi @hadley, i just encountered this again. black legend points on dark grey legend background.

could you please reopen this issue?

**Comment by hadley** [comment]
It's not possible, sorry.

**Comment by flying-sheep** [comment]
sorry, i don’t understand in which way you meant that:

is it just impossible to reopen this issue per your issue reopening policy or?

or is the problem too hard for you to consider? would you accept someone else trying their hand at it?

or is it something else?
