### ISSUE TITLE
geom_histogram: wrong bins?

### ISSUE THREAD

**Issue by collioud** [hadley/ggplot2#1651]
Hello,

I am using ggplot 2.1.0 to plot histograms, and I have an unexpected behaviour concerning the bins.
I put here an example with left-closed bins (i.e. [ 0, 0.1[ ) with a binwidth of 0.1. 

```
mydf <- data.frame(myvar=c(-1,-0.5,-0.4,-0.1,-0.1,0.05,0.1,0.1,0.25,0.5,1))
myplot <- ggplot(mydf, aes(myvar)) + geom_histogram(aes(y=..count..),binwidth = 0.1, boundary=0.1,closed="left")
myplot
ggplot_build(myplot)$data[[1]]
```
On this example, one may expect the value -0.4 to be within the bin [-0.4, -0.3[, but it falls instead (mysteriously) in the bin [-0.5,-0.4[. Same thing for the value -0.1 which falls in [-0.2,-0.1[ instead of [-0.1,0[...etc.

Is there something here I do not fully understand (especially with the new "center" and "boundary" params)? Or is ggplot2 doing weird things there?

Thanks in advance,
Best regards,
Arnaud

PS: Also asked here: http://stackoverflow.com/questions/37876096/geom-histogram-wrong-bins

**Comment by ecoRoland** [comment]
I suspect there is not much that can be done. This is probably an example of [R-FAQ 7.31](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f).

**Comment by collioud** [comment]
That would be...unfortunate. 
However I do not have the same result with ggplot 2.1.0 (http://i66.tinypic.com/1sy2w4.jpg) and ggplot 0.9.3 (http://i65.tinypic.com/4rsvev.jpg), which is very disturbing.
By looking at both graphs, we can see that ggplot 0.9.3 behaves as expected.

**Comment by collioud** [comment]
Well...I suppose I have to stay on ggplot version 0.9.3.

**Comment by ptoche** [comment]
It looks like a piece of code originally borrowed from ``base::hist``, intended to deal with rounding errors, was removed in recent versions of ``ggplot2`` (look for function ``diddle``).  Not sure if that is the problem. I have made comments on stackoverflow, where it is more convenient to post images, even if the discussion probably belonged here to begin with ...

**Comment by collioud** [comment]
Thanks!
But by looking into bin.R, I guess the param "fuzz" took the place of "diddle". Could you please confirm this?

**Comment by collioud** [comment]
The `boundary` param solves indeed this problem if set slightly smaller than the binwidth. But this is not a  'clean' nor logical solution...

**Comment by ptoche** [comment]
I've tried to debug the problem, but I'm not familiar at all with ``ggplot2`` (I'm just a user). It looks to me like the following: the latest ggplot2 does indeed correctly calculate the ``fuzzy`` parameters to the ``bins``. However, it seems to me that the fuzziness disappears at some point, because a ``print(bins$fuzzy)`` doesn't (appear to) show the fuzziness anymore at some point down the line. I spent about an hour on this without cracking it, so I'll give it a rest. Someone else (or my future self) should be able to find the issue by perusing the code. I will copy-paste my preliminary investigations below, in a separate message. To be continued...

**Comment by ptoche** [comment]
################################################################################

    ### Experiment 4: Patch the bins function
    library("ggplot2")
    bins <- function (breaks, closed = c("right", "left"), fuzz = 1e-08 * 
        stats::median(diff(breaks))) 
    {
        stopifnot(is.numeric(breaks))
        closed <- match.arg(closed)
        breaks <- sort(breaks)
        if (closed == "right") {
            fuzzes <- c(-fuzz, rep.int(fuzz, length(breaks) - 1))
        }
        else {
            fuzzes <- c(rep.int(-fuzz, length(breaks) - 1), fuzz)
        }

    ## PATCH
      print(breaks)
    ##   [1] -1.00 -0.95 -0.90 -0.85 -0.80 -0.75 -0.70 -0.65
    ##   [9] -0.60 -0.55 -0.50 -0.45 -0.40 -0.35 -0.30 -0.25
    ##  [17] -0.20 -0.15 -0.10 -0.05  0.00  0.05  0.10  0.15
    ##  [25]  0.20  0.25  0.30  0.35  0.40  0.45  0.50  0.55
    ##  [33]  0.60  0.65  0.70  0.75  0.80  0.85  0.90  0.95
    ##  [41]  1.00

    ## PATCH
      print(breaks + fuzzes)  
    ##   [1] -1.0e+00 -9.5e-01 -9.0e-01 -8.5e-01 -8.0e-01
    ##   [6] -7.5e-01 -7.0e-01 -6.5e-01 -6.0e-01 -5.5e-01
    ##  [11] -5.0e-01 -4.5e-01 -4.0e-01 -3.5e-01 -3.0e-01
    ##  [16] -2.5e-01 -2.0e-01 -1.5e-01 -1.0e-01 -5.0e-02
    ##  [21] -5.0e-10  5.0e-02  1.0e-01  1.5e-01  2.0e-01
    ##  [26]  2.5e-01  3.0e-01  3.5e-01  4.0e-01  4.5e-01
    ##  [31]  5.0e-01  5.5e-01  6.0e-01  6.5e-01  7.0e-01
    ##  [36]  7.5e-01  8.0e-01  8.5e-01  9.0e-01  9.5e-01
    ##  [41]  1.0e+00

        structure(list(breaks = breaks, fuzzy = breaks + fuzzes, 
            right_closed = closed == "right"), class = "ggplot2_bins")
      ## THIS IS THE PATCHED FUNCTION
    }
    assignInNamespace("bins", bins, ns = "ggplot2")

    # ggplot2:::bins # check
    df <- data.frame(var = seq(-100,100,10)/100)
    p <- ggplot(data = df, aes(x = var)) + geom_histogram(aes(y = ..count..), binwidth = 0.05, boundary = 1, closed = "left")
    p


    ################################################################################

    ### Experiment 5: Patch the bin_vector function
    library("ggplot2")
    bin_vector <- function(x, bins, weight = NULL, pad = FALSE) {
      stopifnot(ggplot2:::is_bins(bins))

      if (all(is.na(x))) {
        return(ggplot2:::bin_out(length(x), NA, NA, xmin = NA, xmax = NA))
      }

      if (is.null(weight)) {
        weight <- rep(1, length(x))
      } else {
        weight[is.na(weight)] <- 0
      }

    ## PATCH
      print(weight)
    ## [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

    ## PATCH
      print(str(bins))
    ##  List of 3
    ##   $ breaks      : num [1:41] -1 -0.95 -0.9 -0.85 -0.8 -0.75 -0.7 -0.65 -0.6 -0.55 ...
    ##   $ fuzzy       : num [1:41] -1 -0.95 -0.9 -0.85 -0.8 ...
    ##   $ right_closed: logi FALSE
    ##   - attr(*, "class")= chr "ggplot2_bins"
    ##  NULL

    ## shouldn't bins$fuzzy be fuzzy? Problem appears to be in bins...

    ## PATCH
      print(str(bins$fuzzy))
    ## num [1:41] -1 -0.95 -0.9 -0.85 -0.8 ...
 
    ## PATCH
      print(bins$breaks)
    ##   [1] -1.00 -0.95 -0.90 -0.85 -0.80 -0.75 -0.70 -0.65
    ##   [9] -0.60 -0.55 -0.50 -0.45 -0.40 -0.35 -0.30 -0.25
    ##  [17] -0.20 -0.15 -0.10 -0.05  0.00  0.05  0.10  0.15
    ##  [25]  0.20  0.25  0.30  0.35  0.40  0.45  0.50  0.55
    ##  [33]  0.60  0.65  0.70  0.75  0.80  0.85  0.90  0.95
    ##  [41]  1.00

    ## PATCH
      print(bins$right_closed)
    ## [1] FALSE

      bin_idx <- cut(x, bins$breaks, right = bins$right_closed,
        include.lowest = TRUE)

    ## PATCH
      print(dput(bin_idx)) ## should I not see fuzz here?
    ##    bin_idx <- structure(c(1L, 3L, 5L, 7L, 9L, 11L, 12L, 14L, 16L, 18L, 21L, 
    ##  22L, 24L, 26L, 28L, 31L, 32L, 34L, 37L, 38L, 40L), .Label = c("[-1,-0.95)", 
    ##  "[-0.95,-0.9)", "[-0.9,-0.85)", "[-0.85,-0.8)", "[-0.8,-0.75)", 
    ##  "[-0.75,-0.7)", "[-0.7,-0.65)", "[-0.65,-0.6)", "[-0.6,-0.55)", 
    ##  "[-0.55,-0.5)", "[-0.5,-0.45)", "[-0.45,-0.4)", "[-0.4,-0.35)", 
    ##  "[-0.35,-0.3)", "[-0.3,-0.25)", "[-0.25,-0.2)", "[-0.2,-0.15)", 
    ##  "[-0.15,-0.1)", "[-0.1,-0.05)", "[-0.05,0)", "[0,0.05)", "[0.05,0.1)", 
    ##  "[0.1,0.15)", "[0.15,0.2)", "[0.2,0.25)", "[0.25,0.3)", "[0.3,0.35)", 
    ##  "[0.35,0.4)", "[0.4,0.45)", "[0.45,0.5)", "[0.5,0.55)", "[0.55,0.6)", 
    ##  "[0.6,0.65)", "[0.65,0.7)", "[0.7,0.75)", "[0.75,0.8)", "[0.8,0.85)", 
    ##  "[0.85,0.9)", "[0.9,0.95)", "[0.95,1]"), class = "factor")

      bin_count <- as.numeric(tapply(weight, bin_idx, sum, na.rm = TRUE))
      bin_count[is.na(bin_count)] <- 0

    ## PATCH
      print(bin_count) ## The bin_count is incorrect
    ##  [1] 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1
    ##  [25] 0 1 0 1 0 0 1 1 0 1 0 0 1 1 0 1

      bin_x <- (bins$breaks[-length(bins$breaks)] + bins$breaks[-1]) / 2
      bin_widths <- diff(bins$breaks)

      # Pad row of 0s at start and end
      if (pad) {
        bin_count <- c(0, bin_count, 0)

        width1 <- bin_widths[1]
        widthn <- bin_widths[length(bin_widths)]

        bin_widths <- c(width1, bin_widths, widthn)
        bin_x <- c(bin_x[1] - width1, bin_x, bin_x[length(bin_x)] + widthn)
      }

      # Add row for missings
      if (any(is.na(bins))) {
        bin_count <- c(bin_count, sum(is.na(bins)))
        bin_widths <- c(bin_widths, NA)
        bin_x <- c(bin_x, NA)
      }

      ggplot2:::bin_out(bin_count, bin_x, bin_widths)
      ## THIS IS THE PATCHED FUNCTION
    }
    assignInNamespace("bin_vector", bin_vector, ns = "ggplot2")
    df <- data.frame(var = seq(-100,100,10)/100)
    p <- ggplot(data = df, aes(x = var)) + geom_histogram(aes(y = ..count..), binwidth = 0.05, boundary = 1, closed = "left")
    p



    ################################################################################

    ### Experiment 6: Patch the bin_breaks function
    library("ggplot2")
    bin_breaks <- function(breaks, closed = c("right", "left")) {
    ## PATCH
      print(breaks)
    ##     [1] -1.00 -0.95 -0.90 -0.85 -0.80 -0.75 -0.70 -0.65
    ##   [9] -0.60 -0.55 -0.50 -0.45 -0.40 -0.35 -0.30 -0.25
    ##  [17] -0.20 -0.15 -0.10 -0.05  0.00  0.05  0.10  0.15
    ##  [25]  0.20  0.25  0.30  0.35  0.40  0.45  0.50  0.55
    ##  [33]  0.60  0.65  0.70  0.75  0.80  0.85  0.90  0.95
    ##  [41]  1.00
      ggplot2:::bins(breaks, closed)
      ## THIS IS THE PATCHED FUNCTION
    }
    assignInNamespace("bin_breaks", bin_breaks, ns = "ggplot2")
    df <- data.frame(var = seq(-100,100,10)/100)
    p <- ggplot(data = df, aes(x = var)) + geom_histogram(aes(y = ..count..), binwidth = 0.05, boundary = 1, closed = "left")
    p



    ################################################################################

    ### Experiment 7: Patch the StatBin ggproto object
    library("ggplot2")
    StatBin <- ggproto("StatBin", Stat,
      setup_params = function(data, params) {
        if (!is.null(data$y) || !is.null(params$y)) {
          stop("stat_bin() must not be used with a y aesthetic.", call. = FALSE)
        }
        if (is.integer(data$x)) {
          stop('StatBin requires a continuous x variable the x variable is discrete. Perhaps you want stat="count"?',
            call. = FALSE)
        }

        if (!is.null(params$drop)) {
          warning("`drop` is deprecated. Please use `pad` instead.", call. = FALSE)
          params$drop <- NULL
        }
        if (!is.null(params$origin)) {
          warning("`origin` is deprecated. Please use `boundary` instead.", call. = FALSE)
          params$boundary <- params$origin
          params$origin <- NULL
        }
        if (!is.null(params$right)) {
          warning("`right` is deprecated. Please use `closed` instead.", call. = FALSE)
          params$closed <- if (params$right) "right" else "left"
          params$right <- NULL
        }
        if (!is.null(params$width)) {
          stop("`width` is deprecated. Do you want `geom_bar()`?", call. = FALSE)
        }
        if (!is.null(params$boundary) && !is.null(params$center)) {
          stop("Only one of `boundary` and `center` may be specified.", call. = FALSE)
        }

        if (is.null(params$breaks) && is.null(params$binwidth) && is.null(params$bins)) {
          message_wrap("`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.")
          params$bins <- 30
        }

        params
      },

      compute_group = function(data, scales, binwidth = NULL, bins = NULL,
                               center = NULL, boundary = NULL,
                               closed = c("right", "left"), pad = FALSE,
                               # The following arguments are not used, but must
                               # be listed so parameters are computed correctly
                               breaks = NULL, origin = NULL, right = NULL,
                               drop = NULL, width = NULL) {
    ## PATCH
          print(str(bins))
    ## NULL

        if (!is.null(breaks)) {
          bins <- ggplot2:::bin_breaks(breaks, closed) 
    ## PATCH
            print("loop level 1")
            print(str(bins))
        } else if (!is.null(binwidth)) {
          bins <- ggplot2:::bin_breaks_width(scales$x$dimension(), binwidth, center = center,
            boundary = boundary, closed = closed)
    ## PATCH
            print("loop level 2")
            print(str(bins))
    ##  [1] "loop level 2"
    ##  List of 3
    ##   $ breaks      : num [1:41] -1 -0.95 -0.9 -0.85 -0.8 -0.75 -0.7 -0.65 -0.6 -0.55 ...
    ##   $ fuzzy       : num [1:41] -1 -0.95 -0.9 -0.85 -0.8 ...
    ##   $ right_closed: logi FALSE
    ##   - attr(*, "class")= chr "ggplot2_bins"
 
        } else {
          bins <- ggplot2:::bin_breaks_bins(scales$x$dimension(), bins, center = center,
            boundary = boundary, closed = closed)
    ## PATCH
            print("loop level 3")
            print(str(bins))
        }

        ggplot2:::bin_vector(data$x, bins, weight = data$weight, pad = pad)
      },

      default_aes = ggplot2:::aes(y = ..count..),
      required_aes = c("x")
    )

    assignInNamespace("StatBin", StatBin, ns = "ggplot2")
    df <- data.frame(var = seq(-100,100,10)/100)
    p <- ggplot(data = df, aes(x = var)) + geom_histogram(aes(y = ..count..), binwidth = 0.05, boundary = 1, closed = "left")
    p

**Comment by ptoche** [comment]
I have attempted to track the ``fuzzy`` parameters via all the functions they are processed by. So far, they appear to be correctly computed and saved under ``bins$fuzzy``. But I don't see where/if they are actually used. Consider the function ``bin_vector``, copied below.  If you replace ``bins$breaks`` with ``bins$fuzzy``, at the location indicated below, you get the expected plot. So my current favoured hypothesis is that ``bin_vector`` is supposed to condition on something and return ``bins$breaks`` sometimes and ``bins$fuzzy`` at other times. below at the point I indicate. Expert opinion will be appreciated at this point. 

        ggplot2:::bin_vector
    function (x, bins, weight = NULL, pad = FALSE) 
    {
        stopifnot(is_bins(bins))
        if (all(is.na(x))) {
            return(bin_out(length(x), NA, NA, xmin = NA, xmax = NA))
        }
        if (is.null(weight)) {
            weight <- rep(1, length(x))
        }
        else {
            weight[is.na(weight)] <- 0
        }

        bin_idx <- cut(x, bins$breaks, right = bins$right_closed, 
            include.lowest = TRUE) ## REPLACE bins$breaks with bins$fuzzy 
                                                   ## TO GET EXPECTED OUTPUT
                                                   ## CONDITIONAL MISSING HERE?

        bin_count <- as.numeric(tapply(weight, bin_idx, sum, na.rm = TRUE))
        bin_count[is.na(bin_count)] <- 0
        bin_x <- (bins$breaks[-length(bins$breaks)] + bins$breaks[-1])/2
        bin_widths <- diff(bins$breaks)
        if (pad) {
            bin_count <- c(0, bin_count, 0)
            width1 <- bin_widths[1]
            widthn <- bin_widths[length(bin_widths)]
            bin_widths <- c(width1, bin_widths, widthn)
            bin_x <- c(bin_x[1] - width1, bin_x, bin_x[length(bin_x)] + 
                widthn)
        }
        if (any(is.na(bins))) {
            bin_count <- c(bin_count, sum(is.na(bins)))
            bin_widths <- c(bin_widths, NA)
            bin_x <- c(bin_x, NA)
        }
        bin_out(bin_count, bin_x, bin_widths)
    }
    <environment: namespace:ggplot2>

**Comment by ptoche** [comment]
This is what I think is going on: in the older versions of ``ggplot2``, the ``fuzzy`` breaks were assigned to ``breaks`` no questions asked:

    fuzzybreaks <- sort(breaks) + fuzz

This is **line 123**  in the **old ``bin`` function** located in ``stat-bin.r``  

In the current implementation, the ``bins`` structure holds both the non-fuzzy breaks, named ``bins$breaks`` as well as the fuzzy breaks, named ``bins$fuzzy``. However, **correct me if I'm wrong** it appears that nothing is done of ``bins$fuzzy`` and only the non-fuzzy ``bins$breaks`` are passed to the ``bin_vector`` function and ultimately to ``geom_histogram``.

**Comment by collioud** [comment]
Indeed, `bin$fuzzy` does not seem to be used anywhere.
I hope Hadley (or anyone competent) will enlighten us on this topic...

**Comment by hadley** [comment]
More minimal reprex:

```R
mydf <- data.frame(x = c(-1, -0.5, -0.4, -0.1, -0.1, 0.05, 0.1, 0.1, 0.25, 0.5, 1))
p <- ggplot(mydf, aes(x)) + 
  geom_histogram(binwidth = 0.1, boundary = 0.1, closed = "left")
layer_data(p) %>% subset(count > 0) %>% .[1:5]
```

Looks like a FP bug. @collioud would you mind trying to make the example even more minimal? (i.e. progressively remove the points in `x` until the problem no longer appears). That'll make it easier to find and fix

**Comment by ptoche** [comment]
@hadley , have you seen this ?

http://stackoverflow.com/questions/37876096/geom-histogram-wrong-bins

**Comment by ptoche** [comment]
do you remember when you intended to use ``bins$breaks`` and when you intended to use ``bins$fuzzy``? 

Apart from having located the line where ``bins$fuzzy`` might have been intended, it's not much of a PR as is, I think (never done a PR before)...

**Comment by hadley** [comment]
I don't remember anything about that code :(

**Comment by ptoche** [comment]
I'm not surprised, I'm struggling too and it was only one month ago I was reading it! ;-)  

My understanding of the situation is this: there was a major refactoring of the code. In the earlier version, something like ``bins$fuzzy`` was used (under a different name); in the revised version, both a ``bins$breaks`` and a ``bins$fuzzy`` coexist, but only the former is used. I would guess that substituting ``bins$fuzzy`` for ``bins$breaks`` would be reverting to something close to the earlier implementation. But since you took the trouble of carrying both the non-fuzzy ``bins$breaks`` and their fuzzy counterpart ``bins$fuzzy``, you probably intended to use both based on whether a particular condition was satisfied (hypothethical condition not currently in the code).

**Comment by thomasp85** [comment]
It seems this is a simple oversight during refactoring - exchanging `bins$breaks` for `bin$fuzzy` should solve this... Can't see any negative impact. (as @hadley can't remember I think it is safe to say that fixing by reverting to old behaviour is the best approach)

I can fix this in a PR, but if you want to get PR experience @ptoche this is a simple case that you can learn something from (and I will help you get it right)

**Comment by ptoche** [comment]
Thanks for the feedback Thomas, I was away from the internet (partly at least) during my summer break, just getting back to the 'real' world: yes I'd love to give PR a try. I'll read up on it first and get back to you.

**Comment by ptoche** [comment]
Thanks Hadley, Thanks Thomas, I've had no time to follow up with a PR, so thanks!
