### ISSUE TITLE
Strange scale_*_datetime / breaks / date_breaks timezone offset (cf. #824)

### ISSUE THREAD

**Issue by Sylvain-Frey** [hadley/ggplot2#1653]
When setting `breaks` in a `scale_x_datetime` (or `scale_y_datetime`), ticks on the axis end up shifted by a certain number of hours.

Issue previously described and workaround suggested at: https://github.com/hadley/ggplot2/issues/824

Workaround: set the timezone explicitly in every use of as.POSIX* function.

Example: the following code generates shifted graphs:

```
library(ggplot2)
library(scales)

mydata <- ... as.POSIXct("12:34:56", format = "%H:%M:%S")) ...

ggplot(mydata, ...) +
   scale_y_datetime(limits = c(as.POSIXct("00:00:00", format = "%H:%M:%S"),
                              as.POSIXct("23:59:59", format = "%H:%M:%S")),
                   breaks = seq(as.POSIXct("00:00:00", format = "%H:%M:%S"),
                                as.POSIXct("24:00:00", format = "%H:%M:%S"),
                                6*3600),
                   labels = date_format("%H:%M")) + 
   ...
```  

The following variant generates correct graphs (assuming using the local timezone is correct):

```
mydata <- ... as.POSIXct("12:34:56", format = "%H:%M:%S", tz=Sys.timezone())) ...

ggplot(mydata, ...) +
   scale_y_datetime(limits = c(as.POSIXct("00:00:00", format = "%H:%M:%S", tz=Sys.timezone()),
                              as.POSIXct("23:59:59", format = "%H:%M:%S", tz=Sys.timezone())),
                   breaks = seq(as.POSIXct("00:00:00", format = "%H:%M:%S", tz=Sys.timezone()),
                                as.POSIXct("24:00:00", format = "%H:%M:%S", tz=Sys.timezone()),
                                6*3600),
                   labels = date_format("%H:%M", tz=Sys.timezone())) + 
...
```

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.
