### ISSUE TITLE
Reflected tic marks

### ISSUE THREAD

**Issue by jrevenaugh** [hadley/ggplot2#1658]
In many branches of the physical sciences, the plotting convention is to have tic marks inside the panel AND reflect them across the boundaries(i.e,  tick marks on top, right, bottom, left, all facing inward), with labels on only one side.

This can be done using gtable, but it would be wonderful to have the option to do it directly through ggplot.

**Comment by hadley** [comment]
I think it is a really bad idea to put guides in the plot space.  I have seen so many matlab graphics where the guides are overplotted with the data points.
