### ISSUE TITLE
Behavior of geom_vline depends on order that geoms are added

### ISSUE THREAD

**Issue by expersso** [hadley/ggplot2#1659]
In the following example, geom_vline works fine if it is applied after geom_point, but not if it is applied before:

```
df <-
  structure(
    list(
      date = structure(
        c(
          868485600,
          873928800,
          876348000,
          878770800,
          884214000,
          886633200,
          889052400,
          892072800,
          894492000,
          896911200
        ),
        class = c("POSIXct", "POSIXt"),
        tzone = "CET"
      ),
      length = 1:10
    ),
    .Names = c("date", "n"),
    class = c("data.frame"),
    row.names = c(NA,-10L)
  )

# this works
ggplot(df, aes(x = date, y = n)) + 
  geom_point() +
  geom_vline(xintercept = as.numeric(df$date[5]))

# This does not work
ggplot(df, aes(x = date, y = n)) + 
  geom_vline(xintercept = as.numeric(df$date[5])) +
  geom_point()

# Error in as.POSIXct.numeric(value) : 'origin' must be supplied
```

**Comment by has2k1** [comment]
`geom_vline`, `geom_hline` and `geom_abline` are "guide" geoms. They have no clue about the dimensions (extents/limits) of the plot panel. You need another geom (other geoms) to give the plot some dimensions then you can put a line on it.

To see another implication of this is to try to put a line outside the automatic limits of the plot. It will not be shown.

```R
bignumber <- 10e6   # I don't know if this is big enough
ggplot(df, aes(x = date, y = n)) +
  geom_point() +
  geom_vline(xintercept = as.numeric(df$date[5])+bignumber)
```

**Comment by ChandlerLutz** [comment]
A workaround is to manually set the breaks to give the plot dimensions. For example, the following works:

ggplot(df, aes(x = date, y = n)) +
  geom_vline(xintercept = as.numeric(df$date[5])) +
    geom_point() +
    scale_x_datetime(breaks = df$date)

see ?scale_date
