### ISSUE TITLE
[Feature request] gglocate

### ISSUE THREAD

**Issue by jan-glx** [hadley/ggplot2#1660]
Now that `ggmap`'s `gglocate` [stopped working]( https://github.com/dkahle/ggmap/issues/87)  and I see no way to fix it, can you find the time to implement it (where it belongs -- in `ggplot2`)? That would be really cool.

**Comment by hadley** [comment]
I just don't have the time for this unfortunately, and it's not high on priority list given that you can do it with shiny.
