### ISSUE TITLE
Better documentation webpages?

### ISSUE THREAD

**Issue by jjchern** [hadley/ggplot2#1662]
For some reason, I found the new [ggplot-for-python docs](http://yhat.github.io/ggplot/docs.html) a bit more friendly for new users.

![screen shot 2016-07-07 at 1 21 10 pm](https://cloud.githubusercontent.com/assets/11262574/16664473/be16fe4c-4445-11e6-8447-fee0ef106a2e.png)

Here's the rationale for [the new docs from yhat](http://blog.yhat.com/posts/new-ggplot.html):

> One thing we realized with previously released of ggplot was that the documentation wasn't right. We added docs for every geom, tried making function docstrings more descriptive, and even making the docs prettier. Unfortunately, none of this really worked. What we realized was that while we were adding more documentation, it was all API driven (i.e. describing how individual functions worked). When what people really needed help with was how to do particular tasks using ggplot (i.e. "How do I make a histogram?").

> So with the new release we're taking a more task-oriented approach to our docs. That means lots of "How To's", loads of examples, and very visual docs. The new docs use jupyter notebooks, which makes it really easy to contribute examples and update for new releases changes.

**Comment by hadley** [comment]
That's the role that the ggplot2 book fills currently, and I don't have time for a big reworking on the docs, sorry.
