### ISSUE TITLE
controlling plot order for visual objects with multiple geometries

### ISSUE THREAD

**Issue by geotheory** [hadley/ggplot2#1672]
I'm wondering if [this SO question](http://stackoverflow.com/questions/33989131/controlling-plot-order-for-visual-objects-with-multiple-geometries-in-ggplot2) could possibly get a definitive answer.  I'm doing a lot of graphics plotting with multiple geoms for individual data points (it makes sense when you see it) and am dealing with (a) very slow code and (b) hitting limits expression nesting (even after `options(expressions= 500000)`).  Is there any way to control the plot order by data instead of geom?

**Comment by hadley** [comment]
Geoms are generally constructed in the order in which they are seen in the data, so just change the order of the rows of data.

**Comment by geotheory** [comment]
Ah but the plot order is fine. To illustrate what I mean, say p is polygon and l is line the current plot order is: 

    p p p p p l l l l l

whereas I need to do:

    p l p l p l p l p l

Is that outside ggplot's functionality?

**Comment by hadley** [comment]
Oh yes, that's out of scope unfortunately.

**Comment by geotheory** [comment]
OK thanks Hadley. Guess I'm stuck with looping :)
