### ISSUE TITLE
Only generate one warning about shapes

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1674]
```R
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

not two!

**Comment by hadley** [comment]
In fact you'll get one warning for each layer + one for the legend (`guide_train.legend`):

```R
ggplot(mpg, aes(x = displ, y = hwy, shape = class)) + 
  geom_point() + 
  geom_point()
```

Maybe `DiscreteScale$map()` needs to memoise the call to `palette()`?

**Comment by thomasp85** [comment]
You want to use the memoise package or brew up some solution inside the ScaleDiscrete class?

**Comment by hadley** [comment]
I think do something internal - i.e. have a field that stores the palette.  But I'm not sure what happens if `n` changes, or even if that's possible. Also I don't remember exactly the semantics of scales - I think that would also need a tweak to the clone method.

**Comment by hadley** [comment]
I think we need a `cache_palette()` method that records both the palette and the number of levels. If the number is different in a future call, warn, and re-generate. That will at least allow us to see if and when `n` differs.
