### ISSUE TITLE
Fill in ggplot2 is always red, regardless of what colour is actually specified.

### ISSUE THREAD

**Issue by a-hurst** [hadley/ggplot2#1675]
For whatever reason, whenever I try to specify a fill colour for a violin plot it always renders as a pastel red, regardless of what I tell it. Here is some simple code that reproduces the bug for me in a fresh R session:

```
library(ggplot2)

blah <- rnorm(2000, 3, 1.5)
blah2 <- rep("test", times=2000)
df = data.frame(a = blah2, b = blah)
ggplot(data = df) + geom_violin(aes(x = a, y = b, fill="grey80"))

```
Running this code gives me this:

![screen shot 2016-07-21 at 11 21 27 am](https://cloud.githubusercontent.com/assets/18648066/17026167/939112c0-4f35-11e6-8b9f-480cba62ef2f.png)

This happens no matter which fill colour I specify. When I don't specify a fill, the fill defaults to white as expected:

![screen shot 2016-07-21 at 11 23 31 am](https://cloud.githubusercontent.com/assets/18648066/17027811/cf1abe8a-4f3b-11e6-9a73-c4dc266df029.png)

This happens with the official CRAN binary in the R GUI.app as well as with R 3.3.1 installed from Homebrew. I also did a fresh install of ggplot2 on a fresh install of R when I generated the above graphs. Any ideas what's going on?

Platform info:

```
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)
```

**Comment by jac0bean9** [comment]
You need fill to be outside aes, i.e..:

`library(ggplot2)

blah <- rnorm(2000, 3, 1.5)
blah2 <- rep("test", times=2000)
df = data.frame(a = blah2, b = blah)
ggplot(data = df) + geom_violin(fill="grey80", aes(x = a, y = b))`

![image](https://cloud.githubusercontent.com/assets/4897195/17028121/254f7b5c-4f2c-11e6-8354-446dff3ffdcc.png)

**Comment by a-hurst** [comment]
Thanks, it works properly now! Any reason it defaults to that red instead of throwing an error or something if it's defined within aes()? Had it thrown an error I would have been much less bewildered.

**Comment by steveharoz** [comment]
By putting the values in `aes`, you're basically generating a new factor variable and a legend.

```
ggplot(mtcars)+
    geom_point(aes(x = mpg, y = wt, color = 'blah'))+
    geom_point(aes(x = mpg, y = drat, color = 'asdfasdf'))+
    scale_color_manual(values = c('blah' = 'blue', 'asdfasdf' = 'red'))
```
![image](https://cloud.githubusercontent.com/assets/2257540/17031289/e234f51a-4f38-11e6-9cd7-376b5679e0ed.png)
Notice the legend.

If you set the values outside of aes, ggplot2 won't make the legend for you.

```
ggplot(mtcars)+
  geom_point(aes(x = mpg, y = wt), color = 'blue')+
  geom_point(aes(x = mpg, y = drat), color = 'red')
```
![image](https://cloud.githubusercontent.com/assets/2257540/17031352/4cfa5340-4f39-11e6-9ece-97e1698eb8e1.png)

**Comment by a-hurst** [comment]
Ah, that makes perfect sense. Thanks again for your help!

**Comment by has2k1** [comment]
@ipstone, if you are new to ggplot2 stay away from qplot.

> Might I ask why it makes sense?

The aesthetic values in `aes()` are *data* which is properly fit to a scale, hence it must be interpreted with a guide/legend. Aesthetic values outside `aes()` are direct settings which by-pass the scaling mechanism hence not need for a guide/legend.
