### ISSUE TITLE
Add option for "impartial binning" for histograms

### ISSUE THREAD

**Issue by rpruim** [hadley/ggplot2#1680]
Traditionally (i.e., in `hist()`) one must choose between left-leaning and right-leaning binning with `right = FALSE` or `right = TRUE`.  A more balanced option would be to allow `right = 0.5`.  Under this option, data values exactly on a bin border would count has 0.5 in the bin to the left and 0.5 in the bin to the right.

Naive implementation is easy: 
```r
newcounts <- 
  right       * hist(..., right =  TRUE)$counts + 
  (1 - right) * hist(..., right = FALSE)$counts
```
This would work for other values of `right` a well, although it is less clear that other values are useful.  Setting `right = TRUE` or `right = FALSE` still works as before (although less efficiently).

**Comment by rpruim** [comment]
Another further generalization mentioned by @hadley would be to weight based on distance from the nearest bin edge.  data directly on the border between bins would be weighted at 0.5 in each.  Data at the center of a bin would be weight 1.0 in that bin.  Intermediate weights would be determined by interpolation.

**Comment by hadley** [comment]
Actually can you file this in https://github.com/hadley/ggstat? That's where all the high performance stuff is going, and eventually ggplot2 will use it.

**Comment by rpruim** [comment]
This issue was moved to hadley/ggstat#11
