### ISSUE TITLE
Trying to plot an individual geom_point() in a geom_violin

### ISSUE THREAD

**Issue by carlrhall75** [hadley/ggplot2#1681]
Hello,

I am working on visualizing the historical price to book for a stock.  After building a violin plot, I would like to specifically highlight the last (most recent result, in the case, the 60th observation) to show where the stock is trading relative to its average.  I've tried many approaches but cannot seem to populate the most recent data point and display it using geom_point(color = "red")

60 data points:
![image](https://cloud.githubusercontent.com/assets/20604202/17141757/5ffd491c-531b-11e6-9ddf-12ed67a6391f.png)

ggplot:

v<-DATA
v2<-ggplot(v, aes(PB, Data)

violin plot using custom theme:
v2 + geom_violin(alpha=0.25, size=0.10, fill="#999999", color="#999999") + theme_custom() 
![image](https://cloud.githubusercontent.com/assets/20604202/17141912/14207716-531c-11e6-827c-34e209c615c5.png)

Add quantiles:

v2 + geom_violin(draw_quantiles = c(.10, .20, .30, .40, .50, .60, .70, .80, .90)) + 
    stat_summary(fun.data = "mean_sdl", fun.args = list(mult=1), geom = "pointrange", color = "red")

![image](https://cloud.githubusercontent.com/assets/20604202/17141937/2d475458-531c-11e6-98db-ab6fb1e2a6cd.png)

Now I attempt to add new layer using geom_point and "data="...
Ideally I would like to build a function that captures the last data point and creates the red geom_point() regardless of how many rows I have.  

v2 + geom_violin(draw_quantiles = c(.10, .20, .30, .40, .50, .60, .70, .80, .90)) + 
    stat_summary(fun.data = "mean_sdl", fun.args = list(mult=1), geom = "pointrange", color = "red") +
    geom_point(data = v2([60,], aes(PB, DATA), color = "red", size=5))

Any thoughts are most appreciated!

**Comment by hadley** [comment]
Can you please ask this on the ggplot2 mailing list instead?
