### ISSUE TITLE
stat_smooth fits model to transformed data

### ISSUE THREAD

**Issue by ecoRoland** [hadley/ggplot2#1684]
If a transformation is passed to the x and/or y scale, `stat_smooth` fits the model to the transformed and not to the original data. I find this unexpected and can't find it described in the documentation. Furthermore, I think, according to the grammar of graphics, the model _should_ be fit to the original data.

Example from [the question at SO](http://stackoverflow.com/q/38587877/1412059):

```
conc <- c(1.5188717, 1.8794363, 2.5455899, 1.5810686, 0.4938004, 2.9526288)
absp <- c(6.975519, 2.279606, 2.265391, 1.611868, 1.379097, 1.324827)
mydata <- data.frame(conc, absp)

coef(lm(absp ~ conc, data = mydata))[1]
#(Intercept) 
#    3.214895
2^coef(lm(log2(absp) ~ conc, data = mydata))[1]
#(Intercept) 
#    2.405666 

library(ggplot2)
library(scales)

ggplot(mydata, aes(x=conc, y=absp)) +
  geom_point(size=4) +
  stat_smooth(method=lm, se=FALSE, fullrange = TRUE) +
  labs(x="Conc.", y="Absp. (log2)") + 
  scale_x_continuous(limits = c(0, 3)) +
  scale_y_continuous(trans=log2_trans(),breaks=c(0,1,2,2.4056,3,4,5,6,7)) +
  annotation_logticks(sides="l") 
```

**Comment by hadley** [comment]
Yes, this is by design.

**Comment by ecoRoland** [comment]
A half-sentence saying this in the help page wouldn't be amiss ...

**Comment by hadley** [comment]
This unfortunately is something you need to learn about the grammar as a whole - otherwise every single documentation page would have to contain a lot of repeated information.

**Comment by ecoRoland** [comment]
Well, I have have learned it now. But I think this is an unrealistic expectation. ggplot2 is one of the most popular packages and rightly so. The number of users that consult your book when using it is tiny in comparison. Whereas everyone should be used to consulting the help pages. The grammar is mostly very intuitive, but this isn't. I can accept this behavior of stat_smooth since the focus is data visualization. But it clashes a bit with the possibility to plug in different models and the display of confidence intervals. Maybe you could consider a parameter or additional stat that changes this behavior to using the original values for the model fit?
