### ISSUE TITLE
New geom for geom_bar(stat = "identity")

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1685]
But I don't know what to call it

**Comment by steveharoz** [comment]
@hrbrmstr suggests `geom_col` in pull request https://github.com/hadley/ggplot2/pull/1590

But maybe call it `geom_column` to avoid the abbreviation

**Comment by hrbrmstr** [comment]
nothing really preventing both, too.

**Comment by hadley** [comment]
Oh, I knew I'd seen some work somewhere - I forgot to check the PRs :(
