### ISSUE TITLE
With 2.1.0, svg output no longer matches png and pdf

### ISSUE THREAD

**Issue by dekellum** [hadley/ggplot2#1686]
For comparison, here is correct PNG output (same with 2.0.0 and 2.1.0):

![cum_u](https://cloud.githubusercontent.com/assets/54785/17225617/9271114e-54ba-11e6-9832-36914295573c.png)

As I can't inline SVG here, see the following gist for the SVG outputs for ggplot2  2.0.0 and 2.1.0:

https://gist.github.com/dekellum/c0f7f20915528711184778ad84168f2a

Note that with the 2.1.0 SVG:

* Font sizes are larger
* panel.grid.major.y linetype="dashed" is no longer honored
* Overall output size (default SVG rendering size in pixels) is smaller

I'm assuming this has to do with the change to use svglite for SVG output: 5829262a  I couldn't find any background on rationale for this change, but I'm sure its for good reason.   In addition to trying to fix the output via svglite, I wonder if it would be reasonable to support some kind of non-default setting for using the old grDevices::svg output? 

Also I can attempt to reduce this to a minimal reproducible example but I'm hoping for some initial feedback including indication if this is expected behavior.

**Comment by hadley** [comment]
The rendered output should be identical across png and svg.  Please file a minimal reprex at svglite. If you can reduce it down to just grid commands, it would be greatly appreciated.

If you want the old svg output, you can always do it manually, or create your own wrapper fun. I'd rather force people to use the new one in order to work all the bugs out.

**Comment by dekellum** [comment]
> "do it manually"

Not knowing this code base very well, this was a bit of trial and error, but yes I see I can do the following to workaround my immediate problem, thanks.

~~~ diff
-ggsave( "../public/cum_u.svg", p, width=6.8, height=5.1 )
+grDevices::svg( "../public/cum_u.svg", width=6.8, height=5.1)
+print(p)
 ~~~

Where p is my plot.

**Comment by hadley** [comment]
Oh actually, you can do `ggsave(..., device = grDevices::svg)`
