### ISSUE TITLE
Misleading error message and an inconsistency when using geom_line

### ISSUE THREAD

**Issue by tmalsburg** [hadley/ggplot2#1689]
I want a line plot, where `value` is plotted as a function of `expt` with one line per level in `var`:

Here is my data:

``` R
    lines <- "
    expt,var,value
    1,none.p,0.183065327746799
    2,none.p,0.254234138384241
    3,none.p,0.376477571234912
    1,male.p,-1.58289835719949
    2,male.p,-1.98591548366901
    3,male.p,-2.02814824729229
    1,neutral.p,-2.01490302054226
    2,neutral.p,-1.88178562088577
    3,neutral.p,-1.68089687641625
    1,female.p,-3.27294304613848
    2,female.p,-3.07711187982237
    3,female.p,-2.89652562347054
    1,both.p,-2.40011011312792
    2,both.p,-2.24495598015741
    3,both.p,-2.78501124223834"
    con <- textConnection(lines)
    data <- read.csv(con)
    close(con)
```

`expt` is a factor:
    
``` R
    data$expt <- factor(data$expt)
```

But when I use `geom_line`

``` R
    ggplot(data, aes(expt, value, colour=var)) + geom_line()
```

I get the following error message

```
    geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?
```

and an empty plot.  I understand that the solution above is not correct and that I should use the following

``` R
    ggplot(data, aes(expt, value, group=var, colour=var)) + geom_line()
```

but the error message seems incorrect because all data points belong to the same group, so there is not just one observation in the group.

Interestingly, the solution without `group=var` works when `expt` is a numeric instead of a factor.

``` R
    ggplot(data, aes(as.integer(expt), value, colour=var)) + geom_line()
```

That seems inconsistent.

**Comment by hadley** [comment]
By default, grouping is determined by the combination of all categorical variables in the plot.

**Comment by tmalsburg** [comment]
I see. But in that case the following shouldn't work either but it does:

    ggplot(data, aes(expt, value, colour=var)) + geom_point()

**Comment by thomasp85** [comment]
There is nothing wrong with that. geom_point only requires a single observation while geom_line requires multiple
