### ISSUE TITLE
non-standard params / geom-specific metadata

### ISSUE THREAD

**Issue by tdhock** [hadley/ggplot2#1694]
Hello, this is continuing the discussion from https://github.com/hadley/ggplot2/pull/1649 and https://github.com/hadley/ggplot2/issues/1585 our equivalent animint issue is https://github.com/tdhock/animint/issues/159

For https://github.com/tdhock/animint we need some way of specifying `chunk_vars` which is a geom-specific parameter that has nothing to do with how it appears. With old ggplot2 (pre-2.0) the following was working fine

```r
ggplot()+
  geom_point(aes(Sepal.Length, Petal.Length, showSelected=Species),
    data=iris, 
    chunk_vars=character())
```

With current ggplot2 that now results in an error
```
Error: Unknown parameters: chunk_vars
```

Basically we just need a way for ggplot2 to store that information in the geom, ideally without throwing any errors/warnings/messages. The use case is described by @faizan-khan-iit 's excellent test case from his PR https://github.com/hadley/ggplot2/pull/1649/commits/017b0f3d753a93458e89a67c40593574b82491b5 -- we want the geom to store whatever information is provided in those non-standard parameters, so it can be accessed later by our animint code.

One way to achieve this would be to use Faizan's `validate_params=FALSE` method https://github.com/hadley/ggplot2/pull/1649 but that PR was rejected by @hadley 

Let me propose another way:

```r
l <- geom_point(aes(Sepal.Length, Petal.Length, showSelected=Species), 
    data=iris, 
    meta=list(chunk_vars=character()))
```

`meta` should be recognized by ggplot2 as a special meta-data parameter (no warnings or messages about meta being an unknown parameter). whatever was specified as `meta` should be accessible via `l$meta` Comments?

**Comment by thomasp85** [comment]
It makes a bit more sense now, though I'm still unsure if this is the best approach. Is there any sense in different layers having different settings for chunk_vars? What I'm getting at is, couldn't this option be set globally rather than through each geom?

**Comment by tdhock** [comment]
yes each layer has a different value of chunk_vars

for global options we already have a PR accepted for non-standard theme options https://github.com/hadley/ggplot2/pull/1121

**Comment by tdhock** [comment]
hey @thomasp85 @hadley can you please comment on this approach for adding geom-specific metadata? If this is not appropriate can you please explain why, and suggest and alternative?

**Comment by hadley** [comment]
Well, the good news is that you'll no longer get an error, but you'll now get a warning for both the aesthetic and the parameter.

Can you remind me why you don't want to provide your own geom functions with extra parameters?

**Comment by tdhock** [comment]
Thanks! That solves this issue then.

I guess we could provide our own geom functions with extra parameters, but I did not want to have to copy all the geom code to animint, and make users have to learn new geom functions.
