### ISSUE TITLE
Request: export add_ggplot and add_theme

### ISSUE THREAD

**Issue by jonocarroll** [hadley/ggplot2#1698]
Are there any objections to `add_ggplot` and `add_theme` being exported?

I am working on a [package](https://github.com/jonocarroll/ggghost) that extends `+.gg` and get a CRAN NOTE if I try to use `:::` in an effort to extend this operator.

Exporting these two would be appreciated, if possible.

FWIW, I've tried making my own overload for `+` but get "inconsistent method" errors when trying to use `theme` calls. I understand that `%+%` would get around that, but I'm hoping to be able to use `+`.

**Comment by thomasp85** [comment]
I could see this being potentially dangerous as this could invisibly modify the way standard ggplot2 works.

A suggestion to get around this without changes to ggplot2 would be that you write your own `ggplot` that under the hood called `ggplot2::ggplot` but then modified the class of the return value to e.g. `ghost`. You would then be free to write your own `+.ghost` function (this is just a thought on top of my head)

**Comment by jonocarroll** [comment]
Thanks for that. I think the issue I'm having, given that it occurs mainly
with `theme` calls, is dealing with `%+replace%` too. I can do everything
else (tested and works) with my own overload, but themes revert the
dispatch. Maybe I just need to overload of mask *all* `+` variants.

I see your point regarding protecting the mechanism. I have a startup
message indicating this is a valid concern.

**Comment by jonocarroll** [comment]
I think I've managed to work around the issue, so I'm happy to close #1698. I'm not entirely sure I understand the double dispatch that's going on (if that's what's happening?), but hopefully that will become clear with more reading. Thank you.
