### ISSUE TITLE
violin plots are rendered with long tails in current stable GGPLOT2

### ISSUE THREAD

**Issue by nbafrank** [hadley/ggplot2#1700]
Dear Hadley,

I and others have notice that the current version of GGPLOT2 renders violin plots with long tails at the upper end unlike previous versions. 

Is there any way to revert back to the old rendering?

Thanks,

Francesco

**Comment by thomasp85** [comment]
Can you provide a reproducible example?

**Comment by nbafrank** [comment]
res <- data.frame(a = c(1:100),b=c(rep(0,50),rep(1,50)))
ggplot(res,aes(y=a,x=factor(b))) + geom_violin(trim=F)

When you plot the violins, the tails go to reach the very end of the plot (both ends). Prior to version 2.0.0 (I believe) this was not occurring. It is solely an aesthetic change but I was wondering if there's an option to make it look like it used to be.

Thanks,

FV

**Comment by nbafrank** [comment]
Let me know if you need anything else =)

**Comment by hadley** [comment]
Use `trim = TRUE`?

**Comment by nbafrank** [comment]
so that option will trim and cut the violin. I want a full violin without the ends going all the way to the top like it used to be in the past. Is there a hidden option or you have changed some internal graphic component in an unfixable way? Thanks,FV

**Comment by hadley** [comment]
Can you please carefully explain the previous behaviour and the current behaviour? I don't understand what you want.

**Comment by wch** [comment]
@nbafrank in the future screenshots would help. You can use `devtools::install_version` to install an old version of a package.


This is the plot with 1.0.1:

![violin-1 0 1](https://cloud.githubusercontent.com/assets/86978/18617185/6dee08ec-7d8f-11e6-9e99-e2d7b5c0d4e7.png)

And the current dev version:

![violin-dev](https://cloud.githubusercontent.com/assets/86978/18617187/717d2998-7d8f-11e6-8053-76aa459df88f.png)

**Comment by nbafrank** [comment]
Thanks WHC, I did not know about devtools::install_version =) hope this is clear.

**Comment by hadley** [comment]
@wch do you know what caused the change?

**Comment by wch** [comment]
Nope, sorry. It looks like the y-range is now determined by the raw data instead of the transformed data.

**Comment by hadley** [comment]
I guess someone will have to git bisect this

**Comment by wch** [comment]
@hadley it's your fault: d58b00a58691e1b3753525759535d8abe942e304

**Comment by hadley** [comment]
The reason I have an intern is to fix my mistakes...

**Comment by thomasp85** [comment]
You're going to be in so mush trouble in 7 days

**Comment by nbafrank** [comment]
@hadley @thomasp85 @wch thanks for your help guys. Looking forward to the new version. Maybe make it an option for both styles?

**Comment by thomasp85** [comment]
@hadley thinking about this, there is actually a value in the new approach even though it can look a bit odd, in that it communicate the range of the data clearly - do you want a complete roll-back to the old style (without reemerging the bug that caused the change) or what do you think..?

**Comment by hadley** [comment]
The current dev version doesn't look right because it's truncated to early on one end and too late on another - I think it's probably just that the ranges need to be calculated per group, not overall.
