### ISSUE TITLE
docs links that refered to inside-r go to main page of mran (need to refer to specific function documentation)

### ISSUE THREAD

**Issue by RMHogervorst** [hadley/ggplot2#1701]
I'm not sure it this is the correct place to file this issue, but I noticed on the documentation website that the links to inside-r articles are being referred to MRAN mainpage. 

for example
http://docs.ggplot2.org/current/geom_density.html

this link goes to MRAN mainpage.
http://www.inside-r.org/r-doc/stats/density

**Comment by hadley** [comment]
That's a staticdocs bug unfortunately. Will probably get fixed in the next months.
