### ISSUE TITLE
geom_smooth assumes that the LHS of its model formula is just y

### ISSUE THREAD

**Issue by sschmitz** [hadley/ggplot2#1705]
`predictdf`, which is called by `stat_smooth`, returns a data frame with a sequence of `x` values, and the model predictions as the column `y`. It thereby assumes that `y` is what's on the left-hand side of the model formula. The following example thus produces an unexpected result:

```R
x <- 0:3
qplot(x, 1 + x) + geom_smooth(method = "lm", formula = y - 1 ~ x + 0)
```

To get the correct result, the inverse function of the LHS with respect to y needs to be applied to the model prediction. It is, however, not in general possible to determine this inverse function; in fact, the LHS might not be invertible at all. I would therefore propose to emit a warning when the LHS of the `formula` parameter to `stat_smooth` is not just `y`, and require the user to specify the inverse function (e. g., for the above example, something like `geom_smooth(..., inv = function (pred) (pred + 1)`).

I'm also wondering if there are use cases for other variables than `y` on the LHS (in which case the inverse function would need to return a data frame), but this concern is probably artificial.

**Comment by hadley** [comment]
Yeah, this is outside the scope of `geom_smooth()`. You'll need to fit the model and generate predictions outside of ggplot2.
