### ISSUE TITLE
ggplot filling in x-axis with non-existent values

### ISSUE THREAD

**Issue by dsdesrosiers** [hadley/ggplot2#1706]
Greetings all ... apologies if this is not the right forum. It seems like this might be an issue with the package, but I am relatively new so it might well be a PEBCAK.  I have a set of data for my work which is in customer technical support. I am plotting cases by week and internally we use labels that appear to be decimal values...that is 2016.50 is the 50th week of our 2016 fiscal year. 

The decimal values in my tibble go from 2016.51, 2016.52, 2017.01, 2017.02 as we cross into the new fiscal year.

The issue is that when plotting, the x-axis fills in the gap between 2016.52 and 2017.01 with 2016.53, 2016.54 and interpolates the line between 2016.52 and 2017.01 despite the fact that values are not even in my tibble.

I appear to be able to workaround this using the character representation of the week in a group aesthetic, but this still seems odd to me. 

Happy to work up a sample set of data is this helps.

Thanks in advance
Danielle

**Comment by dsdesrosiers** [comment]
P.S. - we met briefly at the Cleveland R-Users meetup where you suggested that newbies could contribute by working with the packages and submitting issues. Hopefully, this is one of those instances of being helpful.

**Comment by thomasp85** [comment]
Can you provide a reproducible example with a clear description of what you expect to see?

As I read it you will either need to encode your week information differently, or add a grouping variable based on the year... But I'll reserve judgement until I see an example :-)

**Comment by dsdesrosiers** [comment]
Happy to provide an example over the weekend :-)

**Comment by dsdesrosiers** [comment]
Data are attached. I understand that there may be a better way to do the graph but this is a one of our primary ways of annotating fiscal weeks which are defined as the seven days from Saturday to Friday. Regardless of how this can be worked around, I don't thin the plotting engine should add data that simply doesn't exist in the data set. That said, I am not a programmer of this type of code and it may well be easier said than done so any workarounds or suggestions would be most welcome and appreciated.

[sample_for_extended_axis.zip](https://github.com/hadley/ggplot2/files/416835/sample_for_extended_axis.zip)



Code is here
library(ggplot2)

plotdata <- read.csv2("ssample_for_extended_axis.csv", 
                     header=TRUE, 
                     na.strings = "",
                     sep=",",
                     colClasses = c("numeric", "numeric"))

plot <- ggplot(data=plotdata,  aes(x=case_close_week, y=pct)) +
        geom_line(size=1) 

plot

**Comment by hadley** [comment]
Without running your code, I'd say that the problem is that you're using continuous values to represent discontinuous data - since the range (2010.52, 2011) doesn't exist, you should probably use a character vector or real dates.
