### ISSUE TITLE
Margin tweaks

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1712]
* Need slightly more space between axes and titles
* Need slightly less space between legend and plot area

**Comment by hadley** [comment]
I also wonder what it would look like if the axis titles were left/bottom aligned.

**Comment by thomasp85** [comment]
Do you want to tweak this yourself or should I make a proposal?

**Comment by hadley** [comment]
I probably need to tweak it myself

**Comment by hadley** [comment]
Let's move the legend stuff out in to a separate issue - it needs more control to be added.
