### ISSUE TITLE
geom_violin quantile lines respond to alpha

### ISSUE THREAD

**Issue by mnbram** [hadley/ggplot2#1714]
The lines drawn by draw_quantiles in geom_violin are affected by the alpha parameter, so they cannot be included along with a transparent fill. Maybe there is a reason, but it seems to me that they should behave like any other lines.

Simple example:
```
ggplot(mtcars, aes(factor(cyl), mpg)) +
  geom_violin(draw_quantiles = 0.5, alpha = 0)
```

**Comment by mnbram** [comment]
I have a one line fix for this, but as it changes default behavior and I'm not exactly an expert software developer, I'm hesitant to submit it as a pull request. Should I do so anyway?

**Comment by thomasp85** [comment]
No harm in trying - we'll guide you through any quirks
