### ISSUE TITLE
xlim and ylim issues while plotting graph

### ISSUE THREAD

**Issue by kminie** [hadley/ggplot2#1715]
I am using R code for DGE and plot generation 
Following is the code :

**rld <- rlogTransformation(dds, blind=TRUE)
vsd <- varianceStabilizingTransformation(dds, blind=TRUE)
library("vsn")
pdf(paste('plots/vsn_variance',expname,'.pdf',sep=''), height=4,width=12)
par(mfrow=c(1,3))
notAllZero <- (rowSums(counts(dds))>0)
meanSdPlot(log2(counts(dds,normalized=TRUE)[notAllZero,] + 1),ylim = c(0,2.5))
meanSdPlot(assay(rld[notAllZero,]), ylim = c(0,2.5))
meanSdPlot(assay(vsd[notAllZero,]), ylim = c(0,2.5))
dev.off()
rm(rld,vsd)**

While running the code I am getting an error :
**Error: Unknown parameters: ylim
Execution halted**

Reference: https://dwheelerau.com/2014/02/17/how-to-use-deseq2-to-analyse-rnaseq-data/
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.592.2694&rep=rep1&type=pdf

I dont know what is the problem , can some one help?

**Comment by hadley** [comment]
I'd recommend preparing a reproducible example and asking on the ggplot2 mailing list or on stackoverflow. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.
