### ISSUE TITLE
Titles don't scale with base_size in themes

### ISSUE THREAD

**Issue by timcdlucas** [hadley/ggplot2#1717]
Axis and legend text size scales, but main titles, axis titles and legend tiles don't. I can't see why as they are all defined with `rel`.

```
ggplot(mtcars, aes(mpg, disp, colour = cyl)) + 
  geom_point() +
  ggtitle('title') +
  theme_grey(base_size = 5)


ggplot(mtcars, aes(mpg, disp, colour = cyl)) + 
  geom_point() +
  ggtitle('title') +
  theme_grey(base_size = 10)
```

Same occurs with other themes (including ggthemes). I don't think this is the expected behaviour?

**Comment by thomasp85** [comment]
Hmm... I cannot reproduce this behaviour - can you update to the latest version and see if the problem persists?

**Comment by timcdlucas** [comment]
Ah, ok it's because I was using my own theme before hand. 

That said it's still slightly weird. I've probably not defined my theme properly.

```
source('https://raw.githubusercontent.com/timcdlucas/ggplotThemes/master/theme_tcdl.R')
theme_set(theme_bw() + theme_tcdl)

ggplot(mtcars, aes(mpg, disp, colour = cyl)) + 
  geom_point() +
  ggtitle('title') +
  theme_grey(base_size = 5)
```

then stops the titles scaling. I'll have a better look, but I would have though the `+theme_grey()` would override anything else.
