### ISSUE TITLE
[feature request] color gradient along geom_segment()

### ISSUE THREAD

**Issue by ikashnitsky** [hadley/ggplot2#1720]
Following [this SO question](http://stackoverflow.com/questions/17753502/ggplot2-color-gradient-along-geom-segment?rq=1) I tried and failed to find a concise way to color a line/path/segment with a gradient color. This may come useful when one wants to visualize item's changes over time by two variables, e.g. to see how height and weight changes throughout a person's life.   
Another nice option would be to use `alpha` parameter in the same way.   
Is the feature possible to implement?  
**Note:** [Here](http://stackoverflow.com/questions/11058072/create-an-arrow-with-gradient-color) are some solutions that color sections of path in a gradient manner. Still, if the number of sections is relatively small, the result does not look  nice.

**Comment by hadley** [comment]
It's out of scope for ggplot2. But you might want to look at tweenr (https://github.com/thomasp85/tweenr) - it focusses on interpolation in time, but interpolation in space seems like a straight forward generalisation.

**Comment by ikashnitsky** [comment]
@hadley Thanks for the suggestion!
