### ISSUE TITLE
Margin tweaks for legends

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1727]
Currently you can only control the overall margin of the legend, but ideally you'd be able to control each of t/r/b/l separately.  Then the defaults need to be adjusted so that you can easily align a legend to either the top-right or the bottom-left of the plotting area.

**Comment by thomasp85** [comment]
My suggestion would be to go with the CSS approach and let users specify either one, two, or four values. Then we could have a `valid.margin()` function that automatically expands the unit vector.

Don't know the preferred approach to adapting the defaults to the user-set justification?

**Comment by thomasp85** [comment]
This approach to margins should of course be applied to all margin specifications. That is, `panel.margin`, `plot.margin`, and the `margin` argument in `element_text()` should be changed as well.

Come to think of it - `panel.margin` should really be called `panel.spacing` - the same holds for `legend.margin`

I'll hold off on anything before you comment on these thoughts...

**Comment by thomasp85** [comment]
Actually the `margin` function would just need a little tweaking to support the functionality in `element_text` - And it could then be applied for the other margins as well

**Comment by hadley** [comment]
Right — the way to do this is to implement more `margin()` helpers. I think changing how `margin()` works is not great at this point (I did deliberately choose the current behaviour of defaulting to 0), but we could certainly add another function.

I agree that `panel.margin` and `legend.margin` would be better off as `panel.spacing` and `legend.spacing`, but I think changing them now would be a lot of work.  I think we should just adjust the docs to clarify that these are _internal_ margins only.

**Comment by hadley** [comment]
1. Existing behaviour of `legend.margin` needs to become like `panel.margin` and only control the spacing between multiple legends

1. That makes `legend.margin` and `panel.margin` somewhat confusing because they really should be `legend.spacing` and `panel.spacing`. We could leave as is and make clear in documentation, or change names with code in `theme()` to work with either old or new specification.

1. We'll also need a new `legend.box.margin` that controls the margin between the legend box and the panel.

1. We could consider adding `legend.box.background` but that would require an additional margin theme setting so you could independently control the margin inside and outside the box.

**Comment by assaron** [comment]
Hi,

Is it possible to keep `panel.margin` option too, but with throwing a deprecation warning? I have the package in Bioconductor that uses this option and I can't put dependence on the >=2.2.0 ggplot verision, as it's not yet realeased, and can't just ignore this, as it will break my package soon.

**Comment by thomasp85** [comment]
This is how it works currently - It will throw a warning and reassign the value to panel.spacing

**Comment by assaron** [comment]
Oops, sorry, got wrong impression and didn't check properly.

Thanks!

**Comment by hadley** [comment]
You can include pick behaviour using an if statement and packageVersion
