### ISSUE TITLE
Documentation of arrow in geom_spoke (and in geom_segment)

### ISSUE THREAD

**Issue by Henrik-P** [hadley/ggplot2#1734]
1. In the help text of `geom_segment` and `geom_curve` the `arrow` argument is described. On the other hand, `arrow` is not mentioned in `?geom_spoke`. I think this argument should be described there as well.

2. In the help pages where `arrow` is described, make it clear that it is `grid::arrow` which is used, i.e. replace "as created by arrow()" with "as created by `grid::arrow()`" (note: also add code formatting). This makes it easier to find more help on the function.

3. Possibly add an example on the direction of the arrows, i.e. the `ends` argument (see e.g. [this Q&A](http://stackoverflow.com/questions/39173710/change-direction-of-arrows-in-geom-spoke)). This is perhaps less important _if_ you refer to `grid::arrow` for description of further arguments.

**Comment by hadley** [comment]
I'd be happy to review a PR along those lines
