### ISSUE TITLE
Add arrows at the end of x and y axis 

### ISSUE THREAD

**Issue by adamkk** [hadley/ggplot2#1740]
Hi,

After long time searching this issue, I need to ask this request. In my academic work, each chart needs to have x and y axis ending in arrows. Example: http://www.policonomics.com/supply-and-demand/

How can I add this to my ggplot2 charts?

Best,

**Comment by thomasp85** [comment]
@hadley what do you think of this? It's rather straightforward to add an arrow argument to `element_line()` which would make this possible... The grab placements will not be affected by the added width/height from the arrows so it should be a safe change...

**Comment by adamkk** [comment]
Dear @hadley,

perhaps line_type in element_line() could be changed from: "An integer or name: 0 = blank, 1 = solid, 2 = dashed, 3 = dotted, 4 = dotdash, 5 = longdash, 6 = two dash", to 1.... through 7= solidarrow ?

**Comment by thomasp85** [comment]
That would be the wrong approach - the arguments should map directly to polylineGrob so that `element_line` would gain an arrow argument that would get passed along in `element_grob.element_line()`

**Comment by hadley** [comment]
My only concern would be that there might be clipping issues — I can't remember where/when the axes are drawn. If that's not a problem, go ahead and add it.

**Comment by thomasp85** [comment]
My cursory investigation shows no clipping problems so I'll make a PR

**Comment by adamkk** [comment]
**Thanks for the arrows. They look great !** 

Today, I have replicated the chart in RStudio with arrows using theme() and element_line(arrow=arrow()). Yet, while using **theme_bw()** it did not work. Is the element_line an attribute to one theme only, or all themes can make use of it?

Question: how I can get a **clear background** on the chart (without gray background and grid)?
See link: http://www.policonomics.com/supply-and-demand/

Best,
Adam

**Comment by hadley** [comment]
@adamkk a better place for questions of that nature is the ggplot2 mailing list
