### ISSUE TITLE
text justification for multiline titles with uneven line lengths

### ISSUE THREAD

**Issue by enfascination** [hadley/ggplot2#1741]
In the example below, "22" should be directly below "1", as it is when title.hjust=0:

`ggplot(data.frame(x=1,color=1), aes(x=x,color=color)) + geom_bar() + guides(color=guide_legend(title="1\n22\n333\n1", title.hjust=-4))`

(I found this using ggplot 2.1.0, so maybe this is fixed in more recent version, in which case, my apologies.  Thank you for ggplot.)

**Comment by thomasp85** [comment]
This is unfortunately a build in limitation of the grid system that ggplot2 is build upon and is thus not easily fixed. If you wish to pursue this I suggest to contact the grid maintainers (R Core) and lay down the case there
