### ISSUE TITLE
geom_hex no longer recognizes ..count..

### ISSUE THREAD

**Issue by Ax3man** [hadley/ggplot2#1747]
Strongly related to #1608.

This used to work:

```
DF <- data.frame(x=rnorm(1000), y=rnorm(1000))
ggplot(DF) + geom_hex(aes(x=x, y=y, alpha=..count..))
```
But now returns the error: `object 'count' not found`. #1608 reported the same behavior for `..density..` but this has been resolved since. There is a perfectly viable workaround using `..value..` instead, but `..count..` seems more consistent with other stats and geoms, and old code may no longer work.

Also see on [SO](https://stackoverflow.com/questions/39446852/geom-hexbin-map-bincount-to-alpha/).

**Comment by thomasp85** [comment]
@hadley - is there a reason for renaming `count` to `value`? Looking into `StatBin` and `StatBin2D` they still use `count` so I think we need to be consistent...

**Comment by hadley** [comment]
No, just an oversight

**Comment by thomasp85** [comment]
@hadley Should this be fixed in `hexBinSummarise()` - it also touches StatSummaryHex and I'm unsure whether `value` rather than `count` is expected there..?

**Comment by thomasp85** [comment]
The default aes in `StatSummaryHex` uses `value`, but this might just be to fit the output rather than the correct behaviour...

**Comment by hadley** [comment]
Ah this is going to be awkward to fix because it's natural for `stat_hex` to use `count`, but for `stat_summary_hex` to use `value`, and they're both implemented with the same underlying stat.  

Might just be better to leave the behaviour as is, and better document.

**Comment by thomasp85** [comment]
It's not too big of an issue as it can be intercepted in `StatBinHex` after the call to `hexBinSummarise()` - just needed to know where the fix should be implemented

**Comment by hadley** [comment]
But how would you know when to make the transformation?  It seems like a decent amount of work for little gain.

**Comment by thomasp85** [comment]
See PR #1765
