### ISSUE TITLE
Axis tick chopped off

### ISSUE THREAD

**Issue by tklebel** [hadley/ggplot2#1755]
I'm not entirely sure what is going on here. Sorry for posting, if I overlooked something obvious.

I have the following data:

``` r
var <- c(45L, 9L, 0L, 27L, 9L, 0L, 18L, 9L, 0L, 9L, 9L, 0L, 0L, 9L,
         9L, 27L, 9L, 9L, 0L, 91L, 0L, 9L, 27L, 27L, 9L, 9L, 0L, 91L,
         9L, 36L, 18L, 27L, 64L, 82L, 45L, 27L, 0L, 0L, 0L, 18L, 0L, 27L,
         18L, 0L, 27L, 9L, 0L, 18L, 9L, 9L, 55L, 9L, 0L, 18L, 9L, 18L,
         27L, 9L, 9L, 36L, NA, 18L, 18L, 18L, 0L, 18L, 18L, 9L, 18L, 0L,
         9L, 9L, 45L, 0L, 18L, 73L, 18L, 0L, 55L, 0L, 18L, 0L, 18L, 82L,
         9L, 9L, 45L, 0L, 9L, 9L, 0L, 9L, 18L, 0L, 9L, 0L, 0L, 0L, 18L,
         18L, 9L, 9L, 45L, 0L, 55L, 9L, 18L, 0L, 0L, 0L, 9L, 18L, 9L,
         55L, 0L, 9L, 18L, 9L, NA, 0L, 18L, 18L, 27L, 64L, 82L, 36L, 27L,
         45L, 9L, 0L, 0L, 55L, 9L, 9L, 18L, 55L, 0L, 36L, 9L, 45L, 18L,
         0L, 55L, 55L, 0L, 9L, 9L, 9L, 27L, 0L, 0L, 0L, 18L, 9L, 55L,
         36L, 9L, 0L, NA, 0L, 27L, 36L, 64L, 45L, 55L, 36L, 0L, 0L, 0L,
         9L)
```
When I want to plot it, the tick mark for "100" is chopped off. 
``` r
library(ggplot2)

ggplot(data.frame(var), aes(var)) +
  geom_bar()
#> Warning: Removed 3 rows containing non-finite values (stat_count).
```

![](http://i.imgur.com/NBkSXD8.png)

When I set limits, data corresponding to "0" is not displayed.

``` r

ggplot(data.frame(var), aes(var)) +
  geom_bar() +
  xlim(0, 100)
#> Warning: Removed 3 rows containing non-finite values (stat_count).
```

![](http://i.imgur.com/84l7Yv5.png)

This is how the data actually looks:
``` r

barplot(table(var))
```

![](http://i.imgur.com/dHv3Qrc.png)

Is this a bug or am I missing something?

**Comment by tklebel** [comment]
Mh, obviously, setting the limit to "0" will remove those data points. A solution would be:

``` r

ggplot(data.frame(var), aes(var)) +
  geom_bar() +
  xlim(-10, 100)
#> Warning: Removed 3 rows containing non-finite values (stat_count).
```

![](http://i.imgur.com/5YRVk9m.png)

Still, why is the axis in the first plot misaligned?

**Comment by has2k1** [comment]
You are not leaving enough room for the *full width* of the zero-centred bar.

**Comment by tklebel** [comment]
@has2k1 yes, I resolved this problem, as you can see. Still, in the first example the tick.label is chopped off, which seems like a bug to me.

**Comment by has2k1** [comment]
Yes that is a rendering bug, the clipping seems to ignore the `axis-text`.

**Comment by hadley** [comment]
It's not the clipping - I think that's the edge of the plot.

**Comment by Vickic22** [comment]
I didn't know whether to open a new issue or just comment on this one, as I have tried plotting this data (and my own data), and now the x-axis seems completely misaligned.
Why do the bars not straddle the x values anymore?  For example in the plots above the bar for zero values has the zero label in the middle of the bar, on the plot now the bar is to the right of the zero.  I can't seem to find anywhere in the code to tweak this?
![barplot](https://cloud.githubusercontent.com/assets/22855623/19476978/efa686c8-9533-11e6-847f-7fd9cdef102f.png)

**Comment by thomasp85** [comment]
Unless you post the code used to produce the plot it is difficult to help - I've just rerun the examples in this thread and get identical results as @tklebel indicating that nothing has changed...
