### ISSUE TITLE
Contour plots are drawn in color when using theme_bw()

### ISSUE THREAD

**Issue by dlindelof** [hadley/ggplot2#1766]
```
theme_set(theme_bw())
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour()
```

I expect a contour plot in black and white; instead the contours are plotted in blue:

![rplot](https://cloud.githubusercontent.com/assets/245328/18702080/5493cbd6-7fe0-11e6-9882-4638d3f1a6f6.png)

**Comment by thomasp85** [comment]
The theme settings has no effect on the layer (geom) style - only how the decoration is styled (axes, labels, grids etc). `geom_contour` has a default color that can be overwritten e.g.

```r
theme_set(theme_bw())
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour(colour = "black")
```
