### ISSUE TITLE
I'm confusing about width(height) argument in geom_jitter()

### ISSUE THREAD

**Issue by kimchpekr** [hadley/ggplot2#1775]
"width(height)" argument in geom_jitter() is described as [belows.](http://docs.ggplot2.org/current/geom_jitter.html)

> ### **width**
Amount of vertical and horizontal jitter. The jitter is added in both positive and negative directions, so the total spread is `twice the value specified here`. If omitted, `defaults to 40% of the resolution of the data`: this means the `jitter values will occupy 80%` of the implied bins.

So, I expected `geom_jitter()` and `geom_jitter(width = 0.4)` will produce same plot and `"width = 0.4"` spreads points across a range `"base ± resolution * 0.4"`. but the results are not.
```
> p <- ggplot(mtcars, aes(gear, mpg))
> p + geom_jitter()  ## jitter range is 3 ± 0.4
```
![default](https://cloud.githubusercontent.com/assets/22344554/18808390/d0bca7a6-829b-11e6-8b67-10d54c0ea107.png)

```
> p + geom_jitter(width = 0.4) ## jitter range is narrow than 3 ± 0.4
```
![width 0 4](https://cloud.githubusercontent.com/assets/22344554/18808398/11a525d6-829c-11e6-89be-d526e15a08c8.png)

I'm confusing about width argument and how can i calculate a jitter range.

I expect like belows but the result doesn't

geom_jitter(`width = 0.2`) will spread points across a range [2.8 ~ 3.2] : 3 ± 0.2
geom_jitter(`width = 0.4`) will spread points across a range [2.6 ~ 3.4] : 3 ± 0.4
geom_jitter(`width = 0.6`) will spread points across a range [2.4 ~ 3.6] : 3 ± 0.6

but, `geom_point(aes(x = jitter(gear, amount = 0.2))` produce a plot what i expected.
![geom_point jitter](https://cloud.githubusercontent.com/assets/22344554/18808494/3e998386-829f-11e6-944f-be15378a3184.png)

Please, give me some hints...

**Comment by has2k1** [comment]
That is clearly a bug. I think the width is being treated as a substitute for the resolution, if that is the case then the effective amount is `0.4 * 0.4 = 0.16`

**Comment by kimchpekr** [comment]
@has2k1 Thanks for comment.

data resolution at "`gear = 3`" is 1, so amount should be calculated `1 * 0.4 = 0.4` instead of `0.4 * 0.4 = 0.16`
```
> resolution(mtcars$gear[mtcars$gear == 3])
[1] 1
```
but geom_jitter(width = 0.4) spreads points across a range you calculated 3±0.16 like below.
![width 0 16](https://cloud.githubusercontent.com/assets/22344554/18812689/ff86d590-8316-11e6-85f1-f6543bc373dc.png)

I'm still confusing....

**Comment by has2k1** [comment]
I've since looked at the code and I'll submit a PR that fixes it.

**Comment by kimchpekr** [comment]
@has2k1 
I'm looking forward to it.

**Comment by svenhalvorson** [comment]
I'm having a hard time knowing what this means:
'If omitted, defaults to 40% of the **resolution of the data**: this means the jitter values will occupy 80% of the **implied bins**.'

You're saying that the range of values that point could be mapped to is 3 +/- (resolution) * 0.4 so how is resolution determined?

**Comment by has2k1** [comment]
http://ggplot2.tidyverse.org/reference/resolution.html
