### ISSUE TITLE
position_dodge for geom_boxplot should have an option to not drop missing levels

### ISSUE THREAD

**Issue by NattyE** [hadley/ggplot2#1776]
I'm trying to create a series of boxplots using `fill` to create dodged boxplots. One of my levels has no data and so the single boxplot takes up the entire plotting space. See for example

http://stackoverflow.com/questions/12806260/how-to-enforce-ggplots-position-dodge-on-categories-with-no-data
http://stackoverflow.com/questions/15367762/include-space-for-missing-factor-level-used-in-fill-aesthetics-in-geom-boxplot?noredirect=1&lq=1

Ideally, there should be an option to turn this behaviour off and keep the missing level.

**Comment by hadley** [comment]
That's how dodging works. You might want to try facetting instead.
