### ISSUE TITLE
geom_vline: Dates as xintercept

### ISSUE THREAD

**Issue by Plebejer** [hadley/ggplot2#1780]
Right now, the value of the `xintercept` aesthetic of `geom_vline` must be numeric. At least, it throws an error an error if I do not convert the date - which I actually want to put there - into numeric:

![image](https://cloud.githubusercontent.com/assets/6517388/18827047/e43b50ee-83d0-11e6-8ca1-53aa48e20c7e.png)

This seems to be inconsistent to me, since the `aes()` in the `ggplot()` function accept dates without any problem.

**Comment by hadley** [comment]
Yeah, unfortunately this is a long standing problem that I've never figured out how to fix. The difference is the `geom_vline()` doesn't scale it's inputs, so you need to give numeric values.
