### ISSUE TITLE
retrieving mapping of vars with shiny in ggplot 2.1.0.9000

### ISSUE THREAD

**Issue by dcangst** [hadley/ggplot2#1781]
not sure whether this is the right place to post, but the bug only appears when using ggplot 2.1.0.9000 and not with the CRAN version (2.1.0) in R 3.3.1 (mac, 64bit)

i just noticed that with ggplot 2.1.0.9000 shiny is not able to get coordinates on click the example below reports (in my case at least) this with 2.1.0:

```
input$click:
List of 7
 $ x      : num 4.91
 $ y      : num 2.51
 $ mapping:List of 2
  ..$ x: chr "Sepal.Length"
  ..$ y: chr "Sepal.Width"
 $ domain :List of 4
  ..$ left  : num 4.12
  ..$ right : num 8.08
  ..$ bottom: num 1.88
  ..$ top   : num 4.52
 $ range  :List of 4
  ..$ left  : num 37.1
  ..$ right : num 1323
  ..$ bottom: num 369
  ..$ top   : num 5.48
 $ log    :List of 2
  ..$ x: NULL
  ..$ y: NULL
 $ .nonce : num 0.665
```
and this with 2.1.0.9000:
```
input$click:
List of 6
 $ x      : int 176
 $ y      : int 184
 $ mapping: Named list()
 $ domain :List of 4
  ..$ top   : int 0
  ..$ left  : int 0
  ..$ right : int 1327
  ..$ bottom: int 399
 $ range  :List of 4
  ..$ top   : int 0
  ..$ left  : int 0
  ..$ right : int 1327
  ..$ bottom: int 399
 $ .nonce : num 0.254
```

with error `Warning in seq_len(nrow(layout)) :  first element used of 'length.out' argument`

Example Script:
```r
library(shiny)
library(ggplot2)

shinyApp(
  ui = pageWithSidebar(
    headerPanel('Iris Data Plot'),
    sidebarPanel(
      selectInput('xcol', 'X Variable', names(iris)),
      selectInput('ycol', 'Y Variable', names(iris), selected=names(iris)[[2]])
    ),
    mainPanel(
      plotOutput('plot1', click = "click"),
      verbatimTextOutput("inputOut")
    )
  ),
  function(input, output, session) {
    output$inputOut  <- renderPrint({
      cat("input$click:\n")
      str(input$click)
    })

    output$plot1 <- renderPlot({
      ggplot(iris, aes_string(x = input$xcol, y = input$ycol)) + 
        geom_point()
    })
  }
)
```

hope this helps, and thanks for making a great package! (in fact, thanks for making great packages!!)

**Comment by hadley** [comment]
One for you @wch

**Comment by thomasp85** [comment]
@wch I expect this is due to the internal rewrite of panel and facets. There has been some renaming as the `panel` class has been removed and a `Layout` class has been added. The basic layout, scales, and ranges data is unchanged though but is found at different locations e.g. `plot$layout$panel_layout` for the layout defined by the facetting function...

**Comment by wch** [comment]
@dcangst We just merged a fix in shiny.
