### ISSUE TITLE
Coord_flip also flip the axes side.

### ISSUE THREAD

**Issue by xvrdm** [hadley/ggplot2#1784]
Since I went from ggplot2 CRAN version to the one hosted on Github, my "coord_flipped" bar plot have changed.

`+ coord_flip()` flip the axes just like before, but it also flip their position: the horizontal axis is above the chart and the vertical axis ends up on the right hand side (I tried with and without styling).

![image](https://cloud.githubusercontent.com/assets/3109069/18883613/2fd49132-84e4-11e6-89f4-e88213f5d2a7.png)

```r
ggplot(id_fill_tot, aes(x=CREATIVE_SIZE,y=value,fill=metric)) +
  geom_bar(position = position_dodge(), stat="identity") + 
  coord_flip() +
  xlab("CREATIVE SIZES") + ylab("") +
  scale_y_continuous(labels = format_si()) + 
  light_bar_theme() +
  theme(legend.position = "none") +
  ggtitle("Hits per size")
```

Does anybody know if it is a common bug, a bug just for my machine or have the arguments for  `+ coord_flip` changed (cannot find traces of that in the release notes)?

Thanks for the awesome lib!

**Comment by thomasp85** [comment]
Minimal repex

```r
ggplot(mtcars) + geom_histogram(aes(mpg)) + coord_flip()
```
![rplot03](https://cloud.githubusercontent.com/assets/1775316/18887344/f6505ca6-84f3-11e6-8088-2f4b1b8aaee2.png)
