### ISSUE TITLE
geom_boxplot fill passed onto outliers

### ISSUE THREAD

**Issue by schloerke** [hadley/ggplot2#1785]
Is it possible to pass the fill value form geom_boxplot aesthetic to the outlier fill color?  This would allow the fill of the outlier points to match the fill of the box plot if the point is set to a shape that allows for a fill.

Line https://github.com/hadley/ggplot2/blob/master/R/geom-boxplot.r#L211 could be something like 

```{r}
# definition
outlier.fill = NULL,
...

# outlier data.frame
fill = outlier.fill %||% data$fill[1]
```

The example would be 

```{r}
ggplot(iris, aes(Species, Sepal.Length, fill = Species)) + geom_boxplot(outlier.shape = 21)
```
![screen shot 2016-09-27 at 3 46 25 pm](https://cloud.githubusercontent.com/assets/93231/18889146/92388ace-84c9-11e6-9c81-90b17b11064d.png)

The legend isn't correct, but the desired output would be something like...
```{r}
ggplot(iris, aes(Species, Sepal.Length)) + geom_boxplot(mapping = aes(color = Species)) + geom_boxplot(outlier.shape = 21, fill = NULL)
```
![screen shot 2016-09-27 at 3 45 49 pm](https://cloud.githubusercontent.com/assets/93231/18889148/95cb0234-84c9-11e6-9838-df0cfa51afa1.png)

Thank you,
Barret

**Comment by hadley** [comment]
Want to do a PR?

**Comment by schloerke** [comment]
Sure. I'll make one shortly. :-)
