### ISSUE TITLE
Should disable image dragging if any plot interactions are enabled

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1788]
If just clicking is enabled, it's distracting and annoying if you click and drag a little bit and the browser thinks you want to drag the image to a folder. (Currently, when brushing is enabled, the image dragging is disabled.)

**Comment by thomasp85** [comment]
Is this ggplot2?

**Comment by wch** [comment]
Oops, I need to pay attention to which repo I'm in. :(
