### ISSUE TITLE
Add an option to show the statistics on regression plots (geom_smooth)

### ISSUE THREAD

**Issue by Nodragem** [hadley/ggplot2#1792]
Hello,

To make things easier for the user, maybe ggplot could annotate (optionnal) the plot with the statistics of the regression lines/curves made by geom_smooth (e.g., r=0.7 , y=ax + b, polynomial coefficients: a, b, c).

What do you think?

**Comment by hadley** [comment]
It's not possible in general for any model.

**Comment by Nodragem** [comment]
I think that your answer is either really rude or lacks of explanation. It is at least not satisfying from a community that supports a novel grammar of graphics. And I feel sorry for that.

To get the statistics of your regression line  directly on the graph is a simple and practical improvement. That exists in matlab and statistical applications such as SPSS for instance.

For a tool that seeks to make graphing easier, it looks like a relevant feature.

**Comment by thomasp85** [comment]
Still, it is not generally possible to do so - the default (loess) is not easily parameterised in the same way as you know for standard linear models.

If you feel this is simple (as you write) we are welcoming pull requests where we can then discus how you've chosen to implement it in more detail.

As for the shortness of the answer I think you should start watching all of Hadleys repositories and see how many issues pop up each day, then I think you will appreciate that he is short and to the point...

**Comment by Nodragem** [comment]
ho ok, I think that I misunderstood the point of Hadley, then. Sorry for that.
Shortness is good but to wrap it into few words of politeness can be even better for your interlocutor :)

Maybe the feature could be supported for only some of the models, such as lm and glm for instance?

What I am worried about is that the user, in order to get the coefficients of the model will have to write his own code and that adds probability to make a mistake (e.g. writing the wrong model, using the wrong function, the wrong parameters, anything a tired human could do). 

So, there should be a way so that **ggplot returns the exact model** that was used for the plot, **either in R** (ggplot returning the model object) **or on the plot** (writing the coefficients, parameters).

**To go a bit further in the future of ggplot.**
That problem may be even more important when ggplot will be using Bayesian methods, where the coefficients of the model varies across simulations. Then, we would like to access the coefficients of the model from the simulation used to make the graph and not from a second simulation.

It may be just details, I don't know, that is why I wanted to discuss it.

Have a nice day,
