### ISSUE TITLE
expand_limits throws warnings

### ISSUE THREAD

**Issue by thomasp85** [hadley/ggplot2#1795]
After the changes in befc4d00df94c4cfec852fdaffb68897a77684d5 where unused aesthetics throw a warning you now get a warning when using `expand_limits()` (that calls geom_blank() under the hood)

```r
ggplot(mtcars) + 
  geom_point(aes(mpg, cyl)) + 
  expand_limits(x = c(-10, NA))
```

**Comment by thomasp85** [comment]
@hadley can you look at this since you made the change?

**Comment by hadley** [comment]
And `geom_bar()`

```R
ggplot(data = data.frame(a= 1, b =2)) +
   geom_bar(mapping = aes(x = a, y = b), stat = "identity")
```
