### ISSUE TITLE
compute_group in ggplot2 (v 2.1.0)

### ISSUE THREAD

**Issue by GuangchuangYu** [hadley/ggplot2#1797]
In ggplot2 (version 2.1.0), all `geom_` defined in `ggtree` are failed with the following error:

```
Error in .fun(piece, ...) : attempt to apply non-function
> traceback()
16: .fun(piece, ...)
15: (function (i)
    {
        piece <- pieces[[i]]
        if (.inform) {
            res <- try(.fun(piece, ...))
            if (inherits(res, "try-error")) {
                piece <- paste(utils::capture.output(print(piece)),
                    collapse = "\n")
                stop("with piece ", i, ": \n", piece, call. = FALSE)
            }
        }
        else {
            res <- .fun(piece, ...)
        }
        progress$step()
        res
    })(1L)
14: .Call(loop_apply_, as.integer(n), f, env)
13: loop_apply(n, do.ply)
12: llply(.data = .data, .fun = .fun, ..., .progress = .progress,
        .inform = .inform, .parallel = .parallel, .paropts = .paropts)
11: ldply(.data = pieces, .fun = .fun, ..., .progress = .progress,
        .inform = .inform, .parallel = .parallel, .paropts = .paropts)
10: plyr::ddply(data, "PANEL", function(data) {
        scales <- layout$get_scales(data$PANEL[1])
        tryCatch(do.call(self$compute_panel, args), error = function(e) {
            warning("Computation failed in `", snake_class(self),
                "()`:\n", e$message, call. = FALSE)
            data.frame()
        })
    })
9: f(..., self = self)
8: self$stat$compute_layer(data, params, panel)
7: f(..., self = self)
6: l$compute_statistic(d, panel)
5: f(l = layers[[i]], d = data[[i]])
4: by_layer(function(l, d) l$compute_statistic(d, panel))
3: ggplot_build(x)
2: print.ggplot(x)
1: function (x, ...)
   UseMethod("print")(x)
```

When I add a `compute_group` function:

```
           compute_group = function(data, params) {
                              data
            },
```

 all of the `geom_` work fine again.

**Comment by GuangchuangYu** [comment]
If I change the `setup_data` to `compute_group`, it will also works.

**Comment by thomasp85** [comment]
Are you sure you're not messing up between stats and geoms? `compute_group` is a `Stat` method and your call stack also suggests that the layer is calling a `Stat` object...

**Comment by GuangchuangYu** [comment]
Sorry for confusing, `compute_group` need to be defined in `Stat` object even it did nothing.

**Comment by thomasp85** [comment]
Sure - what is the purpose of your `Stat` classes if they do not modify data (i.e. overwrites either `compute_layer`, `compute_panel`, or `compute_group`). This is their prime responsibility...

If you don't need to modify data then use or subclass `StatIdentity` rather than `Stat`...

**Comment by GuangchuangYu** [comment]
I do modify data in most of the `Stat` defined in `ggtree` for supporting `phyloseq` object.

[Here](https://guangchuangyu.github.io/2016/09/ggtree-for-microbiome-data/) is an example, that `geom_point` plots many points associated to each tip.

The underlying data.frame contains many duplicated entry for drawing tree structure (lines), tip labels etc. These duplicated entry should be removed and this is what ggtree `Stat` did.

So the issue here is now `ggplot2` requires `Stat` object must have a `compute_group` method defined. Am I understand correctly?

**Comment by thomasp85** [comment]
`Stat` classes have always needed either `compute_layer`, `compute_panel`, or `compute_group`. The `Stat` class is a virtual class that requires some specific methods to be overridden. If you have situations where the purpose of the `Stat` subclass is only to call `setup_data()` (and thus not do any statistical transformation of the data) you should define it as a subclass of `StatIdentity` rather than as a subclass of `Stat`. (or make a `compute_group()` method as you proposed but it is easier an cleaner to just subclass `StatIdentity`) - see how `StatFilter`[has been implemented in ggraph](https://github.com/thomasp85/ggraph/blob/7212f64b99c69511d2b409b5215cd2b8210e8b54/R/aaa.R) for an example

**Comment by GuangchuangYu** [comment]
Thank you @thomasp85 👍
