### ISSUE TITLE
ggmap Error in zero_range(from) : x must be length 1 or 2

### ISSUE THREAD

**Issue by titaniumtroop** [hadley/ggplot2#1800]
Attempting to use ggmap gives the subject error. Code works with CRAN version.

Code:

`library(ggplot2) # ggplot2_2.1.0.9000`
`library(ggmap) # ggmap_2.6.1`
`lat <- as.numeric("34.807085")`
`lng <- as.numeric("-92.233561")`
`gmap <- get_map(location = c(lon = lng, lat = lat), zoom = 7, maptype = 'roadmap', scale=2, color = "bw") # Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=34.807085,-92.233561&zoom=7&size=640x640&scale=2&maptype=roadmap&language=en-EN&sensor=false`
`map <- ggmap(gmap)`
`map # Error in zero_range(from) : x must be length 1 or 2`

**Comment by thomasp85** [comment]
There has been quite a lot of internal changes which are bound to have an effect some of packages that extends ggplot2. Please report this to ggmap so they can look into it

**Comment by titaniumtroop** [comment]
dev version of ggmap has resolved this issue.
