### ISSUE TITLE
Weirdness with evaluation of facet vars

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1803]
```
# Works
    ggplot(diamonds, aes(carat, price)) + 
      geom_hex(bins = 20) + 
      facet_wrap(~cut_number(depth, 9))

# Doesn't work
    ggplot(diamonds, aes(carat, price)) + 
      geom_hex(bins = 20) + 
      facet_wrap(~cut_number(table, 9))
```

**Comment by AndyClifton** [comment]
Is this related to / the same bug, that is causing 

**Error in as.character(what): cannot coerce type 'closure' to vector of type 'character'**

on http://docs.ggplot2.org/dev/facet_wrap.html?

**Comment by AndyClifton** [comment]
Apologies for hijacking this issue, but my issue was related to the use of a faceting variable that has the same name as a built-in function; changing the name to something else fixed the problem. No idea if that will help here.

**Comment by hadley** [comment]
@DanRuderman this is the flip side to #1822 — the example that doesn't work actually fails with error from `cut_number` because there are insufficient values to produce 9 groups. 

Resolving these two issues will require a little thought. I _think_ the right thing to do is rewrite `quoted_df` so that it drops missing variables silently, but always evaluates expressions. The only downside is that then if you're facetting on an expression, there's no easy way to add data to every panel.
