### ISSUE TITLE
ggplot2 with plotly fail

### ISSUE THREAD

**Issue by emdelponte** [hadley/ggplot2#1806]
Hadley,

The ggplotly function broke when knitting a document. I rolled back to the release version and it worked. Then, I installed the new version again and got this error when running this example code:

> dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
> qplot(carat, price, data=dsamp, colour=clarity)
> ggplotly()
Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function

**Comment by hadley** [comment]
@cpsievert can you please take a look?

**Comment by cpsievert** [comment]
plotly's current CRAN release is not compatible with ggplot2 >2.1.0...you have two options:

(1) Use the CRAN version of both packages
(2) Use the dev version of plotly, which now [requires ggplot2 >2.1.0](https://github.com/ropensci/plotly/blob/master/DESCRIPTION)

**Comment by emdelponte** [comment]
Thanks. I am using the dev version of plotly and everything is working fine.

**Comment by Babakjfard** [comment]
hello,
I used the dev version of plotly and now everything is in a big mess. I receive "Error in loadNamespace( " in many different ways. such as using tidyverse, using ggplot2 after installing it seperately... 
I wonder what has happened. Thank you so much for your help..

**Comment by frkbr** [comment]
I get the same error:

    ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)

    ggplotly(ggiris)

    Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
      attempt to apply non-function

I use plotly 4.7.1.9000 and ggplot2 2.2.1.9000. Same problem if I use any combination of CRAN-versions and dev versions of the two packages.

macOS High Sierra 10.13.3
R version 3.4.3
RStudio Version 1.1.419
