### ISSUE TITLE
Conflict with ggmap

### ISSUE THREAD

**Issue by christianlindell** [hadley/ggplot2#1807]
With the current stable release of ggplot this command produces a map of Europe:

```
map <- get_map(location = 'Europe', zoom = 3, language = "sv-SV", color = "color")
ggmap(map)
```

With ggplot2 v. 2.1.0.9001 the code doesn't show a map. Instead I got an error:

> Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=Europe&zoom=3&size=640x640&scale=2&maptype=terrain&language=sv-SV&sensor=false
> Information from URL : http://maps.googleapis.com/maps/api/geocode/json?address=Europe&sensor=false
> Error in zero_range(from) : x must be length 1 or 2

System: Windows 7.
R-version: 3.3.1
RStudio: 0.99.902
ggmap: 2.6.1

**Comment by hadley** [comment]
cc @dkahle

**Comment by dkahle** [comment]
Works for me.  You just need the dev version of ggmap (to be released on CRAN this week).

<img width="774" alt="2016-10-03_0800" src="https://cloud.githubusercontent.com/assets/424139/19038100/94b5c800-893f-11e6-9e12-fe86b5a960e8.png">
