### ISSUE TITLE
Warning: Ignoring unknown aesthetics: show_guide

### ISSUE THREAD

**Issue by yilingcheng** [hadley/ggplot2#1811]
Thanks a lot. 

I've installed the tested the candidate version (2.2.0) accordingly (devtools::install_github("hadley/ggplot2")). When I check the version using "packageVersion("ggplot2"), it shows '[1] 2.1.0.9001'. Is this right?

when I run my codes "...geom_ribbon(aes(ymin=ll, ymax=ul, group=factor(by), show_guide=FALSE), alpha=0.15)...", the plot is fine but there is a warning note, "Warning: Ignoring unknown aesthetics: show_guide"

**Comment by hadley** [comment]
Yup, and that's because you put `show_guide` in the wrong place (and it's now called `show.legend`)`. So the warning is doing what it's supposed to do :)

**Comment by yilingcheng** [comment]
Oops! Thanks! ^^
