### ISSUE TITLE
y axis line not shown in all facets

### ISSUE THREAD

**Issue by Eluvias** [hadley/ggplot2#1812]
```{r 1}
ggplot(economics_long, aes(date, value)) +
  geom_line() +
  facet_grid(variable~., scales = "free_y")  +
  theme(axis.line = element_line(color = "blue"))
```

```{r 12}
ggplot(economics_long, aes(date, value)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y" ,strip.position = "top") +
  theme(strip.background = element_blank()) +
  theme(axis.line = element_line(color = "blue"))
```

 session info

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0.9000

**Comment by thomasp85** [comment]
I'm unsure it has ever been different - can you provide an example showing different behaviour in an earlier version...

**Comment by Eluvias** [comment]
Hi Thomas,

```{r 1}
#  ggplot2_2.1.0
p <- ggplot(economics_long, aes(date, value)) +
  geom_line() +
  facet_grid(variable~., scales = "free_y")

 p + theme(axis.line.y = element_line(color = "blue"),
        axis.line.x = element_line(color = "blue"))
```

![p_2 10](https://cloud.githubusercontent.com/assets/22600883/19054302/b00a8ba0-89b6-11e6-9a02-c638c6798245.png)

```{r 2}
#  ggplot2_2.1.0.9001
p <- ggplot(economics_long, aes(date, value)) +
  geom_line() +
  facet_grid(variable~., scales = "free_y")

 p + theme(axis.line.y = element_line(color = "blue"),
        axis.line.x = element_line(color = "blue"))
```
![p_2 1 09](https://cloud.githubusercontent.com/assets/22600883/19054338/e63cde8a-89b6-11e6-9fad-17917e362618.png)

**Comment by thomasp85** [comment]
That is not intended - it is fixed now. Thanks

**Comment by Eluvias** [comment]
Thank you!
