### ISSUE TITLE
gtable axis names

### ISSUE THREAD

**Issue by schloerke** [hadley/ggplot2#1813]
Hi,

I heavily depend upon the names of the gtable objects for `GGally`.  With the current master branch of `ggplot2`, I am getting strange axis gtable names.

```r
qplot(1:10, 21:30, geom = "point") %>% ggplot_build() %>% ggplot_gtable()
# TableGrob (10 x 7) "layout": 17 grobs
#     z         cells       name                                    grob
# 1   0 ( 1-10, 1- 7) background        rect[plot.background..rect.4769]
# 2   5 ( 5- 5, 3- 3)     spacer                          zeroGrob[NULL]
# 3   7 ( 6- 6, 3- 3)     axis-t    absoluteGrob[GRID.absoluteGrob.4764]
# 4   3 ( 7- 7, 3- 3)     spacer                          zeroGrob[NULL]
# 5   6 ( 5- 5, 4- 4)     axis-l                          zeroGrob[NULL]
# 6   1 ( 6- 6, 4- 4)      panel               gTree[panel-1.gTree.4744]
# 7   9 ( 7- 7, 4- 4)     axis-r    absoluteGrob[GRID.absoluteGrob.4757]
# 8   4 ( 5- 5, 5- 5)     spacer                          zeroGrob[NULL]
# 9   8 ( 6- 6, 5- 5)     axis-b                          zeroGrob[NULL]
# 10  2 ( 7- 7, 5- 5)     spacer                          zeroGrob[NULL]
# 11 10 ( 4- 4, 4- 4)     xlab-t                          zeroGrob[NULL]
# 12 11 ( 8- 8, 4- 4)     xlab-b titleGrob[axis.title.x..titleGrob.4747]
# 13 12 ( 6- 6, 2- 2)     ylab-l titleGrob[axis.title.y..titleGrob.4750]
# 14 13 ( 6- 6, 6- 6)     ylab-r                          zeroGrob[NULL]
# 15 14 ( 3- 3, 4- 4)   subtitle  zeroGrob[plot.subtitle..zeroGrob.4766]
# 16 15 ( 2- 2, 4- 4)      title     zeroGrob[plot.title..zeroGrob.4765]
# 17 16 ( 9- 9, 4- 4)    caption   zeroGrob[plot.caption..zeroGrob.4767]
```
![screen shot 2016-10-03 at 4 18 11 pm](https://cloud.githubusercontent.com/assets/93231/19052507/0e574cf2-8985-11e6-8f9a-0b4a877fe6e6.png)

`axis-l` is being called `axis-t`. `axis-b` is being called `axis-r`.

If these could be switched back, that'd be great.  

Thank you!
- Barret

**Comment by thomasp85** [comment]
The layout and facet ting has been changed and along with that has come support for freely positioning of axis on either side. Because of this there is now `axis-l`, `-r`, `-t`, and `-b`, though some of them might be zeroGrobs depending on the plot settings. `axis-l` is still `axis-l` as before...

**Comment by schloerke** [comment]
I like the update, but `axis-l` is a zeroGrob when it shouldn't be in the example above.  And `axis-t` is a non-zeroGrob when it shouldn't be.

**Comment by thomasp85** [comment]
Oh - thanks for that catch. That is me failing to convert a matrix to a vector in my head... Will be fixed!

Thanks

**Comment by schloerke** [comment]
thank you!
