### ISSUE TITLE
title not centered in plot

### ISSUE THREAD

**Issue by schloerke** [hadley/ggplot2#1815]
plot title is no longer centered (when it should be?)

```r
qplot(1:10, 21:30, main = "not centered")
```
![screen shot 2016-10-03 at 5 02 10 pm](https://cloud.githubusercontent.com/assets/93231/19053966/47ec0eac-898b-11e6-9d17-79f824b502f4.png)

Thank you!
-Barret

**Comment by thomasp85** [comment]
This a deliberate change as described in the NEWS.md file

**Comment by schloerke** [comment]
sorry about that.  thank you!

**Comment by thomasp85** [comment]
No problem

**Comment by MrAE** [comment]
This helped me:  Here's how you'd put the title back in the center. 

```R
ggplot() +
  ggtitle("(: Title in the center :)") + 
  theme(plot.title = element_text(hjust = 0.5))
```
