### ISSUE TITLE
Warning when using ggplot2 as output in shiny

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1816]
The following code is a minimal usecase of ggplot2 in shiny:

```
library(shiny)
library(ggplot2)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    ggplot(mtcars, aes(wt,mpg)) + geom_point()
  })
}

shinyApp(ui = ui, server = server)
```

I get the following warning:

```
Warning in seq_len(nrow(layout)) :
  first element used of 'length.out' argument
```

ggplot2 2.1.0.9001 shiny 0.14

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.1.0.9001 shiny_0.14        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      assertthat_0.1   digest_0.6.10    mime_0.5         grid_3.3.1      
 [6] R6_2.1.3         plyr_1.8.4       jsonlite_1.1     xtable_1.8-2     gtable_0.2.0    
[11] scales_0.4.0     lazyeval_0.2.0   labeling_0.3     tools_3.3.1      munsell_0.4.3   
[16] httpuv_1.3.3     colorspace_1.2-6 htmltools_0.3.5  tibble_1.2
```

When I use ggplot2 2.1.0 or if I use base `plot()` instead of ggplot2, I don't get the warning

**Comment by thomasp85** [comment]
try installing the latest and greatest shiny from GitHub - they just made some changes in response to ggplot2' update

**Comment by daattali** [comment]
Thanks @thomasp85 , yes shiny fixed it

Do you know if shiny is planning on releasing around the same time as ggplot2?

**Comment by thomasp85** [comment]
No, but I expect they will - there're some breaking changes to the ggplot2 locator as well

**Comment by wch** [comment]
I submitted a new version to CRAN today that should work with both ggplot2 <=2.1.0 and >2.1.0.

**Comment by daattali** [comment]
Thanks Winston

**Comment by wch** [comment]
@hadley In the release announcement, we'll have to make sure to mention this.

**Comment by pierrelafortune** [comment]
I'm having this problem still. I have both ggplot2_2.1.0.9000 and shiny_0.14.2.9000. Using OP's example, I get the warning

**Comment by wch** [comment]
@pierrelafortune Does it still happen if you update to the latest version of ggplot2?

**Comment by pierrelafortune** [comment]
It works thank you much

**Comment by daattali** [comment]
FYI newest version of ggplot2 is once again causing this problem in shiny :)

**Comment by wch** [comment]
@daattali What versions of ggplot2 and shiny are you using?

**Comment by daattali** [comment]
I was using yesterday's ggplot, but now that you ask - I realize shiny was
from cran. Perhaps you did fix it already
