### ISSUE TITLE
theme: strip.placement is not documented

### ISSUE THREAD

**Issue by Eluvias** [hadley/ggplot2#1818]
`strip.placement` is not documented in `theme`.  Do you also think it should default to ` outside`  when  we `switch` the labels to the left-hand side?  - This will be  consistent with the old behaviour.  Please see the example below.

````{r 1}
# cran version
p <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
  geom_point()

p <-p+ facet_grid( cyl~., scales = "free", switch = "y")

p
```
![p_pro](https://cloud.githubusercontent.com/assets/22600883/19057103/84657334-89c5-11e6-9886-3cbdd1d77748.png)

````{r 2}
# dev version
p <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
  geom_point()

p <-p+ facet_grid( cyl~., scales = "free", switch = "y")

p
```
![p_dev](https://cloud.githubusercontent.com/assets/22600883/19057144/b8476d10-89c5-11e6-9596-17d89210b11b.png)

````{r 3}
p + theme(strip.placement = "outside")
```

![p_dev_outer](https://cloud.githubusercontent.com/assets/22600883/19057189/fdf54a44-89c5-11e6-9776-60849957a092.png)

Thanks!

**Comment by hadley** [comment]
@thomasp85 @lionel- I think this might be an interaction between two sets of work on strips

**Comment by thomasp85** [comment]
Lack of docs is an oversight. I don't think the theme should depend on plot settings. The rationale for putting it in theme is that for solid strips (e.g. theme_grey) it looks best with the strip in between the axis and panel, while for strips with no background the reverse is true...
