### ISSUE TITLE
bug: geom_text in middle of stacked bar_plot not in the middle (v2.1.0.9001)

### ISSUE THREAD

**Issue by dapper2dan** [hadley/ggplot2#1821]
The placement of geom_text in the middle of a stacked bar_plot is off. When I run the example from the help file of `geom_text` I get:

```r
df <- data.frame(
  x = factor(c(1, 1, 2, 2)),
  y = c(1, 3, 2, 1),
  grp = c("a", "b", "a", "b")
)

df <- transform(df, mid_y = ave(df$y, df$x, FUN = function(val) cumsum(val) - (0.5 * val)))

ggplot(data = df, aes(x, y, fill = grp, label = y)) +
  geom_col() +
  geom_text(aes(y = mid_y))
```

![stacked_text](https://cloud.githubusercontent.com/assets/1423562/19081941/65229a8c-8a5c-11e6-86da-13581e88c822.png)

I suppose this is [due to](https://blog.rstudio.org/2016/09/30/ggplot2-2-2-0-coming-soon/) "`position_stack()` and `position_fill()` now stack values in the reverse order of the grouping, which makes the default stack order match the legend."

**Comment by aosmith16** [comment]
The dataset will need to be arranged in the reverse order of the `fill` factor to calculate the positions correctly with `cumsum`.

`df <- transform(df[order(rev(df$grp)), ], mid_y = ave(y, x, FUN = function(val) cumsum(val) - (0.5 * val)))`

**Comment by dapper2dan** [comment]
That's a possibility, of course, but a bad one at that, IMHO. Because reversing the order of the grouping of the bars under the hood without reversing the order of the labels is a breaking change. After all the example from the geom_text help file is  working in v2.1 and will break, as it stands, in v2.2, and so will all similar bar charts created with ggplot2 v2.1 and before. So is there a chance to adapt geom_text to the new grouping order?

**Comment by hadley** [comment]
One possible resolution would be a new position adjustment that "stacks" text like this, including an optional parameter (0-1) that lets you control where the text appears within the rectangular region. That wouldn't fix existing code the relies on the specific stacking order, but it would provide a simple fix.

**Comment by hadley** [comment]
Here's a quick implementation:

```R
#' @example
#' df <- data.frame(
#' x = factor(c(1, 1, 2, 2)),
#' y = c(1, 3, 2, 1),
#' grp = c("a", "b", "a", "b")
#' )
#'
#' ggplot(data = df, aes(x, y, fill = grp, label = y)) +
#'   geom_col() +
#'   geom_text(position = "stack_point")
position_stack_point <- function(vjust = 0.5) {
  ggproto(NULL, PositionStackPoint,
    vjust = vjust
  )
}

PositionStackPoint <- ggproto("PositionStackPoint", Position,
  required_aes = c("x", "y"),
  vjust = 0.5,

  setup_params = function(self, data) {
    list(vjust = self$vjust)
  },

  compute_layer = function(self, data, params, panel) {
    data <- data[order(data$x, -data$group), ]
    data$y <- ave(data$y, data$x, FUN = function(x) cumsum(x) - ((1 - params$vjust) * x))
    data
  }
)
```

**Comment by dapper2dan** [comment]
Well, provided that I am not too fond of breaking changes (ah, yes, I mentioned that already), judging from a (very) quick test this seems to work. BUT: If the goal is that the "default stack order match[es] the legend" shouldn't this also be true for a horizontal bar chart?

```r
df <- data.frame(
  x = factor(c(1, 1, 2, 2)),
  y = c(1, 3, 2, 1),
  grp = c("a", "b", "a", "b")
)

ggplot(data = df, aes((x), y, fill = (grp), label = y)) +
  geom_col() +
  geom_text(position = "stack_point") + 
  theme(legend.position = "bottom") +
  coord_flip()
```

If I am not mistaken, the order of the bars in the chart is b, a in the stacked bars, but a, b in the legend (from left to right, with v2.1.0.9001). Now, I know this is a separate issue, but IF this is to be fixed as well (which I think it should for the sake of consistency), does position_stack_point still work here?

**Comment by hadley** [comment]
@dapper2dan deleted your comment here, just to keep the discussion on track

**Comment by hadley** [comment]
I now think that this should be integrated with `position_stack` so it does the right thing for both points and bars

**Comment by thomasp85** [comment]
We could have a `just` argument that could control that. It works fine for points as it is now (I.e. It stacks them) but this would give users even more control

**Comment by hadley** [comment]
That's what I'm in the middle of implementing 😄
