### ISSUE TITLE
Error adding all-data layer to facets

### ISSUE THREAD

**Issue by aosmith16** [hadley/ggplot2#1822]
Previously, you could add a background layer based on all the data to each facet by using a dataset with the faceting variable removed.  

In ggplot2_2.1.0.9001:

```
ggplot(mpg, aes(displ, hwy)) + 
	geom_point(data = mpg[ , 1:10], color = "grey") +
	geom_point()  + 
	facet_wrap(~class)
```

> Error in as.character(what) : 
>   cannot coerce type 'closure' to vector of type 'character'

**Comment by hadley** [comment]
@DanRuderman I think this bug was introduced by the changes to variable evaluation in facetting.

**Comment by thomasp85** [comment]
My thoughts too - I'll look into it

**Comment by DanRuderman** [comment]
@thomasp85 @hadley I'm available to assist with this and/or #1803.

**Comment by hadley** [comment]
Interestingly this works:

```R
df <- data.frame(x = 1:2, y = 1:2, z = 1:2)
ggplot(df, aes(x, y)) + 
  geom_point(size = 5, colour = "red", data = df[c("x", "y")]) + 
  geom_point() +
  facet_wrap(~ z)
```

**Comment by hadley** [comment]
Oh, because `class` is also a function in the globalenv. So this is exactly the same problem as #1803
