### ISSUE TITLE
rstan::stanplot fails with the development version

### ISSUE THREAD

**Issue by singmann** [hadley/ggplot2#1824]
I am not sure if this is the right place to report this, but it appears that the development version of `ggplot2` (2.2.0) fails with the rstan plotting function:

```
require(rstan)
example("read_stan_csv")
stan_plot(fit)
```
Gives:

```
Error in if (e1$inherit.blank) return(e2) else return(e1) : 
  argument is of length zero
```

Also:
```
> stan_trace(fit)
Error in `[.unit`(padding, 4) : index out of bounds ('unit' subsetting)
```

I will also post this on the [rstan mailing list](https://groups.google.com/forum/#!forum/stan-users).

**Comment by hadley** [comment]
Yeah, problems with ggplot2 extensions need to be reported to the maintainer of the package. Thanks!
