### ISSUE TITLE
Unicode donen't work on axis text but on geom_text?

### ISSUE THREAD

**Issue by emillykkejensen** [hadley/ggplot2#1827]
I can't seem to get the axis text showing unicode, but when i try it in geom_text it shows up just fine.

Is there a way to do this or...?

```
ggdata <- data.frame(text = c("text 1", "text <U+2665>", "text ♥"), value = c(1, 3, 5), stringsAsFactors = FALSE)

ggplot(data = ggdata, aes( x = text, y = value, label = text)) + geom_bar(stat="identity") + geom_text(nudge_y = 1)
```

![rplot](https://cloud.githubusercontent.com/assets/8842355/19107766/1a3ec8be-8aee-11e6-9ca3-141207f9cc21.png)

**Comment by hadley** [comment]
It works for me, but you're probably on windows. Can you please confirm the simpler reprex below still illustrates the problem for you?

```R
df <- tibble::tibble(x = c("a", "♥"))

ggplot(df, aes(x, x)) + 
  geom_text(aes(label = x))
```

**Comment by emillykkejensen** [comment]
The problem is stil there. And yes, I'm one a Windows - just tried to run your code on a linux server I have, and there it worked fine.

![rplot](https://cloud.githubusercontent.com/assets/8842355/19112638/316695b8-8b06-11e6-8c39-fb560671a12a.png)

**Comment by hadley** [comment]
The root cause seems to be a buglet in R. On windows, I see:

```R
x <- c("a", "♥")
format(x)
#> [1] "a       " "<U+2665>"
```

😞

**Comment by hadley** [comment]
Ok, pretty sure I fixed it, just by avoiding the use of `format()` (which I'm not sure why was necessary in most cases anyway). Please let me know if this doesn't fix the problem.

**Comment by emillykkejensen** [comment]
Works! Thanks :-)
