### ISSUE TITLE
geom_rug does not allow aesthetic x anymore

### ISSUE THREAD

**Issue by paul-buerkner** [hadley/ggplot2#1830]
This does not matter if aesthetics are inherited from the original `ggplot` object. However, I am not able anymore to add a rug plot for data other than the data used to create the plot (i.e. when using `data = <new data>` and `inherit.aes = FALSE`). Is there a way around that I have just overlooked?

**Comment by hadley** [comment]
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by paul-buerkner** [comment]
Sorry for not providing a reproducible example in the first place. Here we go:

```R
library(ggplot2)
dat <- data.frame(x = 1:9, y = 1:9)
newdat <- data.frame(x = c(rep(2, 4), rep(5, 5)), y = 1:9)

gg <- ggplot(dat, aes(x = x, y = y)) + 
  geom_smooth(stat = "identity")
gg1 <- gg + geom_rug(aes(x = x), inherit.aes = FALSE,
                     data = newdat)
# warns "Ignoring unknown aesthetics: x"
# but plots the rug regardless
plot(gg1)

gg2 <- gg + geom_rug(inherit.aes = FALSE,
                     data = newdat)
# no warning but also no plotting of the rug
plot(gg2)
```

That is, I can still produce the desired plot (contrary to what I said in my initial post), but it will throw a warning that I am not able to get rid of.
