### ISSUE TITLE
v2.2.0 error: cannot use facet_grid() when ggplot() call has no dataframe

### ISSUE THREAD

**Issue by daattali** [hadley/ggplot2#1835]
Previously, the following code worked:

```
library(ggplot2)
df <- data.frame(x = 1:4, y = 1:4, row = c(1,1,2,2), col = c(1,2,1,2))
ggplot() + geom_point(data = df, aes(x,y)) + facet_grid(row~col)
```

Now I get an error

```
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'closure'.
```

This one could potentially fall either under "bug" or "feature". I can see why that code SHOULD produce an error because I didn't explicitly tell facet_grid what data to use, but since ggplot2 is so popular, it might be worth it to still allow that code to work. Hard to tell how many people use code like this and will have broken code without knowing what to do

**Comment by hadley** [comment]
Dup of #1822
