### ISSUE TITLE
Setting Theme Cancels User-defined Title Placement

### ISSUE THREAD

**Issue by DarioS** [hadley/ggplot2#1836]
The documentation shown by `?ggtheme` doesn't suggest that a theme would affect plot title placement, but it does.

    carsPlot <- ggplot(mtcars, aes(wt, mpg)) + geom_point() + ggtitle("Cars")

Left aligned:

    carsPlot + theme(plot.title = element_text(hjust = 0.5)) + theme_classic() 

Centred:

    carsPlot + theme_classic() + theme(plot.title = element_text(hjust = 0.5))

**Comment by thomasp85** [comment]
When adding a theme you're overriding all style settings set prior to adding it as `theme_*` is defining all styles (it is *complete*)
