### ISSUE TITLE
Horizontal bar graphs: Match default stack order in legend as well

### ISSUE THREAD

**Issue by dapper2dan** [hadley/ggplot2#1837]
According to the [v2.2.0 announcement](https://blog.rstudio.org/2016/09/30/ggplot2-2-2-0-coming-soon/): "position_stack() and position_fill() now stack values in the reverse order of the grouping, which makes the default stack order match the legend." IMHO this should also be true for horizontal bar graphs.

```r
df <- data.frame(
  x = factor(c(1, 1, 2, 2)),
  y = c(1, 3, 2, 1),
  grp = c("a", "b", "a", "b")
)

ggplot(data = df, aes((x), y, fill = (grp), label = y)) +
  geom_col() +
  geom_text(position = "stack_point") + 
  theme(legend.position = "bottom") +
  coord_flip()
```

![horizontal_bar_graph_order](https://cloud.githubusercontent.com/assets/1423562/19145097/90b24b00-8bad-11e6-925f-3a3c53cbdfe4.png)

`position = "stack_point"` borrowed from #1821.

**Comment by hadley** [comment]
@thomasp85 we forgot about this important case. Any ideas?  `forcats::fct_rev()` doesn't help as it flips order in both plot and legend.

**Comment by thomasp85** [comment]
Honestly I don't think we can have it both ways, so we need to decide on the preferred default.

**Comment by thomasp85** [comment]
We could add a `reverse` argument to the scale constructors that would make it easy to reverse legend order. An ugly "fix" but it would solve it partly

**Comment by hadley** [comment]
Would reversing legend order work? It doesn't seem great to have labels "b", "a". And reversing the mapping between colour and letter would just flip the colours in both locations.

**Comment by thomasp85** [comment]
Come to think of it the natural thing would be to have a switch in `position_stack`. We cannot make this automatic as neither `Coord`, `Scale`, nor `Position` is aware of each other's presence and it would thus degenerate into horrible `coord_flip` checks everywhere (we already have enough of those)

**Comment by hadley** [comment]
Agreed. Let me merge my stacking changes, and then one of us can add a `reverse` argument.

**Comment by hadley** [comment]
@thomasp85 I also changed the default order to stack from inside-out (i.e. from close to axis to far away). That looks better to me eye because you get a mirror image if each `x` value has the same levels.

**Comment by thomasp85** [comment]
I'm unsure what you mean - skimming the diff it seems default behaviour is preserved (I.e. Stacking from top to bottom)

**Comment by hadley** [comment]
Negative values stack in the opposite direction now
