### ISSUE TITLE
calling theme_set within a function has side effects outside of the function

### ISSUE THREAD

**Issue by jgabry** [hadley/ggplot2#1838]
Currently, calling `theme_set` within a function will change the theme for plots created outside of that function. For example if I do this

```r
library(ggplot2)
f <- function() {
  theme_set(theme_classic())
  ggplot(mtcars, aes(x = mpg, y = wt)) + geom_point()
}
f()
```
then the plot looks like I would expect. However I wouldn't expect `theme_classic` to now be the theme for all plots created _outside_ of `f`. For example if I call `f` and then afterwards execute
```r
ggplot(mtcars, aes(x = disp)) + geom_histogram()
```
it will still use `theme_classic` despite the fact that `theme_classic` was set _inside_ the function `f`. Another consequence of this is that if `theme_set` is called inside a package then it seems to affect plots created by other packages unless they are explicitly overriding the theme. 

Anyway, if this is the intended behavior of `theme_set` then I suggest at least documenting it, as I don't see a mention of it at `help("theme_set")`. 

Thanks!

P.S. I know in my example I could define `f` differently (e.g. with `+ theme_classic()` at the end instead of using `theme_set()`)

**Comment by has2k1** [comment]
That is the intended behaviour. It is the norm that for functions with side effects, the user is responsible for undoing the side effects at the end of the scope for which those effects are desired.

The documentation does show the `set` -`unset` idiom

```R
old <- theme_set(theme_bw())
# plot
# plot
# plot
theme_set(old)
```

**Comment by hadley** [comment]
Yes, that's the whole point of `theme_set()` ;)  If you want a temporary setting either do what @has2k1 suggested, or just add the theme to the plot.

**Comment by jgabry** [comment]
Thanks again for the prompt reply! That makes total sense and I definitely should have noticed from the examples.

**Comment by jgabry** [comment]
@has2k1 

> The documentation does show the set -unset idiom

It does show it and I should have noticed! But in general I would think that breaking with standard scoping inside functions and making global changes (even if idiomatic) would be mentioned in the documentation text itself as opposed to left for uncommented examples (at least uncommented in relation to this). That's a minor quibble though. Thanks again for your quick help.
