### ISSUE TITLE
Horizontal legends

### ISSUE THREAD

**Issue by hadley** [hadley/ggplot2#1842]
Didn't this use to lay out the legends horizontally?

```R
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(colour = factor(cyl), shape = factor(vs))) +
  theme(legend.position = "bottom")
```

i.e. the same as:

```R
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(colour = factor(cyl), shape = factor(vs))) +
  theme(legend.position = "bottom", legend.box = "horizontal")
```

**Comment by thomasp85** [comment]
I don't think so. Hasn't it always been necessary to be explicit ?

**Comment by hadley** [comment]
But there's space to the left of the second legend - that doesn't seem right.

**Comment by hadley** [comment]
In any case, I think it should be changed, so I'll do it
