### ISSUE TITLE
Integration with ggmap

### ISSUE THREAD

**Issue by niklasvm** [hadley/ggplot2#1846]
I am having an issue using the package _ggmap_ with the unreleased version of _ggplot2_. When I rollback to the previous released version it works fine.

Here's my example.

```{r}
library(ggplot2)
library(ggmap)

ggmap(get_map(location=geocode("Cape Town"), 
              scale=1, 
              zoom = 11))
```
The following error is shown:
__Error in zero_range(from) : x must be length 1 or 2__

**Comment by hadley** [comment]
Fixed in dev version of ggmap
