### ISSUE TITLE
issue with coord_flip() + facet_wrap() + free scales in one direction only

### ISSUE THREAD

**Issue by juliasilge** [hadley/ggplot2#1848]
Thank you so much to all the contributors for all the work on this package!

I have run into an issue when using `scales = "free_x"` or similar in just one direction with `coord_flip()` and `facet_wrap()`.

If I do something like this:
```
diamonds %>% 
    group_by(color, cut, clarity) %>% 
    summarise(median_carat = median(carat)) %>%
    ggplot(aes(color, median_carat, fill = cut)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    facet_wrap(~clarity, scales = "free")
```
everything looks great and I get the result I would expect.
![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/12505835/19280062/57ae9e4c-8fa1-11e6-9fac-e0fd4910a987.png)

If I just want to have the scales free on one axis (because all those things are the same on the y-axis):
```
diamonds %>% 
    group_by(color, cut, clarity) %>% 
    summarise(median_carat = median(carat)) %>%
    ggplot(aes(color, median_carat, fill = cut)) +
    geom_bar(stat = "identity", position = "dodge") +
    coord_flip() +
    facet_wrap(~clarity, scales = "free_x")
```
then there is a problem. The data is getting plotted correctly, but the labels on the x-axis at the bottom are wrong.
![unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/12505835/19280110/905dcac4-8fa1-11e6-925a-2ab0dcdd3e77.png)

It's all the same labels.

**Comment by thomasp85** [comment]
I *think* this is an easy fix and probably related to reuse of the scale for the first panel if the scale is fixed (`coord_flip()` messes up so much - we should consider how we can implement it better...)

**Comment by tiernanmartin** [comment]
FWIW, here's an additional example that illustrates two things:

- the value of combining`coord_flip` with `facet_wrap` (moving the longish labels to the y-axis where they are easier to read)
- the failure of the `facet_wrap` to assign the correct labels to the "free" axis (`names` in this example)

```
library(tidyverse)
library(forcats)

mtcars %>% 
        mutate(names = fct_reorder(factor(row.names(mtcars)),mpg,.desc = TRUE)) %>%
        ggplot(aes(x = names, y = mpg)) +
        geom_point() +
        coord_flip() +
        facet_wrap(~vs,nrow = 2,ncol = 1, scales = 'free_y',labeller = "label_both")
        
```
![facet-wrap-bug](https://cloud.githubusercontent.com/assets/8197328/19541331/49dbd486-961a-11e6-8eb4-c6e164187193.png)
