### ISSUE TITLE
install from github not working due to Rtools not working with R3.3.1 

### ISSUE THREAD

**Issue by micstr** [hadley/ggplot2#1849]
Installing is failing due to Rtools missing. 

`devtools::install_github("hadley/ggplot2")`

>Downloading GitHub repo hadley/ggplot2@master
> from URL https://api.github.com/repos/hadley/ggplot2/zipball/master
> Installing ggplot2
> Downloading GitHub repo hadley/scales@master
> from URL https://api.github.com/repos/hadley/scales/zipball/master
> WARNING: Rtools is required to build R packages, but is not currently installed.
> 
> Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
> Error: Could not find build tools necessary to build scales

when I try fix this problem then I get

> install.packages("Rtools")
Installing package into ‘C:/Users/...../Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.3.1)

Is there a way around this without downgrading R?

**Comment by thomasp85** [comment]
Rtools is not a package but a separate suit of executables that allow you to build packages from source - these are required for Windows as the OS does not come with the necessary compilers etc...

Please use the provided link to download an installer...
