### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by lionel-** [hadley/ggplot2#1851]
Hi @thomasp85 and @hadley

I'm still looking into Travis failures, but I've run the visual tests and found the following discrepancies between 2.1.0 and 2.2.0.

With `coord_map()` 2.2.0 shows the x axis on top rather than at bottom:

```r
world_map <- map_data("world")
pworld <- ggplot(world_map, aes(x = long, y = lat, group = group)) + geom_polygon()
pworld + coord_map(projection = "aitoff") +
  scale_y_continuous(breaks = (-2:2) * 30) +
  scale_x_continuous(breaks = (-4:4) * 45, limits = c(-180, 180))
```

In this violin plot, the y scales are not the same:

```r
set.seed(111)
dat <- data.frame(x = LETTERS[1:3], y = rnorm(90))
dat <- dat[dat$x != "C" | c(T, F),]  # Keep half the C's
ggplot(dat, aes(x = x, y = y)) + geom_violin(trim = FALSE) + geom_point(shape = 21)
```

It looks like legend boxes don't have spacing anymore, I'm not sure this is intended:

```r
dat <- data.frame(x = LETTERS[1:3], y = 1)
p2 <- ggplot(dat, aes(x, y, fill = x, colour = 1:3)) +
  geom_bar(stat = "identity") +
  guides(color = "colorbar") +
  theme(legend.background = element_rect(colour = "black"))
p2 + theme(legend.position = c(.5, .5))
```

**Comment by hadley** [comment]
The first problem is another example of #1853 

What did the violins used to look like? We made some changes so it's possible the new display is correct.

I wondered about the spacing around legends too. I think this must've happened accidentally while refactoring the theme names.

**Comment by lionel-** [comment]
hmm I now see that the difference is in the truncation not the scale, so it seems the new version is better.

The violin plot before:

![before](https://cloud.githubusercontent.com/assets/4465050/19392413/9348a8ce-9228-11e6-93da-f449363a56d7.png)

and after:

![after](https://cloud.githubusercontent.com/assets/4465050/19392417/96f097c0-9228-11e6-90fe-dc787fe4e2a4.png)

**Comment by hadley** [comment]
Closing this in favour of one new issue
