### ISSUE TITLE
coord_polar plot the y-axis label on the right

### ISSUE THREAD

**Issue by danilinares** [hadley/ggplot2#1853]
This example:
pie <- ggplot(mtcars, aes(x = factor(1), fill = factor(cyl))) +
 geom_bar(width = 1)
pie + coord_polar(theta = "y")

from http://docs.ggplot2.org/current/coord_polar.html in the new version of ggplot2 plots the y-axis label on the right instead of on the left.

**Comment by thomasp85** [comment]
I know this is not the place for a discussion put just putting it out there - I think we need some way for Coords to modify the positional scales in the beginning of `plot_build()`. There are an increasing number of hoops to hop through to get coord_flip etc to work properly...
