### ISSUE TITLE
Changes in the structure of gg objects between v2.0 - v2.1 and v2.1 - v2.2

### ISSUE THREAD

**Issue by pbiecek** [hadley/ggplot2#1854]
The plot function in v2.2 is not working on gg objects created with v2.1. 
Same with v2.1 vs v2.0.

Do you plan to add support for gg objects created with older version of ggplot2 package?

If not, could you point out differences in structure between gg objects v2.2 and v2.1?

We could then create an ggconvert function that will convert objects created with older version of ggplot2 to the recent version of ggplot2 package.

It's needed to assure some kind of reproducibility of our cached R objects.

**Comment by thomasp85** [comment]
There will not be support for this AFAIK - this would simply be too demanding with very little gain (most code will work fine so it would be better to regenerate the plot object)...

There are both changes to the structure of the plot object itself as well as a lot of internal changes in `plot_build`, `Scale`, `Coord`, `Facet`, etc.

The main change in the plot object itself is that the `panel` element holding a `panel` S3 class object has been substituted for a ggproto `Layout` object that now resides in the `Layout` element. `Layout` and `panel` has overall the same responsibilities but the implementation is quite different and some of `panel`s methods has been delegated to the `Facet` class and subclasses.

It certainly possible to piece together information from old ggplot objects in order t create new ones, but you'll need to recreate both `Layout`, `Facet`, `Scale`, `Coord`, and `theme` objects while choosing sensible defaults for new features (I'm just preparing you for a route filled with problems)...

Where I to do this (I'm not) I would probably extract parameters and classes from the old object and then recreating a new object from scratch...

**Comment by hadley** [comment]
Yeah, unfortunately there was never any intent to make the "binary" representation of ggplot2 objects backward compatible.
