### ISSUE TITLE
geom_text() does not inherit from theme(text)? bug or feature?

### ISSUE THREAD

**Issue by dapper2dan** [hadley/ggplot2#1859]
It is my understanding, that `theme(text = element_text(family = "serif")` should change all text elements to serif font. Apparently this is not the case for `geom_text`, though. 

```r
library(ggplot2)
p <- ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars)))

# all sans
p + geom_text()

# only axes serif, labels sans. I would expect the labels to be serif as well.
p + geom_text() + theme(text = element_text(family = "serif"))

# labels and axes serif. Redundant?!
p + geom_text(family = "serif") + theme(text = element_text(family = "serif"))

```

Is there a reason for `geom_text()` not inheriting from `theme(text)`?

**Comment by hadley** [comment]
Theme elements only affect the non-data components of the plot.
