### ISSUE TITLE
With facets, data order differs in vectors vs. data frame columns

### ISSUE THREAD

**Issue by wch** [hadley/ggplot2#1860]
This is from rstudio/shiny#1432.

In this example, it plots small points on top of large points. The large points get their data from a vector. The small points get their data from a data frame column. The contents of the vector and df column are the same, containing 31 FALSEs and 1 TRUE, so there should be one small red point plotted at the same location as one large red point. But that's not what happens.

```R
# We'll pick out one of the 32 points 
selected <- rep(FALSE, 32)
selected[32] <- TRUE

# Add that as a column to the data frame
mtc <- mtcars
mtc$sel <- selected

ggplot(mtc, aes(x = cyl,y = mpg)) +
  # Plot large points using the vector
  geom_point(aes(color = selected), size = 5, alpha = 0.4) +
  # Plot small points using the data frame column
  geom_point(aes(color = sel)) +
  facet_grid(. ~ gear) +
  scale_color_manual(values = c("black", "red"))
```

![image](https://cloud.githubusercontent.com/assets/86978/19502115/30559c22-9570-11e6-8d05-cdc40a917830.png)

Without facets, this problem doesn't seem to happen. And when using a faceting variable with just two levels (`am`, or `carb`), it also doesn't seem to happen.

**Comment by thomasp85** [comment]
Strange - I'll look into it

**Comment by hadley** [comment]
You can't mix data inside and outside data frames like this - there's no way for ggplot2 to reorder the vector in the same way that it reorders the data frame.

**Comment by has2k1** [comment]
It can be fixed by delaying the reordering action at [this line](
https://github.com/hadley/ggplot2/blob/170919680836605bdf01588727a79bf5ff5ddb55/R/facet-grid-.r#L262) and definitely the equivalent line in `facet_wrap`.

**Comment by hadley** [comment]
It might be possible to work around it, but generally, I don't think it's a good idea to mix data from a data frame and the environment, so I have no interest in supporting it.
