### ISSUE TITLE
geom_spoke goes crazy when x or y are set instead of mapped.

### ISSUE THREAD

**Issue by Ax3man** [hadley/ggplot2#1861]
Setting the `angle` and `radius` is fine, these all produce reasonable plots:

```
ggplot(data.frame(x = 0:1)) + geom_spoke(aes(x, x, radius = x, angle = x))
ggplot(data.frame(x = 0:1)) + geom_spoke(aes(x, x, radius = x), angle = 0)
ggplot(data.frame(x = 0:1)) + geom_spoke(aes(x, x, angle = x), radius = 1)
```
However, when `x` and/or `y` are set outside the `aes`, weird things happen:

`ggplot(data.frame(x = 0:1)) + geom_spoke(aes(x, radius = x, angle = x), y = 1)`

![rplot](https://cloud.githubusercontent.com/assets/15309336/19519115/b586a630-960a-11e6-8cf1-e992d29a552d.png)

`ggplot(data.frame(x = 0:1)) + geom_spoke(aes(y = x, radius = x, angle = x), x = 1)`

![rplot04](https://cloud.githubusercontent.com/assets/15309336/19519119/bf4dd4ea-960a-11e6-9b7a-0189cf1403e0.png)

`ggplot(data.frame(x = 0:1)) + geom_spoke(aes(radius = x, angle = x), x = 1, y = 1)`

![rplot05](https://cloud.githubusercontent.com/assets/15309336/19519130/cb1b064e-960a-11e6-8e72-f2264cfcce5c.png)

**Comment by hadley** [comment]
That's because set values aren't passed to the scale.

```R
df <- data.frame(x = 1:2, y = 1:2)
ggplot(df) + 
  geom_point(aes(x, y))

ggplot(df) + 
  geom_point(aes(x), y= 1)
```
