### ISSUE TITLE
class(theme_grey()$panel.background$color)=logical

### ISSUE THREAD

**Issue by yonicd** [hadley/ggplot2#1865]
shouldnt the class of colour be text?

> theme_grey()$panel.background
List of 4
 $ fill    : chr "grey92"
 $ colour  : logi NA
 $ size    : NULL
 $ linetype: NULL
 - attr(*, "class")= chr [1:2] "element_rect" "element"

**Comment by hadley** [comment]
Yes, but it really doesn't matter.
