### ISSUE TITLE
qplot() error with parameters 'span' or 'method'

### ISSUE THREAD

**Issue by R-kicker** [hadley/ggplot2#1866]
One issue with qplot() discovered recently.
Following code from vignette (http://docs.ggplot2.org/dev/vignettes/qplot.html) causes and error "Error: Unknown parameters: span"

```
set.seed(1410) # Make the sample reproducible 
dsmall <- diamonds[sample(nrow(diamonds), 100), ]
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), span = 1)
```

The same error is for the 'method' parameter or other.
Example below from the same vignette causes an error "Error: Unknown parameters: method, formula"

```
library(mgcv)
qplot(carat, price, data = dsmall, geom = c("point", "smooth"), method = "gam", formula = y ~ s(x))

```

The source of error is inside the following loop of the qplot() code {after debug(qplot)}:

```
  for (g in geom) {
    params <- arguments[setdiff(names(arguments), c(aes_names, 
      argnames))]
    params <- lapply(params, eval, parent.frame())
    p <- p + do.call(paste0("geom_", g), params) ### THIS LINE CAUSES AN ERROR
  }
```

For some reason(?) in that loop all extra parameters being applied to all geoms including "point", which is incorrect.

This issue is for version 2.1.0 of 'ggplot2', but for 1.0.1 that does not appear.

Regards,
Igor Magdeev

**Comment by hadley** [comment]
Fixed in dev version
