### ISSUE TITLE
Bug with size in geom_pointrange

### ISSUE THREAD

**Issue by vmikk** [hadley/ggplot2#1867]
Hello!
I have run into an issue when using `size` in `geom_pointrange`. When `size` is specified the symbols becomes huge irrespectively the value you have chosen. 

Here is a reproducible example:
```
library(ggplot2)

set.seed(1)
datt <- data.frame(X = LETTERS[1:5], Y = rnorm(n = 5, mean = 10))
datt$Yl <- datt$Y - abs(rnorm(n = 5, mean = 0.5))
datt$Yu <- datt$Y + abs(rnorm(n = 5, mean = 0.5))

pp <- ggplot(data = datt, aes(x = X))

pp + geom_pointrange(aes(y = Y, ymin = Yl, ymax = Yu)) + ggtitle("no size")
pp + geom_pointrange(aes(y = Y, ymin = Yl, ymax = Yu, size = 0.1)) + ggtitle("size = 0.1")
pp + geom_pointrange(aes(y = Y, ymin = Yl, ymax = Yu, size = 2)) + ggtitle("size = 2")
pp + geom_pointrange(aes(y = Y, ymin = Yl, ymax = Yu, size = 10)) + ggtitle("size = 10")
```

ggplot2 v.2.1.0.9001 (17091968)
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by thomasp85** [comment]
Try moving size out of the `aes()` call to avoid applying a scale to it..?

**Comment by vmikk** [comment]
My bad. Moving a `scale` out of the `aes` works perfectly.
@thomasp85 Thanks a lot for the fast answer!
I think we can close this issue.
