### ISSUE TITLE
ggplot 2 package load error..

### ISSUE THREAD

**Issue by gbengaRic** [hadley/ggplot2#1873]
Am having this error any time i try to load ggplot2 package in r studio "Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    there is no package called ‘colorspace’ Error: package or namespace load failed for ‘ggplot2’" can any one help please.

**Comment by oatesch** [comment]
Have you tried
`install.packages('colorspace') `

Try
`install.packages('ggplot2', dependencies = TRUE)`

[See also](http://stackoverflow.com/questions/31717850/error-package-or-namespace-load-failed-for-ggplot2-and-for-data-table)
