### ISSUE TITLE
Bug in interaction between ggplot2 and plotly

### ISSUE THREAD

**Issue by sb452** [hadley/ggplot2#1876]
Minimal example:

library(ggplot2)
library(plotly)
generic_plot <- ggplot(data = NULL)
p <- plotly_build(generic_plot)
> Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
>  attempt to apply non-function

The plotly function "plotly_build" appears to no longer play nicely with ggplot2. It's unclear to me whether this is a bug with ggplot2, with plotly, or just an incompatibility that could be fixed by either side.

All best, Steve

**Comment by hadley** [comment]
Any incompatibilities with extension packages have be fixed by those packages.
