### ISSUE TITLE
Different positioning for different factors

### ISSUE THREAD

**Issue by Enchufa2** [hadley/ggplot2#1879]
Let's start with some data to illustrate the issue:

```{r}
library(ggplot2)
library(dplyr)

dt <- data.frame(
  y = c(0.1, 0.2, 0.5, 0.6, 0.2, 0.45, 0.8, 0.85),
  x = c("A", "A", "A", "A", "B", "B", "B", "B"),
  c = factor(c(1, 1, 2, 2, 1, 1, 2, 2)),
  s = factor(c(1, 2, 1, 2, 1, 2, 1, 2))
)
```

As you can see, there are several values per category `x`, and two factors `c` and `s`. Let's produce a basic plot:

```{r}
p <- ggplot(dt, aes(x, y, color = c)) + theme_bw()
p + geom_point(aes(shape = s), size = 3)
```

![rplot](https://cloud.githubusercontent.com/assets/4542928/19777751/f2af7152-9c79-11e6-9925-c6031fdcdf1a.png)

The problem here is that I would like to dodge by colour `c`, but stack by shape `s`. If I'm not mistaken, currently this is not possible. If you specify `position_dodge()`, dodging is performed for all factors, colour and shape in this case, which is not what I want:

```{r}
pos = position_dodge(0.7)
p + geom_point(aes(shape = s), size = 3, pos = pos)
```

![rplot](https://cloud.githubusercontent.com/assets/4542928/19777930/b15941aa-9c7a-11e6-8c52-17f428047689.png)

The point here is that I want to produce a stem plot, e.g.:

```{r}
lims <- dt %>%
  group_by(x, c) %>%
  summarise(yend = max(y), y = min(y))

p + geom_point(aes(shape = s), size = 3) +
  geom_segment(aes(xend = x, yend = yend, y = 0), data = lims, alpha = 0.3) +
  geom_segment(aes(xend = x, yend = yend), data = lims)
```

![rplot](https://cloud.githubusercontent.com/assets/4542928/19778052/508af124-9c7b-11e6-98fe-23d8cb5f2e7f.png)

But I want to keep stacking for shapes and introduce dodging for colours. Obviously, if we specify position as before, it's a total mess:

```{r}
p + geom_point(aes(shape = s), size = 3, pos = pos) +
  geom_segment(aes(xend = x, yend = yend, y = 0), data = lims, alpha = 0.3, pos = pos) +
  geom_segment(aes(xend = x, yend = yend), data = lims, pos = pos)
```

![rplot](https://cloud.githubusercontent.com/assets/4542928/19778137/9be1159a-9c7b-11e6-9bd4-f585b5185074.png)

**Comment by hadley** [comment]
That's unlikely to ever be built-in. I'd recommend doing it by hand.
