### ISSUE TITLE
Better error message for plots (or facets with free scales) with all missing values.

### ISSUE THREAD

**Issue by jasonelaw** [hadley/ggplot2#791]
This bit me in a large,faceted plot where it wasn't entirely obvious what was going on:
```
d <- data.frame(x = 1:5, y = as.double(NA))
ggplot(data = d, aes(x, y)) + geom_point()
Error in seq.default(from = best$lmin, to = best$lmax, by = best$lstep) : 
  'from' must be of length 1
```
This is more like what caught me:
```
d <- expand.grid(x = 1:5, f = letters[1:5])
d$y <- rnorm(25)
is.na(d$y) <- d$f == 'a'
ggplot(data = d, aes(x, y)) + geom_point() + facet_wrap(~ f, scales = 'free_y')
```
Is it possible to catch this error?

**Comment by johnaponte** [comment]
I have the same problem if the y values are Inf

**Comment by drolejoel** [comment]
not sure if this helps but there is a workaround with ggplot2 v1.0.1 (see http://stackoverflow.com/questions/23593159):  The solution for me was to make sure my data.frame was nice and clean, by removing all NA values from the column with the Y axis data.

**Comment by Inventitech** [comment]
I just ran into this problem having upgraded to ggplot 2.0 (which was unrelated, but I did not know that at that time) and it took me 15 mins to figure out what was actually wrong. Yeah, if you can, please provide a better error message that makes it easier to spot that, for example, all your input data is NA.

**Comment by mattbk** [comment]
> all your input data is NA

Not just for `x` and `y`, but other aesthetics as well.

**Comment by hadley** [comment]
No one supplied any reprexes apart from the initial, but I think this is fixed now.
