### ISSUE TITLE
ggplot2 icon

### ISSUE THREAD

**Issue by trinker** [hadley/ggplot2#888]
I'm making a presentation and tried to find an icon that represents ggplot2.  Nothing that I can find.  So I made my own.  Thought I'd share but suggest there should be a ggplot2 icon made in ggplot2.  I kept the trademark ggplot2 background.

```
library(grid); library(ggplot2)
dat <- data.frame(x = seq(0, 1, by = .1), 
    y = c(-.1, .29, .23, .47, .3, .8, .7, .9, .85, 1, 1))

png("ggplot.png", width = 400, height = 150)
ggplot(dat, aes(x=x, y=y)) + geom_path(size=2, alpha=.1) +
    annotate("text", x = .5, y = .5, label = "ggplot2", size=34) +
    theme(axis.text = element_blank(),
        axis.ticks = element_blank(), 
        axis.title = element_blank(),
        panel.border = element_rect(color = "grey80", fill = NA),
        plot.margin = unit(c(1, 1, 0, 0), "lines")) +
    ylim(-.2, 1)
dev.off()
```

![ggplot](https://f.cloud.github.com/assets/1763278/1768009/6b77defe-675c-11e3-9b9b-09429fa6991b.png)

**Comment by hadley** [comment]
Still interested in this PR?

**Comment by hadley** [comment]
Closing - please ping if you want to work on it again.
