### ISSUE TITLE
do not stop for non-standard theme options

### ISSUE THREAD

**Issue by tdhock** [hadley/ggplot2#938]
as of ggplot2-0.9.3.1, I get an error when I use non-standard theme options e.g.

```r
> theme(animint.width=500)
Error in (function (el, elname)  : 
  "animint.width" is not a valid theme element name.
```

For animint it would be nice to define some plot-specific info in the ggplot theme... could you please accept and save non-standard theme options?

**Comment by wch** [comment]
This was closed by #1121.
