### ISSUE TITLE
Bug with coord_map and world map

### ISSUE THREAD

**Issue by blaquans** [hadley/ggplot2#963]
Have you seen that there is a bug when using `coord_map` with a world map ? 
The first picture is drawn using coord map 

    library(ggplot2)
    library(maps) 
    world <- map_data("world")
    ggplot() + geom_map( data=world, aes(x=long, y=lat, group = group, map_id = region),colour="white", fill="grey10", map = world ) + coord_map()

![ggmap3](https://cloud.githubusercontent.com/assets/3227753/2971608/39da794a-db6c-11e3-93c8-9d8d8015c544.png)

The second is done without coord_map and is correct even if the projection is not optimal : 

    ggplot() + geom_map( data=world, aes(x=long, y=lat, group = group, map_id = region),colour="white", fill="grey10", map = world )  

![ggmap4](https://cloud.githubusercontent.com/assets/3227753/2971609/39dbbef4-db6c-11e3-98db-30300d2a3c04.png)

Here is my [gist](https://gist.github.com/blaquans/057d9a250f3088d1cc89)

**Comment by zachcp** [comment]
yeah I see this too. I was just coming to report it. You can get a workaround by specifying the `xlim` and `ylim`:

```[r]
ggplot() + 
  geom_map( data=world, 
            aes(x=long, y=lat, group = group, map_id = region),
            colour="white", fill="grey10", map = world ) +
   coord_map(xlim=c(-180,180))
```
that gets rid of the nasty line but greenland and antarctica are still off. I don't know how to fix that one although I would play around a bit with the the `orientation` parameter
![screen shot 2015-04-09 at 4 29 05 pm](https://cloud.githubusercontent.com/assets/1260667/7076183/a1929776-ded5-11e4-9cb7-c8bf69cb27e6.PNG)

**Comment by hadley** [comment]
This is a problem with the underlying data. Will hopefully have recommendation for better data sources soon.
