### ISSUE TITLE
geom_violin throws error on data with zero variance

### ISSUE THREAD

**Issue by tonytonov** [hadley/ggplot2#972]
As described [here](http://stackoverflow.com/questions/24129772/ggplot2-geom-violin-with-0-variance), the following code  

````
dff=data.frame(x=factor(rep(1:2, each=100)), y=c(rnorm(100), rep(0,100)))
ggplot(dff,aes(x=x,y=y)) + geom_violin()
````
terminates with
````
Error in `$<-.data.frame`(`*tmp*`, "n", value = 100L) : 
  replacement has 1 row, data has 0
````
It would be relatively easy to alter this behaviour and draw something instead, either a single line or nothing at all.

**Comment by hadley** [comment]
Even more minimal reprex

```R
dff <- data.frame(x = factor(rep(1, 10)), y = rep(0, 10))
ggplot(dff, aes(x, y)) + geom_violin()
```

**Comment by hadley** [comment]
Hmmmm, the problem is actually the trimming. This code works just fine:

```R
dff <- data.frame(x = factor(rep(1, 10)), y = rep(0, 10))
ggplot(dff, aes(x, y)) + geom_violin(trim = FALSE)
```

I think the easiest fix is to do the same thing that `geom_density()` does

**Comment by tonytonov** [comment]
I've checked the fix, works perfectly, thanks!
