### ISSUE TITLE
Would it be possible to add notes to a ggplot graph ?

### ISSUE THREAD

**Issue by blaquans** [hadley/ggplot2#978]
Very often, we need to add a small text at the bottom of a graph to give the sources, the field and other notes explaining how to read the graph. Would it be possible to create to add the field "notes" in the `labs()` function or a new function `notes()` which would make it easy to add some notes at the bottom of a graph. I know that there is a very complex solution using grid and gridExtra ([link](http://stackoverflow.com/questions/10014187/displaying-text-below-the-plot-generated-by-ggplot2)) butI think we need a simple solution.

**Comment by hadley** [comment]
I'm with @stefanedwards on this one.

**Comment by ggrothendieck** [comment]
With classic graphics and lattice it's very easy to add a note using `sub=` but it is quite awkward with ggplot2.   In fact, it is such a pain that whenever I have such a need I typically use classic or lattice graphics instead.   From my own experience this is important and frequently needed and so I wanted to add my voice in favor of adding this.

**Comment by ggrothendieck** [comment]
Version 0.5.0 of the cowplot package (on CRAN) handles subtitles using the `add_sub` function.

**Comment by blaquans** [comment]
@ ggrothendieck thanks

**Comment by yimingli** [comment]
Data sources should be bundled with the graph to be reproducible and portable, especially if you write research papers. We usually copy the same graphs around, sometimes to adjust the organization of the paper, sometimes into different documents and presentations slides. Separate texts in R markdown make it very difficult.
