### ISSUE TITLE
Geom not exported?

### ISSUE THREAD

**Issue by bergsmat** [hadley/ggplot2#989]
Hi! 

Thanks for the help at https://github.com/hadley/ggplot2/wiki/Creating-a-new-geom . 

The link to sample code breaks, so I harvested code from the page and added `ggplot(data=data.frame(x=5,y=5,angle=pi/6,length=0.2),mapping=aes(x=x,y=y,angle=angle,length=length)) + layer(geom='field')`.

I had to change `Geom` to `ggplot2:::Geom` apparently because Geom is not exported.  Will that survive modern CRAN check?  Also, my example above gives `Error: attempt to apply non-function`. It would be very useful to author new geoms for use with particular data types.  Thanks in advance for any comments.

**Comment by lionel-** [comment]
@hadley 
The other proto objects `Stat` and `Position` should be exported too as they can be useful to extend ggplot.

Here is an example where I derived from `Stat`: http://stackoverflow.com/questions/10071944/ggplot2-geom-point-with-binned-x-axis-for-binary-data/24995101#24995101

**Comment by hadley** [comment]
I was just waiting for someone to ask for them ;)
