### ISSUE TITLE
rqss in stat_quantile ignore the quantile with large number of values

### ISSUE THREAD

**Issue by lccanon** [hadley/ggplot2#990]
When dealing with a large number of values (more than 1e4), then the rqss method seems to discard the quantile parameter. Here is a minimal example (with a non-linear relationship):

    library(ggplot2)
    X <- runif(1e4)
    V <- data.frame(x=X, y=log(X+runif(length(X))))
    p <- ggplot(data = V, aes(x=x, y=y))
    p + stat_quantile(quantiles = c(0.05, 0.95), method = "rqss")

Instead of doing the quantile regression for 0.05, it may do it for 0.5. This occurs at least half the time (decreasing the number of values reduces the frequency of this problem).

This problem disappear when using the rq method.

**Comment by hadley** [comment]
Seems like a bug in `rqss`?
