### ISSUE TITLE
geom_boxplot with continuous x and without group aesthetics

### ISSUE THREAD

**Issue by krlmlr** [hadley/ggplot2#992]
```
d <- data.frame(x=rep(1:10, 100), y=runif(1000))
ggplot(d) + geom_boxplot(aes(x=x, y=y))
```

will happily produce a single box, while the intention is probably to produce the output of this code:

```
d <- data.frame(x=rep(1:10, 100), y=runif(1000))
ggplot(d) + geom_boxplot(aes(x=x, y=y, group=x))
```

Would a warning be appropriate here -- if `x` is continuous and the `group` aesthetics is missing?

**Comment by hadley** [comment]
Maaaaybe, but I like that there's currently one unifying principle for grouping (i.e. all discrete variable for a group).  But if you feel strongly about, I'd review a PR to add a warning.
