### ISSUE TITLE
ggplot - geom_step error

### ISSUE THREAD

**Issue by pharaveej** [hadley/ggplot2#994]
I am trying to plot a graph of 3 observations (infusion rate, sedation level, tolerance level) as a function of time. 
My data frame looked some thing like this:

![capture](https://cloud.githubusercontent.com/assets/8388961/3849702/0bd77fea-1e7c-11e4-88ba-77c774579854.JPG)

So, far I can plot scatter plot and line with this code:

 p <- ggplot(data, aes(group = Subtype, colour = Subtype)) + facet_wrap(~ Pt_ID, ncol = 6) + geom_point(aes(Time, Observation)) + geom_point(aes(Time, Rate), colour = "pink") + geom_line(aes(Time, Rate)) + geom_line(aes(Time, Observation))

However the graph is not what I wanted, I need to get a step plot.

But when I use geom_step function with this code:

 p <- ggplot(data, aes(group = Subtype, colour = Subtype)) + facet_wrap(~ Pt_ID, ncol = 6) + geom_step(aes(Time, Observation)) + geom_step(aes(Time, Rate), colour="pink")

I received this error message:

Error in grid.Call.graphics(L_lines, x$x, x$y, index, x$arrow) : invalid line type

I am rather new with R. If anyone can tell me what is wrong with my code or any suggestions, I'd really really appreciate it.

**Comment by hadley** [comment]
Please include a minimal reproducible example, and reopen.
