### ISSUE TITLE
Suggestion: Geom replace infix operator

### ISSUE THREAD

**Issue by dorvak** [hadley/ggplot2#999]
In ggplot2, using the %+% infix operator makes it pretty easy to replace the underlying data on an existing ggplot. I wonder wether there is a operator (or any other method) to remove and /or replace an existing geometry from a ggplot? 

[It might be complicated to remove/replace a certain geom, esp. if there are multiple ones of the same type]

**Comment by hadley** [comment]
I'm pretty sure this is a bad idea, given how easy it is to modify code to avoid adding the layer in the first place.
